### ISSUE TITLE
[Binding] - Bind then retrieve other params

### ISSUE THREAD

**Issue by BorisLeMeec** [gobuffalo/buffalo#1005]
Hello,

I have a little issue using binding in buffalo.
I try to recover values passing via `text/json` format : 

```
{
  "first_name": "palo",
  "last_name": "alto",
  "year": 1992,
  "month": 6,
  "day": 12
}
```

And I bind id to this struct containing not all the values : 

```
type Client struct {
	ID        uuid.UUID `json:"id" db:"id"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	FirstName string    `json:"first_name" db:"first_name"`
	LastName  string    `json:"last_name" db:"last_name"`
	BirthDate time.Time `json:"birth_date" db:"birth_date"`
}
```
Using this code :
```
func (cr ClientResource) Create(c buffalo.Context) error {
	cl := &models.Client{}
	err := c.Bind(&cl)
	if err != nil {
		c.Render(401, r.JSON(err.Error()))
	}
	return c.Render(201, r.JSON(cl))
}
```

How is it possible to retrieve the 3 others values `year`, `month` and `day` ? If i try using `context.Params().Get("day")` it is empty...
Thabk you

**Comment by markbates** [comment]
I'm assuming the JSON is the requests body, which is why you can't get the `day` from the `c.Params`, it's not a parameter.

You could do a few things, skip `c.Bind` although and unmarshal the body into something like a `map[string]interface{}`, but that's pretty yucky to work with.

I would update my model like this:

```
type Client struct {
	ID        uuid.UUID `json:"id" db:"id"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	FirstName string    `json:"first_name" db:"first_name"`
	LastName  string    `json:"last_name" db:"last_name"`
	BirthDate time.Time `json:"birth_date" db:"birth_date"`
        Year int `json:"year,omityempty" db:"-"
}
```

Then `c.Bind`, which just uses the `json` package under the covers will grab the `year` value and put it into your model. The `db:"-"` tag tells the DB to ignore that attribute when reading/writing.

Hopefully that helps.

**Comment by BorisLeMeec** [comment]
Yes, I thought about taging a field with `-`...
But I could do that only if the `soda generate` option can generate the field `Year` with the `-` tag... That leads to another question I have. Is `soda generate` can manage tag field in `struct` ?

**Comment by markbates** [comment]
It doesn’t do it via the CLI, you have to just change the file. The CLI assumes that what you pass to it, you’re going to want in the database. But you can always add more fields later, like these.

**Comment by BorisLeMeec** [comment]
Yes surely. I think I will operate this way so. Thank you a lot for your time ! And a huge congrats for the whole project, this is amazing ;)

**Comment by jeffdico** [comment]
> I'm assuming the JSON is the requests body, which is why you can't get the `day` from the `c.Params`, it's not a parameter.
> 
> You could do a few things, skip `c.Bind` although and unmarshal the body into something like a `map[string]interface{}`, but that's pretty yucky to work with.
> 
> I would update my model like this:
> 
> ```
> type Client struct {
> 	ID        uuid.UUID `json:"id" db:"id"`
> 	CreatedAt time.Time `json:"created_at" db:"created_at"`
> 	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
> 	FirstName string    `json:"first_name" db:"first_name"`
> 	LastName  string    `json:"last_name" db:"last_name"`
> 	BirthDate time.Time `json:"birth_date" db:"birth_date"`
>         Year int `json:"year,omityempty" db:"-"
> }
> ```
> 
> Then `c.Bind`, which just uses the `json` package under the covers will grab the `year` value and put it into your model. The `db:"-"` tag tells the DB to ignore that attribute when reading/writing.
> 
> Hopefully that helps.

yes this helped me. I had to convert the c.Request().Body to bytes using ioutil.ReadAll(body)
