### ISSUE TITLE
Webpack is not cleaning up after itself

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#1012]
We making changes to .js or .css files I noticed that web pack isn't cleaning up `public/assets` and leaving a lot of cruft around.

This was after PR #1007 was merged into the `development` branch.

```
├── application.62d4352af591de60cdd4.js
├── application.63b899a2d4b6f5002e9e.js
├── application513b262377e1b76009dd.css
├── application819a2d8895ea56350c13.css
```

**Comment by paganotoni** [comment]
@markbates I see it happening in my projects as well, however, I tried it with a pre #1007 project webpack config and it happens as well.

Working on it.
