### ISSUE TITLE
Named routes in handlers?

### ISSUE THREAD

**Issue by robotlovesyou** [gobuffalo/buffalo#1016]
Hi.

Apologies if I've simply missed how to do this but is there any way to get hold of a named path in a handler rather than in a template?

I mean aside from pulling a RouteHelperFunc from the context, not that I've even checked if that is possible!

The main reason for this would be to get the appropriate path when redirecting after a post/put.

I wonder if it's worth creating a slack channel or discourse for buffalo too since asking what is really a support question as a github issue feels a bit wrong!

While I'm here, thanks for creating Buffalo. It is, as I write, making my life a whole bunch simpler!

**Comment by markbates** [comment]
There’s a great slack channel already https://gobuffalo.io/en/docs/slack. :) it’s very vibrant and welcoming. You should definitely join us there. 

Currently the best way to get them in the Handler is just as you describe, pulling from the context and casting. 

Hope to see you in slack!

**Comment by robotlovesyou** [comment]
Thanks!
