### ISSUE TITLE
route helper not working with patial with extra arguments

### ISSUE THREAD

**Issue by sio4** [gobuffalo/buffalo#1044]
Hello, If I send additional contexts to `partial` by optional argument, something went wrong. In my case, route helpers are not working.

What I understand from URL below is, "local" variables can be passed to partial but at this time, it is **additional** variable or override existing variable, but also _existing contexts of parent are passed with it_.

https://gobuffalo.io/en/docs/partials

> In addition to have the context of the parent template, partials can also be sent additional information as "local" variables.

## Steps to Reproduce the Problem

Following partial is used for test:

    <%= loginPath() %>

From caller side, working version is like this:

    <%= partial("login.html") %>

It shows `/login` as expected.

But if I call this partial with

    <%= partial("login.html", {users: resource.Users}) %>

It makes error

> loginPath: unknown identifier

I am using buffalo 0.11.0.

**Comment by markbates** [comment]
Fixed with #1045
