### ISSUE TITLE
Need a way to easily add "routes" when generating files.

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#105]
When running something like `buffalo g resource` or `buffalo g actions` it would be nice to able to add those to the routes defined in the `actions/app.go` file.

I propose some sort of function in the `generate` package, probably, that can be called, that properly parses the `actions/app.go` file and allows for the inserting of routes where applicable.

**Comment by apaganobeleno** [comment]
@markbates i would love to give this one a shot, more since this was the bonus part of #16, really enjoying what i'm doing, thanks for the chance.

**Comment by markbates** [comment]
I'm loving the help!! Thanks!

**Comment by apaganobeleno** [comment]
i've been thinking a bit about this one before implementing it, wanted to describe the solution before i implement it to see if we can find any issues to the solution i've been thinking on, i've came with a solution to determine where to place the new route by using `ast` :

https://play.golang.org/p/lCW9eqBr4l

However for me it feels a sensible to the changes we could have on the app.go file, please let me know what do you think, i would love to hear your opinion before starting with the PR.
