### ISSUE TITLE
Feature proposal : Front end validator

### ISSUE THREAD

**Issue by hubyhuby** [gobuffalo/buffalo#1052]
Feature proposal:
When you use buffalo in production the validation is done on server side. Which is very important for the consistency of datas.
Also as a bonus we could have a front-end (eventually JS) validation following the same rules generated by buffalo's code generator.

## Expected Behavior

When users enter text in a modern website field, they expect to have direct return on things.
Especially when you have **more than 1 page of fields**, it becomes complicated to answer a form. ( a multi part form in buffalo would be also interesting).

## Actual Behavior

The user needs to push the "Save" button of the form to have the answer from the server and eventually notice that "5 out of 10 fields are wrong". So the users starts over again the form.
The programer using buffalo needs to implement JS validation for each field, following the same rules as the ones generated in the backoffice.

**Comment by yatish27** [comment]
Why would this be specific to Buffalo? You could have normal client-side validation.

**Comment by robbyoconnor** [comment]
This isn't Buffalo's job. This is the job of whatever frontend framework/library you are using. Buffalo's job is to take care of _server side_ validation.

**Comment by hubyhuby** [comment]
Dear @robbyoconnor  @yatish27 ,
I am not saying it is not possible to do on the user side, since it is exactly what I have been doing recently.
Also I would like to point that most of the time you will repeat the same code logic in Javascript to validate...
Would be nice not to repeat  yourself . Now if it is against some logic in the framework please just delete this feature request.

Sometimes going past your own limits may bring interesting innovations ;)

**Comment by robbyoconnor** [comment]
@hubyhuby The unfortunate fact (IMHO) is that Buffalo shouldn't dictate the frontend -- UNLESS you use template, and not the API-only mode -- and even then -- this should be optional. Nothing stops you from making a PR for this, knock yourself out!

**Comment by gedw99** [comment]
I think it's a worthwhile discussion.

The meta data that drives structure level validation is there next to the struct. Surely it makes sense to reuse it for DRY sake.

One option is to export to JSON the meta data as part of codegen. That leaves the door open for any is developed to use it.
For example with vuejs.

Tricky part is that you also need to export the i18n localised data too for the error messages , but that already portable.

Other option is to cross compile using gopherjs / wasm. 

The thing about validation is that you often have one phase to validate the struct scope and the 2nd phase to validate with other db / model data. So there are really two types of validators.

I use buffalo with flutter currently too. So there exporting the struct scoped meta data is the only option along with the i18n error messages

**Comment by gedw99** [comment]
Templates can gen lots of code in other languages too btw. So if I am using vuejs or flutter I can gen my validators and i18 messages for example if I want to.
I would take it that far IMHO

**Comment by hubyhuby** [comment]
@gedw99 ,
Thanks for your constructive approach.
There are so many front-end technologies coming up with WASM and PWA. Finding a sweet spot, without being opinionated (js) isn t easy... If a sweet spot exists ;)

**Comment by gedw99** [comment]
well i am not advodating a technology, but more defining the actual problem space as i worked on code gen and this exact area for large projects.

Wasting the meta data is a sin :) you can always just pump it out as JSON at codegen time and let any language use it too.

**Comment by hubyhuby** [comment]
We are now also using meteor.js which has an integrated aproach of the  back and front end. Bottom line that s what we where looking for. Maybe buffalo will evolve in this way, especially when creating plugins becomes easier (I have seen movement recentely. looking forward)
