### ISSUE TITLE
The tokenauth middleware needs to be documented 

### ISSUE THREAD

**Issue by robbyoconnor** [gobuffalo/buffalo#1056]
The [tokenauth middleware](https://github.com/gobuffalo/buffalo/tree/master/middleware/tokenauth) is currently not documented. The [tests](https://github.com/gobuffalo/buffalo/blob/master/middleware/tokenauth/tokenauth_test.go) can kind of suffice, but not really. There is [this blog post](https://medium.com/@francescodonzello/jwt-and-go-buffalo-4cce3ae73723) linked on the website, but that was written before tokenauth middleware was merged, however, uses the same library, which is unlikely to be coincidental. 

Unless someone takes this on, I might write this. I'm opening an issue so it's tracked.

**Comment by Shivakishore14** [comment]
The gobuffalo.io middleware sections documents how to use middlewares in general https://gobuffalo.io/en/docs/middleware. And it redirects user to GoDoc for middleware specific documentation.

So does it make sense to create a new section on JWT middleware on gobuffalo.io, or to update the docs for the GoDoc ?

**Comment by robbyoconnor** [comment]
No, because it doesn't provide example usage.

**Comment by robbyoconnor** [comment]
No, because it doesn't provide example usage. Document how to use it and
sure :)

**Comment by robbyoconnor** [comment]
I have other concerns about the library you used -- it doesn't validate
very many claims at all. I don't know why it's so popular -- I'll be
writing up all my issues with it soonish -- needless to say -- I don't
trust this library.

**Comment by paulZzhang** [comment]
@stanislas-m I'm a newer, I don't know confige it. Please add doc.

**Comment by Shivakishore14** [comment]
Hi @paulZzhang ,
The documentation should be available in https://godoc.org/github.com/gobuffalo/buffalo/middleware/tokenauth. (not currently available as the documentation is in `development` branch it should be in `master` branch to be available via godoc, it should be available soon).

For now you can take a look at here https://github.com/gobuffalo/buffalo/blob/development/middleware/tokenauth/tokenauth.go#L5.

**Comment by stanislas-m** [comment]
This middleware was moved to https://github.com/gobuffalo/mw-tokenauth

Doc is available here: https://godoc.org/github.com/gobuffalo/mw-tokenauth.
