### ISSUE TITLE
webview

### ISSUE THREAD

**Issue by ghost** [gobuffalo/buffalo#1070]
please consider supporting a webview for Desktop.

I saw the Electron shell request and thats great. But i prefer Webview because its much lighter ( uses the default Webview of each desktop), has a very simple and easy to use API at the golang level, and is very efficient

The other huge thing is that i dont need nodejs.

https://github.com/zserge/webview

For example the classic todo:
https://github.com/zserge/webview/blob/master/examples/todo-go/main.go

line 25: boot the index.html

line 65: handles all RPC calls with a simple Action name string

I guess i should also mention packaging, because Electron has a way to support packaging.

There are now a few packaged that will package the app for windows as an MSI and for MacOS as a dmg. The msi one is here: 
https://github.com/mh-cbon/go-msi

I have to dig out where the DMG one is.

**Comment by gedw99** [comment]
Just wanted to give another approach

Astielectron.
It embeds chrome and is about 50 mb
Advantage is that it's one browser to support.
It also looks powerful in terms of window dialogues and ability to be integrates as a plugin.

**Comment by stanislas-m** [comment]
While it can be a good idea, we want to keep the Buffalo core as light as possible. Feel free to write a plugin for that. :) https://gobuffalo.io/en/docs/plugins#writing-a-plugin
