### ISSUE TITLE
Resource Generator name mismatch

### ISSUE THREAD

**Issue by krehl** [gobuffalo/buffalo#1079]
## Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. generate resource
`buffalo.exe g r messages MessageHeaders:Text ContentType ContentEncoding DeliveryMode CorrelationId ReplyTo:nulls.Text Expiration:nulls.Text MessageId Timestamp:timestamp Type UserId AppId Body:nulls.Text`
  1. migrate DB
`buffalo.exe db migrate`
  1. create new resource or view/list in browser

## Actual Behavior

Error message: table messages has no column named header

Form Data (randomly hitting the keyboard): map[UserID:[132] DeliveryMode:[123] Timestamp:[2001-01-01] ReplyTo:[123] ContentEncoding:[3123] AppID:[123] Type:[123] Body:[123] authenticity_token:[xPmH1EyEhNXSdfzXiYg==] Expiration:[123] MessageID:[132] Headers:[213] ContentType:[21312] CorrelationID:[123]]

## Expected

Model is created without error.

## Info

Somewhere between the models.go and the migrations a "s" is missing:

`t.Column("message_headers", "text", {})`

    MessageHeaders  string       `json:"message_header" db:"message_header"`

**Comment by dnnrly** [comment]
Try changing `MessageHeaders` to `MessageHeader`. I know it won't give the intent of what you want but it will hopefully give us a clue about what's happening. This might be something to do with pluralisation.

**Comment by krehl** [comment]
@dnnrly That's exactly what I did as a workaround :) I also noticed, that the ressource was renamed from "Message**s**" to "Message".

**Comment by paganotoni** [comment]
@krehl just opened https://github.com/gobuffalo/pop/pull/113 which should solve this.

**Comment by paganotoni** [comment]
this one was fixed with gobuffalo/pop#113
