### ISSUE TITLE
buffalo new <project> fails looking for golang.org/x/tools/go/gcimporter

### ISSUE THREAD

**Issue by kevin-cantwell** [gobuffalo/buffalo#108]
I always get this error trying to create a new project:

```
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/Cellar/go/1.7.1/libexec/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/Users/kevincantwell/gdrive/Code/gopath/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
Error: exit status 1
```

The current package name in the tools repo is `golang.org/x/tools/go/gcimporter15`. It looks like buffalo is only compatible with older versions.

**Comment by markbates** [comment]
It looks like you're using home brew, is that correct?

Buffalo is tested using Go 1.7 and tip, so it's definitely compatible with the latest versions of Go. 

I, personally, have always had a number of problems using home brew for Go development. Downloading the prebuilt packages from golang.org have never caused these sorts of problems. 

Can you try using one of those packages? Or using docker?

**Comment by markbates** [comment]
I fond this issue in the gore project:

https://github.com/motemen/gore/issues/63

Can you try updating your local copy of gore, that might be it.

**Comment by kevin-cantwell** [comment]
@markbates Thank you, updating gore did the trick! I'm off and running again 💯

**Comment by markbates** [comment]
Woot!! I'll add this to the docs on gobuffalo.io. Thanks!
