### ISSUE TITLE
Why is Yarn installed and used by default?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [gobuffalo/buffalo#1086]
## Steps to Reproduce the Problem

  1. Created new Buffalo app

## Expected Behavior

Yarn should of not been installed and used, but if I specified the --with-yarn argument, it should have been used (PR #256)

## Actual Behavior

Yarn was used

**Comment by markbates** [comment]
You don’t specify which version of Buffalo you’re using, but, for a while now, definitely in 0.11.x yarn has been the default. There is also now —with-yarn flag anymore, but there is a —skip-yarn flag. https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/new.go

**Comment by markbates** [comment]
Here is the PR that changed that functionality last July. https://github.com/gobuffalo/buffalo/pull/555/files

**Comment by ThatNerdyPikachu** [comment]
Ah, sorry. Didn't see that.

Thanks!

**Comment by markbates** [comment]
np. :)
