### ISSUE TITLE
zsh auto complete

### ISSUE THREAD

**Issue by 1995parham** [gobuffalo/buffalo#1091]
Buffalo cmd has many commands and options. I try to provide ZSH plugin for buffalo command that can help a user by providing autocomplete feature. you can check it [here](https://github.com/1995parham/dotfiles/blob/master/zsh/zsh.plug/plugins/buffalo/buffalo.plugin.zsh). It is not completed yet but I am working on it. what do you think about it? do you think it is useful?

**Comment by stanislas-m** [comment]
That's a nice idea! :+1:
We try to keep buffalo as slim as possible, so I think you can create your own repo for it. When you think it's ready, create an issue in https://github.com/gobuffalo/gobuffalo/issues to explain how it works, and how to install it, and we'll add it to the gobuffalo.io website.
