### ISSUE TITLE
Plugin Load Timing Out

### ISSUE THREAD

**Issue by marstr** [gobuffalo/buffalo#1103]
## Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. Develop on Windows
  1. Work in an office with a despotic and ridiculous IT department, that enforces super invasive scanning everytime one runs a program.
  1. Install a Buffalo Plugin
  1. Run any buffalo command.

## Expected Behavior

Plugins should all load as expected.

## Actual Behavior

Plugins sometimes take more than a second to load, and Buffalo gives up on them. I've modified my local copy of buffalo to timeout after 10 seconds, and plugins always load. When I added a test to see how long it took, most plugins loaded in about 1.5 seconds.

What I'd like to see is a way to parameterize how long before I give up on loading plugins. I can submit a PR to fix this.

## Info

Please run `buffalo info` and paste the information below where it says "PASTE_HERE".

<details>
(I know, I know, I'll upgrade to v0.12.* later today)

?[31mERRO?[0m[0001] [PLUGIN] error loading plugin D:\Users\marstr\go\bin\buffalo-azure.exe: exit status 1

?[31mERRO?[0m[0002] [PLUGIN] error loading plugin D:\Users\marstr\go\bin\buffalo-goth.exe: exit status 1

### Buffalo Version
v0.11.0

### App Information
Pwd=D:\Users\marstr\go\src\github.com\gobuffalo\buffalo
Root=D:\Users\marstr\go\src\github.com\gobuffalo\buffalo
GoPath=D:\Users\marstr\go
Name=buffalo
Bin=bin\buffalo.exe
PackagePkg=github.com/gobuffalo/buffalo
ActionsPkg=github.com/gobuffalo/buffalo/actions
ModelsPkg=github.com/gobuffalo/buffalo/models
GriftsPkg=github.com/gobuffalo/buffalo/grifts
VCS=git
WithPop=false
WithDep=true
WithWebpack=false
WithYarn=false
WithDocker=true
WithGrifts=true

### Go Version
go version go1.9.2 windows/amd64

### Go Env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Users\marstr\go
set GORACE=
set GOROOT=C:\Program Files\Go
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\marstr\AppData\Local\Temp\go-build365257475=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### Node Version
v8.9.1

### NPM Version
5.7.1

   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.5.1 → 6.1.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

### Yarn Version
1.6.0

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
SQLite Not Found

### Dep Version
dep:
 version     : devel
 build date  :
 git hash    :
 go version  : go1.9.2
 go compiler : gc
 platform    : windows/amd64
 features    : ImportDuringSolve=false

### Dep Status

</details>

**Comment by markbates** [comment]
What is your BUFFALO_PLUGIN_PATH set to? If it’s not set, it scans your PATH, I believe, which can be really slow. Try setting it something like GOPATH/bin and see if that helps?

**Comment by marstr** [comment]
Oooh, that's a good tip. That may be a good way to unblock me in the short-term. Thanks!

Okay if I still submit a PR to parameterize the plugin load timeout duration?

**Comment by markbates** [comment]
Absolutely, go for it! Keep the default time really short 2-3s I think.

**Comment by marstr** [comment]
Yep, I'll keep the default where it's at of 1 second. :) I'm not about that slow-everybody down life.
