### ISSUE TITLE
Error installing buffalo. 

### ISSUE THREAD

**Issue by curtisallen** [gobuffalo/buffalo#111]
I have a proper gopath setup (I'm a go developer). I'm unable to install buffalo

```console
~ go version
go version go1.7.1 darwin/amd64
~ echo $GOPATH
/Users/callen/src
~ go get -u github.com/gobuffalo/buffalo/buffalo
package github.com/mattn/go-zglob/fastwalk: cannot find package "github.com/mattn/go-zglob/fastwalk" in any of:
	/Users/callen/.gimme/versions/go1.7.1.darwin.amd64/src/github.com/mattn/go-zglob/fastwalk (from $GOROOT)
	/Users/callen/src/src/github.com/mattn/go-zglob/fastwalk (from $GOPATH)
```

Looks like https://github.com/mattn/go-zglob/commit/760b124c0122b6d6df6e29c8e4074ac84b831d20 is the culprit

**Comment by markbates** [comment]
Looks like @mattn broke his package a few minutes ago. Looks like he's missing a sub package that he's referencing. 

I'll open an issue on his repo.

**Comment by markbates** [comment]
Looks like @mattn fixed this. So it should be good now.

**Comment by curtisallen** [comment]
Confirmed able to go get buffalo now thanks!
