### ISSUE TITLE
Proposal:  allow one to remove a resource as easily as creating it

### ISSUE THREAD

**Issue by conradwt** [gobuffalo/buffalo#1111]
I would like to propose the following:

Given the following generator command

```
buffalo generate resource person first_name last_name email username
```

One should be able to remove it by simply saying without

```
buffalo destroy resource person
```

At this time, the above would require permission for each file which needs to get deleted or modified by the user.  Otherwise, require -y and the end of the command which is required when creating the resource.

**Comment by stanislas-m** [comment]
Hello @conradwt, I don't understand your issue. The `buffalo destroy resource` command should solve that, and you can use the `-y` flag already to confirm all deletion.

Is there anything missing for this command?

**Comment by conradwt** [comment]
@stanislas-m It would be nicer if I didn't have to respond to N different prompts and it would similar to the generate command.

**Comment by kteb** [comment]
@conradwt what statislas said is that `buffalo destroy resource -y person` will delete everything without asking you any details. I think it's good that by default we ask if we want to delete files before doing it (we might want to delete the resource but not the model for example. 

Could we close the issue ?

**Comment by conradwt** [comment]
@kteb Thanks for clarifying the use case and this issue can be closed.
