### ISSUE TITLE
Proposal: Please make a step-by-step tutorial on using writing associations and relations in buffalo

### ISSUE THREAD

**Issue by aramadsanar** [gobuffalo/buffalo#1115]
Hi,

Please make a step-by-step tutorial on using writing associations and relations with pop. The demo video of the feature on this page (https://gobuffalo.io/en/docs/db/relations) is stellar, yet needs more comprehension and explanation on how to build such a relationship to help new users (like me) to adapt with buffalo easily.

Thanks

**Comment by stanislas-m** [comment]
This is related to the docs site, I'm moving your issue there. :)
