### ISSUE TITLE
Proposal: Support for yarn builds

### ISSUE THREAD

**Issue by dnnrly** [gobuffalo/buffalo#1116]
As a developer
I would like to build my frontend assets with yarn
So that I can use the same workflow I familiar with, reusing code from other codebases

<hr />

There are only 3 sub-commands that need to worry about yarn. `build` and `dev` obviously but also `test` should be considered.

Using yarn for building assets means defining entries under the `scripts` object. Let's just call them:

* `buffalo:build` -> `webpack -p --progress`
* `buffalo:dev` -> `webpack --watch`
* `buffalo:test` - will have to think about this one

These would be inserted in to the `package.json` template but only if Yarn is enabled. We could just assume that if you want to perform a yarn build, you must support those scripts.

Adding scripts to `package.json` means that upgrades will require a change to the template of that file. Unless we are somehow able to parse and dynamically add those scripts to the file, we'll have to use the `upgrade` sub command to overwrite it with the new version.

For plumbing in the commands that Buffalo will invoke, we know whether yarn is installed, running `yarn run` will display the available scripts. We can parse this output for the relevant entries.
For `build`, we need to modify `./cmd/build.buildAssets` to test for `buffalo:build` if we have yarn.
For `dev`, we need to modify `./cmd.startWebpack` for `buffalo:dev`.
The tricky one is `test` as this doesn't currently support testing assets. To achieve this we would need to use a similar approach to `dev` so checking for the presence of yarn and it's scripts. If they are there, we can run the command and test it's output.

**Comment by stanislas-m** [comment]
Fixed with #1718
