### ISSUE TITLE
project init with sqlite3 , buffalo dev fail

### ISSUE THREAD

**Issue by kadevland** [gobuffalo/buffalo#1124]
## Steps to Reproduce the Problem

i have installed Buffalo with sqlite3.
i have create project with  buffalo new coke --db-type sqlite3 --bootstrap 4

when lauch buffalo dev i have 

buffalo: 2018/06/21 22:02:10 === Error! ===
buffalo: 2018/06/21 22:02:10 === exit status 1
can't load package: package sqlite: cannot find package "sqlite" in any of:
	/usr/local/go/src/sqlite (from $GOROOT)
	$Home/workspaces/golang/src/sqlite (from $GOPATH)
can't load package: package -o: cannot find package "-o" in any of:
	/usr/local/go/src/-o (from $GOROOT)
	$Home/workspaces/golang/src/-o (from $GOPATH)
can't load package: package tmp/coke-build: cannot find package "tmp/coke-build" in any of:
	/usr/local/go/src/tmp/coke-build (from $GOROOT)
	$Home/workspaces/golang/src/tmp/coke-build (from $GOPATH)

## Info

Please run `buffalo info` and paste the information below where it says "PASTE_HERE".

<details>

```
### Buffalo Version
v0.12.0

### App Information
Pwd=$Home/workspaces/golang/src/buffalotest/coke
Root=$Home/workspaces/golang/src/buffalotest/coke
GoPath=$Home/workspaces/golang/
Name=coke
Bin=bin/coke
PackagePkg=buffalotest/coke
ActionsPkg=buffalotest/coke/actions
ModelsPkg=buffalotest/coke/models
GriftsPkg=buffalotest/coke/grifts
VCS=git
WithPop=true
WithSQLite=true
WithDep=false
WithWebpack=true
WithYarn=true
WithDocker=true
WithGrifts=true

### Go Version
go version go1.10.3 linux/amd64

### Go Env
GOARCH="amd64"
GOBIN=""
GOCACHE="$Home/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="$Home/workspaces/golang/"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build221097587=/tmp/go-build -gno-record-gcc-switches"

### Node Version
v8.11.3

### NPM Version
6.1.0

### Yarn Version
1.7.0

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file

```

</details>

**Comment by markbates** [comment]
Closing as this is a duo of https://github.com/gobuffalo/buffalo/issues/1114
