### ISSUE TITLE
Plugin command to create linux binaries

### ISSUE THREAD

**Issue by drnic** [gobuffalo/buffalo#1128]
I needed to create linux binaries for production deployment. Fortunately we already have a `Dockerfile` that does all the heavy lifting (omg I wish `dep ensure` could do its job faster). Unfortunately the resulting binary is locked inside the docker image. I've written a plugin shell script in my app. Is this a good/right approach or is there a "buffalo-way" for doing this?

```bash
#!/bin/bash

# plugins/buffalo-build-linux.sh

command=$1
case $command in
  available)
    cat <<-JSON
[{"name": "build-linux", "buffalo_command": "root", "description": "Create and export linux binary"}]
JSON
    ;;
  build-linux)
    BUILDIMAGE=${BUILDIMAGE:-$(basename $PWD)}
    docker build -t $BUILDIMAGE .
    mkdir -p tmp
    rm -rf tmp/app{,.zip}
    docker rm -f $BUILDIMAGE
    docker container create --name $BUILDIMAGE $BUILDIMAGE
    docker container cp $BUILDIMAGE:/bin/app tmp/app
    docker rm -f $BUILDIMAGE
    cd tmp
    zip app.zip app
    ;;
  *)
    echo "USAGE: buffalo build-linux"
    exit 1
    ;;
esac
```

**Comment by robbyoconnor** [comment]
Doesn't buffalo-build create it already?

**Comment by drnic** [comment]
Yes, the plugin above is for deploying from local machine. Some people don't setup CI straight away. Or worse, they delay deploying into prod environments until they can get around to both setting up a prod env + setting up CI. I was writing this plugin as part of a "how to deploy to Cloud Foundry (from local machine)" blog post, and wanted to confirm there wasn't a different/better way from local non-linux machines.

**Comment by markbates** [comment]
Could you do `GOOS=linux buffalo build`? That would build a linux buffalo binary for you.

**Comment by kteb** [comment]
@drnic did you see the last comment of Mark ? I think this is the simplest way of doing it, could we close the issue ?
