### ISSUE TITLE
Buffalo sub-commands unavailable

### ISSUE THREAD

**Issue by bscott** [gobuffalo/buffalo#113]
I've noticed that when I an running "buffalo dev" some sub-commands give a timeout error such as the generators, until I stop the buffalo dev server. 

```
$ buffalo g --help
timeout
```

```
$ buffalo g resource hosts
timeout
```

Is this due to the generators needing access to the database?

**Comment by apaganobeleno** [comment]
may this be related with #67 ?

**Comment by bscott** [comment]
Thanks @apaganobeleno

**Comment by markbates** [comment]
Closing as a dup of #67
