### ISSUE TITLE
Huge base image for Dockerfile

### ISSUE THREAD

**Issue by drnic** [gobuffalo/buffalo#1130]
Generated `buffalo new` projects include a `Dockerfile` that starts with:

```dockerfile
FROM gobuffalo/buffalo:v0.12.0 as builder
```

This image is huge at almost 2G:

```
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
gobuffalo/buffalo                          v0.12.0             cfb25fd09a5a        8 days ago          1.89GB
```

Which is the source `Dockerfile` for this image? Could we make it much much smaller?

I was looking to reuse this Dockerfile + therefore upstream `gobuffalo/buffalo:v0.12.0` for my CI, but am weary of its huge size.

**Comment by robbyoconnor** [comment]
I'll PR it -- I see a few areas where it's lacking: 

- Packages need to be installed in one layer and cleaned up in the same layer
- We could use a smaller base that isn't Ubuntu such as alpine

**Comment by robbyoconnor** [comment]
You can see the problem in the dockerfile: https://github.com/gobuffalo/buffalo/blob/master/Dockerfile.build

There is absolutely zero cleanup done -- the cache from apt remains in the image -- remember -- package installs and cleanup has to happen in the same layer -- things are immutable and you cannot go back and clean up easily.

**Comment by drnic** [comment]
@robbyoconnor thx for link to which Dockerfile is being used. Yeah, probably best first steps is combining the RUN's and cleaning the apt cache.

**Comment by drnic** [comment]
@robbyoconnor tame that Dockerfile!

**Comment by robbyoconnor** [comment]
https://github.com/gobuffalo/buffalo/pull/1132

**Comment by robbyoconnor** [comment]
Still cleaner and better: 


b                                                                          latest              3eb5389a30d2        6 seconds ago       1.87GB

**Comment by robbyoconnor** [comment]
Unfortunately -- I'm constrained by the base golang image -- rest assured that this is only used during the bulld stage and you never deploy using this image.

**Comment by robbyoconnor** [comment]
Okay so this being huge doesn't really matter too much -- it's only used during the build and essentially thrown away however I did as much as I could...the base image is already 570MB.

**Comment by drnic** [comment]
I'll close this for now.

**Comment by robbyoconnor** [comment]
There's not much more I can do to get the size down...I did all I could...pulled as many tricks as I could.
