### ISSUE TITLE
Package buffalo app with goreleaser

### ISSUE THREAD

**Issue by Oliveirakun** [gobuffalo/buffalo#1139]
Hi everyone,
I'm trying to package a buffalo app with goreleaser. To build a buffalo app binary I run `buffalo build`, but goreleaser only runs `go build`  with some arguments and I can't change it to run `buffalo build`. Anyone knows how to package a buffalo app with goreleaser?

**Comment by caarlos0** [comment]
I think that right now that's not possible. We could, however, experiment with goreleaser and add a `buffalo` builder or something like that...

I never used buffalo, so I don't really know how `buffalo build` works... but it may be feasible.

PS: as a workaround, maybe `alias go=buffalo` and then calling `goreleaser` works?
