### ISSUE TITLE
Correct Content-Type/Accept header usage

### ISSUE THREAD

**Issue by duckbrain** [gobuffalo/buffalo#1148]
I don't understand the purpose of SetContentType for API's. It overrides the *request's* content type. [#1093](https://github.com/gobuffalo/buffalo/issues/1093#issuecomment-395971816) Makes me think maybe the `Accept` header was intended.

Anyway, this was causing problems with File uploads because the request's content type was always `application/json` (for PUT requests, but not POST requests?), not `multipart/form-data`. Changing it to AddContentType makes it work fine.

I have a patch ready to go to replace it with AddContentType (it's 3 characters), but I wanted some clarification on the purpose before sending a pull request. AddContentType makes more sense to me because it still respects the client's type and doesn't cause conflicts with File uploads and such.

## Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. Generate a new project with the `--api` flag
  1. Add a PUT route with a file upload
  1. Start the server and upload a file

```bash
buffalo new test --api --skip-pop; cd test
buffalo g action upload UploadTest --method PUT --skip-template
vim actions/upload.go
buffalo dev
```

New contents for actions/upload.go

```go
package actions

import "github.com/gobuffalo/buffalo"

// UploadUploadTest default implementation.
func UploadUploadTest(c buffalo.Context) error {
	c.Logger().Debug(c.Request().Header.Get("Content-Type"))
	if _, err := c.File("file"); err != nil {
		return err
	}
	return c.Render(200, r.HTML("upload/upload_test.html"))
}
```

## Expected Behavior

I expect that it fails to display upload/upload_test.html after succeeding to parse the uploaded file

## Actual Behavior

It logs `application/json` to the debug log and errors out with `request Content-Type isn't multipart/form-data`

If I go into `actions/app.go` and change the middleware out, it starts working.

## Info

<details>

```
### Buffalo Version
v0.12.3
### App Information
Pwd=/home/jonathan/src/git.ec2software.com/jonathan/test
Root=/home/jonathan/src/git.ec2software.com/jonathan/test
GoPath=/home/jonathan
Name=test
Bin=bin/test
PackagePkg=git.ec2software.com/jonathan/test
ActionsPkg=git.ec2software.com/jonathan/test/actions
ModelsPkg=git.ec2software.com/jonathan/test/models
GriftsPkg=git.ec2software.com/jonathan/test/grifts
VCS=git
WithPop=false
WithSQLite=false
WithDep=false
WithWebpack=false
WithYarn=false
WithDocker=true
WithGrifts=true
### Go Version
go version go1.10.3 linux/amd64
### Go Env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jonathan/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jonathan"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build564953439=/tmp/go-build -gno-record-gcc-switches"
### Node Version
v9.11.2
### NPM Version
5.6.0
### Yarn Version
1.7.0
### PostgreSQL Version
PostgreSQL Not Found
### MySQL Version
mysql  Ver 15.1 Distrib 10.1.34-MariaDB, for Linux (x86_64) using readline 5.1
### SQLite Version
3.24.0 2018-06-04 19:24:41 c7ee0833225bfd8c5ec2f9bf62b97c4e04d03bd9566366d5221ac8fb199a87ca
### Dep Version
could not find a Gopkg.toml file
### Dep Status
could not find a Gopkg.toml file
```

</details>

**Comment by markbates** [comment]
For a whole host of reasons, all of which are easily fixable, content type is pulling double duty. It needs to be fixed everywhere and replaced with content type in and accept for out. A PR that fixes is all, would be very much. 

A PR to switch to Add from Set wouldn’t be. Partially because the content/accept stuff is held together with duct tape and chewing gum, but also because for 90% of the uses Set is what people want. 

Again, what it’s doing isn’t correct, but it’s achieving the goal of regardless of how you call the app it’s responsing with json, which is most of the time what people want. It also covers the cases with bad actors like browsers making a request. They’ll set a type of text/html and that’s how the app will respond, which is wrong. Which is why there’s the set. 

The currently approach to handling mixed requests like yours it is a custom middleware or using Add; but the correct solution is fixing the accept problem. Then Set goes away, and Add is all that’s needed. 

Probably not the answer you’re looking for, but it’s an honest one. 

Whoever steps up and properly fixes it will get the undying love of this community. :)

**Comment by duckbrain** [comment]
It looks like found a few places that would be a good place to start.

- $GOPATH/src/github.com/gobuffalo/x/responder/responder.go
- $GOPATH/src/github.com/gobuffalo/x/httpx/content_type.go
- $GOPATH/src/github.com/gobuffalo/buffalo/middleware/csrf/csrf.go

So I'm clear, a solution would be to fix the internal workings, so Accept is exclusively used to determine the response type, and Content-Type is used to parse the request. Then it would be appropriate to have middleware for API's that Adds the Content-Type and Sets the Accept of JSON.

I would love to take this on; it'll be a few weeks before I can get to it.

**Comment by markbates** [comment]
Yep. We need to think about how this would affect existing applications and see if there's anything that needs migrating or not. It's all. yours when you're to work on it. :)

**Comment by duckbrain** [comment]
Looks like I'm just starting down the rabbit hole. I started looking into [format for the `Accept` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept). I found that [GoDoc.org's source code](https://github.com/golang/gddo/blob/master/httputil/negotiate.go) has an implementation of parsing and negotiating the `Accept` header, using a list of accepted MIME types and a default. Then I got curious about browser support.

- https://www.keithcirkel.co.uk/the-ups-and-downs-of-the-http-header/#accept-the-biggie
- https://www.newmediacampaigns.com/blog/browser-rest-http-accept-headers

I found some sources that say that a few browsers don't give a very good `Accept` header, the big challenge in our case, is that several of them prioritize XML over HTML. IE [doesn't request HTML at all](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values), but also doesn't request XML or JSON. GoDoc.org only supports plain text and html, so it's no problem for them.

I'm thinking the best solution is to have it give HTML if it's in the `Accept` header at all, then negotiate normally after that. I would think most clients that manually set `Accept` headers for API's accept one type.

---------

@markbates, in a [recent blog post](https://blog.gobuffalo.io/the-road-to-1-0-the-beginnings-34bc5e7603d2#a687) talking about plugins, you mentioned moving some of the functionality from Buffalo to plugins. As I understand it, this means completely decoupling plush and buffalo, instead having the plugin tie the hooks. 

One thought I had for a long-term improvement with APIs was having `buffalo new` generate code that adds Plush to the Buffalo app. Plush would then register as an HTML handler for Buffalo. This way, API projects could just exclude that generated code. Similar to currently excluding pop. Then the `SetContentType` would be unnecessary anyway, but it could still be fixed without breaking apps or needing migration twice.

It mostly works now, would it be better to wait?

**Comment by markbates** [comment]
I loved everything up to the bit about Plush. :)

It’s going to be a while before we get everything split out, and even still I imagine it will also be imported by buffalo so we can use it for generation and stuff, even if the end app doesn’t use it.

If you have a path for us to get to working accept/content headers, without breaking compatibility, then please, please, please add it. :)

--
Mark Bates

**Comment by leodotcloud** [comment]
`middleware.SetContentType("application/json")` is working on `buffalo.Context` but `func (e *Engine) Auto(ctx context.Context, i interface{}) Renderer {` uses context.Context to figure out the Content Type. This is a mismatch which will cause spurious results.

**Comment by leodotcloud** [comment]
Creating my own middleware with the following worked for me:
```
// SetContentType on the request to desired type. This will
// override any content type sent by the client.
func SetContentType(s string) buffalo.MiddlewareFunc {
	return func(next buffalo.Handler) buffalo.Handler {
		return func(c buffalo.Context) error {
			c.Set("contentType", s)
			return next(c)
		}
	}
}
```

**Comment by duckbrain** [comment]
I've been busy with life for the past few months, but I'm going to look at this again.

@leodotcloud The problem is that the request's `Content-Type` *is* currently being used to negotiate the response `Content-Type`, but it should be the request's `Accept` header. However, using a middleware that overwrites it can cause conflicts with other libraries that expect to use the request's `Content-Type` for it's correct use, determining the type of the request body.

v0.13.0's [Override Content Type for Render#Auto](https://blog.gobuffalo.io/buffalo-v0-13-0-released-eac17c4cc4fa#a2fe) is a great step in the right direction, but is only part way there.

I don't know of a completely backwards compatible way to fix this. Anyone overwriting the request's content type to change `Auto`'s behavior would be affected if it's suddenly not used. I'll see if I can get a WIP MR up today or tomorrow.

**Comment by paganotoni** [comment]
@duckbrain @markbates @leodotcloud does this one still need work? I ask because I see a couple of related PRs

**Comment by leodotcloud** [comment]
I haven't worked on this for quite some time, so no idea @paganotoni.

**Comment by duckbrain** [comment]
@paganotoni  Yes it does. The merged PR was updating tests to assert it working using `Accept` instead of `Content-Type`. I also just worked around it by changing to a custom middleware.

I believe the following changes would fix it, but either one of these change would be backwards incompatible.

1. Use *only* `Accept` for determining the response `Content-Type`. Default to HTML.
   - If any consumers of API projects are sending `Content-Type` on their requests, expecting to get that back as a response, it will no longer work. A middle-ground may be prioritizing `Accept` over `Content-Type`, but still considering it.
   - Detecting and displaying a deprecation notice could be a useful way to handle that too. Logger and [HTTP header](https://stackoverflow.com/a/29623798/253298)?
2. Replace the middleware that changes `Content-Type` with some other way that API projects exclude HTML from their `Accept` resolution. Then the default would then be JSON if `Accept` is not matched.
