### ISSUE TITLE
go.rice requirement in build

### ISSUE THREAD

**Issue by slava-vishnyakov** [gobuffalo/buffalo#115]
The docs say:

```go
The buffalo build command will build the asset pipeline, and properly attach it to the 
generated Go binary. One binary to run them all!
```

However, when I try to run the resulting binary, I get:

```go
panic: could not locate box "../public/assets"
```

which traces back to

```go
box := rice.MustFindBox("../public/assets")
```

It seems that:

1) `go.rice` binary is not installed;
2) this error is ignored during `build`: https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/build.go#L129

I'd say that probably this need to have an error that `rice` is not installed / executable, maybe something like:

```go
fmt.Println("`rice` command is not found, you can install it with\n" +
   "go get github.com/GeertJohan/go.rice\n"+
   "go get github.com/GeertJohan/go.rice/rice")
```

(And probably updated docs would be nice)

**Comment by slava-vishnyakov** [comment]
(And BTW, I ❤️ GoBuffalo! It's definitely the most usable framework I've seen in Go)

**Comment by markbates** [comment]
That `err` is not ignored, it's quite the opposite. If that error is `nil` it means rice is installed and we can continue. The error you're getting is this:
https://github.com/gobuffalo/buffalo/issues/104

It's fixed in the upcoming release.

**Comment by slava-vishnyakov** [comment]
Excellent! Thank you for all your work! 👍
