### ISSUE TITLE
Unable to install buffalow in ubuntu 

### ISSUE THREAD

**Issue by nwoow** [gobuffalo/buffalo#1151]
I am trying to use buffalow in my ubuntu but I don't see any instruction `https://github.com/gobuffalo/buffalo` Here I can just see this:

`$ go get -u -v github.com/gobuffalo/buffalo/buffalo`

In my terminal I am running this command it is downloading everything but buffalow command is not working. 

Please add the simplest steps in your doc for ubuntu how to add path and other thing. This is not an issue but it needs attention. I am new to go and I am trying to find a rails like framework.

**Comment by kteb** [comment]
The command is supposed to be `buffalo` not `buffalow` is this the error?

Is your go setup working?

**Comment by nwoow** [comment]
My go was not setup correctly in my terminal I guess that was the problem.

**Comment by nwoow** [comment]
I am getting this error : The standard location for putting Go projects is something along the lines of "$GOPATH/src/github.com//test" (adjust accordingly).

**Comment by stanislas-m** [comment]
Hello @nwoow, please follow the instructions on this page: https://gobuffalo.io/en/docs/installation#requirements

Make sure your Go env is configured properly, and you're working in a `$GOPATH`, it won't work otherwise.

**Comment by hubyhuby** [comment]
Hi @nwoow ,
I am using Ubuntu 18.04 and got it to work perfectly (I am on 0.11 at the moment).
Here is my .profile : 

export GOPATH=/home/Thatsme/Documents/projects
export GOROOT=/usr/lib/go-1.10
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

Let me know if that works for you. 
Note that you can always reach helpful persons on slack.

**Comment by stanislas-m** [comment]
@nwoow Did you solve your problem?

**Comment by stanislas-m** [comment]
I'm closing this issue since you managed to install buffalo (according to #1152). The docs on the website already describe how to install buffalo on Linux, and the Readme on the dev branch was updated to refer to the website as the "single source of truth".

Feel free to open a new issue on https://github.com/gobuffalo/gobuffalo/issues if some docs are missing, or here if something is not working.
