### ISSUE TITLE
Unable to run buffalo

### ISSUE THREAD

**Issue by nwoow** [gobuffalo/buffalo#1152]
I am new to buffalo I have install go and then buffalo I have created a new application using buffalo new test but when I am trying to run my application using buffalo dev I am getting error. In html I am getting this error:

`500 - ERROR!
Error Trace

And in my terminal I am getting this error:
`ERRO[2018-06-30T13:58:30+05:30] couldn't start a new transaction: could not create new transaction: dial tcp 127.0.0.1:5432: connect: connection refused content_type=text/html duration="320.235µs" human_size="0 B" method=GET params="{}" path=/ request_id="272df66b25-e75e1224c7" size="0" status="0"
ERRO[2018-06-30T13:58:30+05:30] could not find favicon.ico
`

**Comment by kteb** [comment]
Did you check your database.yml ? 

Did run `buffalo db create` and `buffalo db migrate`? 

Maybe join slack for this kind of question: https://gobuffalo.io/en/docs/slack

**Comment by stanislas-m** [comment]
@nwoow make sure to follow https://gobuffalo.io/en/docs/db#configuration

**Comment by markbates** [comment]
I'm closing this issue for now as it appears to be an environmental issue. Please re-open if the problem persists after starting Postgres. Thanks.
