### ISSUE TITLE
GoFish based starter for initial install

### ISSUE THREAD

**Issue by gedw99** [gobuffalo/buffalo#1158]
GoFish is the equivalent of HomeBrew, BUT built with golang and works on Windows, Mac and Linux.

https://github.com/fishworks/gofish

There are many golang projects packaged for it now included Kubernettes minikube and about 15 more.

How do you install gofish though ?
its a curl also. Catch 22 :)

**Comment by duffn** [comment]
I've submitted a PR to gofish for Buffalo: https://github.com/fishworks/fish-food/pull/70

**Comment by bacongobbler** [comment]
thanks @duffn! buffalo should now be available via `gofish install buffalo`. This ticket can be closed. :)

**Comment by stanislas-m** [comment]
:tada:
