### ISSUE TITLE
Pop doesn't use `AS` name in the Where clause

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo#1160]
## Steps to Reproduce the Problem

1. Created a model called MyModel which references a table (that exists) in a separate schema called `otherschema`.

2. In order to specify that that table is in a separate schema i did implemented the TableNameAble interface in my model like by adding respective method like:

```go
func (mm *MyModel) TableName() string {
	return "otherschema.my_models"
}
```

## Expected Behavior

If i run something like:

```go
err := tx.Where("email = ?", strings.ToLower(mm.Email)).First(mm)
```

Pop should create the following query:

```sql
SELECT otherschema_my_models.created_at, otherschema_my_models.name ...
FROM otherschema.my_models AS otherschema_my_models  
WHERE otherschema_my_models.email = $1 LIMIT 1 $1=aaa@ww.com
```

Notice the `AS` name in the `WHERE` clause.

If i run something like:

```go
err := tx.Find(mm, mm.ID)
```

Pop should create the following query:

```sql
SELECT otherschema_my_models.ID, otherschema_my_models.created_at,...
FROM otherschema.my_models AS otherschema_my_models  
WHERE otherschema_my_models.id = $1 LIMIT 1 $1=[UUID]
```

## Actual Behavior

On the first query it works but you can notice it doesn't use the `AS` name:

```sql
SELECT otherschema_my_models.created_at, otherschema_my_models.name 
FROM otherschema.my_models AS otherschema_my_models  
WHERE email = $1 LIMIT 1 $1=aaa@ww.com
```

But on the second:

```sql
SELECT otherschema_my_models.ID, otherschema_my_models.created_at,...
FROM otherschema.my_models AS otherschema_my_models  
WHERE otherschema.my_models.id = $1 LIMIT 1 $1=[UUID]
```

Pop uses the `TableName` instead of the `AS` name and postgres doesn't like the query by saying:

```
ERROR: invalid reference to FROM-clause entry for table "my_models"
HINT:  Perhaps you meant to reference the table alias "otherschema_my_models".
```

**Comment by stanislas-m** [comment]
Moved to https://github.com/gobuffalo/pop/issues/175
