### ISSUE TITLE
ServeFiles trailing slash

### ISSUE THREAD

**Issue by 1995parham** [gobuffalo/buffalo#1164]
In [`ServeFiles`](https://github.com/gobuffalo/buffalo/blob/25619606ab2ac525ee38a07a15bfcffc832125b4/router.go#L85), `path.Join` remove the trailing slash so when you passing it into `http.StripPrefix` it needs the trailing slash for correctly strip the prefix based on [this](https://godoc.org/net/http#StripPrefix).

**Comment by Shivakishore14** [comment]
@1995parham can you provide a test case where it fails ?

**Comment by 1995parham** [comment]
Following setup did not work for me in order to access files in `cdn` folder:

```go
app.ServeFiles("/cdn/", http.Dir("/cdn"))
```

**Comment by Shivakishore14** [comment]
I think #955 issue refers the same issue. 
Ideally PR #1137 should fix this issue. I am not sure if this issue is being looked into in that PR.
@markbates you might want to take a look at this.

**Comment by 1995parham** [comment]
Yes, I agree with PR #1137 and I think it will fix my issue. thank you very much 🙌

**Comment by markbates** [comment]
@Shivakishore14 I don’t understand all these / issues. Sorry. To me you just strip the slash before servefiles and it works. Well, for me it works fine out of the box. So none of this makes sense to me. 

No one has yet to lay out a clear test cases and use cases that make me think the answer is more than just remove the /. 

Clearly there’s a problem, but asking me to solve a problem I don’t understand isn’t a smart idea. 

If there really is a problem, which people keep claiming there is, someone needs to do a better job of communicating it clearer. Saying this code doesn’t work, but it doesn’t tell me the problem set. 

When someone opens a PR that has all that it will most likely get merged, but it’s not coming from me. I need the community to solve this one.
