### ISSUE TITLE
Can't use "net/http/pprof" in buffalo?

### ISSUE THREAD

**Issue by dreampuf** [gobuffalo/buffalo#1165]
"net/http/pprof" initializes the views into default HTTP server when `init` func execution. buffalo.app has its own server instance. The debug request will fail if you mount it into buffalo app in a normal way. I have to say eat the last slash is a bad idea.

```
// failed when buffalo eat the last slash.
func initDebugHandler(app *buffalo.App) {
	app.Mount("/debug/pprof/", http.HandlerFunc(pprof.Index))
	app.Mount("/debug/pprof/cmdline", http.HandlerFunc(pprof.Cmdline))
	app.Mount("/debug/pprof/profile", http.HandlerFunc(pprof.Profile))
	app.Mount("/debug/pprof/symbol", http.HandlerFunc(pprof.Symbol))
	app.Mount("/debug/pprof/trace", http.HandlerFunc(pprof.Trace))
}
```

**Comment by markbates** [comment]
First, please keep comments like the last sentence out of a bug report. It’s not helpful to the conversation.

Now, on to the problem. I run net pprof all the time with standard instructions https://golang.org/pkg/net/http/pprof/

There is also a server API to let you add any servers you want https://godoc.org/github.com/gobuffalo/buffalo/servers

I’m closing this as it’s definitely possible to run it. If there’s something, that’s unrelated to stripping of slashes, there are tickets already for that, please reopen.
