### ISSUE TITLE
One of Time Formats in binding is Illogical

### ISSUE THREAD

**Issue by Mohammed90** [gobuffalo/buffalo#1169]
The following registered format doesn't make sense to have it:
https://github.com/gobuffalo/buffalo/blob/25619606ab2ac525ee38a07a15bfcffc832125b4/binding/binding.go#L33

It loses the information of which half of the day it's part of (AM or PM). Either the format `2006-01-02T15:04` should be added to the list, or the format is replaced with `2006-01-02T15:04`.

I'll get back to fix this once I'm done with the project at hand. Meanwhile, which solution is preferred?

**Comment by paganotoni** [comment]
I think you’re right, are you willing to send a PR for this?

**Comment by paganotoni** [comment]
I think is ok to replace it, no breaking change in that.
