### ISSUE TITLE
Logger does not get proper status when calling c.Error

### ISSUE THREAD

**Issue by marwan-at-work** [gobuffalo/buffalo#1171]
Code to reproduce: 

create a simple buffalo app with a handler that returns `c.Error(500, err)` 

Make sure you pass your own logger to the `App.Logger` field. 

Note that when `WithFields` or `WithField` is called, you never get the `500` status. 

If you do normal `c.Render(status, ...)` then you actually get the appropriate status. 

This is because `c.Error` does not call `c.Response().WriteHeader`. And so, all the middlewares are called first (including the logging middleware), and only after that does the errorHandler call `WriteHeader`

Update: this can also apply to a notFoundHandler, the logger should be able to receive the path params to a route that does not have a handler.

**Comment by markbates** [comment]
Is this  still an issue ?

**Comment by Max-Pol** [comment]
Still an issue, even with the default logger: when `c.Error()` is called, there are actually 2 logs (1 ERROR and 1 INFO) and none of them have a `status`.

**Comment by paganotoni** [comment]
This one was fixed in `v0.16.4` please reopen if still relevant.
