### ISSUE TITLE
Add Benchmarks

### ISSUE THREAD

**Issue by paulZzhang** [gobuffalo/buffalo#1179]
Add Benchmarks. The performance and development efficiency are equally important.

eg.[Benchmarks](https://github.com/gin-gonic/gin/blob/master/BENCHMARKS.md)

**Comment by markbates** [comment]
We won’t be adding benchmarks here. Third parties can write up benchmarks, but we’ve long said no benchmarks. http://www.metabates.com/2017/03/03/youre-benchmarking-the-wrong-thing/
