### ISSUE TITLE
bootstrap@4.1.1" has unmet peer dependency "popper.js@^1.14.3".

### ISSUE THREAD

**Issue by paulZzhang** [gobuffalo/buffalo#1180]
`buffalo new mall --db-type mysql --bootstrap 4`

`warning " > bootstrap@4.1.1" has unmet peer dependency "popper.js@^1.14.3".`

PS C:\gopath\src> buffalo info
### Buffalo Version
v0.12.3

### App Information
Pwd=C:\gopath\src
Root=C:\gopath\src
GoPath=C:\gopath
Name=src
Bin=bin\src.exe
PackagePkg=src
ActionsPkg=src/actions
ModelsPkg=src/models
GriftsPkg=src/grifts
VCS=
WithPop=false
WithSQLite=false
WithDep=false
WithWebpack=false
WithYarn=false
WithDocker=false
WithGrifts=false

### Go Version
go version go1.10.1 windows/amd64

### Go Env
set GOARCH=amd64
set GOBIN=C:\gopath\bin
set GOCACHE=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\gopath
set GORACE=
set GOROOT=C:\go
set GOTMPDIR=
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\zlf\AppData\Local\Temp\go-build474805102=/tmp/go-build -gno-record-gcc-switches

### Node Version
v8.11.3

### NPM Version
5.6.0

### Yarn Version
1.7.0

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt2

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file

**Comment by robbyoconnor** [comment]
Make a PR ;)
