### ISSUE TITLE
Buffalo dev with ADDR keeps showing 127.0.0.1

### ISSUE THREAD

**Issue by jtorvald** [gobuffalo/buffalo#1181]
## Steps to Reproduce the Problem

When I use .env to set ADDR or I run buffalo dev with ADDR=0.0.0.0 buffalo dev I keep seeing:  level=info msg="Starting application at http://127.0.0.1:3000"
After trying I figured out that it actually works and it is just a wrong debug message. So this is a minor issue.

## Expected Behavior

If I config: ADDR=0.0.0.0 I expect to see
level=info msg="Starting application at http://0.0.0.0:3000"

## Actual Behavior

If I config: ADDR=0.0.0.0 I see
level=info msg="Starting application at http://127.0.0.1:3000"

When I change the PORT=3001 it works, but not for the address

## Info

Buffalo version is: v0.12.2

**Comment by stanislas-m** [comment]
Fixed with #1183.
