### ISSUE TITLE
Update Buffalo Windows (scoop)

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#1182]
From https://github.com/gobuffalo/pop/issues/174:

The current Buffalo packaged version (the related issue is about `scoop`, but I think all pre-compiled versions are affected) is built against an old version of pop with major fizz issues.

A new version should be released.

**Comment by paulZzhang** [comment]
@stanislas-m Please update it as soon as possible. The Windows Platform is very bad.

**Comment by markbates** [comment]
@stanislas-m I don’t know anything about scoop. What do you need me to do?

**Comment by stanislas-m** [comment]
@markbates Scoop uses a manifest: https://github.com/lukesampson/scoop/blob/master/bucket/buffalo.json

It's based on the Github releases, so we need to recompile buffalo to use the pop fixed version. :)

**Comment by markbates** [comment]
Do we need to recut 0.12.3 or cut a 0.12.4 from master (ie zero changes, just nw binaries)?

I’m leaving today for vacation, so I need to know ASAP what’s going on with this.

Thanks.

--
Mark Bates

**Comment by stanislas-m** [comment]
Hum, let's just cut a 0.12.4 from master. Changing a released version will just confuse the users. :)

**Comment by stanislas-m** [comment]
Thanks @markbates!

**Comment by markbates** [comment]
Ok. Stuff like this is a another good reason to move sub commands to plugins. :)

--
Mark Bates

**Comment by paganotoni** [comment]
i'm up to help on this movement! :)
