### ISSUE TITLE
warning: LF will be replaced by CRLF and Special characters appear

### ISSUE THREAD

**Issue by paulZzhang** [gobuffalo/buffalo#1189]
PS C:\gopath\src> buffalo new --api demo2 --db-type mysql
      create  .buffalo.dev.yml
      create  models/models.go
      create  models/models_test.go
      create  grifts/db.go
         run  go get github.com/gobuffalo/pop/...
      create  ./database.yml
         run  gofmt -w C:\gopath\src\demo2\grifts\db.go C:\gopath\src\demo2\models\models.go C:\gopath\src\demo2\models\models_test.go
      create  Dockerfile
      create  .dockerignore
         run  go get -u golang.org/x/tools/cmd/goimports
      create  README.md
      create  actions/render.go
      create  .env
      create  fixtures/sample.toml
      create  actions/actions_test.go
      create  .codeclimate.yml
      create  inflections.json
      create  main.go
      create  actions/app.go
      create  actions/home.go
      create  actions/home_test.go
      create  grifts/init.go
         run  go get -t ./...
         run  gofmt -w C:\gopath\src\demo2\actions\actions_test.go C:\gopath\src\demo2\actions\app.go C:\gopath\src\demo2\actions\home.go C:\gopath\src\demo2\actions\home_test.go C:\gopath\src\demo2\actions\render.go C:\gopath\src\demo2\grifts\db.go C:\gopath\src\demo2\grifts\init.go C:\gopath\src\demo2\main.go C:\gopath\src\demo2\models\models.go C:\gopath\src\demo2\models\models_test.go
      create  .gitignore
         run  git init
Initialized empty Git repository in C:/gopath/src/demo2/.git/
         run  git add .
warning: LF will be replaced by CRLF in .buffalo.dev.yml.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in .codeclimate.yml.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in .dockerignore.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in Dockerfile.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in actions/actions_test.go.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in actions/app.go.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in actions/home.go.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in actions/home_test.go.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in actions/render.go.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in database.yml.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fixtures/sample.toml.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in grifts/db.go.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in grifts/init.go.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in inflections.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in main.go.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in models/models.go.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in models/models_test.go.
The file will have its original line endings in your working directory.
         run  git commit -q -m Initial Commit
**[36mINFO[0m[0053]** Congratulations! Your application, demo2, has been successfully built!

**[36mINFO[0m[0053]** You can find your new application at:
C:\gopath\src\demo2
**[36mINFO[0m[0053]**
Please read the README.md file in your new application for next steps on running your application.

```
PS C:\gopath\src> buffalo info
### Buffalo Version
v0.12.4

### App Information
Pwd=C:\gopath\src
Root=C:\gopath\src
GoPath=C:\gopath
Name=src
Bin=bin\src.exe
PackagePkg=src
ActionsPkg=src/actions
ModelsPkg=src/models
GriftsPkg=src/grifts
VCS=
WithPop=false
WithSQLite=false
WithDep=false
WithWebpack=false
WithYarn=false
WithDocker=false
WithGrifts=false

### Go Version
go version go1.10.1 windows/amd64

### Go Env
set GOARCH=amd64
set GOBIN=C:\gopath\bin
set GOCACHE=C:\Users\zlf\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\gopath
set GORACE=
set GOROOT=C:\go
set GOTMPDIR=
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\zlf\AppData\Local\Temp\go-build233733626=/tmp/go-build -gno-record-gcc-switches

### Node Version
v8.11.3

### NPM Version
5.6.0

### Yarn Version
1.7.0

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt2

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file
```

**Comment by kteb** [comment]
This is a git warning. It's not a big deal, it's just how the end of line will be saved. 

Here is a good article on [stackoverflow](https://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important) the top answer is great I'll quote a part here:

> In Unix systems the end of a line is represented with a line feed (LF). In windows a line is represented with a carriage return (CR) and a line feed (LF) thus (CRLF). when you get code from git that was uploaded from a unix system they will only have an LF.

**Comment by paulZzhang** [comment]
Special characters appear 
`�[36mINFO�[0m[0053] Congratulations! Your application, demo2, has been successfully built!

�[36mINFO�[0m[0053] You can find your new application at:
C:\gopath\src\demo2
�[36mINFO�[0m[0053]`

**Comment by kteb** [comment]
This is some formatting information to color the info (I've tried a buffalo new on a windows machine with the CMD terminal amd powershell, I got the same git warnings) and I got only INFO[0095] with info in a blue/green color ... so maybe your terminal doesn't recognize the color and instead display some characters.

**Comment by naru6be** [comment]
Solution :
 paste the below code


[core]
 autocrlf = false
[filter "lfs"]
 required = true
 clean = git-lfs clean -- %f
 smudge = git-lfs smudge -- %f
 process = git-lfs filter-process

https://www.ittechnical.solutions/2019/09/warning-lf-will-be-replaced-by-crlf-in.html?m=1

**Comment by lequangdongg** [comment]
using
$ git config --global core.autocrlf false

**Comment by mylovesaber** [comment]
You need to modify the following file:
`[hexo-blog-root-dir]/.deploy_git/.git/config`
```
[core]
# some options
	autocrlf = false
[filter "lfs"]
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
```
