### ISSUE TITLE
Unsetenv redeclared in this block

### ISSUE THREAD

**Issue by beatscode** [gobuffalo/buffalo#1197]
## Steps to Reproduce the Problem
I ran the installation to update buffalo from 0.10.3 to 0.12.4. Then after installation i wanted to create a new project without webpack.

 What does this error mean?
# golang.org/x/sys/unix
../../golang.org/x/sys/unix/env_unset.go:11:27: Unsetenv redeclared in this block
        previous declaration at ../../golang.org/x/sys/unix/env_unix.go:29:27

fyi I'm using Mac OS Sierra
 

## Expected Behavior
Create new project without webpack
## Actual Behavior

New project installation yielded the following:
```
buffalo new leonardo --skip-webpack -f
      create  .buffalo.dev.yml
      create  public/assets/application.js
      create  public/assets/images/favicon.ico
      create  public/assets/application.css
      create  public/assets/images/logo.svg
      create  models/models.go
      create  models/models_test.go
      create  grifts/db.go
         run  go get github.com/gobuffalo/pop/...
      create  ./database.yml
         run  goimports -w leonardo/grifts/db.go leonardo/models/models.go leonardo/models/models_test.go
      create  Dockerfile
      create  .dockerignore
      create  inflections.json
      create  locales/all.en-us.yaml
      create  main.go
      create  public/robots.txt
      create  actions/actions_test.go
      create  grifts/init.go
      create  actions/home_test.go
      create  .codeclimate.yml
      create  templates/application.html
      create  README.md
      create  actions/app.go
      create  templates/_flash.html
      create  .env
      create  fixtures/sample.toml
      create  templates/index.html
      create  actions/home.go
      create  actions/render.go
         run  go get -t ./...
# golang.org/x/sys/unix
../../golang.org/x/sys/unix/env_unset.go:11:27: Unsetenv redeclared in this block
        previous declaration at ../../golang.org/x/sys/unix/env_unix.go:29:27
Usage:
  buffalo new [name] [flags]

Flags:
      --api                  skip all front-end code and configure for an API server
      --bootstrap int        specify version for Bootstrap [3, 4] (default 4)
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci] (default "none")
      --db-type string       specify the type of database you want to use [postgres, mysql, cockroach] (default "postgres")
      --docker string        specify the type of Docker file to generate [none, multi, standard] (default "multi")
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
      --skip-yarn            use npm instead of yarn for frontend dependencies management
      --vcs string           specify the Version control system you would like to use [none, git, bzr] (default "git")
  -v, --verbose              verbosely print out the go get commands
      --with-dep             adds github.com/golang/dep to your app

ERRO[0003] Error: exit status 2

```
### Buffalo Version
v0.12.4

### App Information
Pwd=/Volumes/500GBSSD/projects/go/src/com.drleonardo
Root=/Volumes/500GBSSD/projects/go/src/com.drleonardo
GoPath=/Volumes/500GBSSD/projects/go
Name=com.drleonardo
Bin=bin/com.drleonardo
PackagePkg=com.drleonardo
ActionsPkg=com.drleonardo/actions
ModelsPkg=com.drleonardo/models
GriftsPkg=com.drleonardo/grifts
VCS=
WithPop=false
WithSQLite=false
WithDep=false
WithWebpack=false
WithYarn=false
WithDocker=false
WithGrifts=false

### Go Version
go version go1.10.3 darwin/amd64

### Go Env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Volumes/500GBSSD/projects/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3n/rlkw50rd1rn3dnqbg5frr3680000gn/T/go-build926490615=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Node Version
v10.7.0

### NPM Version
6.2.0

### Yarn Version
1.7.0

### PostgreSQL Version
pg_ctl (PostgreSQL) 10.4

### MySQL Version
MySQL Not Found

### SQLite Version
3.16.0 2016-11-04 19:09:39 0e5ffd9123d6d2d2b8f3701e8a73cc98a3a7ff5f

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file

<details>

```
PASTE_HERE
```

</details>

**Comment by markbates** [comment]
It means that package it’s complaining about is broken on disk. Delete it’s directory and try again. It’s a long standing bug with Go get.

--
Mark Bates

**Comment by beatscode** [comment]
Thanks
