### ISSUE TITLE
Tests only running in latest stable Go version

### ISSUE THREAD

**Issue by apaganobeleno** [gobuffalo/buffalo#123]
I think i've found an issue with the Dockerfile and buffalo's travis configuration, while we're apparently running our tests on go 1.7 and latest, it seems that given we're running our tests by building our Dockerfile we're actually using the latest stable rather than the versions travis sets outside the docker image.

I changed our Dockerfile to print the Go version thats running when we execute `go build .` and as you can see in the following 2 log files

https://travis-ci.org/gobuffalo/buffalo/jobs/191527609#L1641
https://travis-ci.org/gobuffalo/buffalo/jobs/191527608#L1635

its the same version of Go, this seems to be related to the fact that our Dockerfile is built [`FROM golang`](https://github.com/gobuffalo/buffalo/blob/master/Dockerfile#L1).

**Comment by markbates** [comment]
That would make total sense! Why didn't I think about that?

It can probably be fixed by passing in an ENV. Care to take a crack at it?

**Comment by apaganobeleno** [comment]
@markbates sure, i would like to. just to confirm, would you like to continue running our tests with docker build or do you think we should try running these inside travis directly ?. 

i'm thinking on how to determine the docker image to base ours (by setting the ENV) and doesn't seem easy given go version output wont match Go docker images tags.

Any reason why not to run these on travis ? (outside docker).

**Comment by markbates** [comment]
The big reason why i was using docker, was because a) it was easier to get set up than Travis b) i could run the docker file locally when trying to smoke test and figure out why it was failing on Travis.

**Comment by apaganobeleno** [comment]
oh, thats a good reason, one thing i didn't know is we can define env variables per (Go in our case) version inside travis, i'll keep you posted on how it goes, thanks for the explanation @markbates.
