### ISSUE TITLE
Support for JSON API Specification

### ISSUE THREAD

**Issue by leodotcloud** [gobuffalo/buffalo#1239]
It would be nice if we can enable the usage of JSON API Spec when creating a new project which would result in the generator adding the appropriate StructTags.

References: 
http://jsonapi.org
https://github.com/google/jsonapi

Note: When using the UI framework, ember.js, JSON API spec is the default.

**Comment by robbyoconnor** [comment]
https://gobuffalo.io/en/docs/apis

**Comment by robbyoconnor** [comment]
It's already possible.

**Comment by robbyoconnor** [comment]
I'll admit -- I initially didn't read -- apologies -- but see [discussion in the chat](https://gophers.slack.com/archives/C3MSAFD40/p1534917098000100).

**Comment by stanislas-m** [comment]
Pop now support jsonapi: https://github.com/gobuffalo/pop/releases/tag/v4.12.0

**Comment by gaghan430** [comment]
@stanislas-m sorry, I'm newbie
but do you have an example how to use it?
