### ISSUE TITLE
build_path does not work for Windows

### ISSUE THREAD

**Issue by howdoicomputer** [gobuffalo/buffalo#124]
`/tmp` doesn't exist on Windows but, instead, a Windows equivalent exists at `C:\Users\%USERNAME%\AppData\Local\Temp`. 

If you try to change `build_path` to a Windows formatted directory path...

```
C:\Users\drfrankinfurter\gocode\src\boardgamegrouper
λ  buffalo dev
Buffalo version 0.7.0

buffalo: 2017/01/13 00:01:57 === Rebuild on: :start: ===
buffalo: 2017/01/13 00:01:57 === Running: go build -v -i -o C:\Users\drfrankinfurter\AppData\Local\Temp\/boardgamegrouper-build (PID: 13928) ===
boardgamegrouper
buffalo: 2017/01/13 00:01:59 === Building Completed (PID: 13928) (Time: 1.4390013s) ===
buffalo: 2017/01/13 00:01:59 === exec: "C:\\Users\\drfrankinfurter\\AppData\\Local\\Temp\\/boardgamegrouper-build": file does not exist
 ===
```

This affects `buffalo dev` but, understandably, `buffalo build` still works.

**Comment by markbates** [comment]
I would love a PR for this, since I'm not on windows. 

The problem most likely exists in http://github.com/markbates/refresh

**Comment by howdoicomputer** [comment]
@markbates https://github.com/markbates/refresh/blob/master/cmd/init.go#L20

It so does. I wouldn't mind drafting a PR against that repo sometime this weekend or the next.
