### ISSUE TITLE
React+Babel+webpack generator

### ISSUE THREAD

**Issue by kirillDanshin** [gobuffalo/buffalo#125]
Can you add a react+babel+webpack boilerplate generator?

also, it's not an issue, but can you send a PR with buffalo link to awesome-go?

**Comment by markbates** [comment]
Yes to the second question. 

As to the first, I don't do react, so I'm not the most qualified to set it up. PRs are welcome.

**Comment by kirillDanshin** [comment]
@markbates ok, I'll do it, assign this issue to me.

ping me, when you'll send the PR to awesome-go, I'll merge it.

**Comment by markbates** [comment]
@kirillDanshin here's the PR for awesome-go https://github.com/avelino/awesome-go/pull/1258

**Comment by bscott** [comment]
@kirillDanshin Wanted to see if you were still doing this, I was going to submit something this evening or tomorrow.

**Comment by bscott** [comment]
For the most part, the webpack.config.js that Buffalo generates for new apps, already supports React files ( jsx ).

**Comment by kirillDanshin** [comment]
@bscott yep, I'm in progress now. going to submit production-ready solution no later than Friday.

**Comment by fooflare** [comment]
Is this going forward? I am working on a template based on create-react-app mainly as training to know better react (and react scripts) and how integrations work in buffalo. It would be nice to have a react generator, but if you are working on it, I will just finish the template and not work in the generator itself.

**Comment by markbates** [comment]
I'm closing this issue. Please see the discussion in https://github.com/gobuffalo/buffalo/pull/276 of why.

**Comment by kumarsiva07** [comment]
How do i create new app with react? In #276, --with-react is the option for that. But its not working.

**Comment by markbates** [comment]
@kumarsiva07 that PR was not merged. If you read the PR it explains why it was never merged in.
