### ISSUE TITLE
custom error handlers don't have access to context variables set in middleware

### ISSUE THREAD

**Issue by lindavongroote** [gobuffalo/buffalo#1250]
## Steps to Reproduce the Problem

  1. create a simple test app
  2. map a custom error handler to the 404 status code (in actions/app.go):
```golang
app.ErrorHandlers[http.StatusNotFound] = func(status int, err error, c buffalo.Context) error {
	// look for Translator in context or translate a test message	
	// this panics
	if t := c.Value("T"); t == nil {
		panic("translator missing from context")
	}
	// ditto
	// T.Translate(c, "errors.resource_not_found")
	return err
}
```
  3. send a request to the new app with an unregistered path in order to trigger the 404.

## Expected Behavior

Error handlers should have access to context variables (such as the Translator).

## Actual Behavior

Translator is missing from context.

**Comment by kteb** [comment]
Closed with #1248
