### ISSUE TITLE
Channel for community chat

### ISSUE THREAD

**Issue by stuartellis** [gobuffalo/buffalo#126]
It would be great to have an advertised Gitter or Slack channel for folks to be able to talk about Buffalo.

**Comment by markbates** [comment]
There is a slack channel, #buffalo, on gophers.slack.com. Come join us!

I will add a link to http://gobuffalo.io.

**Comment by stuartellis** [comment]
Thanks, @markbates.

Just to note that you need to visit https://invite.slack.golangbridge.org/ to get an invitation to the Gophers Slack, which unfortunately isn't linked to on the Slack login page itself (it just says "contact the administrators to get an invitation").
