### ISSUE TITLE
velvet rendering interferes with ember/turn off velvet

### ISSUE THREAD

**Issue by howdoicomputer** [gobuffalo/buffalo#127]
So I'm playing with this thing and I'm wondering how to set all this up so that Ember.js handles front-end interactions and Buffalo just handles JSON CRUD.

A problem that I'm coming up with is that the Velvet template engine uses `{{blah}}` as an interpolation syntax. What if... I don't want that? Beego has a similar issue: https://github.com/astaxie/beego/issues/163

Thoughts?

**Comment by markbates** [comment]
Can you open an issue on github.com/gobuffalo/velvet to add support for changing the delimiters? That would be great. 

In the meantime, you don't have to use velvet, if you don't need it. 

It's remarkably easy to write you're own custom renderer:

https://github.com/gobuffalo/buffalo/blob/master/render/renderer.go

**Comment by howdoicomputer** [comment]
@markbates Done. Is there a way to 'disable' Velvet without changing Buffalo's source? So that Buffalo only serves static assets?

**Comment by markbates** [comment]
Not sure I understand. If you don't want to use velvet, just don't use the r.HTML or r.Template functions from the render package. 

Buffalo supports serving static files. Look in actions/app.go for an example.

**Comment by markbates** [comment]
Did a bit of digging on this. The parser/lexer that velvet uses, doesn't allow for changing the delimitators, so it's a bigger challenge than I originally thought. 

However, all hope is not lost!

I have two "workarounds" for you. The first is to just serve up a static file. Just like assets, it's easy, and probably the perfect fit. 

The second, if you perhaps want to "pre-populate" data is to escape the react tags:

```html
{{processed}}
\{{not processed}}
```

The first tag will get evaluated by velvet the second will print `{{not processed}}` in the HTML.

**Comment by howdoicomputer** [comment]
@markbates Yeah, it was actually kind of a stupid question, to be honest. I was pretty sleep deprived at the time. I can just serve straight HTML.

So, basically, what I'm trying to do is use Buffalo as a backend CRUD API and then have Ember.js as a frontend. That said, baking the public assets in via `buffalo build` has been somewhat problematic.

However, I can pretty easily get this working using something like Nginx or Caddyserver. Then, I would keep the two codebases separate, host the Ember app using Nginx, and have API endpoints served through a Buffalo-based app.

The remaining problem is that this setup would also require getting Buffalo to output and receive JSON that's compatible with the [JSONAPI spec](http://jsonapi.org/). So I would need something like this: https://github.com/google/jsonapi

I'm just playing around with all this. I really, really, really like Ember on top of Rails and thought I would see how easy it would be to use a different language for the API server.

**Comment by bscott** [comment]
@markbates Does this needs to be an issue still, or an enhancement to Buffalo, otherwise I'll close it if not.

**Comment by markbates** [comment]
There's an open issue on velvet, so this is a dup. We can close
