### ISSUE TITLE
Request Validation

### ISSUE THREAD

**Issue by 1995parham** [gobuffalo/buffalo#1271]
Is there any way to validate request payload when using bind method of context?

I can create a pull request and add validation for example by [validator.v9](https://godoc.org/gopkg.in/go-playground/validator.v9) into bind method in `default_context.go` but I want to know is it a good way to do that and
Will buffalo accept it?

**Comment by yoh** [comment]
I think something like https://github.com/thedevsaddam/govalidator or https://github.com/gookit/validate can help ?

**Comment by paganotoni** [comment]
@1995parham @yoh does this validation needs to happen before Bind() or would calling `instance.Validate()` (and using internally something like `github.com/gobuffalo/validate` inside) work?

**Comment by paganotoni** [comment]
^  We use a similar pattern [in here](
https://github.com/gobuffalo/buffalo/blob/master/generators/resource/templates/actions/resource-use_model.go.tmpl#L98).

**Comment by yoh** [comment]
Thanks for your reply !
This validation needs to be happen before Bind().
The goal (I think) is to have explicit errors/validations messages according to requested data (see https://github.com/gin-gonic/gin#model-binding-and-validation).
Currently, on a /post with invalid json data according to my struct, I get something like "json: cannot unmarshal string into Go struct field Model.field of type int".

**Comment by paganotoni** [comment]
Got it, this sounds more of an issue with Bind() than the validation itself, is the value you're passing to `Model.Field` an integer?. Would it be too much to ask you to post an example of request/response here ?.

As for the explicit error/validations, validate allows to set these.

**Comment by 1995parham** [comment]
I agree with @yoh about similarities with gogin validation.
@yoh why we do not use [validator.v9](https://godoc.org/gopkg.in/go-playground/validator.v9)?

**Comment by 1995parham** [comment]
I create a simple version of this feature by validating the request data after binding in the `Bind` method. you can see it [here](https://github.com/1995parham/buffalo/commit/1c139a27665f28369d1fb4c9d3c9b23497c59570).

**Comment by drlogout** [comment]
I used a custom binding in which the request values are zeroed if not valid. 

A value which will be bound to an int for example is set to "0", if strconv.Atoi returns an error.

```go
func zeroInvalidFormValues(req *http.Request, i interface{}) *http.Request {
	e := reflect.TypeOf(i).Elem()

	for i := 0; i < e.NumField(); i++ {
		f := e.Field(i)
		t := f.Type.String()
		v := req.Form.Get(f.Name)

		switch {
		case strings.Contains(t, "int"):
			_, err := strconv.Atoi(v)
			if err != nil {
				req.Form.Set(f.Name, "0")
			}
		case t == "uuid.UUID":
			v := req.Form.Get(f.Name)
			_, err := uuid.FromString(v)
			if err != nil {
				req.Form.Set(f.Name, uuid.Nil.String())
			}
		}
	}

	return req
}

```

The function is called in the custom binding before decoder.Decode:


```go
req = zeroInvalidFormValues(req, i)

if err := decoder.Decode(req.Form, i); err != nil {
	return errors.WithStack(err)
}
```

With this binding return no error and the validation could be done in the models.
