### ISSUE TITLE
Installation on macOS fails at go-sqlite3 step

### ISSUE THREAD

**Issue by tijs** [gobuffalo/buffalo#128]
versions:

go version go1.7.4 darwin/amd64
macOS Sierra 10.12.2 (16C67)

issue:

when running the `go get -u github.com/gobuffalo/buffalo/buffalo` install command on my machine it fails at the build step for one of the dependencies. Resulting in an unfinished install and buffalo not being built.

stackstrace:

```
$ go get -u github.com/gobuffalo/buffalo/buffalo
# github.com/mattn/go-sqlite3
../../mattn/go-sqlite3/sqlite3-binding.c:29300:6: warning: "gethostuuid() is disabled." [-W#warnings]
# github.com/gobuffalo/buffalo/buffalo
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: URGENT: building for iOS simulator, but linking in object file (/var/folders/c0/xnnrh1051l50yny98x_2ndmr0000gn/T/go-link-792417776/000000.o) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/var/folders/c0/xnnrh1051l50yny98x_2ndmr0000gn/T/go-link-792417776/000000.o) was built for newer OSX version (10.11) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/var/folders/c0/xnnrh1051l50yny98x_2ndmr0000gn/T/go-link-792417776/000002.o) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/var/folders/c0/xnnrh1051l50yny98x_2ndmr0000gn/T/go-link-792417776/000002.o) was built for newer OSX version (10.11) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/var/folders/c0/xnnrh1051l50yny98x_2ndmr0000gn/T/go-link-792417776/000003.o) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/var/folders/c0/xnnrh1051l50yny98x_2ndmr0000gn/T/go-link-792417776/000003.o) was built for newer OSX version (10.11) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/var/folders/c0/xnnrh1051l50yny98x_2ndmr0000gn/T/go-link-792417776/000004.o) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/var/folders/c0/xnnrh1051l50yny98x_2ndmr0000gn/T/go-link-792417776/000004.o) was built for newer OSX version (10.11) than being linked (8.0)
Undefined symbols for architecture x86_64:
  "_SecCertificateCopyNormalizedIssuerContent", referenced from:
      _FetchPEMRoots in 000002.o
  "_SecCertificateCopyNormalizedSubjectContent", referenced from:
      _FetchPEMRoots in 000002.o
  "_SecKeychainItemExport", referenced from:
      _FetchPEMRoots_MountainLion in 000002.o
      _FetchPEMRoots in 000002.o
  "_SecTrustCopyAnchorCertificates", referenced from:
      _FetchPEMRoots_MountainLion in 000002.o
  "_SecTrustSettingsCopyCertificates", referenced from:
      _FetchPEMRoots in 000002.o
  "_SecTrustSettingsCopyTrustSettings", referenced from:
      _FetchPEMRoots in 000002.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by markbates** [comment]
It looks like you're missing the OS X developer command line tools or your SQLIte is out of date.

**Comment by tijs** [comment]
I have the developer command line tools installed (i use xcode quite a bit) but i might indeed lack a recent SQLite install. I have the builtin macOS sqlite installed:

SQLite version 3.14.0 2016-07-26 15:17:14

tried again just now after installing the latest sqlite3 with brew but that did not help either. Maybe i'm misreading the trace above and while sqlite just gives the warning the real issue is with the linker for amd64 which would make it a go issue?

**Comment by markbates** [comment]
Interesting. A quick google brought up this issue https://github.com/golang/go/issues/9411

**Comment by tijs** [comment]
I run into the same issue when i try and install with `go1.8rc1 get -u github.com/gobuffalo/buffalo/buffalo` so if it's a go issue it's not solved yet. I assume i can fix it with different build settings, just never ran into this before. I'll try some things and report back if i find the root cause.

**Comment by markbates** [comment]
Yeah, I haven't seen this issue before. It's very strange. There's something that we're both missing.

**Comment by bscott** [comment]
I tried to reproduce on my Mac, I was able to install just fine in both cases, on my other mac missing xcode Developer tools from App Store,  shows me the same error.

**Comment by tijs** [comment]
@bscott ugh! i did do another `xcode-select -install` just to be sure. double checked eveything was installed and still could not get it to run. today i restarted my mac just to be sure and now it works like a charm. sorry for the wild goose chase. will close the ticket!
