### ISSUE TITLE
buffalo command takes forever

### ISSUE THREAD

**Issue by vikram-rawat** [gobuffalo/buffalo#1290]
I have just updated my PowerShell from 2.0 to 5.0 or something. 
![image](https://user-images.githubusercontent.com/22342596/45083832-5fd71f80-b11a-11e8-91cd-70576c4df9c5.png)

Then I updated the bin path into my path variable in environment. I am not sure if this is because of that but now when I run commands like revel and bee they run on that very instance. I have no problem running them
![image](https://user-images.githubusercontent.com/22342596/45083870-7aa99400-b11a-11e8-9591-4350c05e40fc.png)
![image](https://user-images.githubusercontent.com/22342596/45083895-8ac17380-b11a-11e8-908f-e56b53fc2655.png)

but when I do the same with Buffalo it takes around 5 minutes or more. it works but it takes like forever.
![image](https://user-images.githubusercontent.com/22342596/45083980-bcd2d580-b11a-11e8-9432-985299ef4ea1.png)
![image](https://user-images.githubusercontent.com/22342596/45084028-decc5800-b11a-11e8-8109-e11867a9b5f6.png)
![image](https://user-images.githubusercontent.com/22342596/45084045-eb50b080-b11a-11e8-87ab-78f657769c56.png)

I installed the gcc package after that and reinstalled entire buffalo but it still takes so long. Is there anything I am supposed to do. Please do reply.

**Comment by vikram-rawat** [comment]
I deleted all the paths and ran the same command from cmd and it still takes very long to run the code. So now I am sure it has nothing to do with path variables and powershell versions. Please let me know if there is anything else that you need.

**Comment by vikram-rawat** [comment]
I upgraded my golang version from 1,9 to 1.1 and it reinstalled the entire golang by uninstalling the previous version. and it started working now.

But I don't know why it was working yesterday but didn't work today and then started working again. 

it took me more than 8 hours to get it working but it finally did and I am sorry to post an issue. Thanks for such an awesome package.

**Comment by kteb** [comment]
So we can close the issue ? Is it stable now ? And any kind of feedback are useful especially on Windows.

**Comment by markbates** [comment]
closing for lack of an update. please re-open if it continues.
