### ISSUE TITLE
Auto Render not correctly redirecting POST/PUT on resource if using it in group

### ISSUE THREAD

**Issue by crolly** [gobuffalo/buffalo#1299]
Hi everybody, this is my first ever issue raised on github, so please bear with me, in case my communication is a little bit unclear.

## Steps to Reproduce the Problem

1. Add group to router with
`admin := app.Group("admin")`

2. Add resource to group
`admin.Resource("/users", UsersResource{})`

## Expected Behavior

Have POST requests to create user at "/admin/users/new" and PUT requests to update user at "/admin/users/{user_id}" redirect to either "/admin/users" or "/admin/users/{user_id}".

## Actual Behavior

After creation or update AutoRender (auto.go) redirects to "/users/{user_id}".

## Info

As far as I can tell (I neither have much intel on the concepts nor much experience with go or buffalo), I would tend to change line 153 of function redirect inside auto.go from:
`url := fmt.Sprintf("%s/%v", name.URL(), f.Interface())`

to something like this:
`url := fmt.Sprintf("%s/%v", data["current_path"], f.Interface())`

Otherwise the url will always be strictly set to the struct type instead of the actual origin (in this case as part of a routing group).

**Comment by lukasschlueter** [comment]
This should be fixed by #1332

**Comment by lukasschlueter** [comment]
I didn't test it well enough last week, this seems to still be broken for DELETE requests as they don't call the `redirect` function that is called for POST and PUT. 

DELETE has a special case in `htmlAutoRenderer.Render` and uses `pname.URL()` for the redirect url
