### ISSUE TITLE
Proposal: shouldn't generate the resource templates when skipped the front-end and configured the project for an API server.

### ISSUE THREAD

**Issue by rasheedhamdawi** [gobuffalo/buffalo#1300]
## Steps to Reproduce the Problem

  1. buffalo new blog --api
  2. buffalo g resource posts

## Expected Behavior

If you created a project with the --api flag and generated a resource, shouldn't generate that resource's templates.

## Actual Behavior

When you run

```
buffalo g resource posts
```
It's generate the a the posts templates

```

|-- templates/
    |-- posts/
        |-- _form.html
        |-- edit.html
        |-- index.html
        |-- new.html
        |-- show.html
```

**Comment by gangachris** [comment]
I was thinking about how to solve this. 

I having a config generated in `.buffalo.dev.yml` like `app_type: api`, then whenever `buffalo g` runs, this is checked.

Any thoughts?

**Comment by markbates** [comment]
https://github.com/gobuffalo/buffalo/issues/1153 - there’s a proposal already on the table to store this sort of information.

Feel free and take a first stab at it.

**Comment by markbates** [comment]
Related to https://github.com/gobuffalo/buffalo/pull/1382
