### ISSUE TITLE
Error while trying to scaffold new buffalo API project

### ISSUE THREAD

**Issue by dviramontes** [gobuffalo/buffalo#1326]
## Steps to Reproduce the Problem

As titled.
  1. `buffalo new api --api --skip-pop`

## Expected Behavior

new buffalo app project scaffold

## Actual Behavior

```
$ buffalo new api --api --skip-pop
      create  .buffalo.dev.yml
      create  Dockerfile
      create  .dockerignore
      create  actions/home.go
      create  actions/render.go
      create  README.md
      create  .codeclimate.yml
      create  inflections.json
      create  actions/app.go
      create  go.mod
      create  grifts/init.go
      create  actions/actions_test.go
      create  actions/home_test.go
      create  .env
      create  fixtures/sample.toml
      create  main.go
         run  go get -t ./...
# github.com/.../.../api/actions
actions/render.go:10:23: unknown field 'DefaultContentType' in struct literal of type render.Options
Usage:
  buffalo new [name] [flags]

Flags:
      --api                  skip all front-end code and configure for an API server
      --bootstrap int        specify version for Bootstrap [3, 4] (default 4)
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci] (default "none")
      --config string        config file (default is $HOME/.buffalo.yaml)
      --db-type string       specify the type of database you want to use [postgres, mysql, cockroach] (default "postgres")
      --docker string        specify the type of Docker file to generate [none, multi, standard] (default "multi")
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --skip-config          skips using the config file
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
      --skip-yarn            use npm instead of yarn for frontend dependencies management
      --vcs string           specify the Version control system you would like to use [none, git, bzr] (default "git")
  -v, --verbose              verbosely print out the go get commands
      --with-dep             adds github.com/golang/dep to your app

ERRO[0001] Error: exit status 2

```

## Info

<details>

### Buffalo Version
v0.13.0-beta.2

### App Information
...
GoPath=/Users/user/go
Name=...
Bin=bin/...
...
VCS=git
WithPop=false
WithSQLite=false
WithDep=false
WithWebpack=false
WithYarn=false
WithDocker=false
WithGrifts=false
WithModules=false

### Go Version
go version go1.10.3 darwin/amd64

### Go Env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mmm/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mmm/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5h/jm6p_jfx7ybg1f2frj_0_bx80000gp/T/go-build356947349=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Node Version
v8.9.4

### NPM Version
6.2.0

### Yarn Version
1.10.0

### PostgreSQL Version
pg_ctl (PostgreSQL) 10.5

### MySQL Version
MySQL Not Found

### SQLite Version
3.19.4 2017-08-18 19:28:12 605907e73adb4533b12d22be8422f17a8dc125b5c37bb391756a11fc3a8c4d10

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file

</details>

**Comment by markbates** [comment]
It appears the home-brew image was accidentally updated to `v0.13.0-beta.2`, when it should be the production release of `v0.12.6`. It's been corrected. Try uninstalling and reinstalling.

Also, for the future, you cut out vitally important parts of the `buffalo info` command in the App Information section.

Please re-open if this problem persists after installing `v0.12.6`.

**Comment by dviramontes** [comment]
@markbates thanks! - i'll give it a try :)
