### ISSUE TITLE
Go package dependencies are untracked

### ISSUE THREAD

**Issue by iepathos** [gobuffalo/buffalo#133]
Need something like github.com/tools/godep added so go package dependencies are explicit and easy to install with something like godep update

**Comment by bscott** [comment]
Closing this since @markbates referenced an existing issue.

**Comment by markbates** [comment]
https://github.com/golang/dep

**Comment by markbates** [comment]
Depending on how long it will take the Go team to get a good beta out there, we might want to wait for https://github.com/golang/dep to be released so we don't have to change again.

**Comment by apaganobeleno** [comment]
awesome news!
