### ISSUE TITLE
Problem starting "buffalo dev" server

### ISSUE THREAD

**Issue by bscott** [gobuffalo/buffalo#135]
**Problem:**

When executing command to start local buffalo dev server, get an error when expecting normal start.

**Output:**
```
$ buffalo dev

Buffalo version 0.7.1

There was a problem starting the dev server: Unknown
```

**Details:**
Go Version: 1.7.4
Buffalo Version: 0.7.1
MacOS: Sierra ( 10.12.1 )

**Comment by bscott** [comment]
After doing some digging with @markbates, the local station I was on did not have Node or NPM installed.

Following these steps resolved my issue:

```
1) Ensure both Node & NPM are installed
2) npm install -g webpack
3) try renaming webpack.config.js
```

I'll be submitting a PR to add more context to this error "Unknown"

**Reference:**
https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/dev.go#L80

**Comment by oren** [comment]
I am getting this error:
```
Buffalo version 0.7.1

module.js:472
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/oren/p/go/src/github.com/oren/hello-buffalo/webpack.config.js:1:77)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
There was a problem starting the dev server: Unknown
2017/01/16 09:28:50 exit status 1
```

Can you please explain step 3?

**Comment by fooflare** [comment]
Hi,
the problem is you have not installed webpack. Have you nodejs and npm installed in your system?

**Comment by oren** [comment]
I installed webpack using this command
```
sudo npm install -g webpack
```

npm list -g | grep webpack
```
├─┬ webpack@1.14.0
│ └─┬ webpack-core@0.6.9
```

node --version
```
v7.3.0
```

npm --version
```
3.10.10
```

also, i am getting permission denied when I try to create new project:
```
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/webpack'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules/webpack'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules/webpack' }
```

I think it's because i have to use sudo when i install global npm packages.

**Comment by bscott** [comment]
@oren Try installing webpack without sudo, this would install locally in your buffalo project in node_modules directory but other then that, you may have some permission issues. 

I've seen this issue before with Ubuntu and NPM

**Comment by oren** [comment]
the problem is i don't have any folder. the new command is the one failing.

**Comment by fooflare** [comment]
If you have access problems to webpack, it is possible you have no permission  to read the file. You can check it with: ls -l /usr/lib/node_modules/webpack.
Here you have  the official npm doc page about how to solve permisión issues: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by oren** [comment]
Yes, in Ubuntu you have to use sudo when installing global npm packages. I think the reason is that /usr/lib/node_modules is `drwxr-xr-x  19 root root`

ls -l /usr/lib/node_modules/webpack/
```
drwxr-xr-x   2 nobody oren  4096 Jan 16 22:55 bin
drwxr-xr-x   2 nobody oren  4096 Jan 16 22:55 buildin
drwxr-xr-x   2 nobody oren  4096 Jan 16 22:55 hot
drwxr-xr-x   7 nobody oren  4096 Jan 16 22:55 lib
-rw-r--r--   1 nobody oren  1106 Feb 22  2016 LICENSE
drwxr-xr-x 131 root   root  4096 Jan 16 22:55 node_modules
-rw-r--r--   1 nobody oren  4574 Jan 16 22:55 package.json
-rw-r--r--   1 nobody oren 14976 Feb 22  2016 README.md
drwxr-xr-x   2 nobody oren  4096 Feb 22  2016 web_modules
```

**Comment by oren** [comment]
@fooflare your link solved it.
```
 sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
```

now it's running and i am getting `dial tcp 127.0.0.1:5432: getsockopt: connection refused` but that's a different issue. I'll do some more reading before submitting another ticket.

Thanks!

**Comment by fooflare** [comment]
That error means you have to configure your postgresql connection in database.yml and have a postgresql instance running. Have you it installed?

**Comment by oren** [comment]
i didn't configure anything. i just followed the readme assuming that the default will just work (probably using embedded db like sqlite or bolt) (:

**Comment by bscott** [comment]
By default the database.yml use Postgres, since your on Ubuntu, Docker may be a good option for you.

**Comment by oren** [comment]
i would think it might be better to provide a readme that just works so the Time To Hello World will be seconds instead of minutes/hours.

**Comment by bscott** [comment]
@oren sorry your having trouble, The docs were actually recently updated to offer a smoother start. I was able to get up in running in no time. Any Suggestions?

**Comment by oren** [comment]
sure. maybe a link ubuntu specific instructions and make it clear a db need to be running.

**Comment by bscott** [comment]
@oren I'll look into cleaner Ubuntu material but here in the Getting Started Guide, it states the need for a DB before getting started with Buffalo for further reference under "Running your application in development", hope that helps, the DB docs were recently updated from a previous issue I had opened regarding on-boarding to Buffalo. Thanks for the suggestion.

http://gobuffalo.io/docs/getting-started

**Comment by oren** [comment]
okay. i skipped that (:

I would suggest using BoltDB or sqlite to save some time on configuring a db.

**Comment by bscott** [comment]
MySQL/Sqlite is supported, BoltDB would be a good addition.

**Comment by oren** [comment]
works now. Thank You!

```
buffalo new test --db-type sqlite3
```

I would put this command in the readme or change the default to sqlite3. just my 2 cents.

**Comment by fooflare** [comment]
I don't think changing the default db server is a good option, postgresql is one of the most used in development. Sqlite is fine to make a ```hello world!```, but not for an agile startup.
To configure postgresql, here you are some links:
http://gobuffalo.io/docs/db (buffalo official docs, including explanation of how to change default db type)
https://help.ubuntu.com/community/PostgreSQL (Postgresql installation and configuration from Ubuntu community help wiki)

**Comment by oren** [comment]
got it. thanks!

**Comment by oren** [comment]
just an update.
this command ` sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}` causes me issues. i can't run sudo anymore. when i do that i get: `sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set` ):
