### ISSUE TITLE
Installation instructions are incorrect for GNU / Linux

### ISSUE THREAD

**Issue by el-davo** [gobuffalo/buffalo#1355]
## Steps to Reproduce the Problem

  1. Go here -> https://gobuffalo.io/en/docs/installation#installation-from-a-release-archive-64-bits
  2. Go to section `GNU / Linux` 
  3. Try the command `wget https://github.com/gobuffalo/buffalo/releases/download/vv0.12.7/buffalo_v0.12.7_linux_amd64.tar.gz`
  4. Produces 404 error

## Expected Behavior

Correct file downloads

## Actual Behavior

File seems to be missing and produces a 404 error

**Comment by stanislas-m** [comment]
Fixed by https://github.com/gobuffalo/gobuffalo/pull/370

**Comment by robbyoconnor** [comment]
Is this only seen on GNU/Linux -- what about non-GNU linuxes?
