### ISSUE TITLE
Prevent new app creation from outside the Go workspace

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#140]
If people aren't in their Go workspace, or don't have a Go path set, `buffalo new` shouldn't run, rather, it should error out with information letting people know what the problem is. This should help Go newcomers who aren't familiar with the Go path and workspace.

**Comment by sandorvasas** [comment]
Any workaround to this? I have a multi-project workspace and I don't want to put React/Angular, Python, Java, etc. apps into my Go workspace. Rather, I'd want to keep it organized in a single root folder of the project.

**Comment by markbates** [comment]
https://gobuffalo.io/docs/troubleshooting

You can install Buffalo into the new `$GOPATH` and you'll be fine.
