### ISSUE TITLE
pflag.ParseErrorsWhitelist compile error when running buffalo in a preexisting go project.

### ISSUE THREAD

**Issue by msenmurugan** [gobuffalo/buffalo#1413]
Hello! Thank you so much for your interest in Buffalo. The fact you care enough to be here, right now, helping makes us very happy.

### Steps to Reproduce the Problem

Run `buffalo new code --skip-pop` in a project that has spf13 's pflag from commit `9ff6c6923cfffbcd502984b8e0c80539a94968b7`already vendored.

### Expected Behavior

Buffalo starter proj should be created

### Actual Behavior

After a few initialization steps, it eventually blows up b/c of a compile error.  ParseErrorsWhitelist presumeable is a newer function that isnt in all spf13 versions

```
      create  actions/home.go                                       
      create  .codeclimate.yml                                      
      create  templates/application.html                            
      create  main.go          
      create  templates/_flash.html
      create  README.md                 
      create  go.mod                                                                               
      create  grifts/init.go                                                                          
         run  go get -t ./...                                   
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring go.mod;                                           
        see 'go help modules'                  
# github.com/spf13/cobra
../../../spf13/cobra/command.go:31:25: undefined: pflag.ParseErrorsWhitelist
```

## Note this is minor

PRobably there are a few decent workarounds, just wanted to paste this issue so that it was a known one.  Ideally it would be nice if buffalo mentioned version incompatibilities, or else, maybe if it didnt allow you to create a project in an already existing go directory, that way begginers would never hit this snag.

BTW , this is actually @jayunit100 posting this issue...  as im using someone else's github account to post this bug :)

**Comment by jayunit100** [comment]
Just verifying that this is fixed when we updated our spf13/flags stuff.

I’d suggest maybe not using that call if it’s non essential?  Might be a nice Ux improvement since so many people probably have old versions of pflags in existing go projects.

But either way happy to close.

**Comment by jayunit100** [comment]
vote to close ....
