### ISSUE TITLE
[Question] Modify Output of the Default Logger

### ISSUE THREAD

**Issue by ajoses** [gobuffalo/buffalo#1415]
Hi,

I'm trying to log to file, I found in the Issue 519 that I need to set the output of the default logger, however, I'm unable to do it, this is my last attemp:

		fieldLogger := app.Logger.(logrus.FieldLogger)
		logg := fieldLogger.(*logrus.Entry)
		logg.Logger.SetOutput(os.Stdout)

but after running it I get a message:
panic: interface conversion: buffalo.logrusWrapper is not logrus.FieldLogger: missing method WithField

I'm relative new to golang and I know it something about the interfaces, but I don't get it yet. 

Any advice would be helpful

Thanks, awesome project!

Arnulfo José

_Originally posted by @ajoses in https://github.com/gobuffalo/buffalo/issues/519#issuecomment-433526914_

**Comment by nijeshhirpara** [comment]
@markbates I want to add this feature. Already forked and added [commit ](https://github.com/nijeshhirpara/buffalo/commit/8b7c0048288cd89015003b30bd184ea71681aab9) which will allow setting output via `NewLogger` function, but this will change function definition. I am not sure if any other workaround.

	func NewLogger(level string, output io.Writer) Logger {
		dev := envy.Get("GO_ENV", "development") == "development"
		l := logrus.New()
		l.Out = output
		l.Level, _ = logrus.ParseLevel(level)
		l.Formatter = &textFormatter{
			ForceColors: dev,
		}
		return logrusWrapper{l}
	} 

With above change, we also don't require `ForceColors` to be true by default. File output will not require color encoding. So, I am just thinking to default `ForceColors` only for `os.Stderr` or we may allow to set `Formatter` on instance. I would prefer to set formatter externally as I prefer json output. Please let me know your thoughts.

**Comment by ajoses** [comment]
Hi,

I did something similar meanwhile I look for another option, it put a variable in the Options struct:

`	LogOutput *os.File`
Then in the function a put this code to make it compatible with the current version, the function is something like this:

`func NewLogger(level string, archivo *os.File) Logger {
	dev := envy.Get("GO_ENV", "development") == "development"
	l := logrus.New()
	l.Level, _ = logrus.ParseLevel(level)

	if archivo != nil {
		l.SetOutput(archivo)
	}
	l.Formatter = &textFormatter{
		ForceColors: dev,
	}
	return logrusWrapper{l}
}
`
I used the os.file because in that I can detect if is nil, if there is a way to detect the io.writer is nil or not assigned it would be better I think.

And to use it I do this in the app.go:

`var ENV = envy.Get("GO_ENV", "development")
var LOUT = envy.Get("LOUT", "")
var app *buffalo.App

// App is where all routes and middleware for buffalo
// should be defined. This is the nerve center of your
// application.
func App() *buffalo.App {

	var archivo *os.File
	var err error

	if len(LOUT) > 0 {
		archivo, err = os.OpenFile(LOUT, os.O_APPEND|os.O_WRONLY, 0600)

		if err != nil {
			log.Output(1, err.Error())
		}

		if archivo == nil {
			archivo, err = os.Create(LOUT)
			if err != nil {
				log.Output(1, err.Error())
			} else {
				archivo.Close()
				archivo, err = os.OpenFile(LOUT, os.O_APPEND|os.O_WRONLY, 0600)
				if err != nil {
					log.Output(1, err.Error())
				}
			}
		}

	} else {
		archivo = nil
	}

	if app == nil {
		app = buffalo.New(buffalo.Options{
			Env:          ENV,
			SessionStore: sessions.Null{},
			PreWares: []buffalo.PreWare{
				cors.Default().Handler,
			},
			SessionName: "_gsservicios_session",
			LogOutput:   archivo,
		})`

I'm using it right no in several project where is runned as Windows Service.

About the colors theres is a function "checkIfTerminal" that remove the colors if the Ouput is an os.file, but I don't understand yet why they conserved. My solution as put it in production.  

I can fork it and pull the request, is a complement of the one of @nijeshhirpara

Greetings.

**Comment by nijeshhirpara** [comment]
@ajoses You could do one liner like,

		file, _ := os.OpenFile("info.log", os.O_CREATE|os.O_APPEND, 0644)

I think there are other problems, May be @markbates doesn't want to change `NewLogger` function signature as other people might be using it. 

But apart from that there no immediate solution as it uses `Logrus.FieldLogger` and it doesn't have setOutput method. If we use logrus.Logger then we could achieve setOutput after creating an object. However, in this case local Logger interface needs to be changed.

**Comment by markbates** [comment]
We’re now using https://godoc.org/github.com/gobuffalo/logger for logging which already has this ability.

**Comment by nijeshhirpara** [comment]
I had looked at gobuffalo/logger, but how can I assign that to default
buffalo logger for my app as they are not of same type.

**Comment by markbates** [comment]
It’s in 0.14. My point was that we won’t accept a PR for this as it has been resolved in the next release.

**Comment by markbates** [comment]
Also https://godoc.org/github.com/gobuffalo/logger#FieldLogger should be 100% comp with 0.13

**Comment by markbates** [comment]
So isn’t https://github.com/gobuffalo/logger/blob/master/logrus.go#L14

**Comment by nijeshhirpara** [comment]
I tried it today, but gave me type error. May be I didn't declare properly.

    l := logger.NewLogger("debug")

And then used l in buffalo options like

    Logger:  l

**Comment by markbates** [comment]
Sorry, yes you are right they aren’t compatible like that. I meant their APIs are compatible. They’re used in 0.14.

**Comment by markbates** [comment]
You can either:

* Use 0.14.0-beta.1 which solves this or
* write your own logger - it’s an interface

That’s the best I can do to help you today.

We saw this problem and fixed it in the next release.

**Comment by nijeshhirpara** [comment]
@markbates thank you for you prompt response. Good to know that you're addressing this in next release.

**Comment by ajoses** [comment]
Hi,

I upgrade to version 0.14 and I can set the output 

Thanks.
