### ISSUE TITLE
buffalo new coke - causes logrus and mysql errors

### ISSUE THREAD

**Issue by pfortin-urbn** [gobuffalo/buffalo#1439]
## Description

Bug / Question:  I followed the steps in: https://gobuffalo.io/en/docs/new-project#create-a-new-project
and in the `buffalo new coke`, I get this output:
```
      ...
      create  grifts/db.go
         run  go get github.com/gobuffalo/buffalo-pop
# github.com/gobuffalo/logger
../../gobuffalo/logger/logger.go:53:3: l.SetOutput undefined (type *logrus.Logger has no field or method SetOutput)
# github.com/gobuffalo/pop
../../gobuffalo/pop/connection_details.go:89:16: undefined: mysql.ParseDSN
         run  goimports -w actions/actions_test.go actions/app.go actions/home.go actions/home_test.go actions/render.go grifts/db.go grifts/init.go main.go models/models.go models/models_test.go
      ...
```
Can you tell me what I am doing wrong?

**Comment by therusetiawan** [comment]
I also faced with this problem. I think the erorr is coming when try to import `github.com/gobuffalo/logger` pakcage. Then i am trying to reproduce it by running `go get github.com/gobuffalo/logger` manually and the error is like this : 
```
# github.com/gobuffalo/logger
../gobuffalo/logger/logger.go:53:3: l.SetOutput undefined (type *logrus.Logger has no field or method SetOutput)
```
My suspect is something wrong with this [https://github.com/gobuffalo/logger](https://github.com/gobuffalo/logger) repository especially on [this commit](https://github.com/gobuffalo/logger/commit/73d08d2bb969771485bc674708107354da722622).
