### ISSUE TITLE
/public/assets is gitignored by default: so builds in the cloud (or off your laptop) don't have /public/assets in them 

### ISSUE THREAD

**Issue by jayunit100** [gobuffalo/buffalo#1445]
## Description

If you honor `.gitignore`  to not commit /public/assets, then they don't get shipped into your production containers, and then *local* containers (built from your working buffalo dev environment) will look great, but stuff build outside your dev environment (i.e. directly from source) *won't* have those assets in them.

### Steps to Reproduce the Problem
 
- create a new buffalo project w/ non trivial public/assets
- make sure .gitignore still ignores public/assets
- run the docker build in any environment outside your local laptop (i.e. google cloud build)

You'll ultimately notice that the assets won't be in the same binary, and it will be a megabyte or two smaller then the image you built in your laptop.

## Workaround

Uncomment (in the .gitignore file) the public/assets directory.  This entry is added for you by `buffalo dev` when you created a project.

**Comment by markbates** [comment]
Remove the `.gitignore` file if you want to commit that directory.

**Comment by u007** [comment]
i think its not recommended to add the compiled assets into git.
if you have a version change or you add in a uglifier or any thing that effects the final output of your assets, the changes will be tremendous and your team member whom isn't using the same new "enhanced" assets management will be troubled with conflict that most likely he have to clean entire assets and regenerate again.

**Comment by jayunit100** [comment]
Interesting, I just ran `buffalo build` and it generated my assets.  But yesterday, when I ran `RUN buffalo build --static -o /bin/app` from one of my Dockerfiles, i didn't see the assets in the final product.  I'll dig more to see why.

**Comment by jayunit100** [comment]
So, just confirmed that neither `buffalo dev` nor buffalo `buffalo build` actually rebuild the assets.

**Comment by jayunit100** [comment]
Update: if you `mkdir`, it fixes the issue at the dockerfile level.  See #250

**Comment by msenmurugan** [comment]
Update: If you want to populate the public/assets folder automatically during `buffalo dev`, then `webpack.config.js` file is mandatory
