### ISSUE TITLE
Chocolatey package for buffalo

### ISSUE THREAD

**Issue by abdullah2993** [gobuffalo/buffalo#1459]
Chocolatey package for buffalo installation on windows

**Comment by digitalcoyote** [comment]
I'd be willing to throw a package together for Chocolatey and add it to my AU repo (keeps the package up to date without changes to the release process)

**Comment by stanislas-m** [comment]
Sure @digitalcoyote, please do!

**Comment by digitalcoyote** [comment]
https://chocolatey.org/packages/buffalo/0.14.11
It's awaiting review. I'll ready a pull request including isntall instructions for chocolatey when the first version is approved

**Comment by digitalcoyote** [comment]
Also, If a maintainer for this project wants to be a maintainer (in case a manual package needs to be pushed or a version needs to be delisted) let me know the username and I will add them

**Comment by digitalcoyote** [comment]
Took a bit, but it's approved. (I think the holidays are causing the volunteer moderators to be less available for reviews). and the CI is ready to push new versions.

**Comment by stanislas-m** [comment]
Chocolatey is now listed on the installation page: https://gobuffalo.io/en/docs/getting-started/installation#chocolatey-windows

Thanks a lot @digitalcoyote!
