### ISSUE TITLE
Buffalo scaffolder replaces project names with hyphens to underscores

### ISSUE THREAD

**Issue by thatguychrisw** [gobuffalo/buffalo#1468]
When scaffolding a new project Buffalo replaces project names containing hyphens to underscores.  Is this a convention that needs to be enforced?  My organization's repository names have a hyphen convention which the scaffolder breaks.

**Comment by markbates** [comment]
You are welcome to change the file names, Buffalo doesn’t require it. 

We use that case for two reasons. 

1. It’s the case that is idiomatic for Go files
2. We need to normalize user input to something. As you can imagine people pass in wildly different text, and we need a way to make sure that things don’t break when generating files so we chose Go’s idiomatic naming convention. 

Closing this as it’s not something Buffalo will change soon, for the reasons above, and the “work around” is to rename generated files to your liking.
