### ISSUE TITLE
Is there a way to disable the production log level `INFO`?

### ISSUE THREAD

**Issue by frederikhors** [gobuffalo/buffalo#1471]
Is there a way to disable the production log level `INFO`?

I search all over the world before open this issue.

It seems INFO level is a must, but what if I don't need it?

(Maybe an .env VAR?)

Thanks in advance.

**Comment by stanislas-m** [comment]
See https://godoc.org/github.com/gobuffalo/buffalo#Options, you can set the `LogLevel`. :)

**Comment by sio4** [comment]
You can currently override hardcoded `Options.LogLevel` by use environmental variable `LOG_LEVEL`. 

https://github.com/gobuffalo/buffalo/blob/e362599b8489bd6e0b62e357bdeb044498c04143/options.go#L76-L78

@stanislas-m, do you know why this behavior was removed on `development` branch? in many cases, we need to change log level at runtime not build time.

**Comment by frederikhors** [comment]
@stanislas-m can you reopen until question is answered?

> we need to change log level at runtime not build time.

Maybe we can use an `envy.Get` in options, @sio4?

**Comment by sio4** [comment]
> Maybe we can use an `envy.Get` in options, @sio4?

As you can see in the code I quote, if there is an environmental variable named `LOG_LEVEL`, (or in `.env`) it will override hardcoded configuration in `app.go` (the value we can pass as `Options.LogLevel`). Anyway, in my case, sometimes, I just added code something like `envy.Get("MYAPP_LOG_LEVEL", "info")` for my own named variable. (but it is somewhat annoying :-)

**Comment by stanislas-m** [comment]
> @stanislas-m, do you know why this behavior was removed on development branch? in many cases, we need to change log level at runtime not build time

I don't. I think it was removed when the logger was migrated to a new package.

**Comment by sio4** [comment]
I think it just removed while migration not intensionally at the first time
but there are deprecated function there.
Ok, I will seek history since I like this. :-)

-- 
...and in the end, the love you take is equal to the love make

2018년 11월 27일 (화) 22:06에 Stanislas Michalak <notifications@github.com>님이 작성:

**Comment by markbates** [comment]
It definitely wasn’t intentional and should definitely be added back. :)

**Comment by sio4** [comment]
Cool!

**Comment by markbates** [comment]
closing as this is fixed in `development`.
