### ISSUE TITLE
skipping middleware SetContentType

### ISSUE THREAD

**Issue by luisfernrg** [gobuffalo/buffalo#148]
Im using `middleware.SetContentType()` as an example since my middleware has the same signature. Is there currently a way to skip a `buffalo.MiddlewareFunc` with `buffalo.Middleware.Skip()` 

I keep getting this error `github.com/luisfernrg/meem/actions
actions/app.go:48: cannot use middleware.SetContentType (type func(string) buffalo.MiddlewareFunc) as type buffalo.MiddlewareFunc in argument to vone.Middleware.Skip`

This is what I'm doing `vone.Middleware.Skip(middleware.SetContentType, a.HomeHandler)`

I could just create another grouped routes which is a fix but I want to see if there is a way to do so with `buffalo.Middleware.Skip()`

**Comment by markbates** [comment]
SetContentType itself isn't a MiddlewareFunc, you need to pass a string to it with the content type you want to set, and the it will return a MiddlewareFunc. It's a factory method.

**Comment by luisfernrg** [comment]
@markbates yes, sorry I meant how would you skip the MiddlewareFunc that it returns or is this not possible? I have an authentication middleware which takes a db as an argument I would like to be able to skip this. It's basically like the SetContentType method. Expect it takes a db

**Comment by markbates** [comment]
If you define the function at the top and use that same definition for both the Use and Skip it should work. If you use two different definitions it probably won't work it. The key is to assign it to a variable and use that.

**Comment by luisfernrg** [comment]
@markbates awesome! I will try it out in the morning. I appreciate the help thank you.
