### ISSUE TITLE
Deploy on Heroku (without Docker), err: "lstat /tmp/tmp.pl6MR9ZVFf: no such file or directory"

### ISSUE THREAD

**Issue by frederikhors** [gobuffalo/buffalo#1485]
## Description

I'm trying to deploy on Heroku **without** Docker (simple dyno, old way).

### Steps to Reproduce the Problem

- New folder on my PC
- buffalo (0.13.7) new myApp (with Dep)
- deleted (or renamed) `go.mod` file (Heroku GoMod is not fully supported today)
- new app on heroku from browser dashboard
- heroku git:remote -a myHerokuApp
- set GO_ENV = production
- set SESSION_SECRET = 123456
- set DATABASE_URL = someUrl
- git push heroku master

### Expected Behavior

App should work ok.

### Actual Behavior

After the `git push heroku master` everything ok, build ok, the app start and after 1 second it crash!
This is the Heroku log:

```log
app/api: Build started by user fred@hors.com 
heroku/web.1: State changed from crashed to starting 
heroku/web.1: Starting process with command `myApp` 
app/api: Deploy 12345678 by user fred@hors.com 
app/api: Release v123 created by user fred@hors.com 
heroku/web.1: State changed from starting to crashed 
heroku/web.1: Process exited with status 1 
app/web.1: level=error msg="lstat /tmp/tmp.pl6MR9ZVFf: no such file or directory" 
app/web.1: level=info msg="Starting application at 0.0.0.0:20382" 
app/web.1: 2018/12/04 23:02:02 context canceled 
```

What about this error: **"lstat /tmp/tmp.pl6MR9ZVFf: no such file or directory"**?

**Comment by markbates** [comment]
Heroku build packs don’t support Buffalo natively. This plug-in only support the container method. 

There are a lot of docs and posts on how to compile and push executables to heroku. 

I recommend using the container as heroku fully supports it and the generate Dockerfile works with heroku. 

If that doesn’t work for you, then you’ll have to pre build the binary before pushing it. Again, lots of info out there on how to push compiled binaries to heroku.

**Comment by frederikhors** [comment]
@markbates thanks for the answer.

- Is it easy and possible to understand why it doesn't work with default Heroku?

- What I'm afraid is with Docker on Heroku things are slower than simple dyno.

**Comment by markbates** [comment]
It’s a long explanation unfortunately. It partially they have stopped supporting their build packs and part buffalo not wanting to code around that fact. 

Heroku recommends docker for this case. I use docker on heroku exclusively it works great. 

Do what they recommend; it works and is the approach they, and I, suggest.

**Comment by markbates** [comment]
Alternatively you can build your binary with buffalo build and deploy it however you’d like. The docker file does all of that for you though and runs in a slim alpine container.
