### ISSUE TITLE
buffalo dev fails even though address is not in use

### ISSUE THREAD

**Issue by imorti** [gobuffalo/buffalo#1487]
I run `buffalo dev` and get `listen tcp 127.0.0.1:3000: bind: address already in use`. 

When I run `lsof -i :3000` to see what's running it's a buffalo process. 

I kill it and try to run again and same thing happens. 

I have reinstalled go and buffalo and same behavior. 

buffalo: 2018/12/05 07:01:45 === Rebuild on: :start: ===
buffalo: 2018/12/05 07:01:45 === Running: go build -v -i -tags development -o tmp/elevation-build  (PID: 18095) ===

webpack is watching the files…

Live Reload listening on port 35729

buffalo: 2018/12/05 07:02:35 === Building Completed (PID: 18095) (Time: 49.861393836s) ===
buffalo: 2018/12/05 07:02:35 === Running: tmp/elevation-build (PID: 20528) ===
INFO[2018-12-05T07:02:43-08:00] Starting application at 127.0.0.1:3000
INFO[2018-12-05T07:02:43-08:00] Starting Simple Background Worker
ERRO[2018-12-05T07:02:43-08:00] listen tcp 127.0.0.1:3000: bind: address already in use
2018/12/05 07:02:43 context canceled
INFO[2018-12-05T07:02:43-08:00] Shutting down application
INFO[2018-12-05T07:02:43-08:00] Shutting down worker
INFO[2018-12-05T07:02:43-08:00] Stopping Simple Background Worker
buffalo: 2018/12/05 07:02:43 === exit status 1
INFO[2018-12-05T07:02:43-08:00] Starting application at 127.0.0.1:3000
INFO[2018-12-05T07:02:43-08:00] Starting Simple Background Worker
ERRO[2018-12-05T07:02:43-08:00] listen tcp 127.0.0.1:3000: bind: address already in use
2018/12/05 07:02:43 context canceled
INFO[2018-12-05T07:02:43-08:00] Shutting down application
INFO[2018-12-05T07:02:43-08:00] Shutting down worker
INFO[2018-12-05T07:02:43-08:00] Stopping Simple Background Worker

**Comment by stanislas-m** [comment]
You seems to have a zombie buffalo process. Try to kill it, then restart buffalo.

**Comment by imorti** [comment]
I kill it, run `buffalo dev` again and still get the same problem. 

```INFO[2018-12-06T17:18:52-08:00] Starting application at 127.0.0.1:3000
INFO[2018-12-06T17:18:52-08:00] Starting Simple Background Worker
ERRO[2018-12-06T17:18:52-08:00] listen tcp 127.0.0.1:3000: bind: address already in use
2018/12/06 17:18:52 context canceled
buffalo: 2018/12/06 17:18:52 === exit status 1
INFO[2018-12-06T17:18:52-08:00] Starting application at 127.0.0.1:3000
INFO[2018-12-06T17:18:52-08:00] Starting Simple Background Worker
ERRO[2018-12-06T17:18:52-08:00] listen tcp 127.0.0.1:3000: bind: address already in use
2018/12/06 17:18:52 context canceled ```

```buffalo-a 2986 imorti    8u  IPv4 0xe7240e7e943ba6f9      0t0  TCP localhost:hbci (LISTEN)```

**Comment by imorti** [comment]
this also happens with 0.13.9

**Comment by imorti** [comment]
ok apparently there's buffalo-auth processes running in the background for no reason.

**Comment by imorti** [comment]
Update: removed `buffalo-auth` from `$GOPATH/bin` and `buffalo dev` works now. Build still fails.
