### ISSUE TITLE
Please add example for login forms

### ISSUE THREAD

**Issue by XelaRellum** [gobuffalo/buffalo#149]
This is a very interesting part of every webapp but almost all of the examples omit this.

I guess login/logout would plug in to the context and work on this. But jus how oh how.

**Comment by bscott** [comment]
@XelaRellum I can provide some example of simple forms on the documentation site, I'll discuss with @markbates

**Comment by XelaRellum** [comment]
Thanks a lot. I think i managed to get further along with this and will provide a pull request with the example. Do you think it should be included in one of the existing examples?

**Comment by bscott** [comment]
@XelaRellum Yes that should be good. Thank you!

**Comment by markbates** [comment]
https://github.com/gobuffalo/authrecipe
