### ISSUE TITLE
"buffalo fix" does't update Dockerfile image version.

### ISSUE THREAD

**Issue by frederikhors** [gobuffalo/buffalo#1500]
`buffalo fix` doesn't update `Dockerfile` image version.

For example:

`FROM gobuffalo/buffalo:v0.13.8 as builder`

should be with **Buffalo 0.13.10**:

`FROM gobuffalo/buffalo:v0.13.10 as builder`

Am I wrong?

**Comment by davidmukiibi** [comment]
Is this fixed or can someone pick it up?

**Comment by markbates** [comment]
I just opened a PR for this https://github.com/gobuffalo/buffalo/pull/1591
