### ISSUE TITLE
Reproducible problem with app.Mount (just Copy & Paste).

### ISSUE THREAD

**Issue by frederikhors** [gobuffalo/buffalo#1507]
If you copy & paste the code below you can reproduce the problem with `app.Mount`:

_actions/app.go_:

```go
package actions

import (
	"fmt"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/envy"
	"github.com/gorilla/mux"
	"net/http"
)

var ENV = envy.Get("GO_ENV", "development")
var app *buffalo.App

func funcTest(res http.ResponseWriter, req *http.Request) {
	fmt.Fprintf(res, "%s - HELLOOOOOOOOOOOOO - %s", req.Method, req.URL.String())
}

func muxer() http.Handler {
	r := mux.NewRouter()
	r.HandleFunc("/foo", funcTest).Methods("GET")
	r.HandleFunc("/bar", funcTest).Methods("POST")
	r.HandleFunc("/baz/baz", funcTest).Methods("DELETE")
	return r
}

func App() *buffalo.App {
	if app == nil {
		app = buffalo.New(buffalo.Options{
			Env:         ENV,
			SessionName: "_mytestapp_session",
		})

		app.Mount("/admin", muxer())

		app.Mount("/strip", http.StripPrefix("/strip", muxer()))

		app.ANY("/test/{path:.+}", buffalo.WrapHandler(http.StripPrefix("/test", muxer())))

		app.GET("/one", buffalo.WrapHandlerFunc(funcTest))

		app.GET("/", HomeHandler)

		app.ServeFiles("/", assetsBox)
	}

	return app
}
```

- If you visit http://localhost:3000/admin/foo or http://localhost:3000/test/foo or http://localhost:3000/strip/foo is the same: `404 page not found`.

- If you visit: http://localhost:3000/one it works.

I think there is a problem with `app.Mount` in Buffalo.

Fixing this we can close this and other 2 related issues I think:
- https://github.com/gobuffalo/buffalo/issues/1506
- https://github.com/gobuffalo/buffalo/issues/1503

**Comment by markbates** [comment]
This is a dup of 1506. Please do not keep opening the same issue. 

Also, add a slash to the stuff you mount in the mixer it work.

**Comment by markbates** [comment]
From the docs:

“NOTE: There is a slight breaking change in that incoming path c.Request().URL.Path will ALWAYS have the trailing slash.”

**Comment by frederikhors** [comment]
@markbates with the slash it works (without StripPrefix which is already there in `app.Mount` code.

I read docs but this is not obvious I think.

Plus, can we do something to debug this? How to know which route is called?

Anyway I can close the other issues in a few minutes I think.

Thanks a ton!

**Comment by frederikhors** [comment]
I read now the new comment. Ok. Thanks again.

**Comment by markbates** [comment]
buffalo routes shows the routes in your app.

**Comment by frederikhors** [comment]
@markbates is there a way to disable final slash? I saw in docs:

> The LooseSlash option was removed in v0.13.0-beta.1 in this PR.

I need to mount some external handlers for which I cannot modify the endopoints.

**Comment by markbates** [comment]
No. You’ll have to strip it yourself.

**Comment by frederikhors** [comment]
I did not explain myself: `authboss` for example uses `/login` endpoint without final `/`. And this is just one problem for the integration (which works if I use blank standard gorilla Mux).
What do you suggest for adding final slash on endpoints, Buffalo side?

**Comment by markbates** [comment]
You can either strip the / before you send it Auth boss using a handler. Or mount buffalo on your muxer instead of mounting your mux on buffalo.

**Comment by frederikhors** [comment]
> You can either strip the / before you send it Auth boss using a handler.

What does this phrase mean?

I'm using `app.Mount("/auth", Ab.Config.Core.Router)` and `Ab.Config.Core.Router` comes from `authboss` backbox.

I just wanna use Buffalo to mount everything (like Rails), not a separate mux.

Why `LooseSlash` option removed?

**Comment by markbates** [comment]
I’m sorry, I can’t write this code for you. I’m supporting this in my free time. It’s sunday morning.

app.Mount(somehandlerthatstripsthelastslash(youmux))

**Comment by frederikhors** [comment]
@lukasschlueter I did here: https://github.com/gobuffalo/gobuffalo/pull/418

@lukasschlueter as you can see I'm not a useless "spammer". 😄 I'm trying to help Buffalo to become the "non plus ultra" of the frameworks in Go. The most used like "Rails and devise" in the Ruby world. I'm one step away from doing it: can you help find a way to add final slashes in `ab.Config.Core.Router` here: https://github.com/frederikhors/buffalo-authboss-sample?

**Comment by lukasschlueter** [comment]
Well, does it work?

**Comment by frederikhors** [comment]
Yes. Thanks. 😄
