### ISSUE TITLE
Project Creation Error

### ISSUE THREAD

**Issue by intelwalk** [gobuffalo/buffalo#1515]
## Expected Behavior

Clean project build behavior

### Actual Behavior

sudo buffalo new coke2
[sudo] password for intelwalk: 
      create  .buffalo.dev.yml
      create  .babelrc
      create  public/assets/.keep
      create  webpack.config.js
      create  assets/css/application.scss
      create  assets/images/favicon.ico
      create  assets/images/logo.svg
      create  assets/js/application.js
      create  package.json
      create  assets/css/_buffalo.scss
         run  yarnpkg install --no-progress --save
yarn install v1.10.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 31.20s.
      create  Dockerfile
      create  .dockerignore
      create  actions/render.go
      create  .env
      create  public/robots.txt
      create  actions/home.go
      create  actions/home_test.go
      create  go.mod
      create  grifts/init.go
      create  locales/all.en-us.yaml
      create  README.md
      create  actions/actions_test.go
      create  .codeclimate.yml
      create  templates/application.html
      create  templates/index.html
      create  actions/app.go
      create  fixtures/sample.toml
      create  inflections.json
      create  main.go
      create  templates/_flash.html
      create  models/models.go
      create  models/models_test.go
      create  grifts/db.go
         run  go get github.com/gobuffalo/buffalo-pop
[DEPRECATED] generate.Config has been deprecated.
	Use github.com/gobuffalo/pop/genny/config instead.
         run  goimports -w actions/actions_test.go actions/app.go actions/home.go actions/home_test.go actions/render.go grifts/db.go grifts/init.go main.go models/models.go models/models_test.go
         run  go get -t ./...
# github.com/intelwalk/coke2/actions
actions/app.go:75:35: cannot use packr.NewBox("../locales") (type packr.Box) as type packd.Box in argument to i18n.New:
	packr.Box does not implement packd.Box (wrong type for AddBytes method)
		have AddBytes(string, []byte)
		want AddBytes(string, []byte) error
Usage:
  buffalo new [name] [flags]

Flags:
      --api                  skip all front-end code and configure for an API server
      --bootstrap int        specify version for Bootstrap [3, 4] (default 4)
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci] (default "none")
      --config string        config file (default is $HOME/.buffalo.yaml)
      --db-type string       specify the type of database you want to use [cockroach, mysql, postgres, sqlite3] (default "postgres")
      --docker string        specify the type of Docker file to generate [none, multi, standard] (default "multi")
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --skip-config          skips using the config file
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
      --skip-yarn            use npm instead of yarn for frontend dependencies management
      --vcs string           specify the Version control system you would like to use [none, git, bzr] (default "git")
  -v, --verbose              verbosely print out the go get commands
      --with-dep             adds github.com/golang/dep to your app

ERRO[0032] Error: exit status 2

### Info

Please run `buffalo info` and paste the information below where it says "PASTE_HERE".

<details>

### Buffalo Version
v0.13.12

### App Information
Pwd=/home/intelwalk/go/src/github.com/intelwalk
Root=/home/intelwalk/go/src/github.com/intelwalk
GoPath=/home/intelwalk/go
Name=intelwalk
Bin=bin/intelwalk
PackagePkg=github.com/intelwalk
ActionsPkg=github.com/intelwalk/actions
ModelsPkg=github.com/intelwalk/models
GriftsPkg=github.com/intelwalk/grifts
VCS=
WithPop=false
WithSQLite=false
WithDep=false
WithWebpack=false
WithYarn=false
WithDocker=false
WithGrifts=false
WithModules=false

### Go Version
go version go1.10.4 linux/amd64

### Go Env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/intelwalk/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/intelwalk/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build517562902=/tmp/go-build -gno-record-gcc-switches"

### Node Version
v8.10.0

### NPM Version
3.5.2

### Yarn Version
1.10.1

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
SQLite Not Found

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file

</details>

**Comment by stanislas-m** [comment]
It looks like your buffalo dependencies are not up to date. Please run `go get -u -t github.com/gobuffalo/buffalo` and try again.
