### ISSUE TITLE
Buffalo returns truncated static assets

### ISSUE THREAD

**Issue by hdm** [gobuffalo/buffalo#1538]
## Description

Buffalo is returning static assets with exactly 512 less than expected. This was reproduced using buffalo v0.13.x and 0.14.0-beta2 with the web font `Roboto-Regular.woff2` stored in the assets directory, running in development mode with `buffalo dev`.

### Steps to Reproduce the Problem

  1. Stuff a copy of https://github.com/mdbootstrap/bootstrap-material-design/raw/master/font/roboto/Roboto-Regular.woff2 into `./assets/fonts/Roboto/`
  1. Start `buffalo dev`
  1. Download this file via curl: `$ curl -o t http://127.0.0.1:3000/assets/fonts/Roboto/Roboto-Regular.woff2`
  1.  Observe the error message and the missing content:
```
$ curl -o t http://127.0.0.1:3000/assets/fonts/Roboto/Roboto-Regular.woff2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 99 65916   99 65404    0     0  65404      0  0:00:01 --:--:--  0:00:01 1358k
curl: (18) transfer closed with 512 bytes remaining to read

$ curl -I http://127.0.0.1:3000/assets/fonts/Roboto/Roboto-Regular.woff2
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 65916
Content-Type: font/woff2
Last-Modified: Wed, 16 Jan 2019 18:24:53 GMT
Date: Wed, 16 Jan 2019 18:24:53 GMT

$ ls -la t
-rw-r--r-- 1 Developer 197121 65404 Jan 16 12:23 t
```

### Expected Behavior

I expected the complete file to be returned.

### Actual Behavior

A truncated file is returned.

### Info

<details>

```
### Buffalo Version
v0.14.0-beta.2

### App Information
Pwd=C:\Users\Developer\go\src\github.com\gobuffalo\buffalo\buffalo
Root=C:\Users\Developer\go\src\github.com\gobuffalo\buffalo\buffalo
GoPath=C:\Users\Developer\go
PackagePkg=github.com/gobuffalo/buffalo/buffalo
ActionsPkg=github.com/gobuffalo/buffalo/buffalo/actions
ModelsPkg=github.com/gobuffalo/buffalo/buffalo/models
GriftsPkg=github.com/gobuffalo/buffalo/buffalo/grifts
WithModules=false
Name=buffalo
Bin=bin\buffalo.exe
VCS=
WithPop=false
WithSQLite=false
WithDep=false
WithWebpack=false
WithNodeJs=false
WithYarn=false
WithDocker=false
WithGrifts=false
AsWeb=true
AsAPI=false

### Go Version
go version go1.11.4 windows/amd64

### Go Env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Developer\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Developer\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\DEVELO~1\AppData\Local\Temp\go-build940888554=/tmp/go-build -gno-record-gcc-switches

### Node Version
v10.15.0

### NPM Version
6.4.1

### Yarn Version
1.12.3

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file

```

</details>

**Comment by markbates** [comment]
This is caused by an old version of packr. Please make sure you have the latest versions.

**Comment by hdm** [comment]
It appears to be a problem with the latest version of packr as well:
```
C:\Users\Developer\go\src\github.com\gobuffalo\buffalo\buffalo>packr version
v1.21.9```

**Comment by hdm** [comment]
I installed packr with `go get -u github.com/gobufallo/packr`, buffalo was installed from the development branch of git with `go get -u && go build && go install`, can you point me to a particular step I missed that would result in the non-release version of packr being used? Should I be pinning the release candidate into the dependency file? I'll grab the latest version of packr manually, but wondering what the right way is to avoid this in the future.

**Comment by markbates** [comment]
Without using a package manager I can’t help you. Again, make sure you have the latest. If the problem persists open an issue against packr with a reproducible example.

Original issue https://github.com/gobuffalo/packr/issues/105

**Comment by hdm** [comment]
Thanks! Upgrading the project to use packr/v2 solved it, following the guidelines at https://github.com/gobuffalo/packr/tree/master/v2
