### ISSUE TITLE
Proposal: tree directory

### ISSUE THREAD

**Issue by oyepez003** [gobuffalo/buffalo#1539]
This is not an issue, is an Improvement Proposal in the tree directory:

```
.my_project
├── app
│   ├── actions
│   ├── grifts
│   └── models
├── config
├── bin
├── database
│   ├── fixtures
│   └── migrations
├── Dockerfile
├── go.mod
├── main.go
├── package.json
├── package-lock.json
├── public
│   ├── assets
│   └── robots.txt
├── README.md
├── resources
│   ├── assets
│   ├── inflections.json
│   ├── locales
│   └── views
├── storage
│   └── logs
│   └── tmp
└── webpack.config.js
```
I think a structure like this can be a bit more intuitive to find files and folders in the project.

I have created a project with this structure and after the update some paths in the Packr configuration, the project works perfect in development environment but I got an error on run `buffalo build`, the command continues searching the actions in the root directory.

This is just a suggestion, you can close the issue if it's not relevant.

Thanks for Buffalo, it's an excellent framework.

**Comment by markbates** [comment]
Thanks for the suggestion on a new folder layout, but at this point we're pretty satisfied with how it is laid out, and we we won't be making large changes, such as this, without a strong argument for the change. I hope you understand. Thanks.
