### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by desylva** [gobuffalo/buffalo#1553]
### Expected Behavior
`make install` should make sure the deps are up to date, in non-module mode

Setting GO111MODULE=on fixed the issue.

### Actual Behavior

```
$ make install
go get github.com/gobuffalo/release
go get github.com/gobuffalo/packr/v2/packr2
# github.com/gobuffalo/packr/v2/jam/store
../packr/v2/jam/store/disk.go:309:13: cannot use plog.Logger (type logger.FieldLogger) as type genny.Logger in assignment:
	logger.FieldLogger does not implement genny.Logger (missing Print method)
../packr/v2/jam/store/legacy.go:111:13: cannot use plog.Logger (type logger.FieldLogger) as type genny.Logger in assignment:
	logger.FieldLogger does not implement genny.Logger (missing Print method)
make: *** [deps] Error 2
```

**Comment by markbates** [comment]
`make install` is failing because of out of date packages on the local computer. To make this work a change to `Makefile` for doing a `go get` when not using modules would need to be made.

This is a good first issue for someone to contribute to.
