### ISSUE TITLE
There was a problem starting the dev server

### ISSUE THREAD

**Issue by astropanic** [gobuffalo/buffalo#156]
Wanted trying it out. Went to the [docs](http://gobuffalo.io/docs/getting-started),

Issued an: ```go get -v -u github.com/gobuffalo/buffalo/buffalo```, 

then: ```buffalo new coke --db-type sqlite3```

after ```buffalo dev``` got:

> Buffalo version 0.7.1
> 
> There was a problem starting the dev server: Unknown

my go environment:

~~~shell
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wopi/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p_/xr4056w17_17_sk_kzg6r4fc0000gn/T/go-build041465092=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
~~~

**Comment by markbates** [comment]
There was an issue closed the other day to fix that error in the next version. 

It's a node/npm issue.

**Comment by bscott** [comment]
@markbates  I have a branch with the addition of the context of that error, should I still submit the PR or did you already take care of it?

**Comment by markbates** [comment]
@bscott if you have better docs than what is in master, please add them! :)

**Comment by bscott** [comment]
@markbates Will do, should have a PR to the docs page and a PR to bring context to the "Unknown" error in next hour or so.
