### ISSUE TITLE
Buffalo should follow XDG Base Directory specification for dotfiles

### ISSUE THREAD

**Issue by petermbenjamin** [gobuffalo/buffalo#1566]
## Description

Buffalo creates a `.buffalo` directory in the users' `$HOME` directory, thus not respecting the users' XDG environment variables.

Per [Freedesktop spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

- `$XDG_CONFIG_HOME` defines the base directory relative to which user specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.
- `$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used.
- `$XDG_CACHE_HOME` defines the base directory relative to which user specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache` should be used.

Applications/tools that comply with XDG specifications:

- git
- neovim
- yarn
- more here: https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by lukasschlueter** [comment]
The generated file is for caching the available buffalo plugins. The relevant line is https://github.com/gobuffalo/buffalo-plugins/blob/b7c1610bb54b8baf21a2b68dc8ad33b1353ef867/plugins/cache.go#L28

As it's pretty much irrelevant where we store the cache file, be might as well follow some standard, especially as it's a small change. 
Is the freedesktop spec widely accepted?

**Comment by petermbenjamin** [comment]
@lukasschlueter,

>Is the freedesktop spec widely accepted?

Yes, I would say it is widely accepted. 
I added examples of applications/tools that comply with freedesktop's XDG spec above.

**Comment by lukasschlueter** [comment]
Maybe something like this would be helpful:
https://github.com/ProtonMail/go-appdir
I'm not sure about the MacOS path though, it differs from yours.

**Comment by markbates** [comment]
I think this ticket should move to the `meta` repo because I think we need a `meta.CacheDir()` or some equivalent so everywhere in the eco system can take advantage of it. Thoughts?

**Comment by petermbenjamin** [comment]
@markbates - I agree.

I can close this ticket and work on a PR against `meta` repo. Let me know if you think otherwise.

**Comment by markbates** [comment]
On second thought, `envy` might be the better place for it, as that's where "environment" stuff is managed. 

I say close the ticket and add a couple functions in `envy` for `envy.HomeDir()` `envy.CacheDir()`, etc... 

Thanks @petermbenjamin

**Comment by markbates** [comment]
@lukasschlueter I looked at that package, and while the idea is good, I don't like that you have to create a new value with a name. I'd rather have the raw dir and then append whatever I want on the end of it.
