### ISSUE TITLE
Creating a new app with webpack requires admin privileges

### ISSUE THREAD

**Issue by mdhender** [gobuffalo/buffalo#157]
`buffalo new coke` attempts to install webpack globally. That fails if the user doesn't have the ability to update the global `npm` install.

```
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/coke/coke/npm-debug.log
There was a problem running npm install. You may want to checkout their docs for help!
https://docs.npmjs.com/getting-started/fixing-npm-permissions
Error: exit status 243
Usage:
  buffalo new [name] [flags]
```

The `-g` option is wired in to `buffalo/cmd/generate/webpack.go`:

```
cmd := exec.Command("npm", "install", "webpack", "-g")
```

There's no option to work around, except to run `buffalo new coke --skip-webpack` and doing a local install of webpack by hand. It's not clear what else needs to be done since buffalo creates `assets/` and `webpack.config.js` when installing webpack.

It would be nice if there were an option to install `webpack` locally and still have buffalo generate the assets and configuration.

**Comment by bscott** [comment]
@mdhender I have not been able to get webpack working properly when installed locally, believe this is more of a webpack issue then buffalo.

Were you able to start buffalo with webpack installed locally?,  I can look into extending support for local support.

**Comment by mdhender** [comment]
Not yet. I got an admin to install it globally. Still have problems because buffalo wants to install it again (it doesn't recognize that it's already there). I'm looking at the go code there to see if I can get buffalo to skip the global install and still install the assets and such.

**Comment by bscott** [comment]
@mdhender Ok, Buffalo is just using the local system $PATH, so if your npm isn't properly setup, it could be that your local environment has webpack missing in it's path.

I would ```echo $PATH``` and make sure that where ever NPM is installing webpack is there. 

I don't think you can skip the global install and still use webpack, it's either you install webpack or skip that feature completely in the current state of buffalo.

**Comment by mdhender** [comment]
After fighting with it a bit, I do agree with forcing webpack to install globally. But, if webpack is already installed, buffalo should skip running the installation again. If `func NewWebpackGenerator` could look at some flag and avoid the `npm install` while still doing the `npm init` and such, I think that would work.

**Comment by mdhender** [comment]
Is that something that you'd accept a PR on?

**Comment by bscott** [comment]
@mdhender Yes in deed, might be better to have `func NewWebpackGenerator` to detect if webpack is already in the PATH, instead of adding an extra flag. PR's are most welcome 👍

**Comment by mdhender** [comment]
I'll do that PATH check. Thanks.

**Comment by mdhender** [comment]
I made the update but I don't know how to write a test case for this. The change is wrapping the `npm install` with
```
_, err = exec.LookPath("webpack")
```

I can test it by changing PATH, but how would I test the Go code in that if condition?
