### ISSUE TITLE
buffalo new fails with error

### ISSUE THREAD

**Issue by andrewebdev** [gobuffalo/buffalo#1574]
I ran the `buffalo new testproject` command and got the following error:

```
<---snip--->

         run  go get github.com/gobuffalo/buffalo-pop
# github.com/gobuffalo/buffalo
../../gobuffalo/buffalo/app.go:69:10: a.router.MethodNotAllowedHandler undefined (type *mux.Router has no field or method MethodNotAllowedHandler)
         run  gofmt -w actions/actions_test.go actions/app.go actions/home.go actions/home_test.go actions/render.go grifts/db.go grifts/init.go main.go models/models.go models/models_test.go
Usage:
  buffalo new [name] [flags]

<---snip--->

ERRO[0167] Error: exit status 2
```

*Buffalo version*: `INFO[0002] Buffalo version is: v0.13.13`
*Go version*: `go version go1.10.4 linux/amd64`

**Comment by markbates** [comment]
This is the result of out of date dependencies, probably caused by `go get` failing. Removed the broken dependencies and try again with `go get -u`. 

It is recommended to use a package management system, like Go Modules or `dep`, to prevent these sorts of issues.
