### ISSUE TITLE
Error: exec: "buffalo-pop": executable file not found in $PATH

### ISSUE THREAD

**Issue by owen2345** [gobuffalo/buffalo#1589]
Following the get started tutorial I got this error on generating resources:
```
buffalo g resource widget title description:nulls.Text
```
ERRO[0001] Error: exec: "buffalo-pop": executable file not found in $PATH
I tried to fix by several days without success. Could you please let me know how to fix it?
Details:
- go version go1.11.5 darwin/amd64
- Buffalo Version v0.13.13
As a RoR developer I am very happy to see a framework  based on RoR.

Cheers!

**Comment by mrkmcknz** [comment]
I'm also running into this issue on v0.14.1. How did you resolve @owen2345?

**Comment by mrkmcknz** [comment]
This was related to my GOPATH inside my Docker executable.

**Comment by benosoftware** [comment]
I am also facing the same issue. What changes make it work @mrkmcknz

**Comment by dixpac** [comment]
I've the same problem. I'm new to go and buffalo. I've installed buffalo v0.14.10.
Running `buffalo db create` works fine, but when I try to generate a resource like this
```go
buffalo g r posts title
```
`ERRO[0004] Error: exec: "buffalo-pop": executable file not found in $PATH` is raised

**Comment by stanislas-m** [comment]
Try `buffalo plugins install github.com/gobuffalo/buffalo-pop`.

**Comment by dixpac** [comment]
@stanislas-m per your instruction I've tried but still the same problem:

<img width="1266" alt="Screenshot 2019-08-29 at 10 11 47" src="https://user-images.githubusercontent.com/7427365/63922681-7110ee80-ca45-11e9-840e-122d45dd6d79.png">

NOTE: I'm using go modules

**Comment by oliwerhelsen** [comment]
@markbates any idea on this error?

**Comment by markbates** [comment]
You’re PATH is not set up properly and doesn’t include your GOPATH/bin. That’s a Go requirement. The buffalo info command will tell you this and point to documentation that helps you resolve it.

**Comment by oliwerhelsen** [comment]
Ah, awesome! I didn't know that command. Thanks!

**Comment by ricktimmis** [comment]
I ran into the same issue, and found this via google. Pointer for the next person looking

your friend is

$>buffalo info

**Comment by vineetdaniel** [comment]
having same issue on Mac OS Mojave 10.14.6 using postgres as db. Output of `buffalo info`
`-> Go: Checking installation
✓ The `go` executable was found on your system at: /usr/local/go/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.14.2, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /Users/avemaria/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /usr/local/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v12.16.3, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /usr/local/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.14.4, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /usr/local/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.22.4, meets the minimum requirements.

-> PostgreSQL: Checking installation
✓ The `postgres` executable was found on your system at: /Applications/Postgres.app/Contents/Versions/latest/bin/postgres

-> PostgreSQL: Checking minimum version requirements
✓ Your version of PostgreSQL, 12.3.0, meets the minimum requirements.

-> MySQL: Checking installation
✘ The `mysql` executable could not be found on your system.
For help setting up your MySQL environment please follow the instructions for you platform at:

https://www.mysql.com/downloads/

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.24.0, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /usr/local/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.16.8, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /Users/avemaria/ll
Root        /Users/avemaria/ll
GoPath      /Users/avemaria/go
PackagePkg  ll
ActionsPkg  ll/actions
ModelsPkg   ll/models
GriftsPkg   ll/grifts
WithModules true
Name        LL
Bin         bin/LL
VCS         none
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack -p --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "LL"
bin = "bin/LL"
vcs = "none"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-auth"
  go_get = "github.com/gobuffalo/buffalo-auth"

[[plugin]]
  binary = "buffalo-goth"
  go_get = "github.com/gobuffalo/buffalo-goth"

[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop/v2"

-> Buffalo: go.mod
module ll

go 1.14

require (
	github.com/gobuffalo/buffalo v0.15.5
	github.com/gobuffalo/buffalo-auth v1.3.1 // indirect
	github.com/gobuffalo/buffalo-goth v1.3.0 // indirect
	github.com/gobuffalo/buffalo-pop/v2 v2.0.6
	github.com/gobuffalo/envy v1.9.0
	github.com/gobuffalo/genny/v2 v2.0.6 // indirect
	github.com/gobuffalo/mw-csrf v1.0.0
	github.com/gobuffalo/mw-forcessl v0.0.0-20180802152810-73921ae7a130
	github.com/gobuffalo/mw-i18n v0.0.0-20190129204410-552713a3ebb4
	github.com/gobuffalo/mw-paramlogger v0.0.0-20190129202837-395da1998525
	github.com/gobuffalo/packr/v2 v2.8.0
	github.com/gobuffalo/pop/v5 v5.1.1
	github.com/gobuffalo/suite/v3 v3.0.0
	github.com/gobuffalo/validate/v3 v3.1.0
	github.com/gobuffalo/x v0.0.0-20190224155809-6bb134105960
	github.com/gofrs/uuid v3.2.0+incompatible
	github.com/karrick/godirwalk v1.15.6 // indirect
	github.com/markbates/goth v1.64.1
	github.com/markbates/grift v1.5.0
	github.com/pkg/errors v0.9.1
	github.com/rogpeppe/go-internal v1.6.0 // indirect
	github.com/sirupsen/logrus v1.6.0 // indirect
	github.com/spf13/cobra v1.0.0 // indirect
	github.com/unrolled/secure v0.0.0-20190103195806-76e6d4e9b90c
	golang.org/x/crypto v0.0.0-20200510223506-06a226fb4e37
	golang.org/x/mod v0.3.0 // indirect
	golang.org/x/sys v0.0.0-20200523222454-059865788121 // indirect
	golang.org/x/tools v0.0.0-20200528185414-6be401e3f76e // indirect
)
`
buffalo plugins install github.com/gobuffalo/buffalo-pop didn't solved the issue. 
Let me know if more information is required.

**Comment by ricktimmis** [comment]
Hi, Check your GOPATH as well, see MarkBates comment 5th Dec

echo $GOPATH

Also if you have the specific error that would help too

**Comment by MatheusGelinskiPires** [comment]
go install github.com/gobuffalo/buffalo-pop@latest
