### ISSUE TITLE
Two or more buffalo app in the same windows server

### ISSUE THREAD

**Issue by ajoses** [gobuffalo/buffalo#1603]
## Description

I'm putting several buffalo apps in a windows server 2008 machine, but each one has it's own configuration.
I tried using .env files for each application but after initializing the first one, the second take the environment variables setted by the first one.

### Steps to Reproduce the Problem

Install in the same windows machine two application in different directorys and each one with the .env. Each application .evn has the "PORT" variable configured with different values (for example one with 3000 and the other with 3001).
Run the first application, and it run correctly.
Run the second and get an error of port already used or sometimes it exit after trying to bind to the port, because it takes the same port of the first application.

### Expected Behavior

I want each application take it's own configuration without being affected by the other.

### Actual Behavior

The second application take the parameters setted by the first one, causing an error in the second application because the port is already taken.

### Info

Right now my "solution" was to put a prefix by application to the variables in order to get them running side by side. For example for the "PORT" I changed to "FP_PORT".

I know that in Linux I can use Docker, however right now I'm attached to a windows server 2008.

I want to know if this is the correct behavior or what I need to do in order to get them running without the prefix in the variables.

**Comment by stanislas-m** [comment]
Consider using `setlocal` and `endlocal` batch commands (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setlocal) to restrict the scope of your env vars on Windows.
