### ISSUE TITLE
Error generate new project

### ISSUE THREAD

**Issue by Cloud-Man** [gobuffalo/buffalo#1609]
I'm trying to start a new project with the command:

<pre>$  buffalo new coke</pre>
<p>
and I get wrong generated path in grifts/init.go with next error:
</p>
<pre>grifts/init.go:5:2: cannot find package "../coke/actions" in: /home/me/go/coke/coke/actions</pre>
<p>
How I can resolve it?
</p>

**Comment by markbates** [comment]
You're not inside the GOPATH or you're trying to use modules without having the turned on. https://www.gobuffalo.io/en/docs/gomods

**Comment by Cloud-Man** [comment]
@markbates thanks. Enabling module support - resolve this problem
