### ISSUE TITLE
Introduce `.plush` extension as default template engine

### ISSUE THREAD

**Issue by imranismail** [gobuffalo/buffalo#1630]
This is just a question and a suggestion. Is it possible to introduce a `.plush` clause here as default?

https://github.com/gobuffalo/buffalo/blob/98c7d0bad5a8b2995a5f4517df1346819386ed60/render/render.go#L40

I want to give a shot at this if possible.

My use case is that I want to dynamically render yaml/json file. I do it right now by naming the templates for these files like so: `openapi.yaml.tmpl`

**Comment by markbates** [comment]
Absolutely! PRs welcome!

-----------
Mark Bates

**Comment by markbates** [comment]
This was fixed in `v0.14.7`
