### ISSUE TITLE
Buffalo generates a Link tag to Bootstrap CSS by default in application.html

### ISSUE THREAD

**Issue by zeknox** [gobuffalo/buffalo#1632]
## Description

This seems to be a bug report whenever you generate a new buffalo application using the default options with no arguments supplied it will add a bootstrap link tag to the `templates/application.html:7` file.

<pre>&ltlink rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous"></pre>

### Steps to Reproduce the Problem

  1. Generate a new application such as `buffalo new coke` while running on version v0.14.2
  1. Navigate over to `templates/application.html` line 7 and you should notice an HTML link tag to bootstrap
  1. Removing this bootstrap line does not impact the CSS structure at all which leads to believe it's redundant

### Expected Behavior

When discussing this in the slack chat room, Stanislas mentioned that: "It should only be generated if you took the "without nodejs" option.

### Actual Behavior

The HTML link tag for bootstrap CSS is generated by default when generating a buffalo application.

### Info

Generated Head tags from `templates/application.html`
<pre>
  &lthead>
    &ltmeta name="viewport" content="width=device-width, initial-scale=1">
    &ltmeta charset="utf-8">
    &lttitle>Buffalo - Vue</title>
&ltlink rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    &lt%= stylesheetTag("application.css") %>
    &ltmeta name="csrf-param" content="authenticity_token" />
    &ltmeta name="csrf-token" content="<%= authenticity_token %>" />
    &ltlink rel="icon" href="<%= assetPath("images/favicon.ico") %>">
  &lt/head>
</pre>

**Comment by paganotoni** [comment]
Confirmed this one working on a PR that fixes it.

**Comment by paganotoni** [comment]
Solved by #1641
