### ISSUE TITLE
Generated font-awesome is out of date

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#1642]
We currently generate: 

package.json
`"font-awesome": "~4.7.0"` should be `"@fortawesome/fontawesome-free": "^5.8.1",`

application.scss
`@import "~font-awesome/css/font-awesome.css";` should be `@import "~@fortawesome/fontawesome-free/css/all.min.css";`

**Comment by jrepe** [comment]
Mind if I take this one?

**Comment by markbates** [comment]
Go for it! :)

-----------
Mark Bates
