### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference content_type=application/json

### ISSUE THREAD

**Issue by sillysachin** [gobuffalo/buffalo#1649]
## Description
LOGS for CURL Command
```
SELECT schedule.delete_fl, schedule.disable_fl, schedule.id, schedule.period_from_hour, schedule.period_from_minute, schedule.period_to_hour, schedule.period_to_minute, schedule.service, schedule.submitted_date FROM schedule AS schedule WHERE schedule.id = ? LIMIT 1 $1=1
/api/v1/schedules/1/ content_type=application/json db=1.341216ms duration=35.074433ms human_size="195 B" method=GET params="{\"id\":[\"1\"]}" path=/api/v1/schedules/1/ render="193.732µs" request_id=TWyjNVSBKX-wgGQKDzjvF size=195 status=200
```

LOGS for Browser URL Visit
```
SELECT schedule.delete_fl, schedule.disable_fl, schedule.id, schedule.period_from_hour, schedule.period_from_minute, schedule.period_to_hour, schedule.period_to_minute, schedule.service, schedule.submitted_date FROM schedule AS schedule WHERE schedule.id = ? LIMIT 1 $1=1
/api/v1/schedules/1/ content_type=application/json db=2.292141ms duration=3.029946ms human_size="0 B" method=GET params="{\"id\":[\"1\"]}" path=/api/v1/schedules/1/ render="205.267µs" request_id=xsWBAmJJoN-fIiotbYuAV size=0 status=0
runtime error: invalid memory address or nil pointer dereference content_type=application/json db=2.292141ms duration=3.029946ms human_size="0 B" method=GET params="{\"id\":[\"1\"]}" path=/api/v1/schedules/1/ render="205.267µs" request_id=xsWBAmJJoN-fIiotbYuAV size=0 status=0
```

For bug reports, please provide as much *relevant* info as possible.

### Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. buffalo new equibot-app --db-type mysql
  1. buffalo generate resource Schedule
  1. buffalo dev 
  1. curl -X GET \         
  http://localhost:3000/api/v1/schedules/1 \
  -H 'Postman-Token: bafb2f43-5a43-43e0-926b-36b558054d50' \
  -H 'cache-control: no-cache'
{"delete_fl":"N","disable_fl":"N","period_from_hour":19,"period_from_minute":0,"period_to_hour":19,"period_to_minute":30,"service":"bse_bulk_deal","ID":1,"submitted_date":"2018-06-21T08:56:40Z"}
  1. visit in browser - http://localhost:3000/api/v1/schedules/1

### Expected Behavior
curl command, postman use works and browser invocation of url fails.
Browser invocation in URL bar for http://localhost:3000/api/v1/schedules/1 should not trigger a 500 error
### Actual Behavior
Browser invocation of api url fails.

### Info
Using MAMP on MAC Mojave 10.14.4 (18E226)

Please run `buffalo info` and paste the information below where it says "PASTE_HERE".

<details>

```
Pwd         /Volumes/Workspace/GoWork/src/equibot
Root        /Volumes/Workspace/GoWork/src/equibot
GoPath      /Volumes/Workspace/GoWork
PackagePkg  equibot
ActionsPkg  equibot/actions
ModelsPkg   equibot/models
GriftsPkg   equibot/grifts
WithModules false
Name        equibot
Bin         bin/equibot
VCS         
WithPop     false
WithSQLite  false
WithDep     false
WithWebpack false
WithNodeJs  false
WithYarn    false
WithDocker  false
WithGrifts  false
AsWeb       true
AsAPI       false
InApp       false
PackageJSON {map[]}
```

</details>

**Comment by sillysachin** [comment]
Adding Two Different Curl commands with change in -H 'Accept:" 
```
➜  equibot curl -X GET http://localhost:3000/api/v1/schedules/1 -H 'cache-control: no-cache' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'
{"error":"runtime error: invalid memory address or nil pointer dereference","trace":"runtime error: invalid memory address or nil pointer dereference\n\nruntime error: invalid memory address or nil pointer dereference","code":500}

➜  equibot curl -X GET http://localhost:3000/api/v1/schedules/1 -H 'cache-control: no-cache' -H 'Accept: */*'                                               
{"delete_fl":"N","disable_fl":"N","period_from_hour":19,"period_from_minute":0,"period_to_hour":19,"period_to_minute":30,"service":"bse_bulk_deal","ID":1,"submitted_date":"2018-06-21T08:56:40Z"}

```

**Comment by dfwmountainbiker** [comment]
@sillysachin Did you create your app as an api only app? eg: --api on create?

I received a similar error, and tried:
- API vs "regular" app creation (buffalo new without --api) and only the API had the issue
- tried sqlite3, postgres drivers thinking it was them (no difference)
- tried seeing if it needed "go get github.com/gobuffalo/mw-i18n" (didn't make a difference)

**Comment by markbates** [comment]
https://gobuffalo.io/en/docs/rendering

If you’re using Auto and ask for HTML it will try and render HTML. You can either not ask for HTML, or you can switch to the JSON renderer instead of the Auto one.

**Comment by dfwmountainbiker** [comment]
Buffalo responds to the input method (eg: form, json) by inferring how to respond. From Mark's suggestion above, if you look at an Action, the method might replace the Auto line with something similar for an API only to:

From
	return c.Render(201, r.Auto(c, event))
To
	return c.Render(200, r.JSON(event)) 

Then you can test a curl command for with the Content type for json, for example:
curl -H "Content-Type: application/json" --data '{"username":"xyz"}' http://localhost:3000/event
