### ISSUE TITLE
All buffalo commands end up in a deadlock.

### ISSUE THREAD

**Issue by twisted1919** [gobuffalo/buffalo#1659]
This is what i get out of a sudden when i run `buffalo help` `buffalo dev` etc:  

	$ buffalo help
	fatal error: all goroutines are asleep - deadlock!

	goroutine 1 [semacquire, locked to thread]:
	sync.runtime_SemacquireMutex(0xc0003a5714, 0x0)
		/usr/local/go/src/runtime/sema.go:71 +0x3d
	sync.(*Mutex).Lock(0xc0003a5710)
		/usr/local/go/src/sync/mutex.go:134 +0x109
	sync.(*Once).Do(0xc0003a5710, 0xc00032cf70)
		/usr/local/go/src/sync/once.go:40 +0x3b
	github.com/markbates/oncer.Do(0xc00028c3c0, 0x97, 0xc00032cf70)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/markbates/oncer@v0.0.0-20181203154359-bf2de49a0be2/oncer.go:12 +0xbb
	github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports(0xc0000ae8a0, 0xc00038ec40, 0x3d, 0xc00038ec40, 0x3d, 0x5, 0x8, 0x5)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/jam/parser/finder.go:51 +0x1db
	github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports.func1()
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/jam/parser/finder.go:92 +0x510
	sync.(*Once).Do(0xc0000b2c90, 0xc00032d318)
		/usr/local/go/src/sync/once.go:44 +0xb3
	github.com/markbates/oncer.Do(0xc00028c280, 0x96, 0xc00032d318)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/markbates/oncer@v0.0.0-20181203154359-bf2de49a0be2/oncer.go:12 +0xbb
	github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports(0xc0000ae8a0, 0xc000345e40, 0x3c, 0xc000345e40, 0x3c, 0x0, 0x0, 0x0)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/jam/parser/finder.go:51 +0x1db
	github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports.func1()
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/jam/parser/finder.go:92 +0x510
	sync.(*Once).Do(0xc0003a5710, 0xc0001c36c0)
		/usr/local/go/src/sync/once.go:44 +0xb3
	github.com/markbates/oncer.Do(0xc000223180, 0x97, 0xc0001c36c0)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/markbates/oncer@v0.0.0-20181203154359-bf2de49a0be2/oncer.go:12 +0xbb
	github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports(0xc0000ae8a0, 0xc00013ae80, 0x3d, 0xc00013ae80, 0x3d, 0x20, 0x1b556c0, 0xc00015f2c0)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/jam/parser/finder.go:51 +0x1db
	github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports.func1()
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/jam/parser/finder.go:92 +0x510
	sync.(*Once).Do(0xc0000341d0, 0xc0001c3a68)
		/usr/local/go/src/sync/once.go:44 +0xb3
	github.com/markbates/oncer.Do(0xc0001cc000, 0x8f, 0xc0001c3a68)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/markbates/oncer@v0.0.0-20181203154359-bf2de49a0be2/oncer.go:12 +0xbb
	github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports(0xc0000ae8a0, 0xc000036084, 0x35, 0x0, 0x0, 0x2, 0x2, 0x1)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/jam/parser/finder.go:51 +0x1db
	github.com/gobuffalo/packr/v2/jam/parser.NewFromRoots(0x21cf300, 0x0, 0x0, 0xc0000ae860, 0xc0000cc000, 0x10, 0x1911880)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/jam/parser/roots.go:70 +0x969
	github.com/gobuffalo/packr/v2.glob..func1()
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/packr.go:14 +0x5e
	github.com/markbates/safe.Run.func1(0xc000000008, 0x1a49608)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/markbates/safe@v1.0.1/safe.go:12 +0x24
	github.com/markbates/safe.RunE(0xc0000e1f08, 0x0, 0x0)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/markbates/safe@v1.0.1/safe.go:32 +0x55
	github.com/markbates/safe.Run(0x1a492d0, 0x25, 0x1b549c0)
		/Users/markbates/Dropbox/go/pkg/mod/github.com/markbates/safe@v1.0.1/safe.go:11 +0x49
	github.com/gobuffalo/packr/v2.init.ializers()
		/Users/markbates/Dropbox/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.1.0/packr.go:13 +0x67

Any idea what might cause it?

Go 1.12 using modules.

**Comment by stanislas-m** [comment]
Hello, can you please provide more info about the buffalo version you're using, OS, and anything that can help to reproduce? Thanks. :)

**Comment by twisted1919** [comment]
@stanislas-m - i am using `Buffalo version is: v0.14.3` on MacOS Mojave.  
Since i couldn't fix the issue i had removed everything, and started from scratch. I don't know how i could provide more information, sorry for that.

**Comment by stanislas-m** [comment]
I can't reproduce with the given info, please reopen the issue if you find a way to reproduce.

**Comment by jackbit** [comment]
mine:
```
➜ buffalo
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire, locked to thread]:
sync.runtime_SemacquireMutex(0xc0000284b8, 0x0, 0x1)
	/opt/hostedtoolcache/go/1.13.7/x64/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000284b4)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/mutex.go:81
sync.(*Once).doSlow(0xc0000284b0, 0xc00011c918)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:62 +0x122
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:57
github.com/gobuffalo/packr/v2/internal/takeon/github.com/markbates/oncer.Do(0xc000124210, 0xad, 0xc00011c918)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/internal/takeon/github.com/markbates/oncer/oncer.go:12 +0xc1
github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports(0xc00008de80, 0xc00018e180, 0x54, 0xc00018e180, 0x54, 0xc0000e8500, 0x4, 0x8)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/finder.go:62 +0x1da
github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports.func1()
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/finder.go:103 +0x50d
sync.(*Once).doSlow(0xc000095170, 0xc00011cd28)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:57
github.com/gobuffalo/packr/v2/internal/takeon/github.com/markbates/oncer.Do(0xc0001240b0, 0xae, 0xc00011cd28)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/internal/takeon/github.com/markbates/oncer/oncer.go:12 +0xc1
github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports(0xc00008de80, 0xc000073d40, 0x55, 0xc000073d40, 0x55, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/finder.go:62 +0x1da
github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports.func1()
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/finder.go:103 +0x50d
sync.(*Once).doSlow(0xc0000284b0, 0xc00011d138)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:57
github.com/gobuffalo/packr/v2/internal/takeon/github.com/markbates/oncer.Do(0xc000148160, 0xad, 0xc00011d138)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/internal/takeon/github.com/markbates/oncer/oncer.go:12 +0xc1
github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports(0xc00008de80, 0xc00002be60, 0x54, 0xc00002be60, 0x54, 0xc00013a200, 0x8, 0x10)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/finder.go:62 +0x1da
github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports.func1()
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/finder.go:103 +0x50d
sync.(*Once).doSlow(0xc000028130, 0xc00011d548)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:57
github.com/gobuffalo/packr/v2/internal/takeon/github.com/markbates/oncer.Do(0xc000148000, 0xae, 0xc00011d548)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/internal/takeon/github.com/markbates/oncer/oncer.go:12 +0xc1
github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports(0xc00008de80, 0xc00002ae40, 0x55, 0xc00002ae40, 0x55, 0x20, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/finder.go:62 +0x1da
github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports.func1()
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/finder.go:103 +0x50d
sync.(*Once).doSlow(0xc000094dc0, 0xc00011d958)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.13.7/x64/src/sync/once.go:57
github.com/gobuffalo/packr/v2/internal/takeon/github.com/markbates/oncer.Do(0xc000124000, 0xa6, 0xc00011d958)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/internal/takeon/github.com/markbates/oncer/oncer.go:12 +0xc1
github.com/gobuffalo/packr/v2/jam/parser.(*finder).findAllGoFilesImports(0xc00008de80, 0xc00002a004, 0x4d, 0x0, 0x0, 0x2, 0x2, 0x1)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/finder.go:62 +0x1da
github.com/gobuffalo/packr/v2/jam/parser.NewFromRoots(0xc000075280, 0x1, 0x1, 0xc00008dca0, 0xc000107a78, 0xc000107abc, 0x8)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/jam/parser/roots.go:70 +0x938
github.com/gobuffalo/packr/v2.glob..func1()
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/packr.go:15 +0x50
github.com/gobuffalo/packr/v2/internal/takeon/github.com/markbates/safe.Run.func1(0xc0000e3dd8, 0x18fe7c0)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/internal/takeon/github.com/markbates/safe/safe.go:12 +0x24
github.com/gobuffalo/packr/v2/internal/takeon/github.com/markbates/safe.RunE(0xc0000e3e38, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/internal/takeon/github.com/markbates/safe/safe.go:32 +0x63
github.com/gobuffalo/packr/v2/internal/takeon/github.com/markbates/safe.Run(0x1999a40, 0x25, 0x0)
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/internal/takeon/github.com/markbates/safe/safe.go:11 +0x49
github.com/gobuffalo/packr/v2.init()
	/home/runner/go/pkg/mod/github.com/gobuffalo/packr/v2@v2.7.1/packr.go:14 +0x7c
```

my go.mod

```
go 1.13

require (
	github.com/cockroachdb/cockroach-go v0.0.0-20190925194419-606b3d062051 // indirect
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/fatih/color v1.9.0 // indirect
	github.com/gobuffalo/buffalo v0.14.11
	github.com/gobuffalo/buffalo-pop v1.23.1
	github.com/gobuffalo/envy v1.9.0
	github.com/gobuffalo/fizz v1.9.6 // indirect
	github.com/gobuffalo/flect v0.2.1 // indirect
	github.com/gobuffalo/genny v0.6.0 // indirect
	github.com/gobuffalo/mw-contenttype v0.0.0-20190129203934-2554e742333b
	github.com/gobuffalo/mw-forcessl v0.0.0-20180802152810-73921ae7a130
	github.com/gobuffalo/mw-paramlogger v0.0.0-20190129202837-395da1998525
	github.com/gobuffalo/mw-tokenauth v0.0.0-20190129201951-95847f29c5c8
	github.com/gobuffalo/nulls v0.2.0 // indirect
	github.com/gobuffalo/packd v1.0.0 // indirect
	github.com/gobuffalo/packr/v2 v2.7.1
	github.com/gobuffalo/pop v4.13.1+incompatible
	github.com/gobuffalo/validate v2.0.4+incompatible
	github.com/gobuffalo/x v0.0.0-20190224155809-6bb134105960
	github.com/gofrs/uuid v3.2.0+incompatible
	github.com/jackc/pgconn v1.3.2 // indirect
	github.com/markbates/grift v1.1.0
	github.com/pkg/errors v0.9.1
	github.com/rs/cors v1.7.0
	github.com/unrolled/secure v0.0.0-20190103195806-76e6d4e9b90c
)
```

OS Catalina 10.15.3

**Comment by jackbit** [comment]
I found the problem: Added mailers in the model will occur  deadlock, example:

```
package models

import (
  "encoding/json"

  "github.com/gobuffalo/envy"
  "github.com/gobuffalo/pop"
  "github.com/gobuffalo/validate"
  "github.com/gobuffalo/validate/validators"
  "github.com/gofrs/uuid"

  "crypto/hmac"
  "crypto/sha256"
  "encoding/hex"

  "strings"
  "time"

  "project.mine/admin/mailers"
)
```

my mailers.go

```
package mailers

import (
  "log"

  "github.com/gobuffalo/buffalo/mail"
  "github.com/gobuffalo/buffalo/render"
  "github.com/gobuffalo/envy"
  "github.com/gobuffalo/packr/v2"
)

var smtp mail.Sender
var r *render.Engine

func init() {
  
  port, _ := envy.MustGet("SMTP_PORT")
  host, _ := envy.MustGet("SMTP_HOST")
  user, _ := envy.MustGet("SMTP_USER")
  password, _ := envy.MustGet("SMTP_PASSWORD")

  var err error
  smtp, err = mail.NewSMTPSender(host, port, user, password)
  // smtp.Dialer.SSL = true

  if err != nil {
    log.Fatal(err)
  }

  r = render.New(render.Options{
    HTMLLayout:   "layout.html",
    TemplatesBox: packr.New("app:mailers:templates", "../templates/mail"),
    Helpers:      render.Helpers{},
  })
}
```
