### ISSUE TITLE
Binding error when parsing power of 10 integer from number input

### ISSUE THREAD

**Issue by Raqbit** [gobuffalo/buffalo#1663]
## Description

I'm using `form_for` to generate my form, using `form.InputTag()` to generate a number field for my integer model field.
When entering the input `2e3` (2 * 10 ^ 2), which is a valid value for the html5 number input, I'm getting an integer parsing error from the `context.Bind` call.
### Steps to Reproduce the Problem

  1. Setup a model with an integer field
  1. Setup a `validators.IntIsPresent` validator on this integer field
  1. Create a form for this model and use a number input for the integer field
  1. Enter `2e3`

### Expected Behavior

It should parse it as `2000` or give a validation error.

### Actual Behavior

500 response:
`formam: could not parse number for field "<field>" in path "<field>": strconv.ParseInt: parsing "2e3": invalid syntax`

### Info

<details>

```
-> Buffalo: Application Details
WithModules false
Name        <name>
Bin         bin/<name>
VCS         git
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[]}

-> Buffalo: config/buffalo-app.toml
name = "<name>"
bin = "bin/<name>"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-plugins"
  go_get = "github.com/gobuffalo/buffalo-plugins"

[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop"
```

</details>

**Comment by markbates** [comment]
This isn’t a Buffalo issue. The Go standard library can’t parse that syntax.

**Comment by Raqbit** [comment]
Shouldn't buffalo catch that then? As it's valid to enter in the frontend, the user would at least expect a validation error. Now this simply returns an error in the binding call, which I can't use to create a validation error lookalike.

**Comment by markbates** [comment]
It’s not a valid Go integer. The error message tells you that. If you want to use that syntax you’ll need to use a type that can support it.

**Comment by Raqbit** [comment]
After reading up on it, it appears that float32 and float64 types do support parsing this.
