### ISSUE TITLE
"unable to find pop config file" runtime error

### ISSUE THREAD

**Issue by ItalyPaleAle** [gobuffalo/buffalo#1682]
## Description

I have built an app using Buffalo and compiled it with `GO111MODULE=on buffalo build --static`. If I run the app from anywhere outside of the folder containing the source code, the app fails all the time with a runtime error "unable to find pop config file".

### Steps to Reproduce the Problem

  1. Write an app using Buffalo that uses pop and SQLite
  1. Build the app for production with `GO111MODULE=on buffalo build --static`
  1. Move the binary `bin/app` to another system (or another folder) and run it

### Expected Behavior

The config file should be baked into the binary? Or at least that's what the documentation and the Dockerfile make me think.

### Actual Behavior

App doesn't launch.

### Info

- Go v1.12
- Linux Ubuntu x64
- buffalo v0.14.3
- pop v4.11.0
- buffalo-pop: v1.12.0
- Database uses SQLite

**Comment by markbates** [comment]
fixed in `development`

**Comment by badstorm** [comment]
I have the same issue with buffalo v0.15.3.
My dev envirorment is macOS (10.15.1) with GO (1.13.5) and in the _.zshrc_ config file I have

```
export GO111MODULE=on
export PATH=$PATH:$HOME/GO/bin
```

If I call _**buffalo build**_ the exectuable work perfect. But if I create a linux executable with **_GOOS=linux GOARCH=amd64 buffalo build_**, running it on a linux system i get _unable to find pop config file_
