### ISSUE TITLE
The defined router does not work, and it seems that there is no match.

### ISSUE THREAD

**Issue by triptips-top** [gobuffalo/buffalo#1693]
我尝试了3种创建新项目的方式
1. --api
2. --skip-webpack
3. 没有附加参数
仅 1 的方式路由是正常的
2 和 3 的方式路由是无法使用的

**Comment by lukasschlueter** [comment]
Hi,

I'd like to kindly ask you to stick to the English language. As far as I know, none of the core developers know Chinese.

Regarding your problem - based on Google translate:
It seems like you tried creating a new app with `--api`, `--skip-webpack` and without special parameters. Apparently only `--api` did work.

To be able to help you, we need exact and specific information about why it's not working and what's happening instead. Additionally, please include the output of `buffalo info`.

**Comment by markbates** [comment]
Skip web pack should be a no-op when using the api flag. I can’t read Chinese, so I’m guessing based on the flags. 

Is the problem that it’s generating webpack? It shouldn’t, but can’t tell.

**Comment by TripTips-top** [comment]
I tried three ways to create a project.

`1. buffalo hello --api`

`2. buffalo hello --skip-webpack`

`3. buffalo hello`

In the case of the second and third ways, the defined router does not work, and it seems that there is no match.

`app.GET("/hello", func (c buffalo.Context) error {
    return nli
})`

**Comment by TripTips-top** [comment]
![2019-06-15 03-26-01 的屏幕截图](https://user-images.githubusercontent.com/45717948/59533224-6a320f80-8f1d-11e9-8140-f4f25da910dc.png)
