### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by triptips-top** [gobuffalo/buffalo#1699]
![{3350D475-177C-4933-A908-F6FF40EA5601}_20190618114653](https://user-images.githubusercontent.com/45717948/59652077-d2ebe700-91be-11e9-8328-2147bda82764.jpg)

**Comment by markbates** [comment]
First, buffalo is only at 0.14.6, not 1.x. Second of all two screenshots are not a useful bug report. Please fill out the GitHub issue template so other can help you properly.

**Comment by triptips-top** [comment]
1. Can't know the version number on the screenshot.what are you saying?

2. The screenshot shows just the project creation process.

3. The pop plugin is not installed correctly with the project and cannot be installed manually.

4. In --sikp-webpack, the first line of a css file is missing.

5. I also found more bugs, so I won't list them one by one.

6. The experience of these days is very bad, I want to consider other projects.

**Comment by paganotoni** [comment]
@triptips-top for #4 ensure you have latest version of buffalo (v0.14.6) installed by running:
```
GO111MODULE=off go get -u -v github.com/gobuffalo/buffalo/buffalo
```
I know that this issue was solved in latest release.
