### ISSUE TITLE
Allow build command to split assets bundle and binary app

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#170]
Hello,

Is it possible to add an option to the `buffalo build` command, to split assets (js, css, images...) and app output ? This way, it will be possible to serve assets from another server (like a CDN for instance).

**Comment by markbates** [comment]
It would be possible, and it's a great idea. This would make a great first PR! :hint: :)

**Comment by markbates** [comment]
It wouldn't be difficult to add to `buffalo/cmd/build.go`

**Comment by stanislas-m** [comment]
Ah ah, I'll give it a try this week-end. :)

**Comment by bscott** [comment]
+1, let me know if I can help

**Comment by stanislas-m** [comment]
For now, I've just added an option to the build command, which gets the contents of the public/static dir and makes a zip file from it.

I think to be able to not-include assets in the binary, we have to remove the `app.ServeFiles("/assets", assetsPath())` in app.go, and remove the `assetsPath` function from render.go. Is that correct?

Moreover, the assets path will not be served by the app. Can we just let the user re-map it with a HTTP server (using NGINX or Apache, it won't be difficult to redirect requests to the assets location)? Do we have to rewrite all /assets paths to match an assets root location?
