### ISSUE TITLE
Pre-compiled arm binaries

### ISSUE THREAD

**Issue by ItalyPaleAle** [gobuffalo/buffalo#1713]
Currently, you're releasing binaries for Linux on Intel 32-bit and 64-bit. Any plans to release binaries for Linux on ARM? (both armv6 and arm64, as supported by the official Go binaries)

**Comment by markbates** [comment]
Sure! Open a PR.

**Comment by stanislas-m** [comment]
Fixed with #1733, so the next release will have ARM binaries.
