### ISSUE TITLE
Assets are not being extracted with -e flag

### ISSUE THREAD

**Issue by seguidor777** [gobuffalo/buffalo#1717]
Hello,
I am having trouble since yesterday because the assets are not being extracted in the build process

The command that I am running is
```
buffalo build --environment production -e
> (No output)
```

It has not worked with neither the -e nor the --extract-assets flags because it only generates a binary file in the /bin directory

I am used to have the compiled assets in the /public directory as in Rails and I would like to serve all of them by the reverse proxy

```
buffalo version
> INFO[0001] Buffalo version is: v0.14.3
node -v
> v10.12.0
```

Thanks in advance

**Comment by stanislas-m** [comment]
Fixed with #1736.
