### ISSUE TITLE
Bind is not really safe, as it binds any user input to the struct

### ISSUE THREAD

**Issue by ruudk** [gobuffalo/buffalo#1739]
First of all, Buffalo looks great! 

Have a look at the generated `Update` func for my `Week` resource:
```golang
// Update changes a Week in the DB. This function is mapped to
// the path PUT /weeks/{week_id}
func (v WeeksResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty Week
	week := &models.Week{}

	if err := tx.Find(week, c.Param("week_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Week to the html form elements
	if err := c.Bind(week); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(week)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, week))
	}

	// and redirect to the weeks index page
	return c.Render(200, r.Auto(c, week))
}
```

As you can see it allocates a Week model and then binds the request to it.

It then goes to `tx.ValidateAndUpdate` that accepts an optional `excludeColumns`.

I feel that this should be different. The `Bind` method should force you to supply a list of columns that you actually want to bind to. Because if you don't, it allows the requester to change ALL columns from a struct.

This would be better IMHO:
```golang
// Only bind column1 + column2 + column3 from the Request to the Week struct
if err := c.Bind(week, column1, column2, column3); err != nil {
    return err
}
```

What do you think? I feel that Buffalo should give best practices out of the box.

**Comment by kkirsche** [comment]
I don't think this implementation model makes sense from a developer experience perspective as you get into models with complicated relationship trees, depending on how deeply this has to be defined.

With that said, an optional chain method of `.permit` similar to Ruby on Rails's strong params may be an option or a permit hash / slice:

https://guides.rubyonrails.org/action_controller_overview.html#strong-parameters

```ruby
def person_params
      params.require(:person).permit(:name, :age)
    end
```

**Comment by markbates** [comment]
You can control which fields to bind to already using struct tags. https://gobuffalo.io/en/docs/bind#html-form-binding

You could also use "form models" as well.

**Comment by ruudk** [comment]
@markbates Nice, TIL! Is there also documentation about `form models` or an example somewhere?
