### ISSUE TITLE
Action generator should append new tests instead of clearing test file

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#174]
Hello,

On **Buffalo v0.7.1**, when you run the **action generator multiple times**, the new actions are added to the action file, but the test file is cleared. The generator should keep the already defined tests, like it keeps the already defined actions.

**Comment by markbates** [comment]
Great find! This would make a great first PR for someone. ;)

**Comment by markbates** [comment]
Closed with #175
