### ISSUE TITLE
0.14.7 is not released to docker hub

### ISSUE THREAD

**Issue by dcardamo** [gobuffalo/buffalo#1749]
## Description

gobuffalo 0.14.7 was released, but not pushed to docker hub.  So 
`FROM gobuffalo/buffalo:latest as builder` will give version 0.14.6
`FROM gobuffalo/buffalo:v0.14.7 as builder` will fail to find a tagged image

For bug reports, please provide as much *relevant* info as possible.

### Steps to Reproduce the Problem

1. change Dockerfile to one of the two examples above
2. `docker build -t dan:0.1 .` results in a failed build or old version

### Expected Behavior

Buffalo 0.14.7 should be released to docker hub

### Actual Behavior

In "lastest" example got version 0.14.6
In "v0.14.7" example, got error "no image"

### Info

Here is the output of buffalo version from the Dockerfile using "latest"
Step 10/18 : RUN buffalo version
 ---> Running in ece9774e00db
time="2019-07-30T19:14:39Z" level=info msg="Buffalo version is: v0.14.6"

**Comment by dcardamo** [comment]
If anyone wants a workaround, this is an image that doesn't base of the gobuffalo/buffalo docker image:

```
FROM golang:alpine as builder

RUN apk add --no-cache --upgrade apk-tools \
&& apk add --no-cache bash curl openssl git build-base nodejs npm postgresql libpq postgresql-contrib sqlite sqlite-dev mysql-client vim
RUN  curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
RUN cd /tmp && wget https://github.com/gobuffalo/buffalo/releases/download/v0.14.7/buffalo_0.14.7_linux_amd64.tar.gz && tar -xvzf buffalo_0.14.7_linux_amd64.tar.gz && mv buffalo /bin

RUN mkdir -p $GOPATH/src/reflector
WORKDIR $GOPATH/src/reflector

# this will cache the npm install step, unless package.json changes
ADD package.json .
ADD yarn.lock .
RUN npm install -g --no-progress yarn && yarn install --no-progress
ADD . .
ENV GO111MODULE=on
RUN go get ./...
RUN buffalo build --static -o /bin/app

FROM alpine
RUN apk --update upgrade && \
    apk add --no-cache curl bash ca-certificates tzdata && \
    update-ca-certificates && \
    rm -rf /var/cache/apk/*

WORKDIR /bin/

COPY --from=builder /bin/app .

# Uncomment to run the binary in "production" mode:
# ENV GO_ENV=production

# Bind the app to 0.0.0.0 so it can be seen from outside the container
ENV ADDR=0.0.0.0

EXPOSE 3000

# Uncomment to run the migrations before running the binary:
CMD /bin/app migrate; /bin/app
#CMD exec /bin/app
```

**Comment by markbates** [comment]
If you have a fix, that would be great. Docker hub isn't being very forgiving, and I'm unsure what the problem is.

**Comment by paganotoni** [comment]
@dcardamo we just pushed the `v0.14.7` docker image to our official dockerhub repo, Also if you want to give it a shot we also pushed a `v0.14.7-slim` alpine based version.

**Comment by dcardamo** [comment]
@paganotoni thanks!  Working great.

**Comment by paganotoni** [comment]
Awesome Thanks for reporting this @dcardamo
