### ISSUE TITLE
Best way to get the current resource name

### ISSUE THREAD

**Issue by seguidor777** [gobuffalo/buffalo#1762]
Hello,

I am working on a feature that uses policies to authorize requests basing on a user role, an action and a resource.

I have no problem to get the first two, but I am facing issues with getting the resource name, since I only have the full path. Is there any efficient way to get that with any function similar to `controller_name` from Rails?

**Comment by seguidor777** [comment]
I could extract the resource name from the name of the handler, for example:
`handlerName: = c.Data () ["current_route"].(buffalo.RouteInfo).HandlerName`

Lets suppose that handlerName is something like "github.com/company/project/actions.UsersResource.Edit"
And with some regexp stuff I capture the `UsersResource` string, but this does not convince me at all

**Comment by alexisvisco** [comment]
With the RouteInfo you have the Handler, maybe using reflect you could get the resource name ?

(I am doing a pr with the resource name in the RouteInfo and I rely on the name of the handler with reflect as they do to have the `HandlerName` (with suffix List, Delete, Show ...)

**Comment by seguidor777** [comment]
Hello! Thanks for replying. I agree with the proposal, it would be great to have the resource and the action names on separate fields, for example ResourceName and ActionName

**Comment by paganotoni** [comment]
@seguidor777 the RouteInfo has both: ResourceName and Handler name.

**Comment by paganotoni** [comment]
Closing this one as it seems to be solved. please reopen if still relevant.
