### ISSUE TITLE
[Question] Is possibile to add more "yield" area to a layout?

### ISSUE THREAD

**Issue by badstorm** [gobuffalo/buffalo#1768]
## Description
Suppose you have a layout page with two area (center and aside) and in your actions pages you need to set differnt contents for the two areas.
 
### Actual Behavior
At this time, i need to setup the structure (center and aside) for each pages.

### Expected Behavior
It is possible to define  two areas in the layout and in the action page, set contents for each area callaing for example multiple  <%= yield %>?

**Comment by dnnrly** [comment]
Could you provide an example?

**Comment by markbates** [comment]
https://gobuffalo.io/en/docs/helpers

**Comment by badstorm** [comment]
Thansk @markbates, **[contentFor and contentOf](https://gobuffalo.io/en/docs/helpers#the-contentfor-and-contentof-helpers)** is what i'm looking for!
