### ISSUE TITLE
allow passing a timeout to buffalo test

### ISSUE THREAD

**Issue by kiambogo** [gobuffalo/buffalo#1796]
## Description

Buffalo test should be allowed to take a `timeout` argument, similar `$ go test -timeout 300ms`. 

### Steps to Reproduce the Problem

Buffalo test does not currently provide a timeout option, as seen in the source code (https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/test.go) and by testing with the likes of `$ buffalo test -timeout 10m`

### Expected Behavior

Adding a timeout argument should work, allowing the tests to run for the specified duration before it panics. 

### Actual Behavior

Test seems to exit after reloading the schema.

### Info

go 1.13
buffalo v0.14.3

**Comment by pavan541cs** [comment]
@kiambogo Can I work on this issue ?

**Comment by kiambogo** [comment]
Fine by me! I attempted but was having issues with it playing nicely with
other arguments if I recall correctly. Hopefully you can have better luck.

**Comment by paganotoni** [comment]
I confirmed that for some reason this one still not fixed.

**Comment by paganotoni** [comment]
Covered in v0.16.4 thanks @kiambogo
