### ISSUE TITLE
Setup referencing wrong path, causing setup failure

### ISSUE THREAD

**Issue by mjboroski** [gobuffalo/buffalo#1817]
## Description

I found a bug.

### Steps to Reproduce the Problem

  1. buffalo new myapp -v
 
### Expected Behavior

"buffalo new" should work

### Actual Behavior

it didn't

### Info

<details>

***NOTICE THE DOUBLING OF "\myapp" IN THE LAST LINE'S PATH***
This is probably just a path variable fix, but I don't know where to even begin digging through the code to find it.

...
DEBU[2019-10-26T16:42:33-04:00] Step: 5488397b
DEBU[2019-10-26T16:42:33-04:00] Chdir: C:\Users\username\go\myapp
DEBU[2019-10-26T16:42:33-04:00] File: C:/Users/username/go/myapp/config/buffalo-plugins.toml
DEBU[2019-10-26T16:42:33-04:00] Step: c35a71ae
DEBU[2019-10-26T16:42:33-04:00] Chdir: C:\Users\username\go\myapp
DEBU[2019-10-26T16:42:33-04:00] Exec: go get -t ./...
grifts\init.go:5:2: cannot find package "../myapp/actions" in:
        C:\Users\username\go\myapp\myapp\actions

</details>

**Comment by markbates** [comment]
https://gobuffalo.io/en/docs/gomods/

If you run `buffalo info` it will tell you the problem.
