### ISSUE TITLE
Proposal: Reduce Context Size in 0.8.0

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#182]
With the addition of implementing `context.Context` and `Flash()` recently, the `Context` interface is starting to feel bloated.

I'm proposing that in version 0.8.0 we reduce the size of the interface.

I'm proposing that in 0.8.0 the `Context` look like this:

```go
type Context interface {
	context.Context
	Response() http.ResponseWriter
	Request() *http.Request
	Session() *Session
	Params() ParamValues
	Param(string) string
	Set(string, interface{})
	Logger() Logger
	Bind(interface{}) error
	Render(int, render.Renderer) error
	Error(int, error) error
	Redirect(int, string, ...interface{}) error
	Data() map[string]interface{}
	Flash() *Flash
}
```

That means the following functions will be abandoned:

```go
	ParamInt(string) (int, error)
	Get(string) interface{}
	LogField(string, interface{})
	LogFields(map[string]interface{})
	Websocket() (*websocket.Conn, error)
```

Since `Get` is currently deprecated in favor or `Value`, I'm fine with removing it completely in `0.8.0`.

I'm not sure what to do with the reset of the fields. One idea is to create a new type, something like `ExtendedContext` that would have this functions:

```go
func MyHandler(c buffalo.Context) error {
  ec := buffalo.ExtendedContext{c}
  ec.Websocket()
  ec.LogField("foo", "bar")
  // ...
}
```

Another idea is drop all of the extra functions entirely and move the `WebSocket` function to some sort of stand alone function that would be called like `Websocket(c)`.

I'm looking for feedback on this proposal, so please let me know how everyone feels.

**Comment by bketelsen** [comment]
Let it be big.  Adding extra confusion just because there are a lot of methods is counterintuitive.

**Comment by matryer** [comment]
App Engine does a lot of this kind of thing:

```go
buffalo.ParamInt(ctx, string) (int, error)
buffalo.Websocket(ctx) (*websocket.Conn, error)
```

Another option is to embed the `Request` and add extensions:

```go
struct BuffaloRequest struct {
  *http.Request
}

func (br * BuffaloRequest) ParamInt(name string) (int, error) { ... }
```

That way, you could use it as a normal `http.Request` but also it would have some Buffalo helpers.
