### ISSUE TITLE
Silent failure of unknown db type

### ISSUE THREAD

**Issue by amedeiros** [gobuffalo/buffalo#183]
If you run the following.

`buffalo new coke --db-type SOMETHING-BAD! > result.out 2>&1`

It seems like the db setup fails silently due to the unknown type being passed. I don't see a warning in the output file.

The issue seems to be around here https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/soda_generators.go#L34.

`generate.GenerateConfig("./database.yml", data)` returns an error but is being ignored and instead on line 35 nil is being returned silencing the error.

Possible solution is to return the error from GenerateConfig.

```go
g.Add(&gentronics.Func{
		Should: should,
		Runner: func(rootPath string, data gentronics.Data) error {
			data["dialect"] = data["dbType"]
			return generate.GenerateConfig("./database.yml", data)
		},
	})
```

This change results in the following output but does not fail the new app from generating. However, it does give the user some information to know what went wrong.

`Error: Could not initialize something-bad!!`

However, a better solution is to return the error but also validate the arguments being supplied by the user and bail out if they are invalid with a helpful message.

I can come up with a pull request for this if this sounds good.

**Comment by markbates** [comment]
Good find! Yes a PR would be excellent!
