### ISSUE TITLE
Quickly build Buffalo app for debug, using GO111MODULE=on

### ISSUE THREAD

**Issue by marius-nicolae** [gobuffalo/buffalo#1852]
Hello,

First, thank you for your effort. Appreciating!

## Description
On my machine, a newly created Buffalo app takes approx 23 seconds to build, every time. Since I'm new to Go and Go web frameworks such as Buffalo I tend to just add/modify one or two lines and launch a new debug session using IDEs (such as VS Code). Build time is getting in the way.

Is there any way of quickly building Buffalo applications (eventually just issuing "go build"), for debugging purposes? Loading every other dependency (such as the assets) directly from the disk, with a performance penalty, should be just fine.

### Steps to Reproduce the Problem

 time buffalo build -o Out/HelloWorldBuf

real	0m22,898s
user	0m22,767s
sys	0m4,021s

### Expected Behavior

Issue a command (like "go build") to quickly build the app.

### Actual Behavior

I could found just the "buffalo build" command.

### Info

Please run `buffalo info` and paste the information below where it says buffalo info
-> Go: Checking installation
✓ The `go` executable was found on your system at: /usr/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.13.4, meets the minimum requirements.

-> Go: Checking GOPATH
✓ You are using Go Modules, so no need to worry about the GOPATH.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✘ Your PATH (/home/mne/bin:/home/mne/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/mne/.npm/bin) does not contain /home/mne/go/bin.

Without /home/mne/go/bin in your `PATH` any Go executables can not be run globally.

For help setting up your Go environment please follow the instructions for you platform at:

https://www.gopherguides.com/courses/preparing-your-environment-for-go-development

-> Node: Checking installation
✓ The `node` executable was found on your system at: /usr/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v8.10.0, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /usr/bin/npm

-> NPM: Checking minimum version requirements
✘ Your version of NPM, 3.5.2, does not meet the minimum requirements.

Minimum versions of NPM are:

* >=6.0.0

* >=7.0.0

For help setting up your NPM environment please follow the instructions for you platform at:

https://docs.npmjs.com/getting-started/configuring-your-local-environment

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /home/mne/.npm/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.19.2, meets the minimum requirements.

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
✘ The `mysql` executable could not be found on your system.
For help setting up your MySQL environment please follow the instructions for you platform at:

https://www.mysql.com/downloads/

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.22.0, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /usr/local/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.15.1, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /home/mne/Work/Devel/toys/Go/HelloWorldBuf
Root        /home/mne/Work/Devel/toys/Go/HelloWorldBuf
GoPath      /home/mne/go
PackagePkg  HelloWorldBuf
ActionsPkg  HelloWorldBuf/actions
ModelsPkg   HelloWorldBuf/models
GriftsPkg   HelloWorldBuf/grifts
WithModules true
Name        HelloWorldBuf
Bin         bin/HelloWorldBuf
VCS         git
WithPop     true
WithSQLite  true
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack -p --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "HelloWorldBuf"
bin = "bin/HelloWorldBuf"
vcs = "git"
with_pop = true
with_sqlite = true
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop"
  tags = ["sqlite"]

-> Buffalo: go.mod
module HelloWorldBuf

go 1.13

require (
	github.com/gobuffalo/buffalo v0.15.1
	github.com/gobuffalo/buffalo-pop v1.23.1
	github.com/gobuffalo/envy v1.7.1
	github.com/gobuffalo/mw-csrf v0.0.0-20190129204204-25460a055517
	github.com/gobuffalo/mw-forcessl v0.0.0-20180802152810-73921ae7a130
	github.com/gobuffalo/mw-i18n v0.0.0-20190129204410-552713a3ebb4
	github.com/gobuffalo/mw-paramlogger v0.0.0-20190129202837-395da1998525
	github.com/gobuffalo/packr/v2 v2.7.1
	github.com/gobuffalo/pop v4.12.2+incompatible
	github.com/gobuffalo/suite v2.8.2+incompatible
	github.com/markbates/grift v1.5.0
	github.com/unrolled/secure v0.0.0-20190103195806-76e6d4e9b90c
)

**Comment by markbates** [comment]
https://gobuffalo.io/en/docs/getting-started/new-project#running-your-application-in-development

**Comment by marius-nicolae** [comment]
I've read that page but my question was how to run the application through a debugger, in an IDE, without waiting 23 seconds every time.

Is there any possibility?
