### ISSUE TITLE
Buffalo New Coke errors re: meta.BuildTags, and new properties of meta.App, among others

### ISSUE THREAD

**Issue by forrest321** [gobuffalo/buffalo#1855]
## Description

Receiving the following error while trying to build a new buffalo site:
`../../gobuffalo/buffalo/plugins/plugdeps/plugin.go:15:11: undefined: meta.BuildTags`

### Steps to Reproduce the Problem

  1. Install buffalo v 15.3 via the instructions under GNU/Linux as described [here.](https://gobuffalo.io/en/docs/getting-started/installation/)
  2. `buffalo new coke`
  3. Error will scroll by quickly, however the server will fail later.

### Expected Behavior

The command to update meta to v2 in the documentation doesn't (no longer?) work, with and without the GO111MODULE=off prefix.
`go get github.com/gobuffalo/meta/v2`
`GO111MODULE=off go get github.com/gobuffalo/meta/v2'

### Actual Behavior

`meta.BuildTags` and others are needed by the app, however they have not yet been merged to master. The meta branches encode and fix-envy both need to be merged in order to make it through the build process, however I'm still getting errors after that.

`package dloc/actions: unrecognized import path "dloc/actions" (import path does not begin with hostname)`

This could be due to a version mismatch as I've tried merging locally to get things running again, but with no luck.

### Info

<details>

-> Go: Checking installation
✓ The `go` executable was found on your system at: /home/fo/sdk/go1.12.5/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.12.5, meets the minimum requirements.

-> Go: Checking GOPATH
✓ You appear to be operating inside of your GOPATH.

-> Go: Checking Package Management
⚠ You do not appear to be using a package management system.

It is strongly suggested that you use one of the following package management systems:

* Go Modules (Recommended) - https://gobuffalo.io/en/docs/gomods
* Dep - https://github.com/golang/dep

For help setting up your Go environment please follow the instructions for you platform at:

https://www.gopherguides.com/courses/preparing-your-environment-for-go-development

-> Go: Checking PATH
✓ Your PATH contains /home/fo/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /usr/local/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v11.11.0, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /usr/local/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.11.3, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /home/fo/.yarn/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.19.1, meets the minimum requirements.

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
✓ The `mysql` executable was found on your system at: /usr/bin/mysql

-> MySQL: Checking minimum version requirements
✓ Your version of MySQL, 14.14, meets the minimum requirements.

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.24.0, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /home/fo/go/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.15.3, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /home/fo/go/src/github.com/forrest321
Root        /home/fo/go/src/github.com/forrest321
GoPath      /home/fo/go
PackagePkg  forrest321
ActionsPkg  forrest321/actions
ModelsPkg   forrest321/models
GriftsPkg   forrest321/grifts
WithModules false
Name        forrest321
Bin         bin/forrest321
VCS         
WithPop     false
WithSQLite  false
WithDep     false
WithWebpack false
WithNodeJs  false
WithYarn    false
WithDocker  true
WithGrifts  false
AsWeb       true
AsAPI       false
InApp       false
PackageJSON {map[]}

</details>

**Comment by gustavotero7** [comment]
I'm facing the same problem here, deploying same code as 2 weeks ago but now failing with 
```
 ---> Running in dd6d976b009d
# github.com/gobuffalo/buffalo/plugins/plugdeps
/go/src/github.com/gobuffalo/buffalo/plugins/plugdeps/plugin.go:15:11: undefined: meta.BuildTags                                                                                                                    
Usage:                                                                                                                                                                                                              
  buffalo build [flags]                                                                                                                                                                                             
                                                                                                                                                                                                                    
Aliases:                                                                                                                                                                                                            
  build, b, bill, install                                                                                                                                                                                           
                                                                                                                                                                                                                    
Flags:                                                                                                                                                                                                              
      --clean-assets               will delete public/assets before calling webpack                                                                                                                                 
      --dry-run                    runs the build 'dry'                                                                                                                                                             
      --environment string         set the environment for the binary (default "development")                                                                                                                       
  -e, --extract-assets             extract the assets and put them in a distinct archive                                                                                                                            
  -h, --help                       help for build                                                                                                                                                                   
      --ldflags string             set any ldflags to be passed to the go build                                                                                                                                     
      --mod string                 -mod flag for go build                                                                                                                                                           
  -o, --output string              set the name of the binary                                                                                                                                                       
  -k, --skip-assets                skip running webpack and building assets                                                                                                                                         
      --skip-build-deps            skip building dependencies                                                                                                                                                       
      --skip-template-validation   skip validating templates                                                                                                                                                        
  -s, --static                     build a static binary using  --ldflags '-linkmode external -extldflags "-static"'                                                                                                
  -t, --tags string                compile with specific build tags                                                                                                                                                 
  -v, --verbose                    print debugging information                                                                                                                                                      
                                                                                                                                                                                                                    
time="2019-12-01T20:41:20Z" level=error msg="Error: exit status 2"                                                                                                                                                  
The command '/bin/sh -c buffalo build -o /bin/app' returned a non-zero code: 255                                                                                                                                    
```

Buffalo 0.14.9 & buffalo 0.15.0

**Comment by markbates** [comment]
Buffalo now requires the Go Modules and no longer supports `GOPATH`.

https://blog.gobuffalo.io/the-road-to-1-0-requiring-modules-5672c6b015e5

Set `GO111MODULE=on` and use `1.13`, or at the very least `1.12`, and this issue should resolve itself for you. If after using modules the problem persists, please reach out and we will re-open the issue. 

Thanks.

**Comment by gustavotero7** [comment]
Yeah, you're right, thanks!

**Comment by forrest321** [comment]
I've been fighting conflicting installations of a few different things since posting this with varying levels of failure. Going to nuke my ubuntu install. Thanks for the help!
