### ISSUE TITLE
Binary Installation not working for Mac.

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo#1857]
## Description

Following mac binary installation method doesn't work. 
```
$ curl -OL https://github.com/gobuffalo/buffalo/releases/download/v0.15.3/buffalo_0.15.3_darwin_amd64.tar.gz
$ tar -xvzf buffalo_0.15.3_darwin_amd64.tar.gz
$ sudo mv buffalo /usr/local/bin/buffalo
# or if you have ~/bin folder setup in the environment PATH variable
$ mv buffalo ~/bin/buffalo
```

### Steps to Reproduce the Problem
File downloads but when I attempted to run `tar -xvzf buffalo_0.15.3_darwin_amd64.tar.gz` I get:
```
tar: Error opening archive: Unrecognized archive format
```
### Expected Behavior
The tar should untar correctly.

### Actual Behavior
Get `tar: Error opening archive: Unrecognized archive format`.

**Comment by bjwschaap** [comment]
You are using the wrong url. It should be `Darwin` in uppercase. If you actually check the size and sha-sum of the file you downloaded, you can see it is only 9 bytes, and contains the text: `Not found`.

The correct download link is:
https://github.com/gobuffalo/buffalo/releases/download/v0.15.3/buffalo_0.15.3_Darwin_x86_64.tar.gz

This issue should be closed.
