### ISSUE TITLE
logger.go:61:3: l.SetOutput undefined (type *logrus.Logger has no field or method SetOutput)

### ISSUE THREAD

**Issue by ctalladen78** [gobuffalo/buffalo#1867]
### Description

running my first ever buffalo app.
disappointing.

buffalo CLI throws an error with default new app
```
github.com/gobuffalo/buffalo/plugins/plugdeps
# github.com/gobuffalo/buffalo/plugins/plugdeps
../../github.com/gobuffalo/buffalo/plugins/plugdeps/plugin.go:15:11: undefined: meta.BuildTags
github.com/gobuffalo/logger
# github.com/gobuffalo/logger
../../github.com/gobuffalo/logger/logger.go:61:3: l.SetOutput undefined (type *logrus.Logger has no field or method SetOutput)
```

### Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. create new buffalo app
  2. run $buffalo dev
  3.

### Expected Behavior

What did you want to happen? Tell us a story. We love to read.
Well, if buffalo wanted to be the ruby on rails of golang, then it should have ran right away. it didnt

### Actual Behavior

What actually happended and what, exactly, is different than expected?

### Info

Please run `buffalo info` and paste the information below where it says "PASTE_HERE".

<details>

```
PASTE_HERE
```

</details>

**Comment by stanislas-m** [comment]
Hello @ctalladen78, can you please provide more information about your setup? It would help us a lot to understand the issue and help you.

We need at least the Go version you're using, the OS and if you use go modules or not. Thanks!

**Comment by ernierasta** [comment]
Hi,
I am not actually gobuffalo user, but try:
```
go get -u github.com/gobuffalo/logger
```

**Comment by paganotoni** [comment]
Closing this one. Please reopen if still relevant.
