### ISSUE TITLE
Proposal: Use `yarn` instead of `npm install`

### ISSUE THREAD

**Issue by philipithomas** [gobuffalo/buffalo#187]
Yarn is a drop-in replacement from Facebook for `npm install`. The advantage is that is deterministic in its build, and it pulls from a local cache (similar to how the [glide](http://glide.sh) package manager works). 

The advantage is that it is significantly faster than 

**Proposal**:

* When generating new files, include a `yarn.lock` file. (On TravisCI, [this triggers the use of yarn](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn))
* Check if `yarn.lock` file exists locally. If it does, use `yarn` to install modules.  
* If no `yarn.lock` file is present, check if `yarn` is installed locally. If it is, use `yarn`
* Fallback to `npm install` if yarn is unavailable

**Comment by markbates** [comment]
I would like to hear about the disadvantages as well. Everyone I've talked to who has used yarn has had to go back to NPM for various reasons. Currently I don't know anyone who uses it in production or on bigger projects. I definitely need to be sold more on it.

**Comment by philipithomas** [comment]
We've been using Yarn for awhile without issue. I'm curious to hear about others' experiences. 

What would you think of having Buffalo check for the presence of a `yarn.lock` file, and if and only if it exists - using `yarn` instead of `npm install`? I would personally use that on projects.

**Comment by markbates** [comment]
That doesn't help much when generating a new project. I'd be open to a second asset generator and let people pick if they want npm or yarn or neither when building a new app. The default should be npm since it's still the "standard" for whatever that term means in JS land. :)

**Comment by philipithomas** [comment]
Ok. I should have some time this weekend for a test implementation. Could probably break it into two PRs - the first for detecting a yarn.lock during the build process, and the second for modifying the `buffalo create` tool.

**Comment by markbates** [comment]
Ah. The build part that's why you would look for the lock file. Gotcha. Didn't think of that.

**Comment by markbates** [comment]
Buffalo dev would need to be updated as well.

**Comment by gillchristian** [comment]
I was going to open an issue for this as well. If you need any help @philipithomas let me know :smile: 

_Btw_, I've been using `yarn` in production too with no issues.

**Comment by fooflare** [comment]
What about adding a --with-yarn option and keep npm as default? The file yarn.lock would be generated during the first build, so you can check if it exists in the next ones. Is this going forward? If any help is needed, I am open to work on it.

**Comment by markbates** [comment]
Closed via #256
