### ISSUE TITLE
Buffalo build failed with pop module "v5" in buffalo_build_main.go.plush template 

### ISSUE THREAD

**Issue by Prnyself** [gobuffalo/buffalo#1875]
### Description

My app try to use pop with module "github.com/gobuffalo/pop/v5". When I build my app with `buffalo build`, the generated `buffalo_build_main.go` file encounters an error as below:
`./buffalo_build_main.go:95:44: cannot use models.DB (type *"github.com/gobuffalo/pop/v5".Connection) as type *"github.com/gobuffalo/pop".Connection in argument to "github.com/gobuffalo/pop".NewMigrationBox`

I check the code in `buffalo/genny/build/templates/buffalo_build_main.go.plush`, and find that it only checks the `WithPop` env, for pop module, but not the `pop/v5`.

I think we should check the version of pop, and generate different import in the template.

### Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. import "github.com/gobuffalo/pop/v5" in your app
  2. buffalo build

### Expected Behavior

Check the version of pop and generate differently in "import".

### Actual Behavior

No matter what the version is, it always generates "github.com/gobuffalo/pop".

### Info

<details>

```
### Buffalo Version
v0.14.2

### App Information
Pwd=/Users/lance/Desktop/projects/modgo/my-web
Root=/Users/lance/Desktop/projects/modgo/my-web
GoPath=/Users/lance/Desktop/projects/go
PackagePkg=my-web
ActionsPkg=my-web/actions
ModelsPkg=my-web/models
GriftsPkg=my-web/grifts
WithModules=true
Name=my-web
Bin=bin/my-web
VCS=git
WithPop=true
WithSQLite=false
WithDep=false
WithWebpack=true
WithNodeJs=true
WithYarn=true
WithDocker=true
WithGrifts=true
AsWeb=true
AsAPI=false
PackageJSON={map[]}

### Go Version
go version go1.13.5 darwin/amd64

```

</details>

**Comment by paganotoni** [comment]
@Prnyself this should be solved with `v0.16.2`.
