### ISSUE TITLE
Custom installation is broken

### ISSUE THREAD

**Issue by vitr** [gobuffalo/buffalo#1877]
From here https://gobuffalo.io/en/docs/getting-started/installation/#custom-installation-without-sqlite3-support

running the command

```
go get -u -v github.com/gobuffalo/buffalo/buffalo
```
gives this error
```
$ go get -u -v github.com/gobuffalo/buffalo/buffalo
go: finding golang.org/x/sync latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/crypto latest
go: finding golang.org/x/net latest
go: finding github.com/monoculum/formam latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/xerrors latest
go: finding github.com/cockroachdb/cockroach-go latest
go: finding github.com/kballard/go-shellquote latest
go: finding github.com/sourcegraph/annotate latest
go: finding github.com/sourcegraph/syntaxhighlight latest
github.com/gobuffalo/buffalo/render
# github.com/gobuffalo/buffalo/render
..\..\..\..\pkg\mod\github.com\gobuffalo\buffalo@v0.15.3\render\template_helpers.go:21:23: cannot use "github.com/gobuffalo/helpers/tags".JS (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value
..\..\..\..\pkg\mod\github.com\gobuffalo\buffalo@v0.15.3\render\template_helpers.go:22:23: cannot use "github.com/gobuffalo/helpers/tags".CSS (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value
..\..\..\..\pkg\mod\github.com\gobuffalo\buffalo@v0.15.3\render\template_helpers.go:23:16: cannot use "github.com/gobuffalo/helpers/tags".Img (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value
```

**Comment by leosunmo** [comment]
Same issue here. Makes it impossible for me to use Sqlite3 at the moment.

**Comment by lagorsse** [comment]
I am having these issues too, I reset but I think, it comes from manual plugin installation.

**Comment by flaviotruzzi** [comment]
I'm having this issue when installing github.com/gobuffalo/mw-basicauth (buffalo version v0.15.5):

```
buffalo plugins install github.com/gobuffalo/mw-basicauth
# github.com/gobuffalo/buffalo/render
../../../../pkg/mod/github.com/gobuffalo/buffalo@v0.14.11/render/template_helpers.go:21:23: cannot use "github.com/gobuffalo/helpers/tags".JS (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value
../../../../pkg/mod/github.com/gobuffalo/buffalo@v0.14.11/render/template_helpers.go:22:23: cannot use "github.com/gobuffalo/helpers/tags".CSS (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value
../../../../pkg/mod/github.com/gobuffalo/buffalo@v0.14.11/render/template_helpers.go:23:16: cannot use "github.com/gobuffalo/helpers/tags".Img (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value
```

**Comment by flaviotruzzi** [comment]
> I'm having this issue when installing github.com/gobuffalo/mw-basicauth (buffalo version v0.15.5):
> 
> ```
> buffalo plugins install github.com/gobuffalo/mw-basicauth
> # github.com/gobuffalo/buffalo/render
> ../../../../pkg/mod/github.com/gobuffalo/buffalo@v0.14.11/render/template_helpers.go:21:23: cannot use "github.com/gobuffalo/helpers/tags".JS (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value
> ../../../../pkg/mod/github.com/gobuffalo/buffalo@v0.14.11/render/template_helpers.go:22:23: cannot use "github.com/gobuffalo/helpers/tags".CSS (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value
> ../../../../pkg/mod/github.com/gobuffalo/buffalo@v0.14.11/render/template_helpers.go:23:16: cannot use "github.com/gobuffalo/helpers/tags".Img (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value
> ```

Scratch that. I had a wrong version on my go.mod which caused the issue.

**Comment by ricktimmis** [comment]
Yes I ran into this too, I compared go.mod with output from buffalo version and found 0.14.11, and 0.15.5. 
Edited go.mod which resolved it.
