### ISSUE TITLE
Docker: "cannot find package"

### ISSUE THREAD

**Issue by jonysy** [gobuffalo/buffalo#1891]
## Steps to reproduce
1) `buffalo new coke`
2) `cd coke`
3) `docker build .`

## Error
```
Step 8/17 : RUN go get ./...
 ---> Running in 1c31af99224b
../../gobuffalo/buffalo/render/helpers.go:10:2: cannot find package "github.com/gobuffalo/tags" in any of:
        /usr/local/go/src/github.com/gobuffalo/tags (from $GOROOT)
        /go/src/github.com/gobuffalo/tags (from $GOPATH)
The command '/bin/sh -c go get ./...' returned a non-zero code: 1
```

## Environment

Microsoft Windows 10 Home

```
buffalo version
Bufalo version is: v0.15.4
```

```
$ docker -v
Docker version 19.03.1, build 74b1e89e8a
```

**Comment by henry-jackson** [comment]
Ran into this issue as well. It appears that the Dockerfile that is generated has the following line:
```
 ENV GO111MODULES=on
```
but it should be
```
 ENV GO111MODULE=on
```
(note the lack of an `S` at the end of the variable name)

Changing this resolved the error for me.

**Comment by jonysy** [comment]
@henry-jackson that fixed it for me. Thanks.

Closing now..

**Comment by searsaw** [comment]
This should be updated in the default Dockerfile template.
