### ISSUE TITLE
Make 404 for sql.ErrNoRows optional / middleware

### ISSUE THREAD

**Issue by AtomicNibble** [gobuffalo/buffalo#1902]
if you return sql.ErrNoRows you get a 404 instead of 500 since: https://github.com/gobuffalo/buffalo/pull/1149 line: https://github.com/gobuffalo/buffalo/blob/master/errors.go#L109

I think it would be better as a middleware that I can optionally enable as for some of my routes failing to find rows should be a fatal error.

Was also a bit confusing that zero error info was been logged and only once I dug through the code did I see the error is swallowed and turned into 404, initially I thought there was some issue with my routing.

So by having it as a middleware a user has must enable they will be more aware of said functionality.

Thanks.

**Comment by paganotoni** [comment]
@AtomicNibble you can always clear the middleware stack and add write your own implementation of the errors middleware. Does that solution works for you ?

**Comment by paganotoni** [comment]
@AtomicNibble closing this one as it seems not to continue to be relevant. Please LMK if it needs to be reopen.

**Comment by AtomicNibble** [comment]
You can leave it closed as I just removed it in my fork that has few other fixes.

But I do think having none optional MW is quite annoying.
