### ISSUE TITLE
[Bug] Wrong buffalo reference in go.mod

### ISSUE THREAD

**Issue by badstorm** [gobuffalo/buffalo#1905]
Creating a new project with the last Buffalo 0.15.5 using `buffalo new myproject` and running it with `buffalo dev` I need to update the version of buffalo in the auto generated go.mod from 

`github.com/gobuffalo/buffalo v0.14.11`

to

`github.com/gobuffalo/buffalo v0.15.5`

so I can run my project where I can use the "Middleware.Remove" function. 

If i not update this version i get:

`api.Middleware.Remove undefined (type *buffalo.MiddlewareStack has no field or method Remove)`

**Comment by adam-buckley** [comment]
See the docs on [upgrading to 0.15.x](https://gobuffalo.io/en/docs/release-notes/buffalo/v0150/#how-to%C2%A0upgrade).

First, ```go get``` the latest Buffalo, inside your project dir:
```bash
go get -u github.com/gobuffalo/buffalo/buffalo
```
This pulls the latest v0.15.5, then run ```buffalo fix```.

I hope I understood your issue correctly.

**Comment by paganotoni** [comment]
Closing this issue. If it still an issue in v0.16.x please reopen.
