### ISSUE TITLE
[Question] - How to setup debugger for Buffalo project.

### ISSUE THREAD

**Issue by int18h** [gobuffalo/buffalo#1910]
Hello. 
I am learning Buffalo and I am a newbie in Golang. I need to use delve to debug couple of issues in my project and found no information or tutorial how to setup environment for debugging, for example in VSCode.
I guess that it would be really helpful not only for me if you will create tutorial how to setup VSCode or delve CLI to debug project inside docker container and outside of it.

**Comment by mclark4386** [comment]
https://blog.gobuffalo.io/configuring-vscode-delve-for-your-buffalo-app-or-go-binary-730523e2363 googled `buffalo vscode debug`

**Comment by int18h** [comment]
Thanks for your response, @mclark4386. 
I read this article and to be honest I can debug my app outside the docker with this article. 
But it wouldn't solve case: i just connect to docker container with application in dev mode. Buffalo has nice option `buffalo dev -d`, which starts app with delve. So my proposal is to build not special case of usage (like in blog article) but complete tutorial how to debug application on local env and inside docker container. Hope it would be very helpful for all new developers.
To be honest I have same questions for myself - how to setup buffalo with delve inside docker and connect to it from vscode.

**Comment by mclark4386** [comment]
I've never tried to connect delve to an app in a docker container before... it's probably possible, just not an expert on either. If you figure it out please either add it to the docs (https://github.com/gobuffalo/docs), write a blog post and link it here, or give the steps here and one of us will try to write it up for you!^^ 
Sorry I missed the `in docker` part of your question! I can definitely understand wanting to develop in docker to keep the dev env consistent in a team! Can't wait to hear back!

**Comment by paganotoni** [comment]
Closing this one. For more questions on this topic please reach out to the gophers slack.

**Comment by aminpaks** [comment]
@paganotoni Thank you for all your work. What do we do when no one answers?

**Comment by paganotoni** [comment]
Thats a good question @aminpaks. When I don't know something about Buffalo and no one answers I try to take a look at the source code to figure out the issue, a lot of improvements to the framework have arrived through that approach.

**Comment by TomHutter** [comment]
The following `launch.json` works for me with Remote-Contaiers. 

~~~
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch remote",
            "type": "go",
            "request": "launch",
            "mode": "exec",
            "remotePath": "",
            "program": "${workspaceRoot}/doors/tmp/doors-build",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}
~~~

My buffallo container runs with workpath `/workspaces/buffalo`. Here I created an app called `doors` by calling :  `buffalo new doors` . So the app is in the path: `/workspaces/buffalo/doors`. You should have a similar path for your app and replace `${workspaceRoot}/doors/tmp/doors-build` with `${workspaceRoot}/<your app>/tmp/<your-app>-build`. Eeasiest to find by calling `buffalo dev` and cheking the `tmp` sub folder of your app.

Then start app with `buffallo dev -d`. Set some break points. Use the browser of your choice. If you hit a break point, you should see the usual debug view in vscode.

**Comment by aminpaks** [comment]
> The following `launch.json` works for me with Remote-Containers.

@TomHutter If I may I think you're mistaken. Remote debugging means the delv debugger is running inside of the container and we connect to it via an available port. What you described here is actually running the executable on your local machine.

**Comment by TomHutter** [comment]
@aminpaks Thanks for clarifying this. And everybody else sorry for any confusion ;-)
