### ISSUE TITLE
Flashes won't clear when using store other than default CookieStore

### ISSUE THREAD

**Issue by lufinima** [gobuffalo/buffalo#1913]
I've already seen older issues about this case when using Redis backed store #911 and supposedly it has been fixed with PR #1141 but it seem's there is an reversion because the bug is still around.
The fix in the PR if applied to current code seem's to fix the issue.
If the code 
```go
defer c.Flash().persist(c.Session())
``` 
line in the [route_info.go](https://github.com/gobuffalo/buffalo/blob/bbdf70341bf44365b8fb0c83689ebe030ce76e5b/route_info.go#L97) is removed and added after [route_info.go](https://github.com/gobuffalo/buffalo/blob/bbdf70341bf44365b8fb0c83689ebe030ce76e5b/route_info.go#L109) as 
```go
c.Flash().persist(c.Session())
```
, without the 
```go
defer
```
it works.
I've tested this fix with 
```go
FilesystemStore
```
 and with a custom 
```go
SQLiteStore
```

**Comment by paganotoni** [comment]
This one is solved by v0.16.16
