### ISSUE TITLE
Buffalo and VueJS

### ISSUE THREAD

**Issue by ochorocho** [gobuffalo/buffalo#1916]
Hey, i'm completely new to gobuffalo
I followed this guide to get Buffalo and VueJS working together. Most parts work. :-) 

https://blog.gopheracademy.com/advent-2017/using-vue-with-buffalo/

1. Buffalo does not have the --type option anymore in 0.15.5, is there a replacement for it?
```
buffalo generate resource band name bio:text --type=json
```
2. When adding `app.GET("/{path:.+}", HomeHandler)` to app.go file assets fail to load with 404. Do i have to change something different in newer buffalo versions?

Buffalo is working nicely so far. Just want to get it going together with VueJS

Thanks.

**Comment by ochorocho** [comment]
Did not change the assetBox ...
```
// render.go
var assetsBox = packr.New("../public/assets", "../public/assets")
// app.go
app.ServeFiles("/assets", assetsBox)
```

Sorry for the noise

**Comment by frankmariette** [comment]
Thanks for posting this @ochorocho. Just helped me figure out the same issue though with React. This wasn't mentioned in the vuejs video in the examples and I just spent the afternoon realizing that the assetsBox needed to be updated to something other than root for this to work. Might be something needed to be added to the docs.

**Comment by ochorocho** [comment]
your welcome :-)
