### ISSUE TITLE
[Question] How free memory after return Render Download?

### ISSUE THREAD

**Issue by badstorm** [gobuffalo/buffalo#1917]
I noticed that when I download a file using Render Download the ram memory usage increase a lot and some time the app crashs.
When I start a simple buffalo app the ram usage is about 7MB. After i call my function the ram is about 850MB. My demo file to be downloaded is about 300 MB.
How I can release memory after the download is finish? I noticed that after some minutes the RAM amount start to shrink in automatic.

**Here my example:**
1. Create a new buffalo app:
`buffalo new myapp`
2. Add a UPLOAD_PATH variable in .env file:
`UPLOAD_PATH="/path/to/my-file/folder"`
3. Add this function:
```
func DownloadFile(c buffalo.Context) error {
	envy.Load()
	privatePath, err := envy.MustGet("UPLOAD_PATH")
	if err != nil {
		return nil
	}
	src := filepath.Join(privatePath, "demo.iso")
	reader, _ := os.Open(src)
	return c.Render(200, r.Download(c, "demo.iso", reader))
}
```
4. Add path to function to app.go:
`app.GET("/download", DownloadFile)`
5. Try to download the file with your browser:
`http://localhost:3000/download`

**Here my RAM status**
Before:
![before](https://user-images.githubusercontent.com/230256/75791850-75f48900-5d6d-11ea-8f15-3b206eef08b7.png)
After:
![after](https://user-images.githubusercontent.com/230256/75791864-7b51d380-5d6d-11ea-991c-afd7f368f72f.png)

**Comment by badstorm** [comment]
I'm trying to understand which variable allocates all this amount of space. In the mean time I found this workaround to force reduction memory and prevent app crash. However this solution is not good for production:
```
...
src := filepath.Join(privatePath, "demo.iso")
reader, _ := os.Open(src)
response := c.Render(200, r.Download(c, "demo.iso", reader)) 

debug.FreeOSMemory()

return response
...
```

**Comment by ironsalsa** [comment]
Try adding this after you open the file:
```
defer reader.Close()
```
Currently the ioReader isn't closed, which may be causing your memory issues.

**Comment by paganotoni** [comment]
@badstorm I'm assuming this one was resolved by closing the reader as @ironsalsa mentioned. Thanks @ironsalsa.
