### ISSUE TITLE
Logging from model using App.Logger

### ISSUE THREAD

**Issue by pctj101** [gobuffalo/buffalo#1923]
If I want to log from a model (AfterSave for example) using the buffalo.Context.Logger(), what's the typical way to do so?

**Comment by paganotoni** [comment]
Hi @pctj101 👋, I think AfterSave does not receive the context so it would not be possible to use the buffalo context to use it. I would suggest that you keep an instance of your Logger in your `models` package level and use it as you need it.

**Comment by paganotoni** [comment]
Also I know that if you ask this in the Gophers slack #buffalo channel there will be greater ideas than mine :D. I'm closing this issue as I think that would be a better space to ask for this. Thanks for this one.
