### ISSUE TITLE
[Question]: How to write custom plugins in Buffalo 0.16

### ISSUE THREAD

**Issue by badstorm** [gobuffalo/buffalo#1942]
In my prevoius question #1836 I found a solution to build new plugins on buffalo 0.15
Now I have the same problem with 0.16 since seems that there is no more a command for generate a new plugin.

Where I can find some update docs for write new plugins?

**Comment by paganotoni** [comment]
@badstorm If you're willing to write some plugins my suggestion is to take a look at the new CLI CLI and plugin system being written at the [buffalo-cli repo](https://github.com/gobuffalo/buffalo-cli), I think you can find some examples of plugins in [here](https://github.com/gobuffalo/buffalo-cli/blob/master/cli/internal/plugins/plush/generators/resource/generator.go)

I have not seen much documentation for this new architecture as this still in alpha stage.
