### ISSUE TITLE
[Proposal] Custom template for 404 and 500 in production

### ISSUE THREAD

**Issue by badstorm** [gobuffalo/buffalo#1950]
I'm working on implement the possibility to add a custom 404 and 500 template in a buffalo application when in production.
Before send the PR there are some problem that I can't figure out. Here is my implementation: [Show](https://github.com/badstorm/buffalo/commit/1b2bd4a125d948fa76f0c0062465a03157b72c7c)

1. when rendering the 500 template i get: 
` application.plush.html: line 15: could not call partial function: line 3: "flash": unknown identifier `

2. when rendering the 404 template seems that context variables are not setted so I get errors like:
` application.plush.html: line 9: "authenticity_token": unknown identifier `

Question: for this kind of issue is better open an issue in this way or send anyway the PR?

**Comment by sio4** [comment]
You don't need to fix the buffalo core library for your own error handlers. You can simply set your own application-specific error handlers by doing something like the below:

```go
		app = buffalo.New(buffalo.Options{
			Env:         ENV,
			SessionName: "_app_session",
		})
		app.ErrorHandlers[http.StatusInternalServerError] = myOwnErrorHandler
```

The last line will register `myOwnErrorHandler` as an error handler for Internal Server Error.
