### ISSUE TITLE
New buffalo binaries do not include "pop" for db creation/migration

### ISSUE THREAD

**Issue by jh125486** [gobuffalo/buffalo#1967]
With the latest update to the gobuffalo docker file my CI/CD is breaking since `buffalo db create` isn't in the Docker image anymore.

As far as I know, the built application binary only includes `$APP migrate`, so I have to rely upon the gobuffalo/buffalo Docker image to contain `buffalo db create` for tests.

When I roll back to v0.15.5  `buffalo db create` works in the image.

P.S.
Having "create" part of the built app binary would be fantastic, but that is probably a separate issue to this one.

**Comment by paganotoni** [comment]
Thanks @jh125486.

**Comment by paganotoni** [comment]
Solved in v0.16.8
