### ISSUE TITLE
Support for gzip compression of static assets

### ISSUE THREAD

**Issue by vincentchu** [gobuffalo/buffalo#1968]
### Description

Compressing static assets like CSS/JS files can lead to big performance improvements. While this is typically done by a frontend proxy like Apache or Nginx, some providers like [Heroku](https://devcenter.heroku.com/articles/compressing-http-messages-with-gzip) do not offer this.

The existing middleware API allows a developer to add compression *except* for files served via `ServeFiles` (static assets) where compression would be most useful. In this case, `ServeFiles` creates a separate `http.Handler` that is outside of the middleware stack.

To solve my immediate problem, I created a quick fix on a [personal branch](https://github.com/vincentchu/buffalo/commit/cf77ce5340724abeb71fb2a3e76073ab74955a17#diff-b1bf5313903dc951eacac638dc5b7060R118) using Gorilla's `CompressionHandler`. I'm happy to clean this up and submit it if the buffalo core team finds it helpful. I'd need some pointers as to the best and cleanest way to get this into buffalo.

As an example, here is a before/after of the size of my served assets (CSS, JS) as measured by pingdom from my production app.  

<img width="776" alt="Screen Shot 2020-04-13 at 12 00 19 PM" src="https://user-images.githubusercontent.com/27597/79466362-5928b380-7fb1-11ea-864c-7f24a992f4b0.png">

**Comment by paganotoni** [comment]
Oh nice! Thanks for sharing this! The change seems to be backwards compatible. @vincentchu are you willing to create a PR with this one? I would be trilled to test it locally.

**Comment by vincentchu** [comment]
> Oh nice! Thanks for sharing this! The change seems to be backwards compatible. @vincentchu are you willing to create a PR with this one? I would be trilled to test it locally.

Thanks @paganotoni . I just pushed a PR. Would it be best to allow the user to control compression via an option in the `App`?

**Comment by paganotoni** [comment]
That’s awesome! I’ll take a look soon.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by paganotoni** [comment]
Released in v0.16.8

**Comment by AtomicNibble** [comment]
This adds gzip to png,jpg,etc which is bad.

I do think Gorilla should update the handler to not just blindly compress all content types tho.
