### ISSUE TITLE
Offer a way to omit form data from logs

### ISSUE THREAD

**Issue by taliesinmillhouse** [gobuffalo/buffalo#1981]
Hi all, I'm quite new to Buffalo so my apologies if there is already a way to do this that I've missed.

### Description

It would be great to have a way to omit form data for logging in HTTP requests. Currently, it looks like password fields are filtered, but it would be great to filter other fields or completely omit the form data from the logs.

### Steps to Reproduce the Problem

  1. Perform an HTTP request that submits form data.
  2.  Observe logs to see the form data.

Thanks in advance!

**Comment by paganotoni** [comment]
Hi @taliesinmillhouse! 

Thanks for posting this question. Parameter/Data form data logging is done by `gobuffalo/mw-paramlogger`. You should see in your `app.go` something like:

```
app.Use(paramlogger.ParameterLogger)
```

If you remove that middleware your buffalo app should not log form data. Please LMK how it goes.

**Comment by taliesinmillhouse** [comment]
Great thanks @paganotoni! That's exactly what I was looking for.
