### ISSUE TITLE
add a `grift test` task

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#20]
this should run a `test:db:prepare` task as well

**Comment by bscott** [comment]
To clearify, this would run all tests after `test:db:prepare` correct? @markbates

**Comment by markbates** [comment]
Yep! Although there is `buffalo test` so I'm not sure we need this.

**Comment by apaganobeleno** [comment]
@markbates i would like to stick with the `buffalo test`, if thats ok, should this task be about running `test:db:prepare` before the tests when developer runs `buffalo test` ?

**Comment by markbates** [comment]
Agreed. I don't think we need this. Going to close it for now.
