### ISSUE TITLE
[Proposal] Contribute a to a benchmark

### ISSUE THREAD

**Issue by waghanza** [gobuffalo/buffalo#2001]
Hi,

I'm leading a benchmarking project => https://github.com/the-benchmarker/web-frameworks

The purpose of this project is to compare performances (other indicators will come), based on a fairest, as we can, comparison for `go` **frameworks** (comparing on the same version, **production-grade** environments, same compilation options ...).

Do you mind that I (or any member) add `buffalo`  ? :heart:

Regards,

**Comment by hubyhuby** [comment]
You have to see with the mainteners of buffalo.
Personally I think it can make no harm. And could give us informations on the speed of buffalo compared to raw gorilla mux for ex. Does your test takes into acount bdd access aswell ? ( Pop library /sqlx)

**Comment by markbates** [comment]
This is a duplicate. The answer is still no. Thanks.

**Comment by waghanza** [comment]
Ok :heart: 

I thought you've missed https://github.com/the-benchmarker/web-frameworks/issues/1131

**Comment by waghanza** [comment]
but may as I ask you why ?
