### ISSUE TITLE
Named routes always giving a trailing slash

### ISSUE THREAD

**Issue by ernsheong** [gobuffalo/buffalo#2013]
Named routes are always generating a trailing slash. Is there a way to prevent it from doing so?

I wish to have a single canonical route (either with trailing `/` or no `/`). However, the named routes are always giving me a trailing slash, preventing the use of the option with no trailing slash.

**Comment by paganotoni** [comment]
Yes. Named routes are `trailing slash` in Buffalo. Maybe something to revisit in the future but it's a delicate change.

**Comment by gboddin** [comment]
If I get this right, trying to get an URL for `/search` with the path helper it will always return `/search/` ? 

That's probably an issue for anyone trying to migrate from Revel.

Maybe I'm missing something ?

**Comment by sio4** [comment]
Not only for anyone trying to migrate from Revel or something. I don't think forcing trailing slash for every URL is not a good idea for the general-purpose framework.

I tried to understand what was the background context for the decision of this change and found the related change #1168 (and linked issue), but it seems like it was just a workaround to suppress related issues. (actually, those issues were about _wrong_ trailing slashes, but the change made them as normal :-)

Can we reconsider that decision?
