### ISSUE TITLE
Can't get buffalo starting

### ISSUE THREAD

**Issue by AmirrezaKN** [gobuffalo/buffalo#2020]
i have installed buffalo recently and when i tried to run it for the first time i got this

> buffalo: 2020/07/20 16:38:34 === Rebuild on: :start: ===
> buffalo: 2020/07/20 16:38:34 === Error! ===
> buffalo: 2020/07/20 16:38:34 === context canceled

i runned buffalo test but it runs just fine
i have no idea how to solve this, can anyone help?

**Comment by hubyhuby** [comment]
Note that you may post this kind of questions on the slack.
Do you have more logs ? Can you do a buffalo info.
I guess you are doing biffalo dev?
What is the commande line you used? Buffalo new myapp ?

**Comment by AmirrezaKN** [comment]
> Note that you may post this kind of questions on the slack.
> Do you have more logs ? Can you do a buffalo info.
> I guess you are doing biffalo dev?
> What is the commande line you used? Buffalo new myapp ?

hey tnx for the reply. i used the buffalo new shortech --db-type mysql
then i configured the database settings and runned buffalo test and it was all ok
but when i used buffalo dev i got that error
anyway here is my buffalo info result

> -> Go: Checking installation
> ✓ The `go` executable was found on your system at: /usr/local/go/bin/go
> 
> -> Go: Checking minimum version requirements
> ✓ Your version of Go, 1.14.6, meets the minimum requirements.
> 
> -> Go: Checking Package Management
> ✓ You are using Go Modules (`go`) for package management.
> 
> -> Go: Checking PATH
> ✓ Your PATH contains /home/persiansatan/work/bin.
> 
> -> Node: Checking installation
> ✘ The `node` executable could not be found on your system.
> For help setting up your Node environment please follow the instructions for you platform at:
> 
> https://nodejs.org/en/download/
> 
> -> NPM: Checking installation
> ✘ The `npm` executable could not be found on your system.
> For help setting up your NPM environment please follow the instructions for you platform at:
> 
> https://docs.npmjs.com/getting-started/configuring-your-local-environment
> 
> -> Yarn: Checking installation
> ✘ The `yarnpkg` executable could not be found on your system.
> For help setting up your Yarn environment please follow the instructions for you platform at:
> 
> https://yarnpkg.com/en/docs/install
> 
> -> PostgreSQL: Checking installation
> ✘ The `postgres` executable could not be found on your system.
> For help setting up your Postgres environment please follow the instructions for you platform at:
> 
> https://www.postgresql.org/download/
> 
> -> MySQL: Checking installation
> ✓ The `mysql` executable was found on your system at: /usr/bin/mysql
> 
> -> MySQL: Checking minimum version requirements
> ✓ Your version of MySQL, 14.14, meets the minimum requirements.
> 
> -> SQLite3: Checking installation
> ✘ The `sqlite3` executable could not be found on your system.
> For help setting up your SQLite3 environment please follow the instructions for you platform at:
> 
> https://www.sqlite.org/download.html
> 
> -> Cockroach: Checking installation
> ✘ The `cockroach` executable could not be found on your system.
> For help setting up your Cockroach environment please follow the instructions for you platform at:
> 
> https://www.cockroachlabs.com/docs/stable/
> 
> -> Buffalo (CLI): Checking installation
> ✓ The `buffalo` executable was found on your system at: /usr/local/bin/buffalo
> 
> -> Buffalo (CLI): Checking minimum version requirements
> ✓ Your version of Buffalo (CLI), v0.16.13, meets the minimum requirements.
> 
> -> Buffalo: Application Details
> Pwd         /mnt/s/CodeReborn/buf/shortech
> Root        /mnt/s/CodeReborn/buf/shortech
> GoPath      /home/persiansatan/work
> PackagePkg  shortech
> ActionsPkg  shortech/actions
> ModelsPkg   shortech/models
> GriftsPkg   shortech/grifts
> WithModules true
> Name        shortech
> Bin         bin/shortech
> VCS         git
> WithPop     true
> WithSQLite  false
> WithDep     false
> WithWebpack true
> WithNodeJs  true
> WithYarn    true
> WithDocker  true
> WithGrifts  true
> AsWeb       true
> AsAPI       false
> InApp       true
> PackageJSON {map[]}
> 
> -> Buffalo: config/buffalo-app.toml
> name = "shortech"
> bin = "bin/shortech"
> vcs = "git"
> with_pop = true
> with_sqlite = false
> with_dep = false
> with_webpack = true
> with_nodejs = true
> with_yarn = true
> with_docker = true
> with_grifts = true
> as_web = true
> as_api = false
> 
> -> Buffalo: config/buffalo-plugins.toml
> [[plugin]]
>   binary = "buffalo-pop"
>   go_get = "github.com/gobuffalo/buffalo-pop"
> 
> [[plugin]]
>   binary = "buffalo-pop"
>   go_get = "github.com/gobuffalo/buffalo-pop/v2"
> 
> -> Buffalo: go.mod
> module shortech
> 
> go 1.14
> 
> require (
>         github.com/gobuffalo/buffalo v0.16.13
>         github.com/gobuffalo/buffalo-pop/v2 v2.0.6 // indirect
>         github.com/gobuffalo/envy v1.9.0
>         github.com/gobuffalo/mw-forcessl v0.0.0-20200131175327-94b2bd771862
>         github.com/gobuffalo/mw-paramlogger v1.0.0
>         github.com/gobuffalo/packr/v2 v2.8.0
>         github.com/gobuffalo/pop/v5 v5.2.3
>         github.com/gobuffalo/suite v2.8.2+incompatible
>         github.com/markbates/grift v1.5.0
>         github.com/unrolled/secure v1.0.8
> )

**Comment by hubyhuby** [comment]
You are doing a regular app with the front end. I think you need yarn and npm...maybe node too..
You may want to rmtry with --api flag aswell to avoid the js stuf

**Comment by paganotoni** [comment]
Thanks for the help @hubyhuby 💪💪
