### ISSUE TITLE
run buffalo build error

### ISSUE THREAD

**Issue by chaho** [gobuffalo/buffalo#2021]
cli info:
./buffalo_build_main.go:95:44: cannot use models.DB (type *"github.com/gobuffalo/pop/v5".Connection) as type *"github.com/gobuffalo/pop".Connection in argument to "github.com/gobuffalo/pop".NewMigrationBox

**Comment by hubyhuby** [comment]
Note that you may post this kind of questions on the slack.

Do you have more logs ? Can you do a buffalo info.
Is buffalo dev working ?
What is the commande line you used? Buffalo new myapp ?

**Comment by paganotoni** [comment]
@chaho did you solve this one ? Closing for now. If it still an issue please reopen.
