### ISSUE TITLE
ServeFiles exposes files outside of public

### ISSUE THREAD

**Issue by cosmouser** [gobuffalo/buffalo#2024]
### Description

ServeFiles exposes files outside of the directory specified in the *packr.Box (../public)
This issue seems to be present on the [buffalo docs site](https://gobuffalo.io/README.md).

### Steps to Reproduce the Problem

1. `buffalo new issue`
2. `cd issue && buffalo db create`
3. `buffalo dev`
4. Navigate to http://127.0.0.1:3000/README.md or http://127.0.0.1:3000/database.yml

### Expected Behavior

I expected that only the contents and subcontents of `public` would be exposed.

### Actual Behavior

Files outside of the `public` folder were accessible through the browser.

### Info

<details>
-> Go: Checking installation
✓ The `go` executable was found on your system at: /usr/local/go/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.14.6, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /home/cosmo/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /usr/local/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v14.2.0, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /usr/local/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.14.5, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /usr/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.22.4, meets the minimum requirements.

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
✘ The `mysql` executable could not be found on your system.
For help setting up your MySQL environment please follow the instructions for you platform at:

https://www.mysql.com/downloads/

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.31.1, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /usr/local/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.16.13, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /home/cosmo/Projects/issue
Root        /home/cosmo/Projects/issue
GoPath      /home/cosmo/go
PackagePkg  issue
ActionsPkg  issue/actions
ModelsPkg   issue/models
GriftsPkg   issue/grifts
WithModules true
Name        issue
Bin         bin/issue
VCS         git
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack -p --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "issue"
bin = "bin/issue"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop/v2"

-> Buffalo: go.mod
module issue

go 1.14

require (
	github.com/gobuffalo/buffalo v0.15.5
	github.com/gobuffalo/buffalo-pop/v2 v2.0.6
	github.com/gobuffalo/envy v1.9.0
	github.com/gobuffalo/mw-csrf v0.0.0-20190129204204-25460a055517
	github.com/gobuffalo/mw-forcessl v0.0.0-20180802152810-73921ae7a130
	github.com/gobuffalo/mw-i18n v0.0.0-20190129204410-552713a3ebb4
	github.com/gobuffalo/mw-paramlogger v0.0.0-20190129202837-395da1998525
	github.com/gobuffalo/packr/v2 v2.8.0
	github.com/gobuffalo/pop/v5 v5.1.1
	github.com/unrolled/secure v0.0.0-20190103195806-76e6d4e9b90c
)

</details>

**Comment by forrest321** [comment]
If you build the project and run the resulting binary, this does not occur. This seems like a timesaver for developers.

**Comment by cosmouser** [comment]
Thanks for the suggestion. I tried building the project and running the resulting binary `./bin/issue` and the issue still occurred. I tried it again after changing my directory to the bin folder and the issue didn't persist. I left the app running and copied the README.md file into the bin folder. After that, I was suddenly able to read it in the browser by going to localhost:3000/README.md.

I've only found two ways to mitigate this behavior.

1. Run the program from `/` or
2. Change directory to an empty leaf in your filesystem and run the app from there.

**Comment by r3ap3r2004** [comment]
I tried this out with a `buffalo build` running on localhost:3000 and was also able to download the application compiled binary.  Of course you need to know the binary name, but it was happy to grab it.   So even if you put the binary in its own empty folder structure, you can still get the application itself.

**Comment by keisukefunatsu** [comment]
@r3ap3r2004 
> "if you put the binary in its own empty folder structure, you can still get the application itself."

My understanding is that this bug depends on where working directory is.
If binary is executed in source directory, then source files will be exposed.
So, I think it can not be happen in the case binary is executed in an empty folder such as `/exec_app_dir`

Does this also happen in the example I wrote below? 
If so, could you tell me the way to reproduce it?

```
# make empty folder to execute app
mkdir /exec_app_dir

# build binary file in source file directory
buffalo build -o /exec_app_dir/app_binary

# then exec app from  /exec_app_dir directory
cd  /exec_app_dir
./app_binary
```

**Comment by r3ap3r2004** [comment]
You should try it.

```
cd <your app root>
go build -o /exec_app_dir/app_binary
cd /exec_app_dir
./app_binary
```

Then open a browser and go to http://localhost:3000/app_binary and watch your browser download the executable file.

**Comment by keisukefunatsu** [comment]
I see.
I confirmed reproducing the situation and solution.

`NG` file exposed
```
go build -o /exec_app_dir/app_binary
cd /exec_app_dir
./app_binary
```

`OK` file not exposed
```
# make empty working directory
cd /app_exec_dir
go build -o /app_file_dir/app_binary
cd /app_exec_dir
/app_file_dir/app_binary
```

**Comment by r3ap3r2004** [comment]
@keisukefunatsu - Thank you for explaining in detail how to get around the issue.
