### ISSUE TITLE
Update to formam v3.4.0 to avoid denial of service attack

### ISSUE THREAD

**Issue by hdm** [gobuffalo/buffalo#2040]
https://github.com/monoculum/formam/issues/31

**Comment by hdm** [comment]
A quick go.mod fix for now (for callers):
`replace	github.com/monoculum/formam v0.0.0-20200527175922-6f3cce7a46cf => github.com/monoculum/formam v0.0.0-20200905010316-d7a8fbd33677`

**Comment by paganotoni** [comment]
Thanks for this one @hdm !

**Comment by paganotoni** [comment]
covered in v0.16.15
