### ISSUE TITLE
Buffalo CLI fails to build binary if there is no Grifts package

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo#2058]
### Description

Removing the Grifts folder causes `Buffalo build` task to fail. 

### Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. Create a new buffalo app with `buffalo new app`
  2. Remove `grifts` folder
  3. Run `buffalo build`

### Expected Behavior

Buffalo CLI should build the application binary.

### Actual Behavior

Buffalo CLI fails with:
```
buffalo_build_main.go:20:3: package app/grifts is not in GOROOT (/usr/local/Cellar/go/1.15.3/libexec/src/app/grifts)
Usage:
  buffalo build [flags]

Aliases:
  build, b, bill, install

Flags:
      --clean-assets               will delete public/assets before calling webpack
      --dry-run                    runs the build 'dry'
      --environment string         set the environment for the binary (default "development")
  -e, --extract-assets             extract the assets and put them in a distinct archive
  -h, --help                       help for build
      --ldflags string             set any ldflags to be passed to the go build
      --mod string                 -mod flag for go build
  -o, --output string              set the name of the binary
  -k, --skip-assets                skip running webpack and building assets
      --skip-build-deps            skip building dependencies
      --skip-template-validation   skip validating templates
  -s, --static                     build a static binary using  --ldflags '-linkmode external -extldflags "-static"'
  -t, --tags string                compile with specific build tags
  -v, --verbose                    print debugging information

ERRO[0032] Error: exit status 1   
```
### Info
<details>
-> Go: Checking installation
✓ The `go` executable was found on your system at: /usr/local/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.15, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /Users/paganotoni/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /usr/local/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v14.4.0, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /usr/local/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.14.4, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /Users/paganotoni/.yarn/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.22.4, meets the minimum requirements.

-> PostgreSQL: Checking installation
✓ The `postgres` executable was found on your system at: /Applications/Postgres.app/Contents/Versions/latest/bin/postgres

-> PostgreSQL: Checking minimum version requirements
✓ Your version of PostgreSQL, 11.8.0, meets the minimum requirements.

-> MySQL: Checking installation
✘ The `mysql` executable could not be found on your system.
For help setting up your MySQL environment please follow the instructions for you platform at:

https://www.mysql.com/downloads/

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.32.3, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /Users/paganotoni/go/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.16.15, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /Users/paganotoni/code/livenote/app
Root        /Users/paganotoni/code/livenote/app
GoPath      /Users/paganotoni/go
PackagePkg  livenote/app
ActionsPkg  livenote/app/actions
ModelsPkg   livenote/app/models
GriftsPkg   livenote/app/grifts
WithModules true
Name        app
Bin         bin/app
VCS         git
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack -p --progress dev:webpack --watch test:jest assets/js/*.test.js]}

-> Buffalo: config/buffalo-app.toml
name = "app"
bin = "bin/app"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop/v2"

-> Buffalo: go.mod
module livenote/app

go 1.15

require (
        cloud.google.com/go/storage v1.0.0
        github.com/dustin/go-humanize v1.0.0
        github.com/gobuffalo/buffalo v0.16.16
        github.com/gobuffalo/buffalo-pop/v2 v2.3.0
        github.com/gobuffalo/envy v1.9.0
        github.com/gobuffalo/httptest v1.5.0
        github.com/gobuffalo/mw-csrf v1.0.0
        github.com/gobuffalo/mw-forcessl v0.0.0-20180802152810-73921ae7a130
        github.com/gobuffalo/mw-paramlogger v0.0.0-20190129202837-395da1998525
        github.com/gobuffalo/packr/v2 v2.8.0
        github.com/gobuffalo/pop/v5 v5.3.1
        github.com/gobuffalo/suite/v3 v3.0.0
        github.com/gobuffalo/validate/v3 v3.3.0
        github.com/gofrs/uuid v3.2.0+incompatible
        github.com/pkg/errors v0.9.1
        github.com/sirupsen/logrus v1.5.0
        github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
        github.com/unrolled/secure v0.0.0-20190103195806-76e6d4e9b90c
        golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
        google.golang.org/api v0.13.0
)

</details>

**Comment by dionysius** [comment]
setting `with_grifts = false` in `config/buffalo-app.toml` seems to solve that
