### ISSUE TITLE
 create a new buffalo app in the current directory

### ISSUE THREAD

**Issue by bscott** [gobuffalo/buffalo#206]

**Comment by bscott** [comment]
requested from the folks at nanobox.io

**Comment by apaganobeleno** [comment]
this is a good one! would `buffalo new . -f` be a good starting point ?

**Comment by markbates** [comment]
Great idea! I can't tell you how many times I've rebuilt the `coke` example project, and I always have to keep going up and then down again.

**Comment by markbates** [comment]
Issue #210 is going to add support for named routes in 0.8.0 apparently we already have a context variable called `current_route` which gives back the current route information.

Seems like all this ticket really needs to the actual URL path of the current request to the context and it'll be done.

Does that seem correct to everyone?

If so, I think we can easily get this into 0.7.3.
