### ISSUE TITLE
Current Route

### ISSUE THREAD

**Issue by apaganobeleno** [gobuffalo/buffalo#207]
What do you think about adding the current route/path available to the view ?
I'm asking this because in certain scenarios you would like to do some rendering based on the current route, i think the following example will make it clear:

Lets say you're building a navigation like this one:

<img width="551" alt="screenshot 2017-02-01 08 21 38" src="https://cloud.githubusercontent.com/assets/645522/22508529/637fd4ce-e858-11e6-86cd-e9be731f705c.png">

And you want to add an active class to the navigation element you are currently in so it looks like:

<img width="487" alt="screenshot 2017-02-01 08 31 27" src="https://cloud.githubusercontent.com/assets/645522/22508639/dad94d0c-e858-11e6-98d2-7293df26aa69.png">

it would be useful to know the route i'm in to add appropiate class to the html element.

@markbates @bscott @stanislas-m  thoughts on this one ?

**Comment by stanislas-m** [comment]
@apaganobeleno Good idea, I have this kind of use case at least once per project.

**Comment by markbates** [comment]
I think it's a great idea.

The question becomes do we put `/users/1` in the context, `/users/{user_id}` or both?

**Comment by apaganobeleno** [comment]
any way would help on the view, if we would like to be a bit more fancy maybe we could consider naming routes as an option, thoughts ?

**Comment by markbates** [comment]
I'm thinking both would be nice to have in the context.

Since we're using http://www.gorillatoolkit.org/pkg/mux under the covers we could easily create named routes for everything. When we create a new route we return the `RouteInfo` for it so we could hang a `Name` function on that calls the underlying mux name function.

We would also need to expose those in the context.

**Comment by bscott** [comment]
+1

**Comment by markbates** [comment]
Issue #210 is going to add support for named routes in 0.8.0 apparently we already have a context variable called current_route which gives back the current route information.

Seems like all this ticket really needs to the actual URL path of the current request to the context and it'll be done.

Does that seem correct to everyone?

If so, I think we can easily get this into 0.7.3.
