### ISSUE TITLE
need python2? 

### ISSUE THREAD

**Issue by whidbey** [gobuffalo/buffalo#2100]
platform:windows
step:
1. conda install buffalo
2. change go/env to set GO111MODULE = on
3. buffalo new myproject -f -v 

shows :

gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Administrator\myproject\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Administrator\myproject\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Administrator\myproject\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Administrator\myproject\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Administrator\myproject\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Administrator\myproject\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Administrator\myproject\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Administrator\myproject\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Administrator\myproject\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Administrator\myproject\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Administrator\myproject\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Administrator\myproject\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Administrator\miniconda3\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Administrator\miniconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax

seems needs python2?? why not py3 ..

**Comment by paganotoni** [comment]
@whidbey this seems to be related with the node packages being used in the app. It could be node-sass or something like that requiring python.
