### ISSUE TITLE
Provide alternative webpack starters

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#214]
The current new app generator creates a bootstrap-powered webpack.

It can be a plus to provide alternative webpack seeds (like one for foundation http://foundation.zurb.com/, jQuery UI or even Javascript frameworks like Angular).

**Comment by philipithomas** [comment]
If you go down this route - VueJS has two webpack starters:

simple - https://github.com/vuejs-templates/webpack-simple
standard - https://github.com/vuejs-templates/webpack

**Comment by markbates** [comment]
@matryer and I were just have a really great conversation about how to hook in 3rd party generators.

**Comment by markbates** [comment]
I'm going to mark this as closed. This was discussed at length in different issues and PRs. It doesn't make sense to put this into Buffalo. There are plenty of great tutorials and generators for web pack that can be used for this purpose.
