### ISSUE TITLE
Can't install buffalo on Ubuntu. Golang is 1.7

### ISSUE THREAD

**Issue by tresero** [gobuffalo/buffalo#2144]
Any clues?

Trying to install sqlite version on Ubuntu.

 go get -u -v -tags sqlite github.com/gobuffalo/cli/cmd/buffalo@0.17.2
go get: github.com/gobuffalo/cli/cmd/buffalo@0.17.2: invalid version: unknown revision 0.17.2

**Comment by sio4** [comment]
See https://github.com/gobuffalo/docs/pull/596. the command line should be as following

go get -u -v -tags sqlite github.com/gobuffalo/cli/cmd/buffalo@v0.17.2

v0.17.2 instead of 0.17.2

**Comment by tresero** [comment]
That worked. The docs are way out of date I'm guessing.

**Comment by sio4** [comment]
Yeah, maybe a typo I guess.

FYI, buffalo cli (the package be installed by the command) was introduced recently and the command `buffalo` is now not a part of this repo anymore.

**Comment by tresero** [comment]
Now I'm at:

`
 error /home/mayuli.com/books/node_modules/node-sass: Command failed
 /usr/bin/node /home/mayuli.com/books/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
`
It's a python issue and it appears you need python2 and I have python 3. There has to be a better way :( I hate python, it truly sucks.

Oh well, not sure this project is maintained anymore. So many deprecated dependencies.

**Comment by tresero** [comment]
FYI, buffalo cli (the package be installed by the command) was introduced recently and the command buffalo is now not a part of this repo anymore.

Not sure what you mean. So the docs are completely wrong. I'm not sure what to do at this point. It looked promising, but...

**Comment by sio4** [comment]
@tresero, I think the right place to discuss or digging this issue is not here but https://github.com/gobuffalo/cli. I opened an issue there (https://github.com/gobuffalo/cli/issues/26), and let's discuss it there if you still want to. (as a user, I like buffalo and hope it could be maintained well by the community :-)

**Comment by paganotoni** [comment]
@sio4 should we close this one?

**Comment by sio4** [comment]
@paganotoni yeah, I think so. I think we have no action item on this issue.
