### ISSUE TITLE
module updating (mainly for security bugfix) for gobuffalo families

### ISSUE THREAD

**Issue by sio4** [gobuffalo/buffalo#2152]
I am writing this issue to track/manage a set of PRs of module updating (mainly for security bugfix) for gobuffalo families.

### Related PRs

* https://github.com/gobuffalo/github_flavored_markdown/pull/5
* https://github.com/gobuffalo/tags/pull/138
* https://github.com/gobuffalo/helpers/pull/19
* https://github.com/gobuffalo/plush/pull/147

### Next

* buffalo and pop
* genny, fizz, buffalo-pop, cli  will be checked if they need to be updated.

**Comment by sio4** [comment]
Thanks for your command @paganotoni ! then I will work from the deepest modules also will try update external dependencies such as testify which is used for many packages (version 1.7.0 or version 1.4.0). I made PR for genny as draft, and will update that with newer versions too!

**Comment by sio4** [comment]
PRs for current stage, which is for packages without buffalo internal dependencies:

* https://github.com/gobuffalo/flect/pull/52
* https://github.com/gobuffalo/nulls/pull/7
* https://github.com/gobuffalo/packd/pull/15
* https://github.com/gobuffalo/envy/pull/38
  * https://github.com/gobuffalo/envy/pull/39 (off topic but important)
* https://github.com/gobuffalo/logger/pull/15

Please take a look at above PRs and release them if there is no issue. Then the next steps will be:

* validte and attrs which depend on flect
* packr which depends on envy and packd

The next would be tags which depends on validate. (followed by helpers, plush, and so on)

Updated dependency map:
![gobuffalo--pop-20211030](https://user-images.githubusercontent.com/69406/139524666-44601aae-09fb-469f-8618-e0ccfa195315.png)

**Comment by sio4** [comment]
Additionally, I found the version control for `packr` is now not the best solution for go module. I would like to fix this before proceeding with this module updating. Please take a look at my suggestion on https://github.com/gobuffalo/packr/issues/294 and consider if the proposal could be a solution for it. Currently, the tree structure has circular reference and it makes maintaining module dependencies harder.

**Comment by sio4** [comment]
Started checking dependencies for `buffalo`, updated some modules, and updated the dependency map.

* https://github.com/gobuffalo/httptest/pull/16
* https://github.com/gobuffalo/events/pull/8
* https://github.com/gobuffalo/here/pull/9

![gobuffalo--deps 20211031](https://user-images.githubusercontent.com/69406/139575290-eec23487-2d2b-4f5d-bd74-f7f37972395a.png)

**Comment by paganotoni** [comment]
@sio4 covered the first part, while on it I did update all of those repos to use github actions.

**Comment by sio4** [comment]
Thank you! I submitted PRs for packages using flect just a minute ago. Will continue for others. By the way, I would like to change directory structure of packr as suggested here. https://github.com/gobuffalo/packr/issues/294 What do you think?

**Comment by sio4** [comment]
updated packages that use `flect`.

* https://github.com/gobuffalo/validate/pull/28
* https://github.com/gobuffalo/attrs/pull/3
* https://github.com/gobuffalo/meta/pull/10 (quick fix for gobuffalo/buffalo#2154)
* https://github.com/gobuffalo/packr/pull/295

**Comment by sio4** [comment]
For those PRs which is not yet reviewed, I just fixed workflow to run go 1.16 and 1.17, also added a badge for the action. I hope it could help your work!

**Comment by sio4** [comment]
@paganotoni Could you please take a look at the open PRs above? By dependency chain, they are needed to be merged before the next steps.

**Comment by sio4** [comment]
Just PRed gobuffalo/meta#12.

Current blocking PRs are gobuffalo/validate#28 and gobuffalo/attrs#3 (gobuffalo/tags depends on them).

**Comment by sio4** [comment]
PRed gobuffalo/tags#139.

Current blocking PR is gobuffalo/packr#295 and gobuffalo/tags#139, next will be helpers followed by plush.

**Comment by sio4** [comment]
Currently, gobuffalo/genny#41 and gobuffalo/fizz#108 are open. Then next will be pop and buffalo!

Today's dependency map is here!

![gobuffalo-deps 20211120](https://user-images.githubusercontent.com/69406/142659949-1cb406ad-9b85-4a8b-acdd-4fc6f6ab7979.png)

**Comment by sio4** [comment]
Phase 1 of the original plan is almost done. Currently `buffalo` and `pop` are not finished but it will be done by @fasmat 's work on packr to embed migration.

By the way, originally `cli`, `suite`, middleware, cli plugins, and other tools were the target of the next phase. Some of them already have some progress.

Current ongoing PRs:
* gobuffalo/clara#7
* gobuffalo/buffalo-goth#43
* gobuffalo/buffalo-auth#85

**Comment by sio4** [comment]
Current dependencies

##### buffalo and pop

![gobuffalo-deps-20211124](https://user-images.githubusercontent.com/69406/143234163-76f85d9d-9d7d-476e-8a8c-b5458a93a536.png)

##### cli and major plugins

![gobuffalo-deps-cli-and-plugins 20211124](https://user-images.githubusercontent.com/69406/143234298-2a4f0fae-2927-47a3-8a78-9ddde2e136d4.png)

**Comment by fasmat** [comment]
With the next release of gobuffalo/buffalo the dependency tree should become quite a bit smaller, we should also avoid overwriting transient dependencies with `replace` or `go get -u` (which adds ``// indirect`` directives). This also makes the dependency tree significantly smaller

**Comment by sio4** [comment]
The final dependency graph for buffalo v0.18 as of today, once three remaining PRs are merged.

* https://github.com/gobuffalo/buffalo-goth/pull/43
* https://github.com/gobuffalo/buffalo-auth/pull/85
* https://github.com/gobuffalo/buffalo-heroku/pull/18

![gobuffalo-deps-buffalo-0 18](https://user-images.githubusercontent.com/69406/143855302-c04a1b25-dbd4-446d-9815-e903b90685bd.png)

**Comment by sio4** [comment]
All PRs were merged even though some of them are not yet released. Closing the issue now.
