### ISSUE TITLE
Eager creation not working for varchar primary key

### ISSUE THREAD

**Issue by siwymilek** [gobuffalo/buffalo#2159]
### Description
So far I had many_to_many relationship with UUID as primary key – everything was working well, just changed primary key type to varchar(255) and now eager creation stopped working. Any clues?

### Steps to Reproduce the Problem

  1. Create working association
  2. Make sure eager creation is working
  2. Change primary keys from UUID to varchar 
  3. Eager creation not working

**Comment by ernsheong** [comment]
I'm curious, what prompted your remarks on https://github.com/gobuffalo/buffalo/issues/2158
