### ISSUE TITLE
Mail Registration/Authentication.

### ISSUE THREAD

**Issue by yageek** [gobuffalo/buffalo#217]
Dealing with user registration is something that is often needed.

It would be nice to have some primitives like those implemented in https://github.com/go-authboss/authboss.

**Comment by markbates** [comment]
I'm not sure this is something that should be built into Buffalo. Would it make more sense as an add-on package that has a few middleware and the like?

**Comment by yageek** [comment]
Sure! Maybe something like the `goth` package for oauth2 authentication.

**Comment by markbates** [comment]
That's what I'm thinking, something that can easily be plugged in, but isn't in core.

**Comment by yageek** [comment]
`authboss` is a nice package but it has its own template rendering method and it has not abstracted the rendering yet. May be would it make sens to perform some PR on this package and use it when it is ready? Or would you prefer something implemented from scratch?

**Comment by qarth** [comment]
I would love to see an authboss style plugin for Buffalo. Has there been any progress on this?

**Comment by markbates** [comment]
I'm closing this since I think it's out of scope of the main buffalo project, but could easily be implemented using plugins. I believe @apaganobeleno is working on a plug in, but I don't know if it's status.

**Comment by edevil** [comment]
Even though this is closed I would just like to add that integrating authboss or something similar would be very helpful since user management is a common requirement and easy to get wrong. Is there more information about the mentioned plugin in development?

**Comment by frederikhors** [comment]
https://github.com/volatiletech/authboss/issues/163

Are there any news?

`authboss` can become Go's "`devise`" with Buffalo.

Would it be possible to invest a few minutes of your time?

Here an official sample with chi router: https://github.com/volatiletech/authboss-sample
