### ISSUE TITLE
Server reports incorrect listening address

### ISSUE THREAD

**Issue by hut8** [gobuffalo/buffalo#2248]
### Description

Today, I deployed my Buffalo application. I had written some TLS code that integrates it with autocert (Let's Encrypt). Basically, I copied this code: https://gist.github.com/hdm/d271eb94a51f7f908ecb9ddc82d2b644

When I started my app in production, it said it was listening at http://0.0.0.0:3000 -- that's not what I wanted! When I visited the site, everything worked fine, including the TLS (and redirect from 80 to 443). Port 3000 was not open. So the log message was wrong.

I saw this FIXME: https://github.com/gobuffalo/buffalo/blob/215a8f9bd2a8e533030c4a432f51a3b341d4f81d/server.go#L25-L27

It seems pretty straightforward; one could just display the endpoint as it's running rather than blindly copying from the configuration.

I've already solved this problem on my fork, so I'll open a PR in a sec after I make sure nothing is broken.

**Comment by sio4** [comment]
Thanks for filing an issue and the PR for it. Indeed, the information is not correct, and I am considering what could be the best solution. I will review your PR soon and will reply.

**Comment by sio4** [comment]
related issue: #2151

**Comment by sio4** [comment]
The PR was merged and now the change is included in the released version. Closing.

```
buffalo: 2022/05/14 22:45:10 === Running: tmp/todo-build (PID: 884943) ===
DEBU[2022-05-14T22:45:10+09:00] starting application
INFO[2022-05-14T22:45:10+09:00] starting simple server on 127.0.0.1:3000
INFO[2022-05-14T22:45:10+09:00] starting Simple background worker
<...>
```
