### ISSUE TITLE
migrating from hugo to buffalo

### ISSUE THREAD

**Issue by piti2** [gobuffalo/buffalo#2250]
hi there, 

is there an easy process to migrate hugo projects to bufallow thanks

**Comment by sio4** [comment]
From your question, I wonder if Buffalo is what you are looking for.

While Hugo is a "static" site generator that generates HTML files from markup contents you wrote in human language, Buffalo is a web application development framework that generates executable application binary with your code written in go programming language (along with database integration probably).

Buffalo can serve static files, and also could generate content with templates, but I think it could not be a popular/desired use case.

If you really want to use Buffalo for a static site, I think you can start it by reading the following article and documents:

- https://www.gopherguides.com/articles/converting-a-static-website-to-golang-buffalo
- https://gobuffalo.io/documentation/frontend-layer/templating/
- https://gobuffalo.io/documentation/frontend-layer/layouts/
