### ISSUE TITLE
Issues in downloading packages from go get command

### ISSUE THREAD

**Issue by neilsamant** [gobuffalo/buffalo#2253]
While downloading gobuffalo packages, I am seeing "unrecognized import path" error for two modules.

This was not the case 1 year ago when I was able to download the packages.

Here is the exact error: 

 > [builder 4/6] RUN GO111MODULE=auto go get github.com/gobuffalo/pop/...:
#12 28.01 package github.com/gobuffalo/pop
#12 28.01       imports io/fs: unrecognized import path "io/fs": import path does not begin with hostname
#12 28.01 package github.com/gobuffalo/pop/genny/config
#12 28.01       imports embed: unrecognized import path "embed": import path does not begin with hostname
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c GO111MODULE=auto go get github.com/gobuffalo/pop/...]: runc did not terminate sucessfully

**Comment by sio4** [comment]
What was the version of buffalo and tools 1 year ago? and what is your current environment? (as the issue template explained, including the output of `buffalo info` is always better)

I guess your app (including dependencies) and/or environment are not compatible with the current version of buffalo. As you can see here[1], buffalo now only works with go modules and only works with golang versions 1.17 and 1.18.

[1] https://github.com/gobuffalo/buffalo#%EF%B8%8F-important
