### ISSUE TITLE
Unable to install gobuffalo via homebrew on Mac 

### ISSUE THREAD

**Issue by piti2** [gobuffalo/buffalo#2254]
hi there, 

i am unable to install gobuffalo via homebrew on mac. it is showing false error running `brew install gobuffalo/tap/buffalo` on MacOS Monterey version 12.3.1 i see error

```
Running `brew update --preinstall`...
==> Downloading https://github.com/gobuffalo/cli/releases/download/v0.18.3/buffa
Already downloaded: /Users/akisp/Library/Caches/Homebrew/downloads/15cb66582b89c98eed4960c3f64bc6b0049e64ff92d920f36fd0f7072f2b43d5--buffalo_0.18.3_Darwin_x86_64.tar.gz
==> Installing buffalo from gobuffalo/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.
```

if i run the suggested command there is not available updates as all tools and OS is uptodate

```
softwareupdate --all --install --force
Software Update Tool

Finding available software
No updates are available.
```

where there isnt a brew package like you have for packr so one can use like `brew install buffalo`

there is possibility all developers are on window or linux and you havent really tested it on mac?

can you please check 

thanks

**Comment by fasmat** [comment]
I primarily use a mac for development and haven't had any issues. Did you follow the next steps listed in the response from homebrew?

```
If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
```
