### ISSUE TITLE
process: preparing go1.18 support, step 1 - package level testing

### ISSUE THREAD

**Issue by sio4** [gobuffalo/buffalo#2263]
As a part of "preparing go1.18 support", I am now updating test workflows for all major packages. This will ensure that those packages are fine with the new version of go.

#### Buffalo core engine and dependencies

* [x] https://github.com/gobuffalo/buffalo/pull/2265
* [x] https://github.com/gobuffalo/pop/pull/715
* [x] https://github.com/gobuffalo/events/pull/9
* [x] https://github.com/gobuffalo/httptest/pull/17
* [x] https://github.com/gobuffalo/meta/pull/13
* [x] https://github.com/gobuffalo/fizz/pull/125
* [x] https://github.com/gobuffalo/genny/pull/46
* [x] https://github.com/gobuffalo/nulls/pull/8
* [x] https://github.com/gobuffalo/here/pull/12
* [x] https://github.com/gobuffalo/plush/pull/154
* [x] https://github.com/gobuffalo/helpers/pull/22
* [x] https://github.com/gobuffalo/tags/pull/144
* [x] https://github.com/gobuffalo/github_flavored_markdown/pull/7
* [x] https://github.com/gobuffalo/validate/pull/29
* [x] https://github.com/gobuffalo/attrs/pull/4
* [x] https://github.com/gobuffalo/flect/pull/58
* [x] https://github.com/gobuffalo/logger/pull/16
* [x] https://github.com/gobuffalo/envy/pull/40

#### CLI, the major plugins, and packages used in the created app

* [x] https://github.com/gobuffalo/cli/pull/151
* [x] https://github.com/gobuffalo/clara/pull/11
* [x] https://github.com/gobuffalo/refresh/pull/3
* [x] https://github.com/gobuffalo/buffalo-pop/pull/51
* [x] https://github.com/gobuffalo/buffalo-auth/pull/86
* [x] https://github.com/gobuffalo/buffalo-goth/pull/44
* [x] https://github.com/gobuffalo/mw-csrf/pull/10
* [x] https://github.com/gobuffalo/mw-i18n/pull/25
* [x] https://github.com/gobuffalo/mw-paramlogger/pull/8
* [x] https://github.com/gobuffalo/mw-forcessl/pull/2
* [x] https://github.com/gobuffalo/suite/pull/67

**Comment by sio4** [comment]
Done. The transition for all current active packages was finished. Thank you @paganotoni for your quick and strong support!

IMO, the following two packages should be included in this process as they were created as the new structure of the plugin/generator concept, but skip them now.

* https://github.com/gobuffalo/soda
* https://github.com/gobuffalo/plugins

**Comment by paganotoni** [comment]
This is great @sio4. I think this will reduce a lot of work when 1.19 arrives. It may be time now to start sunsetting the v1.16 support.

**Comment by sio4** [comment]
(missing) closing note:

IMPORTANT:

Since database-related tests are complex and different from the standard, the following two packages still use their own test workflows. I hope we can make another standard for the database support, but now we keep the original tests and just fixed the version of golang.

* https://github.com/gobuffalo/pop
* https://github.com/gobuffalo/fizz
