### ISSUE TITLE
Error: couldn't create database bcms_dev: error creating MySQL database bcms_dev: Error 1045: Access denied for user 'root'@'172.17.0.1' (using password: YES)

### ISSUE THREAD

**Issue by esobczak1970** [gobuffalo/buffalo#2278]
Even with mariadb set and database.yml configured buffalo is trying to communicate with 172.17.0.1 even though db is localhost at 127.0.0.1
buffalo pop create -a -c database.yml
Error: couldn't create database bcms_prod: error creating MySQL database bcms_prod: Error 1045: Access denied for user 'root'@'172.17.0.1' (using password: YES)

or
buffalo dev
then visiting http://localhost:3000/
couldn't start a new transaction: could not create new transaction: Error 1045: Access denied for user 'root'@'172.17.0.1' (using password: YES)

**Comment by sio4** [comment]
Could you please provide outputs of commands `buffalo info` from your app's root and `env` from your working environment? Also the content of `database.yml`? (Please erase password in it)

(The output of `buffalo env` is always mandatory)

**Comment by sio4** [comment]
One quick respones:

The error message `Error 1045: Access denied...` might be generated by the mariadb which means the network connection to the mariadb (on the `localhost` if you configured correctly) from pop was successful but the server rejected the access on the authentication stage.

I think you need to check:

1. Your configurations including auth parts
2. If the server got the connection.
3. Server's authentication configuration.

first.

**Comment by esobczak1970** [comment]
Based on a few other posts out there I'm wondering if the way the database
settings are used to communicate with my docker instance of Mariadb is
passing in the username of ***@***.*** which for some reason is getting
translated inside the docker instance to ***@***.*** internal to the instance
which maybe is 172.27.0.1

When I connect to the mariadb from mysql workbench with an account and my
password it connects fine to my mariadb instance. But I think the passing
of the more fully qualified ***@***.*** is converting to localhost being
resolved as the internal ip of the instance which is not authenticating.
Maybe I can just add a grant that somehow allows that ***@***.***

Sorry I thought this communication issue was something getting passed from
the code where something in the pop code was converting it to
***@***.*** (maybe it is but I think what I describe above may be what
is going on)

Any additional suggestions are appreciated.

Eric

Eric Sobczak

***@***.***

Chief Technology Officer

*Design Force Marketing*

*https://designforcemarketing.com <https://designforcemarketing.com>*

231-766-7347 office

**Comment by sio4** [comment]
Oh, you are using docker! Then it make sense. So you just treat it as "the mariadb is on the localhost" but actually the dbms is not on your localhost but on the docker's network. Just SNAT hides the structure from client but the server still feels it.

Then the address part, 172.17.0.1, could be the IP of your host (maybe your laptop, desktop, or server) on the docker network. Please check your network using `ifconfig` or whatever. You may be able to see that address on the bridge.

**Comment by esobczak1970** [comment]
It seems to be that I need to be able to leave the localhost off the config

See:
https://stackoverflow.com/questions/69903716/access-denied-for-user-root172-17-0-1-for-a-mysql-db-running-in-a-local-doc

It seems that buffalo/pop is trying to send username and host to
authenticate versus just username that for example mysqlworkbench or a few
other things allow so unless there is a way to get it to just authenticate
with a username I may have to setup an account on the docker that matches
the ip to be able to get it to authenticate right.

Thanks,

Eric

Eric Sobczak

***@***.***

Chief Technology Officer

*Design Force Marketing*

*https://designforcemarketing.com <https://designforcemarketing.com>*

231-766-7347 office

**Comment by esobczak1970** [comment]
I reinitized the docker image with a new root password and everything seems to working right. Consistent in mysql workbench and with buffalo and pop itself. Thanks
