### ISSUE TITLE
new app creation problem

### ISSUE THREAD

**Issue by AntonVTR** [gobuffalo/buffalo#2286]
### Description

Error during creating new app 
`buffalo new coke`

in the docker container env this img gobuffalo/buffalo

### Steps to Reproduce the Problem

  1. pull image `docker pull gobuffalo/buffalo`
  2. docker run
  3. `buffalo new coke`

### Expected Behavior

New app

### Actual Behavior

Error: exit status 1

### Info

` buffalo info
-> Go: Checking installation
✓ The `go` executable was found on your system at: /usr/local/go/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.17.10, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /usr/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v12.22.12, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /usr/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.14.16, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /usr/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.22.18, meets the minimum requirements.

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
✘ The `mysql` executable could not be found on your system.
For help setting up your MySQL environment please follow the instructions for you platform at:

https://www.mysql.com/downloads/

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.34.1, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /go/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.18.6, meets the minimum requirements.

-> Buffalo: Application Details
Warning: It seems like it is not a buffalo app. (.buffalo.dev.yml not found)
`

<details>

```
`DEBU[2022-07-01T11:26:06Z] LookPath: yarn
DEBU[2022-07-01T11:26:06Z] Exec: yarn --version
1.22.18
DEBU[2022-07-01T11:26:06Z] Exec: yarn set version berry
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.2.1/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.2.1.cjs
➤ YN0000: Done in 2s 801ms
DEBU[2022-07-01T11:26:20Z] Exec: yarn config set enableGlobalCache true
➤ YN0000: Successfully set enableGlobalCache to true
DEBU[2022-07-01T11:26:22Z] Exec: yarn config set logFilters --json [{"code":"YN0013","level":"discard"}]
➤ YN0000: Successfully set logFilters to [
  {
    code: 'YN0013',
    text: undefined,
    pattern: undefined,
    level: 'discard'
  }
]
DEBU[2022-07-01T11:26:24Z] Exec: yarn --version
3.2.1
DEBU[2022-07-01T11:26:26Z] Exec: yarn install
DEBU[2022-07-01T11:26:28Z] ➤ YN0000: ┌ Resolution step

DEBU[2022-07-01T11:26:36Z] ➤ YN0001: │ RequestError: getaddrinfo ENOTFOUND registry.yarnpkg.com
    at ClientRequest.<anonymous> (/usr/src/project/coke/.yarn/releases/yarn-3.2.1.cjs:195:14361)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.o.emit (/usr/src/project/coke/.yarn/releases/yarn-3.2.1.cjs:190:90453)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

DEBU[2022-07-01T11:26:36Z] ➤ YN0000: └ Completed in 8s 635ms

DEBU[2022-07-01T11:26:36Z] ➤ YN0000: Failed with errors in 8s 640ms

Usage:
  buffalo new [name] [flags]

Flags:
      --api                  skip all front-end code and configure for an API server
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci, circleci] (default "none")
      --config string        config file (default is $HOME/.buffalo.yaml)
      --db-type string       specify the type of database you want to use [cockroach, mariadb, mysql, postgres, sqlite3] (default "postgres")
  -d, --dry-run              dry run
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --module string        specify the root module (package) name. [defaults to 'automatic']
      --skip-config          skips using the config file
      --skip-docker          skips generating the Dockerfile
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
      --skip-yarn            use npm instead of yarn for frontend dependencies management
      --vcs string           specify the Version control system you would like to use [none, git, bzr] (default "git")
  -v, --verbose              verbosely print out the go get commands

ERRO[0036] Error: exit status 1` 
```

</details>

**Comment by sio4** [comment]
As you can see in the output, your environment (maybe within a docker container?) has an issue with domain name resolution for the hostname `registry.yarnpkg.com`. (The first line of the below snippet)

Please check your environment.

```
DEBU[2022-07-01T11:26:36Z] ➤ YN0001: │ RequestError: getaddrinfo ENOTFOUND registry.yarnpkg.com
    at ClientRequest.<anonymous> (/usr/src/project/coke/.yarn/releases/yarn-3.2.1.cjs:195:14361)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.o.emit (/usr/src/project/coke/.yarn/releases/yarn-3.2.1.cjs:190:90453)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
```

**Comment by AntonVTR** [comment]
curl -L registry.yarnpkg.com
{"db_name":"registry","engine":"couch_bt_engine","doc_count":2945006,"doc_del_count":333,"update_seq":23801306,"purge_seq":0,"compact_running":true,"sizes":{"active":85295456567,"external":190193456036,"file":86813876464},"disk_size":86813876464,"data_size":85295456567,"other":{"data_size":190193456036},"instance_start_time":"1656924542759659","disk_format_version":7,"committed_update_seq":23801306,"compacted_seq":23756428,"uuid":"964c127ddcbbd59982db296a0f9e8a56"}root@ba0c39
