### ISSUE TITLE
setting a time zone for default time stamps

### ISSUE THREAD

**Issue by scottywm** [gobuffalo/buffalo#2301]
Hello, i am needing a way to set the default time stamp in my migrations table so I hav the below example where i have a column called "time_test" and its default value is the time the row is created. 

create_table("users") {
  t.Column("id", "bigint", {primary: true})
  t.Column("user_name", "varchar(20)")
  t.Column("password", "varchar")
  t.Column("time_test", "timestamp", {"default": "now"})
}

i need a way to set this time zone for this column to UTC, How do I do it?

Thanks

Scott

**Comment by sio4** [comment]
Actually, this is not in Buffalo's scope but Pop's. However, there were some related discussions and closed PRs for this:

https://github.com/gobuffalo/pop/issues?q=timezone

Basically, the timezone configuration is usually the scope of the database engine itself and the connector or application just uses them. If you just want to store a UTC value in a specific column, I guess you can set the value from your app or from the model's validation functions.

Please check the discussions linked above. Also, I am going to close this issue for now and will move it under Pop.
