### ISSUE TITLE
what is  problem

### ISSUE THREAD

**Issue by itildesk** [gobuffalo/buffalo#2304]
time="2022-08-17T08:21:12+08:00" level=error msg="[PLUGIN] error loading plugin D:\\goworkcode\\bin\\pkg\\mod\\github.com\\gobuffalo\\buffalo@v0.15.5\\genny\\build\\_fixtures\\coke\\config\\buffalo-app.toml: fork/exec D:\\goworkcode\\bin\\pkg\\mod\\github.com\\gobuffalo\\buffalo@v0.15.5\\genny\\build\\_fixtures\\coke\\config\\buffalo-app.toml: %1 is not a valid Win32 application.\n"

**Comment by sio4** [comment]
Hi @itildesk

Not sure what is the problem just with a single line of the log you posted. Anyway, the version of the buffalo in your log is v0.15.5 and it is quite an old version which we cannot support for now. I would like to suggest you update the buffalo version to the recent one, along with updating golang version if needed, then please report an issue with details about the issue and the output of `buffalo info` if you are still facing an issue.

I am going to close this issue for now, but please feel free to reopen it with more data if you still need a help.
