### ISSUE TITLE
how to  easy quick  run as  https  server

### ISSUE THREAD

**Issue by itildesk** [gobuffalo/buffalo#2305]
pls !
because    sometimes  i need  quick Create a  tmp  https server  for  my  customer,who  can help me?

**Comment by itildesk** [comment]
who can  show me  buffalo  https  example? thanks

**Comment by sio4** [comment]
I think you can find some examples such as #1113. Anyway, having an HTTPS proxy in front of the buffalo app is also one of the preferred solutions. (which is more popular in the Cloud era.)
