### ISSUE TITLE
bug: [webpack-cli] Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by fivetwentysix** [gobuffalo/buffalo#2347]
#### Description

Updating the `_buffalo.scss` in a freshly generated app results in a error like the following:

```
[webpack-cli] [Error: EBUSY: resource busy or locked, unlink 'C:\code\harpy\public\assets\application.8e5193b5842a2a95eaef.css'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\code\\harpy\\public\\assets\\application.8e5193b5842a2a95eaef.css' 
}
time="2022-11-01T12:19:13+08:00" level=error msg="There was a problem starting the dev server, Please review the troubleshooting docs: Unknown\n"
```

#### Expected Behavior

I expect the app not to crash or if it does present Windows users with instructions on how to resolve this issue.

#### Actual Behavior

See description.

### To Reproduce

buffalo dev

### Additional Context

Windows specifications

<details>

```
Edition	Windows 11 Home
Version	22H2
Installed on	‎10/‎2/‎2022
OS build	22621.674
Experience	Windows Feature Experience Pack 1000.22634.1000.0
```
</details>
Environment specifications

<details>
```
go version go1.19.2 windows/amd64

node -v     
v16.13.1

buffalo version
time="2022-11-01T12:23:35+08:00" level=info msg="Buffalo version is: v0.18.8"

	github.com/gobuffalo/buffalo v1.0.1
	github.com/gobuffalo/buffalo-pop/v3 v3.0.6
	github.com/gobuffalo/envy v1.10.2
	github.com/gobuffalo/grift v1.5.2
	github.com/gobuffalo/mw-csrf v1.0.1
	github.com/gobuffalo/mw-forcessl v1.0.1
	github.com/gobuffalo/mw-i18n/v2 v2.0.2
	github.com/gobuffalo/mw-paramlogger v1.0.1
	github.com/gobuffalo/pop/v6 v6.0.8
	github.com/gobuffalo/suite/v4 v4.0.3
	github.com/unrolled/secure v1.13.0
```

**Comment by fivetwentysix** [comment]
I have managed to work around this by excluding my working directory from Virus Threat and Protection built into Windows.
![image](https://user-images.githubusercontent.com/516274/199159512-d4ad6cdd-b347-432a-bfd4-a4e16a67df59.png)

![image](https://user-images.githubusercontent.com/516274/199159623-bbf1b484-b1d7-42a0-9f29-f4ba17b94470.png)

**Comment by sio4** [comment]
Good to hear that you found the root cause!
