### ISSUE TITLE
feature: Support Rate Limiting HTTP Requests?

### ISSUE THREAD

**Issue by itildesk** [gobuffalo/buffalo#2369]
### Description

just like title

**Comment by sio4** [comment]
A feature request with a single line of description is not acceptable. All people have their own viewpoints and think differently with the same sentence. It could be better if you explain your points of view, and the issue you want to be addressed with example situations.

Anyway, rate-limiting is not a simple topic and it could be implemented differently for each size of service, the aim of the implementation, and the topology/architecture of the whole service. Commonly, rate-limiting is implemented at the proxy layer if the purpose of limiting is just to save backend applications, but sometimes the limiting could be implemented per user which is not the area of the framework.

One possible approach for rate-limiting is using a proxy with rate limiting feature such as http://nginx.org/en/docs/http/ngx_http_limit_req_module.html

I will keep this issue open for now, please update your issue description with your actual requirements then we can consider if the detailed request is acceptable or not.

**Comment by itildesk** [comment]
In fact, our program is running on the LAN,   only start a service process, not any proxy,so  we hope  it  as  a Built -in component
