### ISSUE TITLE
Is this project still under development at all?

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [gobuffalo/buffalo#2374]
Im here asking this because i see there arent many commits across the different repos and theres still quite a bit of work to be done.

So far ive been using this and loving it but theres still a lot of work to be done and its not mature enough for me to use it for any serious project.

For example the ORM is really underbaked and missing some crutial features.

Im here asking this question because I am almost inclined to fork these projects and just replace soda with smth like gorm that actually works well.

**Comment by sio4** [comment]
Hi @JamesTiberiusKirk 

Yes, this project is still "alive" but we are currently not that active for two conditions:

* We finished the last sprint early this year and most of the open issues were addressed during the period: https://github.com/orgs/gobuffalo/discussions/5 and https://github.com/gobuffalo/buffalo/discussions/2365
* We are considering the next generation and now working on the planning. The ORM thing is one of the considered topics.

We are still open for bugfix for the current version, but feature requests will be considered in the next generation mostly. Please feel free to open an issue with any ideas or suggestions for any of the interest modules. PRs are also welcome. :-)

**Comment by JamesTiberiusKirk** [comment]
AH! amazing to hear!
thanks for the reply

In that case, when i have some time ill see if I can contribute myself to stuff thats needed.
Do you have a comprehensive list things people could help out with? or is it just isses tagged with 'help wanted'?

**Comment by sio4** [comment]
We don't hardly limit any specific area/issue to contribute but we highly recommend to check if the topic was already discussed before and to discuss the topic in an issue before sending a PR so we could prevent any conflicts and waste of time.

See also org-wide contribution guide.

**Comment by JamesTiberiusKirk** [comment]
Thanks @sio4
