### ISSUE TITLE
feature: how to open two or many port for app?

### ISSUE THREAD

**Issue by itildesk** [gobuffalo/buffalo#2383]
### Description

sometimes  biz require  more than one port   buffalo support this feature?

**Comment by pierredup** [comment]
@itildesk Do you want to run the same app on multiple ports, with the same routes?
If that is the case, then you can just update your `cmd/app/main.go` file to run multiple servers with different ports

```go
func main() {
    app := actions.App()

    appOne := servers.New()
    appTwo := servers.New()

    appOne.Addr = ":3000"
    appTwo.Addr = ":3001"

    if err := app.Serve(appOne, appTwo); err != nil {
        log.Fatal(err)
    }
}
```

**Comment by itildesk** [comment]
@pierredup thanks for your suggest,I followed what you said, the program has an additional access entrance, and the background process has not changed.
