### ISSUE TITLE
I can't cross compile to linux

### ISSUE THREAD

**Issue by adeolaibigbemi** [gobuffalo/buffalo#2386]
### Description

I am building a buffalo project on windows.
I am trying to cross compile the project to linux.

I have set all the needed env variables for linux. see attached image.
<img width="946" alt="image" src="https://github.com/gobuffalo/buffalo/assets/19607858/508af90d-52b4-46a0-8154-5394e620ea1c">

The problem is that I get a .exe file when I compile and this is not usable on linux.

Am I doing anything wrong?

Please help.

### Additional Context

Details

<details>

```
Paste the output of `buffalo info` here!
```

</details>

**Comment by vadviktor** [comment]
I believe this has been answered in Slack: https://gophers.slack.com/archives/C3MSAFD40/p1697996217777509

The issue @adeolaibigbemi had was that on Windows you have to be very specific with the file extensions. The executables must be have least `.exe`. 

TBH it has caught me out also at least once 😄
