### ISSUE TITLE
feature: Is this project active?

### ISSUE THREAD

**Issue by narup** [gobuffalo/buffalo#2393]
### Description

Looks like no commit for almost a year or any PRs has been merged. Maintainers don't seem to be active either, so even if someone creates a PR less likely to get merged. Confused if folks who are using this framework are migrating or maintaining their own fork of this project?

**Comment by rayjanoka** [comment]
Seems like it didn't catch on. And the gorilla toolkit has also been archived. https://x.com/elithrar/status/1601247147332358144?s=46&t=dHEN0hRnUzuc76TS7CVkzQ

**Comment by narup** [comment]
Yeah! Ambitious effort. Since go 1.22 has improved router, I am going in pure golang http handler with htmx which I think works for our case

**Comment by rayjanoka** [comment]
> Yeah! Ambitious effort. Since go 1.22 has improved router, I am going in pure golang http handler with htmx which I think works for our case

yes, HTMX is the way! nice1 🚀
