### ISSUE TITLE
[Question] Is this framework in a stalled state?

### ISSUE THREAD

**Issue by stormenergy91** [gobuffalo/buffalo#2397]
Since I see that the last version is about a year ago and , is his development in a stalled state? What are  the plans for the future?
I have a project builded in Buffalo and I need to build a new update but I don't know if is better to switch to an other framework.
Thanks any way for you great work done so far.

**Comment by goofcc** [comment]
Same question!!!
Buffalo is currently the greatest project I have ever seen based on Golang, without anyone to maintain it. It's really a pity. I need to consider whether it's necessary to keep it alive. Community promotion is an important task, but it also requires a blueprint to drive it. Is the author still here?

**Comment by stormenergy91** [comment]
I agree, it's a great framework. Why not create a Foundation like other open source projects to mange It and with donation or other receipts keep the development active?

**Comment by talglobus** [comment]
I'd be open to getting the engine spinning

**Comment by rpwatkins** [comment]
I'd like to help as well.

**Comment by paganotoni** [comment]
Hi, @rpwatkins @stormenergy91 @talglobus @goofcc 👋, I appreciate you stepping in and wanting to keep Buffalo running. This is a topic I've been struggling with for some time. One part of me knows about the need for a framework like Buffalo and gets excited while describing it. Another part of me knows Buffalo was built when the Go language was changing a lot in its foundation, which led to some decisions made in the framework to age poorly. I may want to start something like Buffalo again, considering the current context of the Go language (embed, modules, and generics) and being more opinionated about `Who is Buffalo for?` but that's another topic 😅.

Back to the original question of whether the framework is stalled. I can say the answer is _Yes_. As much as I would like to keep pushing Buffalo forward (And I've done that over the last few years, including through the pandemic), the best decision is to archive the repo.

Thank you for asking and being attentive to Buffalo. I have had a blast building Buffalo and still have the fire to build something similar; we'll see what happens.
