### ISSUE TITLE
Best way to wrap or dispatch to http.Handler

### ISSUE THREAD

**Issue by nuclearsandwich** [gobuffalo/buffalo#241]
This is just a question, but I'm not in the gophers Slack.

I have a buffalo app running on a RaspberryPi which administers several resources on an internal network. I would like to be able to reverse proxy some content from those resources, specified by db model properties, directly within my application rather than configuring a static reverse proxy using something like nginx.

I don't see anything in the buffalo router documentation that "upgrades" an http.Handler into a buffalo.Handler or otherwise allows me to pass an http.Handler through. I was able to make it work by calling ServeHTTP on the reverse proxy directly and returning nil in a buffalo handler function but this seems either like something I shouldn't be doing (am I missing some critical stage of processing by doing this naively?) or something that could have an API for doing so in a way that simplifies buffalo.handlerToHandler (https://github.com/gobuffalo/buffalo/blob/master/handler.go#L58) for http.Handlers passed in directly.

```go
func proxyHandler(c buffalo.Context) error {
   rp := &httputil.ReverseProxy{Director:dirFunc}
   rp.ServeHTTP(c.Response(), c.Request())
  return nil
}
```

Thanks!

**Comment by markbates** [comment]
Not sure I fully understand the questions, but is this what you are looking for: https://godoc.org/github.com/gobuffalo/buffalo#WrapHandler

**Comment by nuclearsandwich** [comment]
> Not sure I fully understand the questions, but is this what you are looking for: https://godoc.org/github.com/gobuffalo/buffalo#WrapHandler

Yes! I have no idea how I missed that. Blaming lack of coffee. Appreciated.

**Comment by markbates** [comment]
lol. don't mention it. glad to be of help!
