### ISSUE TITLE
Provide a CSRF middleware

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#243]
CSRF (Cross-site request forgery) protection is often needed, and could be implemented as a core middleware.

See a sample implementation for Revel (another Go web framework) here: https://github.com/cbonello/revel-csrf

**Comment by markbates** [comment]
Yes! This would make a great PR for someone. Easy to add.

There is already support for csrf in the `github.com/gobuffalo/tags` package:

https://github.com/gobuffalo/tags/blob/master/form%2Fform.go#L13
https://github.com/gobuffalo/tags/blob/master/form%2Fvelvet.go#L33

Just needs implementing on the Buffalo side.

**Comment by apaganobeleno** [comment]
@stanislas-m will you work on this one ?

**Comment by stanislas-m** [comment]
@apaganobeleno I can. :)

**Comment by philipithomas** [comment]
Gorilla has a CSRF package that I've used with gorilla/mux (the Buffalo router) in the past. It's great. Adding CSRF support to the gorilla context so that it's easier to display in templates would be helpful. 

https://github.com/gorilla/csrf

**Comment by stanislas-m** [comment]
It seems I can't use Gorilla CSRF package without having access to the mux router. Buffalo middleware interface don't provide this kind of access.

**Comment by markbates** [comment]
You could use it, but it is meant to be used like this in `main.go`:

```
CSRF(actions.App())
```

With that said, I don't like that approach. There are two approaches that we can take:

1) Write a piece of Buffalo middleware that does this. Using the CSRF package as an example, it should only take about 10 minutes to actually write it. It's not overly complex bit of code.
2) Insert CSRF when using `buffalo.Automatic`, which is meant to set up a Buffalo application with "good" defaults, which one could argue this is.

If it is "automatic" it should only be triggered on HTML form posts.

Thoughts?

**Comment by stanislas-m** [comment]
> With that said, I don't like that approach.

Same here. I'll really like it to be a middleware, since you can choose where you want to apply it (then, you can exclude API endpoints for example). Then, I think the first option is the best.

**Comment by stanislas-m** [comment]
I'll work on that this weekend.

**Comment by stanislas-m** [comment]
Closed with #271.
