### ISSUE TITLE
I18n (internationalisation) support

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#249]
As a plugin / module, I think we can provide a way to manage translations.

Common solutions:
- GNU gettext with po/pot/mo files
- ini files
- yaml or json files

**Comment by u007** [comment]
will this help?
https://gist.github.com/u007/fda1dd4f92f424242732b5f7a82d5fc3

**Comment by stanislas-m** [comment]
@u007 Hum, if you look at the comments in the code:

``` go
// Use Tfunc or MustTfunc to fetch a TranslateFunc that will return the translated string for a specific language.
//     func handleRequest(w http.ResponseWriter, r *http.Request) {
//         cookieLang := r.Cookie("lang")
//         acceptLang := r.Header.Get("Accept-Language")
//         defaultLang = "en-US"  // known valid language
//         T, err := i18n.Tfunc(cookieLang, acceptLang, defaultLang)
//         fmt.Println(T("Hello world"))
//     }
```

I think it just have to be called like this in a custom middleware.

**Comment by markbates** [comment]
We also need to think about, make sure, that translation files get bundled into the binary that is built.

**Comment by u007** [comment]
ive done an update, will update the gist soon, made a middleware to setup velvet with context
and pass shared i18n setup to another sub directory so it can be shared among actions
