### ISSUE TITLE
Documentation Needs to State Requirement for Go >= 1.7

### ISSUE THREAD

**Issue by gillchristian** [gobuffalo/buffalo#251]
When running the installation on Ubuntu 16.04 I get the following output.

```bash
$ go get -u github.com/gobuffalo/buffalo/buffalo  
package context: unrecognized import path "context" (import path does not begin with hostname)
```
And buffalo does not get installed.
```
$ which buffalo 
buffalo not found
```

**Comment by markbates** [comment]
You need to use Go 1.7 or later. This error implies you are running on 1.6 or below.

**Comment by gillchristian** [comment]
Thanks for the quick answer, totally missed that!

Do you think adding a line about the Go version to the `README.md` is a good idea @markbates? I could PR right away :smile:

**Comment by markbates** [comment]
It's an excellent PR! Would love to have it.

**Comment by gillchristian** [comment]
Closing in favor of #254
