### ISSUE TITLE
Add Support for MongoDB via mgo package

### ISSUE THREAD

**Issue by qawarrior** [gobuffalo/buffalo#252]
It would be nice to have a NOSQL option for the database part of Buffalo. Mongo is and excelent choice and the mgo package is very robust and allows access to almost all mongo features.

**Comment by markbates** [comment]
What support would you want for it?

Right now a Buffalo application can be generated with the `--skip-pop` flag which will generate an application without any database support, so you could easily use Mongo, Gorm, or whatever you want would want to use.

The generators, and other tools, found under the `buffalo db` command come from the `github.com/markbates/pop/soda` library.

**Comment by qawarrior** [comment]
ok i see. Then I guess i can just wire up my mongo instance myself fairly easily.

**Comment by carepollo** [comment]
I think that would be better if the framework had the option to set that up for you instead.
