### ISSUE TITLE
install fails when sqllite fails to build.

### ISSUE THREAD

**Issue by qawarrior** [gobuffalo/buffalo#253]
I have tried everything to get mingw64 to build sqllite-3 driver but gcc always fails. so go get stops when this happens and buffalo never finishes installing.

**Comment by markbates** [comment]
Is that windows? Have you opened an issue with the SQLite driver? I'm on my phone and don't have the repo at hand.

**Comment by qawarrior** [comment]
I think I figured it out,I still did not have gcc for 64 bit.

**Comment by markbates** [comment]
Closing this as it appears that it was resolved on the user end.
