### ISSUE TITLE
Destroy CLI

### ISSUE THREAD

**Issue by apaganobeleno** [gobuffalo/buffalo#277]
Sometimes as a developer you need to remove a generated model/migration/other because its no longer relevant or you mistyped it, it would be great to have buffalo's CLI to help destroying the generated code, which should be in most of the cases the oposite operation that the generate command does.

@markbates Thoughts ?

**Comment by markbates** [comment]
That seems like it would be a good idea.

**Comment by stanislas-m** [comment]
I like it too!
