### ISSUE TITLE
Documented video link is broken

### ISSUE THREAD

**Issue by sivalingams** [gobuffalo/buffalo#284]
https://github.com/gobuffalo/buffalo/blob/master/app.go#L74

https://www.youtube.com/watch?v=BKbOplYmjZM

The above video link in document is broken. It gives an message of " This video is not available. "

**Comment by markbates** [comment]
The video might not be available in certain parts of the world. In any case, it's just an Easter Egg video. It's for a song called, "Automatic Buffalo", by a band called The Sheila Divine.
