### ISSUE TITLE
sql: Scan error

### ISSUE THREAD

**Issue by vhontar** [gobuffalo/buffalo#288]
Hi i have this strange error, my db postgressql, buffalo 0.7.4
`sql: Scan error on column index 7: unsupported Scan, storing driver.Value type <nil> into type *string`

I took code from your json_crud example

`// UsersList returns all user data in JSON
func UsersList(c buffalo.Context) error {
	users := &models.Users{}
	tx := c.Get("tx").(*pop.Connection)
	err := tx.All(users)
	if err != nil {
		return c.Error(404, errors.WithStack(err))
	}

	return c.Render(200, render.JSON(users))
}`

I added some field that can have null value, and when i tried to get data, i got this error

What i should do in this case?

**Comment by markbates** [comment]
Go doesn't allow that. You have to use a special type that can handle null values correctly. Try this package https://github.com/markbates/pop/tree/master/nulls

**Comment by vhontar** [comment]
Thank you
