### ISSUE TITLE
The migrate command on a built binary doesn't work

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#289]
After building a binary and trying to run `mybin migrate` it starts the server instead of running the migrations. This appears to only be broken in `0.8.0`.

**Comment by markbates** [comment]
Apparently this was just me being stupid. I had an binary of the same name installed and instead of running `./mybin` I was running `mybin` which ran the old binary. Oops. :)

**Comment by JamesMura** [comment]
Seem to be having this issue with v0.9.1 is there any way I can debug this, when I run the migrate command all it prints out is "--> Running migrations" and the time it took

**Comment by markbates** [comment]
There is a big 0.9.1 that broke migrations. Use either 0.9.1.2 or 0.9.2

**Comment by JamesMura** [comment]
upgrading the version worked. Thank you

**Comment by fdonzello** [comment]
Commenting here @markbates since looks like the most appropriate place even if the issue is closed.

I'm using the shipped Dockerfile to run a buffalo app on kubernetes.
Migrations are not executed on pods recreation. 

Do you use k8s for buffalo and have any hints?

**Comment by markbates** [comment]
I don’t use k8s, so I’m the wrong person to ask. Sorry.
