### ISSUE TITLE
db based session store

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#291]
hi,

how do i apply custom store to my project for session?

thank you

**Comment by u007** [comment]
nvm, i found the app initialization supporting custom session store option
https://github.com/gobuffalo/buffalo/blob/cae4585044138c8ea367cc869e70b2d3c7afae1c/options.go

anybody did a pop based session store?

**Comment by markbates** [comment]
I'm closing this since I don't think it'll be part of Buffalo "core". If one gets written it should be linked to.
