### ISSUE TITLE
Best practices of model error handling 

### ISSUE THREAD

**Issue by vhontar** [gobuffalo/buffalo#304]
Hi, can you send example of the best practice of model error handling, because when i try to save model to db it returns ugly error
`
{"code":500,"error":"pq: duplicate key value violates unique constraint \"user_email_key\"\npostgres error inserting record\ngithub.com/markbates/pop.(*postgresql).Create\n\t/go/src/github.com/markbates/pop/postgresql.go:44\ngithub.com/markbates/pop.(*Connection).Create.func1\n\t/go/src/github.com/markbates/pop/executors.go:71\ngithub.com/markbates/pop.(*Connection).timeFunc\n\t/go/src/github.com/markbates/pop/connection.go:162\ngithub.com/markbates/pop.(*Connection).Create\n\t/go/src/github.com/markbates/pop/executors.go:72\ngitlab.oms.systems/go_itcraft/vlad.informatics.work/vlad/actions.UsersSignUp\n\t/go/src/gitlab.oms.systems/go_itcraft/vlad.informatics.work/vlad/actions/users.go:112\ngithub.com/gobuffalo/buffalo/middleware.glob..func1.1.1.1\n\t/go/src/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:28\ngithub.com/markbates/pop.(*Connection).Transaction.func1\n\t/go/src/github.com/markbates/pop/connection.go:100\ngithub.com/markbates/pop.(*postgresql).Lock\n\t/go/src/github.com/markbates/pop/postgresql.go:133\ngithub.com/markbates/pop.(*Connection).Transaction\n\t/go/src/github.com/markbates/pop/connection.go:110\ngithub.com/gobuffalo/buffalo/middleware.glob..func1.1.1\n\t/go/src/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:29\ngithub.com/gobuffalo/buffalo.RequestLoggerFunc.func1\n\t/go/src/github.com/gobuffalo/buffalo/request_logger.go:44\ngithub.com/gobuffalo/buffalo.(*App).handlerToHandler.func1\n\t/go/src/github.com/gobuffalo/buffalo/handler.go:64\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1942\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/gorilla/mux/mux.go:114\ngithub.com/markbates/refresh/refresh/web.ErrorChecker.func1\n\t/go/src/github.com/markbates/refresh/refresh/web/web.go:23\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1942\ngithub.com/gobuffalo/buffalo.(*App).ServeHTTP\n\t/go/src/github.com/gobuffalo/buffalo/app.go:40\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2568\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1825\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2197\nerror inside of calling function\ngithub.com/markbates/pop.(*Connection).timeFunc\n\t/go/src/github.com/markbates/pop/connection.go:164\ngithub.com/markbates/pop.(*Connection).Create\n\t/go/src/github.com/markbates/pop/executors.go:72\ngitlab.oms.systems/go_itcraft/vlad.informatics.work/vlad/actions.UsersSignUp\n\t/go/src/gitlab.oms.systems/go_itcraft/vlad.informatics.work/vlad/actions/users.go:112\ngithub.com/gobuffalo/buffalo/middleware.glob..func1.1.1.1\n\t/go/src/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:28\ngithub.com/markbates/pop.(*Connection).Transaction.func1\n\t/go/src/github.com/markbates/pop/connection.go:100\ngithub.com/markbates/pop.(*postgresql).Lock\n\t/go/src/github.com/markbates/pop/postgresql.go:133\ngithub.com/markbates/pop.(*Connection).Transaction\n\t/go/src/github.com/markbates/pop/connection.go:110\ngithub.com/gobuffalo/buffalo/middleware.glob..func1.1.1\n\t/go/src/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:29\ngithub.com/gobuffalo/buffalo.RequestLoggerFunc.func1\n\t/go/src/github.com/gobuffalo/buffalo/request_logger.go:44\ngithub.com/gobuffalo/buffalo.(*App).handlerToHandler.func1\n\t/go/src/github.com/gobuffalo/buffalo/handler.go:64\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1942\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/gorilla/mux/mux.go:114\ngithub.com/markbates/refresh/refresh/web.ErrorChecker.func1\n\t/go/src/github.com/markbates/refresh/refresh/web/web.go:23\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1942\ngithub.com/gobuffalo/buffalo.(*App).ServeHTTP\n\t/go/src/github.com/gobuffalo/buffalo/app.go:40\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2568\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1825\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2197\nerror inside of calling function\ngithub.com/markbates/pop.(*Connection).Transaction.func1\n\t/go/src/github.com/markbates/pop/connection.go:107\ngithub.com/markbates/pop.(*postgresql).Lock\n\t/go/src/github.com/markbates/pop/postgresql.go:133\ngithub.com/markbates/pop.(*Connection).Transaction\n\t/go/src/github.com/markbates/pop/connection.go:110\ngithub.com/gobuffalo/buffalo/middleware.glob..func1.1.1\n\t/go/src/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:29\ngithub.com/gobuffalo/buffalo.RequestLoggerFunc.func1\n\t/go/src/github.com/gobuffalo/buffalo/request_logger.go:44\ngithub.com/gobuffalo/buffalo.(*App).handlerToHandler.func1\n\t/go/src/github.com/gobuffalo/buffalo/handler.go:64\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1942\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/gorilla/mux/mux.go:114\ngithub.com/markbates/refresh/refresh/web.ErrorChecker.func1\n\t/go/src/github.com/markbates/refresh/refresh/web/web.go:23\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1942\ngithub.com/gobuffalo/buffalo.(*App).ServeHTTP\n\t/go/src/github.com/gobuffalo/buffalo/app.go:40\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2568\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1825\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2197"}
`

**Comment by markbates** [comment]
I think what you want is the `Error` function on `buffalo.Context` https://godoc.org/github.com/gobuffalo/buffalo#Context. It allows you to set the status code and error you want to return.

It looks like you are probably just returning whatever you get from the database. When you do that you get a `500` status code, and the original error.

You probably want to handle the errors a bit better, and perhaps return a different status code. How you go about handling those errors, is entirely up to you.

**Comment by obedtandadjaja** [comment]
@vhontar @markbates since buffalo uses `pq`, we can leverage pq's error code to provide better error message:

```golang
err := tx.Create(user)
if err != nil {
  if pqerr, ok := err.(*pq.Error); ok {
    if pqerr.Code == "23505" {
      return errors.New("Email has been taken")
    }
  }
}
```

For more info about pq error codes: https://github.com/lib/pq/blob/master/error.go
