### ISSUE TITLE
Context Session

### ISSUE THREAD

**Issue by vhontar** [gobuffalo/buffalo#306]
hi, i try to set variable into session, but every time when i send post request to server session changed and i lost all my data that i saved in session, what i've done wrong. Here is example of code:
`c.Logger().Info(c.Session().Session.Values)

	c.Logger().Info(body.Hash)
	userID, ok := c.Value(body.Hash).(int)
	c.Logger().Info(c.Value(body.Hash))
	user := models.User{}

	if ok {
		value := models.FindUserByID(userID)
		err := value.First(&user)

		if err != nil {
			return err
		}

		c.Logger().Info(body)

		user = models.UserInitValues(body)
		err = tx.Update(&user)

		if err != nil {
			return err
		}
	} else {
		user = models.UserInitValues(body)

		quesry := models.User{}

		if models.FindUserByEmail(user.Email.String).First(&quesry); quesry.ID == 0 {

			err := tx.Create(&user)

			if err != nil {
				return err
			}

			c.Set(body.Hash, user.ID)
			c.Set("test", 3)
			c.Session().Save()

		} else {
			return c.Render(500, render.JSON(user))
		}
	}`

**Comment by markbates** [comment]
`buffalo.Context` is not a session, it's a per request context. 

To set a value on the session you have to get the session via `c.Session()`, and use it accordingly. https://godoc.org/github.com/gobuffalo/buffalo#Session

```go
c.Session().Set("something", "some value")
err := c.Session().Save()
```

Make sure to check the error on `c.Session().Save()` as well to make sure things are good.

**Comment by vhontar** [comment]
Thank you

**Comment by vhontar** [comment]
Interesting things:
i sent post query 
my log: time="2017-03-21T10:02:52Z" level=info msg="map[requestor_id:814590668c e060c98bca4eb4469bcc9202d9ffe25a:26 dermo:3]" method=POST path="/signup" request_id=814590668c-8290
it was written to session normal
my next post query after previous:
my log:time="2017-03-21T10:04:34Z" level=info msg="map[requestor_id:f2f15ffb59]" method=POST path="/signup" request_id=f2f15ffb59-b1dd465e93 
i lost my data, and request_id different in both cases, how it's possible

`func UsersSignUp(c buffalo.Context) error {
	tx := c.Get("tx").(*pop.Connection)
	body := extensions.ConvertBodyRequestToJson(c)
	church := models.Church{}

	if _, err := strconv.Atoi(body.ChurchID.(string)); err != nil {
		if body.ChurchID.(string) != "" {

			err := models.FindChurchByName(body.ChurchID.(string)).First(&church)

			if church.ID == 0 {
				church.Name = body.ChurchID.(string)
				err = tx.Create(&church)

				if err != nil {
					return err
				}
			}

			body.ChurchID = church.ID
		}
	}

	c.Logger().Info(c.Session().Session.Values)

	c.Logger().Info(body.Hash)
	userID, ok := c.Value(body.Hash).(int)
	c.Logger().Info(c.Value(body.Hash))
	user := models.User{}

	if ok {
		value := models.FindUserByID(userID)
		err := value.First(&user)

		if err != nil {
			return err
		}

		c.Logger().Info(body)

		user = models.UserInitValues(body)
		err = tx.Update(&user)

		if err != nil {
			return err
		}
	} else {
		user = models.UserInitValues(body)

		quesry := models.User{}

		if models.FindUserByEmail(user.Email.String).First(&quesry); quesry.ID == 0 {

			err := tx.Create(&user)

			if err != nil {
				return err
			}

			c.Session().Set(body.Hash, user.ID)
			c.Session().Set("dermo", 3)
			err = c.Session().Save()

			c.Logger().Info(c.Session().Session.Values)
			c.Logger().Info(c.Session().Get("dermo"))

			if err != nil {
				c.Logger().Info(err)
				return err
			}

		} else {
			return c.Render(500, render.JSON(user))
		}
	}

	return c.Render(200, render.JSON(user))
}
`
