### ISSUE TITLE
Lower case package dependency

### ISSUE THREAD

**Issue by maxmeyer** [gobuffalo/buffalo#308]
There are several places where you use `github.com/Sirupsen/logrus` in your imports (https://github.com/gobuffalo/buffalo/search?utf8=%E2%9C%93&q=Sirupsen) - sirupsen with capital "s". But: The import path is lower case on Github. Would you mind to fix this and use the lower case import path in your packages?

With the current implementation you might see the following error:
~~~
case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
~~~

Cheers,
Dennis

**Comment by markbates** [comment]
According to their documentation it's uppercase Sirupsen. That's what they are using in the code on their README.
