### ISSUE TITLE
Install in Arch Linux fails

### ISSUE THREAD

**Issue by pitakill** [gobuffalo/buffalo#311]
I'm running Arch Linux:

`$ uname -a`
```text
Linux euler 4.10.4-1-ARCH #1 SMP PREEMPT Sat Mar 18 19:39:18 CET 2017 x86_64 GNU/Linux
```

`$ go env`
```text
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pitakill/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build713278517=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

And

`$ go get -u github.com/gobuffalo/buffalo/buffalo`

after some time only get the package but does not build anything.

I've been trying to debug what is happening but without luck.

In `$GOPATH/src/github.com/gobuffalo/buffalo` the command `$ go build -x -v .` output is: `WORK=/tmp/go-build116307171` and immediately after is my prompt, and no binary in `$GOPATH/bin`

If I do a `$ go build -x -v github.com/gobuffalo/buffalo` is a output similar to the command above

I can build the binary in Mac OS X, I'm going to try the cross compile and update this issue. :-)

Cheers!

___EDIT___

I try this in a MacOS Sierra: `$ go build -x -v github.com/gobuffalo/buffalo` and the output is in the next gist

https://gist.github.com/pitakill/de36da90302795abe396cc621b5b34ef

I can't build the binary in Mac either, in the Mac in my work in the morning was working :(

**Comment by pitakill** [comment]
I can confirm that with the new release (v0.8.0); it installs and works as expected. :)

Cheers!

**Comment by markbates** [comment]
Woot!!!
