### ISSUE TITLE
Update docs to reflect current state of template context.

### ISSUE THREAD

**Issue by MerreM** [gobuffalo/buffalo#312]
> Params returns all of the parameters for the request, including both named params and query string parameters. These parameters are automatically available in templates as "{{.params}}".

>> Expecting ID, got: 'Sep{"."}'

Don't know what I'm doing wrong, but I suspect the docs need updating.

**Comment by markbates** [comment]
The docs do need updating. Where did you find that? Which doc?

**Comment by MerreM** [comment]
https://godoc.org/github.com/gobuffalo/buffalo#DefaultContext.Params
