### ISSUE TITLE
Having trouble installing -- prob easy fix

### ISSUE THREAD

**Issue by SpencerCDixon** [gobuffalo/buffalo#317]
Apologize this is probably total Go noob question but I'm having troubles installing buffalo.  I keep getting git issues and not entirely sure how to approach debugging this.  Maybe someone here knows??

<img width="723" alt="screen shot 2017-03-24 at 1 43 59 pm" src="https://cloud.githubusercontent.com/assets/7471018/24306772/16bba5ba-1098-11e7-8bf0-7537a9a6756b.png">

**Comment by markbates** [comment]
I've seen this happen before with `go get`. Something, I don't know what, causes those packages to get into some weird git state where they're not a branch any more.

The "fix" is to go into those packages and set them all to `master` again. I think this is a known issue with `go get`, it's not actually a Buffalo issue.

**Comment by markbates** [comment]
For reference: https://groups.google.com/forum/#!topic/golang-nuts/t9dLLVwsMlM

**Comment by SpencerCDixon** [comment]
Yeah just saw that! Fixed it by `rm -rf`ing all the paths in that go get output.  Thanks for the quick response though!
