### ISSUE TITLE
Potential enhancement -- version cmd

### ISSUE THREAD

**Issue by SpencerCDixon** [gobuffalo/buffalo#322]
Hey Mark/buffalo team,

New to Go but really digging this lib after coming from Rails world.  Was wondering if I put together a PR for a `buffalo version` command if that is something you would accept/find useful?

**Comment by markbates** [comment]
Absolutely! I thought this one already, but apparently there isn't. :)

Should be a fairly straightforward first PR.

**Comment by apaganobeleno** [comment]
@SpencerCDixon i think it would be helpful, not sure if @markbates agrees but anyways make sure to send the PR from the 0.8.0 branch, which will be the next release for features, am i right @markbates  ?

**Comment by markbates** [comment]
You are definitely correct there @apaganobeleno

**Comment by SpencerCDixon** [comment]
Will do, thanks guys!  Figured it be an easy PR, will work on it this weekend.  Cheers
