### ISSUE TITLE
Integration test to resources fails, when basic implementation contains a model.

### ISSUE THREAD

**Issue by as27** [gobuffalo/buffalo#328]
If the resource generator does more than just a empty basic implementation (see #297) the tests fails: 

See [here](https://travis-ci.org/gobuffalo/buffalo/jobs/214762148#L1481)

```
Step 32 : RUN buffalo g resource admins --skip-model
 ---> Running in 8ccf04b9e3eb
Buffalo version 0.8.0.dev
--> actions/admins.go
--> actions/admins_test.go
--> gofmt -w .
 ---> 1428b9ae935b
Removing intermediate container 8ccf04b9e3eb
Step 33 : RUN filetest -c $GOPATH/src/github.com/gobuffalo/buffalo/buffalo/cmd/filetests/resource_skip_model.json
 ---> Running in eea7a90220e3
All of your tests have passed with flying colors!
 ---> 76a1858463d8
Removing intermediate container eea7a90220e3
Step 34 : RUN rm actions/admins_test.go
 ---> Running in eb9f33fdb703
 ---> ec66716a3e22
Removing intermediate container eb9f33fdb703
Step 35 : RUN buffalo test -race
 ---> Running in 7c68a1d8022e
Buffalo version 0.8.0.dev
dropped database /go<no value>/hello_world_test.sqlite
created database /go<no value>/hello_world_test.sqlite
dumped schema for /go<no value>/hello_world_development.sqlite
loaded schema for /go<no value>/hello_world_test.sqlite
go test -p 1 -race hello_world hello_world/actions hello_world/grifts hello_world/models
# hello_world/actions
actions/admins.go:23: undefined: models in models.Admins
actions/admins.go:44: undefined: models in models.Admin
actions/admins.go:59: undefined: models in models.Admin
actions/admins.go:67: undefined: models in models.Admin
actions/admins.go:101: undefined: models in models.Admin
actions/admins.go:117: undefined: models in models.Admin
actions/admins.go:152: undefined: models in models.Admin
actions/users.go:23: undefined: models in models.Users
actions/users.go:44: undefined: models in models.User
actions/users.go:59: undefined: models
actions/users.go:59: too many errors
```

If the generator generates the basic functions for adding, editing and removing entries, there is a reference to the models package inside the generated code. If the generator runs with the flag `--skip-model` the code can cause compiler errors, because of a missing model definition.

**Comment by as27** [comment]
I just made a version for `--skip-model` and the error is still there. So I think it is not that flag. It is really inside the `RUN buffalo test -race`. But I do not understand what happens there.

**Comment by as27** [comment]
I can reproduce the error now at a own repository and inside the test that line (https://github.com/gobuffalo/buffalo/blob/v0.8.0/generators/resource/resource.go#L37) `g.Add(makr.NewCommand(makr.GoFmt()))` does not make a `goimport` then the import path is not correct.

But if we know the base import path of the project we could generate the correct path inside the code. Is there a simple solution to find out the import path of the buffalo project?

**Comment by as27** [comment]
After adding the import path for the model ([commit](https://github.com/as27/buffalo/commit/3df58466e9d2edacabd8e818080c0cccfd85393f#diff-9c771dec48a95d0bf3c57c125e65e2f9) the error is still there. So it is not the import path. But that commit causes a real performance boost to the `goimport` step.

**Comment by markbates** [comment]
So here is my thoughts regarding all of this. 

I think `--skip-model` shouldn't generate any model stuff, and should generate the same resource stuff that it does today.

We should add a new flag, `--use-model`, that takes an existing model to use, so don't generate new model stuff like migrations, but generate the resource stuff with all the bells and whistles of talking to that model.

Finally, if no flag is passed, it should create the new model, like it does today, but also add all of the bells whistles of talking to the new model.

Does that all make sense?

**Comment by as27** [comment]
Now I know why the tests are failing, because the model is deleted here:
https://github.com/gobuffalo/buffalo/blob/master/Dockerfile#L45

If I delete this line there is another error:
```
models/user.go:38: undefined: validators in validators.StringIsPresent
models/user.go:39: undefined: validators in validators.StringIsPresent
```

But that when the model definition is needed inside the resource file the model should be not deleted.

So one solution to solve this is to delete the tests at line 52 and 53
https://github.com/gobuffalo/buffalo/blob/master/Dockerfile#L52

Another solution should be to correct the model generator that there will be no error inside the model that the generated model has not to be deleted in line 45. Maybe a new issue?

**Comment by as27** [comment]
I just found another solution. Moved the tests to the user model after `buffalo test -race` so the test just runs on the `--skip-model` part, which has no errors.

**Comment by as27** [comment]
With merge of #333 this issue can be closed.
