### ISSUE TITLE
Windows 10 new buffalo site sqlite3 "<no value>" in database.yml

### ISSUE THREAD

**Issue by michaelkacher** [gobuffalo/buffalo#336]
I am pretty new to buffalo, but I believe when I experimented with .7 and ran:
$ buffalo new coke --db-type sqlite3
I was able to immediately run the dev site.  Now I receive a 500 error.  Looking at my database.yml I see the following:

production:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}< no value >/theater_production.sqlite

After removing the "< no value >" I am to run as before.

**Comment by nathankerr** [comment]
Same results with buffalo 0.8.0, go1.8, macOS 10.12.3

0.7.4 used:

database: ./theater_production.sqlite

**Comment by markbates** [comment]
Thanks. The problem was actually at https://github.com/markbates/pop if you rebuild the Buffalo binary it will pick up the change and generate the sqlite configs correctly. Thanks.
