### ISSUE TITLE
Getting "Killed: 9" response from buffalo binary

### ISSUE THREAD

**Issue by carimura** [gobuffalo/buffalo#338]
simply followed the installation instructions and then ran `buffalo new` and i got the response:

> [~/workspace/go/src/github.com/carimura] # buffalo new
> Killed: 9

No commands work.

**Comment by markbates** [comment]
Can you please give some more info? OS? Results of `go env`? That sort of thing. Thanks.

**Comment by markbates** [comment]
https://gophers.slack.com/archives/buffalo/p1490777379178679

**Comment by markbates** [comment]
https://github.com/golang/go/issues/19734

This is apparently a bug with Go and an old version of MacOS.

**Comment by damienstanton** [comment]
This issue is closed, but in case it is helpful - rolling back from Xcode 8.3 to 8.2.1 followed by a re-`go get` resolved this for me.
