### ISSUE TITLE
Upgrade of gobuffalo and running go setup -u wants to reference a resolvers package that doesn't exist anymore

### ISSUE THREAD

**Issue by sreimer15** [gobuffalo/buffalo#339]
Hi.
I recently updated my go buffalo version by removing buffalo from $GOPATH/pkg and $GOPATH/src/github.com/gobuffalo and re running go get -u github.com/gobuffalo/buffalo/...
and on running go setup I get the following error.

`
=== Error! ===
buffalo: 2017/03/29 01:06:02 === exit status 1   
actions/render.go:8:2: cannot find package "github.com/gobuffalo/buffalo/render/resolvers" in any of:  /usr/local/go/src/github.com/gobuffalo/buffalo/render/resolvers (from $GOROOT)         /home/seanreimer/projects/go/src/github.com/gobuffalo/buffalo/render/resolvers (from $GOPATH)                 
 ======
`
Maybe there is some file that I didn't delete correctly referencing the old version?
Thank you for any help you can be!

**Comment by markbates** [comment]
There are some changes in your app you need to make. Here is a blog post that explains what has changed in the latest release. 

https://blog.gobuffalo.io/buffalo-v0-8-0-released-33f1786eadf
