### ISSUE TITLE
Patch for a new project, "buffalo new" cmd on windows 10

### ISSUE THREAD

**Issue by xenamorph** [gobuffalo/buffalo#340]
>cd $GOPATH\github.com\xenamorph
>buffalo new quick --db-type sqlite3 -f

The standard location for putting Go projects is something along the lines of "$GOPATH/src/github.com/host name\user name/./..." (adjust accordingly).

OS Win 10
$GOPATH=d:\gosrc\src

**Comment by markbates** [comment]
Can you explain this a bit more? I don't understand what you mean by "patch". There is no PR.

**Comment by xenamorph** [comment]
I can't create a new project in Windows with "buffalo new"

**Comment by markbates** [comment]
Looking at it, it looks like you're not in your `$GOPATH/src/github.com/...` folder, but rather in `$GOPATH/github.com/...` all Go projects need to be under `$GOPATH/src`. Try creating the project in under `$GOPATH/src/github.com/...` and it should work.

**Comment by xenamorph** [comment]
>D:\gosrc\src>echo %GOPATH%
d:\gosrc

>D:\gosrc\src>cd github.com

>D:\gosrc\src\github.com>buffalo new quick --db-type sqlite3 -f
Buffalo version 0.8.0

Oops! It would appear that you are not in your Go Workspace.

Your $GOPATH is set to "d:\gosrc".

You are currently in "D:\gosrc\src\github.com\quick".

The standard location for putting Go projects is something along the lines of "$GOPATH/src/github.com/Cheef\radex/quick" (adjust accordingly).

We recommend you go to "$GOPATH/src/github.com/Cheef\radex/" and try "buffalo new quick" again.

**Comment by markbates** [comment]
Ok. It looks like a capitalization issue. Definitely we can fix here. In the meantime, if you set your $GOPATH to start with `D:` instead of `d:` it should work.

**Comment by xenamorph** [comment]
Thank you, sorry for my bad english

**Comment by markbates** [comment]
No need to apologize. I don't use Windows, so it's hard for me to understand the problem. This should be relatively easy to fix in Buffalo.

**Comment by lanybass** [comment]
I just want create my project whereever I want. I don't want to modify my computer's name or user name to fit my Github's Username.
so if it's "We recommend .." ,so what if I unaccept . No choice for me ?
@markbates

**Comment by xenamorph** [comment]
That is unnecessary
markbates>> if you set your $GOPATH to start with D: instead of d: it should work.

**Comment by as27** [comment]
@lanybass when you use Buffalo you use Go. Then you don't have choice. Look here: [How to Write Go Code: Workspaces](https://golang.org/doc/code.html#Workspaces). The discussion about the GOPATH is a big thing in the Go community. 
But a Buffalo project is a Go project, so that project needs to follow the Go restrictions.
