### ISSUE TITLE
context.Logger().InfoF or Errorf does not have color

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#344]
Hi,

i realized all my logging does not have color on my mac terminal.
i can see color when it runs in green for this text:
=== Running: go build -v -i -o tmp/project-build (PID: 32828) ===

but all my context logger is in plain white text.
iam using black background terminal with white text

please advice

thank you

**Comment by markbates** [comment]
That's expected. It's a result of using `io.Multiwriter` to capture error output during development when building the binaries. We need to both display the error and capture it so we can should the build error later on. Unfortunately `io.Multiwriter` strips out color information. 

When running the final built binary, i.e. not using `buffalo dev`, colors should be rendered as expected.
