### ISSUE TITLE
Upgrading to V0.8X

### ISSUE THREAD

**Issue by SpencerCDixon** [gobuffalo/buffalo#346]
I wanted to upgrade my buffalo version to start playing around with V0.8 features and something odd is happening.

First I tried just re-running the `go get` command.  That didn't work so next I tried:

* `rm -rf gobuffalo`
* `rm ~/go/bin/buffalo`
* `go get ....`

Here is a screenshot of the output:
![screen shot 2017-03-30 at 11 52 36 am](https://cloud.githubusercontent.com/assets/7471018/24513509/5c938926-153f-11e7-855c-ebedf248442c.png)

It just keeps saying: `[1]    10500 killed     buffalo`

Any thoughts?

**Comment by markbates** [comment]
You are probably a victim of this:

https://github.com/gobuffalo/buffalo/issues/338

It's a known Go issue that happened with the recent update to MacOS. It's affecting a lot of Go binaries. 

I worked around it by downloading Xcode 8.2.1 and replace the one in my `/Applications` directory with it.

The Go team, I believe is working on a fix.
