### ISSUE TITLE
New Generator - Caddyfile

### ISSUE THREAD

**Issue by bscott** [gobuffalo/buffalo#355]
Create a Generator to create a Caddyfile

```
lovego.com, www.lovego.com {
        gzip
        tls golang@ilovegolang.com
        proxy / http://127.0.0.1:8080/ {
        }
}
```

**Comment by stanislas-m** [comment]
Same point as in #356, I think we can document it, but a generator for production matters seems a bit overkill to me.

**Comment by markbates** [comment]
I think this would be better suited as a plugin for buffalo, not part of the Buffalo project itself. Plugins are meant for exactly this type of extending of the project.

Documentation on how to write plugins can be found at [http://gobuffalo.io/docs/plugins](http://gobuffalo.io/docs/plugins).
