### ISSUE TITLE
New Generator - SystemD Unit

### ISSUE THREAD

**Issue by bketelsen** [gobuffalo/buffalo#356]
# /etc/systemd/system/gcon.service
[Unit]
Description=gophercon website
[Service]
PIDFile=/tmp/gophercon.pid-3000
User=www-data
Group=www-data
Environment=GO_ENV=production
Environment=POSTGRES_PASSWORD=SuperS3cretSquirr3l
WorkingDirectory=/root/go/src/github.com/gopheracademy/gcon
ExecStart=/bin/bash -c '/root/go/src/github.com/gopheracademy/gcon/gcon'
[Install]
WantedBy=multi-user.target

**Comment by stanislas-m** [comment]
Hum, maybe just providing a template in the documentation is enough? A production-dependent generator seems a bit overkill to me.

**Comment by markbates** [comment]
I think this would be better suited as a plugin for buffalo, not part of the Buffalo project itself. Plugins are meant for exactly this type of extending of the project.

Documentation on how to write plugins can be found at [http://gobuffalo.io/docs/plugins](http://gobuffalo.io/docs/plugins).
