### ISSUE TITLE
Investigate GopherJS integration

### ISSUE THREAD

**Issue by bketelsen** [gobuffalo/buffalo#358]
Pie in the sky - but would be nice to enable some basic GopherJS usage.  I'm going to experiment this week and see if it's something that's worth adding.

**Comment by markbates** [comment]
I think this would be better suited as a plugin for buffalo, not part of the Buffalo project itself. Plugins are meant for exactly this type of extending of the project.

Documentation on how to write plugins can be found at [http://gobuffalo.io/docs/plugins](http://gobuffalo.io/docs/plugins).
