### ISSUE TITLE
Create project issue

### ISSUE THREAD

**Issue by tingxin** [gobuffalo/buffalo#359]
Hi Mark Bates,
I am glad to see the buffalo such a so good go-web framework, but when i use it to create a project, i meet an issue, any idea? i use go version go1.8 darwin/amd64

<img width="1565" alt="screen shot 2017-04-05 at 15 36 32" src="https://cloud.githubusercontent.com/assets/6802222/24694835/10ea1748-1a16-11e7-9ab8-3d95d90c7193.png">

**Comment by markbates** [comment]
It looks like there's an issue with `npm init` have you tried googling the error? It's not a Buffalo issue.
