### ISSUE TITLE
generate a default .travis.yml file for new projects

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#36]

**Comment by briandowns** [comment]
Should there be a flag similar to `--db-type` for CI provider? e.g. `--ci-provider` and support Travis and Circle out of the box? Maybe add others depending on demand?

**Comment by markbates** [comment]
That seems like a good idea.

**Comment by briandowns** [comment]
I have a branch started to complete the default travis file but if the additional flag is an acceptable approach, I'd like to include that as well.  Also, was hoping for feedback on implementation: cobra command to generate the `buffalo g` flags mentioned above.

**Comment by markbates** [comment]
If there's only CI we don't need a flag, for now. When we want different CI files, then we can add a flag. 

There are plenty of examples of how to use flags in the cmd directory.

**Comment by briandowns** [comment]
I can add that flag functionality for different CI providers in this branch if you want.  Your call. :)

**Comment by markbates** [comment]
I'd love it if you feel comfortable enough generating files for other CIs!

**Comment by markbates** [comment]
Those two would be great! Wercker would be awesome as well,  if you can get to it.

**Comment by apaganobeleno** [comment]
@briandowns are you working on this one ? i have some time to give it a shot, but if you're working on it prefer you to complete it :)

**Comment by cdrx** [comment]
Is there an example of a working circle.yml or travis-ci.yml file?

**Comment by briandowns** [comment]
I'll try to get this pushed up today.

**Comment by stanislas-m** [comment]
Gitlab CI support could be cool too. :)

**Comment by markbates** [comment]
A wercker set up would be great too. These should be separate tickets though.

**Comment by apaganobeleno** [comment]
@markbates i started working on this the `.travis.yml` however when running the tests for the first time its panic'ing with:

```
--- FAIL: Test_HomeHandler (0.00s)
panic: could not locate box "../public/assets" [recovered]
	panic: could not locate box "../public/assets"
```

Should we remove the `.gitignore` from that folder or handle rice diferently when running tests ?
Also for the travis configuration, i'm assuming we should run migrations/setup database and run the tests with `buffalo test`, am i right ?

**Comment by apaganobeleno** [comment]
@markbates nevermind, i ended up creating the folder on the `.travis.yml`
