### ISSUE TITLE
colored logs

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#360]
hi,

sorry to raise this issue again, any possible way to solve this?
my eyes is looking at logs all day and its killng me...

**Comment by markbates** [comment]
What is the problem with the logs?

**Comment by u007** [comment]
lack of coloring and highlight support (bold/italic)
and would will be great if its alike uber/zap with line number indicator of the calling line

**Comment by markbates** [comment]
I would welcome a PR that made this happen.

**Comment by bigblind** [comment]
@bscott Are you still working on this? I'd love to take a look at what it'd take to implement this.

**Comment by markbates** [comment]
Actually this was solved the other day here: https://github.com/gobuffalo/buffalo/commit/71a39e46525fc61934c6ff0586ff55d264554afb
