### ISSUE TITLE
Resource generator should be able to generate JSON

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#365]
Currently the resource generator only generates HTML resources. It should be able to generate JSON resources as well.

A flag will be needed to do this:

```
$ buffalo g resource --type=json users name email
```

When generating a JSON resource, no template files should be generated, and instead of `r.HTML("template.html")` being used in actions it should be `r.JSON(model)`.

**Comment by stanislas-m** [comment]
@markbates I can take this one if you want.

**Comment by markbates** [comment]
that would be awesome!

**Comment by u007** [comment]
i have modified model_templates with this code:
```
func (a *{{.model_name}}) ToJSON() ([]byte, error) {
	res, err := json.Marshal(a.ToHash())
	return res, err
}

func (a *{{.model_name}}) ToHash() map[string]interface{} {
	res := map[string]interface{}{
		{{range $a := .model.Attributes -}}"{{$a.Names.Original}}":         {{if eq $a.Names.Original "created_at"}}ISOTimeFormat(a.{{$a.Names.Proper}}){{else if eq $a.Names.Original "updated_at"}}ISOTimeFormat(a.{{$a.Names.Proper}}){{else}}a.{{$a.Names.Proper}}{{end}},
		{{end -}}
	}
	return res
}

func ISOTimeFormat(pTime time.Time) string {
	if pTime.Year() <= 1 {
		return ""
	}
	return pTime.UTC().Format("2006-01-02T15:04:05")+"Z"//for utc
}
```
and also, ive replaced with my own command with copy of original code to generate reactjs+redux templates :)
