### ISSUE TITLE
go get on macOS Sierra exits with Killed: 9

### ISSUE THREAD

**Issue by jwyo** [gobuffalo/buffalo#371]
When calling buffalo from new install using 'go get -u github.com/gobuffalo/buffalo/buffalo' on macOS Sierra with 'go version go1.8 darwin/amd64', the program exits with Killed: 9.  Let me know if I can provide any other information or if I am just missing something...  Thanks in advance for the help!

**Comment by markbates** [comment]
This is a known issue with Go. https://github.com/golang/go/issues/19734

The best solution is to upgrade to Go 1.8.1 and rebuild your Go binaries.

**Comment by jwyo** [comment]
Yup, that worked.  Thanks!

**Comment by BiggerNoise** [comment]
Can you elaborate on "rebuild your Go binaries"? 

I have:
- updated to go 1.8.1 (via homebrew, not from source)
- done a go get -u for buffalo

I still get the killed: 9

Obviously, I missed something.

**Comment by markbates** [comment]
First, don't use the homebrew installer, it's the cause of a lot of issues, always use the official installers.

Second, doing a `go get -u` will only reinstall binaries if there are changes. The best thing to do is the following:

```
cd $GOPATH/src/github.com/gobuffalo/buffalo
go install -v ./buffalo
```

Repeat and rinse for all Go binaries that error like this.

**Comment by BiggerNoise** [comment]
Thanks for the information. I'm still having the issue, I'll try a few more things and let you know the outcome.

**Comment by BiggerNoise** [comment]
I've been away from the computer for a while; i just wanted to let you know that your instructions worked just fine and to say , "thanks!"
