### ISSUE TITLE
sqlite cant store image blobs

### ISSUE THREAD

**Issue by gedw99** [gobuffalo/buffalo#372]
matts sqllite driver has a bug in it in that it cant handle image blobs.

steps to reproduce:
Create a SQLite (or SQLCipher) database with a column type of integer,
then insert some non integer data in it.  For example, an image. :)

---

You should try this instead:

https://github.com/aebruno/whisperfish/blob/master/store/store.go

https://github.com/aebruno/whisperfish/blob/master/store/store.go#L30

so its using this SQL lite driver:
https://github.com/mutecomm/go-sqlcipher

**Comment by markbates** [comment]
That driver has a lot of bugs in it! I've been looking for a driver to replace it. I've replaced it with `go-sqlcipher` here https://github.com/markbates/pop/commit/dbfc018d6fca23c86d463571b92f6fc04fcd0f53

Hopefully that resolves a lot of issues we've had.

**Comment by gedw99** [comment]
Wow that was quick.
I will kick the tires on it
