### ISSUE TITLE
Remove or rebuild the apps in the examples folder

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#376]
The apps in the `examples` folder are really starting to show their age. They need to either be rebuilt or removed.

I like having them there, they also provide an extra layer of testing, but they are difficult to maintain.

**Comment by apaganobeleno** [comment]
@markbates WDYT about removing these and having [toodo](https://github.com/gobuffalo/toodo) as the sample app for buffalo ?

**Comment by apaganobeleno** [comment]
@markbates if we're planning to rebuild the sample apps we need to wait 'til 0.9.0 and the config folder change.

**Comment by markbates** [comment]
Yeah. That would makes sense.
