### ISSUE TITLE
migration with model

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#379]
hi,

is it possible to run a model oriented migration like:
```
var users models.Users
pop.Q(tx).Where("id > 5").All(&users)
for i := range users {
  users[i].DoSomething()
}
```

or anyway to allow migration to import modules and use them?

**Comment by markbates** [comment]
No. You execute pure sql in a migration though, if you want. 

I would recommend using a grift task for this sort of thing.

**Comment by apaganobeleno** [comment]
@markbates @u007 should we close this one ?

**Comment by u007** [comment]
any possible way to allow fizz to run a grift task?
sometimes there might be some migration value, then running a task, then continue with the rest of the migration in one fizz file

**Comment by markbates** [comment]
Not currently, but it would be great to add support to `fizz` to allow it to run shell out and run a command. It would be pretty easy to add. If anyone wanted to do it, this would be the starting place: https://github.com/markbates/pop/blob/master/fizz%2Fbubbler.go ;)

**Comment by markbates** [comment]
@u007 I believe this PR https://github.com/markbates/pop/pull/68 solves this issue for you.

**Comment by u007** [comment]
nice, thank you :)
