### ISSUE TITLE
Default routes listing link to the route

### ISSUE THREAD

**Issue by apaganobeleno** [gobuffalo/buffalo#381]
I've been thinking that adding a link to the list of routes (it could be the same path column) could help in cases you miss-typed the URL in development.

So instead of:
<img width="959" alt="screenshot 2017-04-12 13 28 36" src="https://cloud.githubusercontent.com/assets/645522/24973342/0283836a-1f84-11e7-86e5-fc2f073ddaa6.png">

We render something like:

<img width="987" alt="screenshot 2017-04-12 13 30 09" src="https://cloud.githubusercontent.com/assets/645522/24973417/3b233260-1f84-11e7-8396-45a4d8e47883.png">

@markbates thoughts ?

**Comment by markbates** [comment]
I like it, but half of them aren't valid links.

**Comment by apaganobeleno** [comment]
#trueStory, i'll close it for now, you're right, it could be handy for non-variable-inside routes but for the rest will be invalid.
