### ISSUE TITLE
Handle multiple types for resources

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#389]
XML, JSON... why not both? :)

This mean we should find a way to discriminate rendering. Maybe we can suffix the url (with .xml or .json), or use Content-Type HTTP header.

**Comment by markbates** [comment]
I like that. Maybe we could have a `render.Interface` function or something better named that uses the content type to render non-HTML requests appropriately like xml or JSON.

**Comment by stanislas-m** [comment]
@markbates, I've pushed a new branch about this: https://github.com/gobuffalo/buffalo/tree/389-auto-resources

I think it's almost done, but I'm struggling with something:
* On some cases, we have to add a flash message and redirect the user after the action (in the HTML case) ; but when we use JSON/XML endpoints, the result must be shown on the same page: how can we have the auto mode to make either a redirect or a rendering, according to the mime type?
For the flash message, it can be overwritten by the user, so, maybe it's not a problem to keep it, but not using it. In a stateless condition (as an API), I don't know the behavior...
* In HTML cases, we need to give the data to the context, to make it available in the template. That's not the case with the JSON, and we need to define a name to give to the context. From now, it has to be defined outside the auto handler, and it leads the user to duplicate the code.

What's your opinion on this?

**Comment by stanislas-m** [comment]
@markbates, I still need your input on this one. :)

**Comment by markbates** [comment]
@stanislas-m I wonder if this should be done here https://github.com/gobuffalo/x/tree/master/responder thoughts?

**Comment by stanislas-m** [comment]
@markbates, sure! I'll take a look on this. :)

**Comment by made2591** [comment]
Hi! This is closed, right?

**Comment by markbates** [comment]
It’s actually still open. I forgot all about this idea. It’s not the same as the resource generator. The idea is that you could do something like `c.Render(200, User{})` or something like that and it would render it correctly based on the content type of the request. 

It’s a great idea I would love to revisit.

**Comment by made2591** [comment]
If it's ok I will have a look, maybe I can handle this ^^ I'm not a buffalo or golang expert, but it seems not so difficult to me - I will be wrong for sure. I would like to contribute. ps: I worked a lot with goa.design in the past, maybe could be useful to someone else for something else...

**Comment by markbates** [comment]
Please! I’d love to see someone take the reigns.
