### ISSUE TITLE
Proposal: Add a `config` package

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#394]
I believe it is time to add a `config` package to Buffalo applications.

With the current package structure it is difficult, if not impossible, to access things like `actions.App()` from a sub-package.

For example, if you want to have `actions/admin` you can not access anything in the `actions` package, like `App()` or any other settings because of cyclical dependencies.

This proposal is to add a `config` package where common configurations can be placed.

I suggest moving the following current files into that new package:

```
actions/app.go    -> config/app.go
actions/render.go -> config/render.go
database.yml      -> config/database.yml
```

In the future this package is also where you would configure things such as mail and background workers.

It is expected that this package does not import any other packages from inside the application.

This is a big change, and I would appreciate any feedback, concern, or other comments from the community.

**Comment by apaganobeleno** [comment]
@markbates adding my comment also here from #382 

I agree on moving into config, that was my second option to solve this, but at that time i was working on this i thought on backwards compatibility as a MUST, i think one thing to keep in mind with this change is some sort of migration guide so, old versioned (beta) app builders can move to 0.9.0.

Overall this provides a level of separations that will allow us to support nested resources without generating much (maybe duplicated) code, i agree on this one.

**Comment by bketelsen** [comment]
+1 sounds right by me.

**Comment by as27** [comment]
I like the idea, because the code will be very readable.

main.go would look like:

    log.Fatal(http.ListenAndServe(fmt.Sprintf(":%s", port), config.App()))

config/app.go would look:

	app.GET("/", actions.HomeHandler)

	usersResource = actions.UsersResource{&buffalo.BaseResource{}}
	app.Resource("/users", usersResource)

I think that looks really good.

Something what is missing inside the proposal would be a clear definition of the new action package. After puting `app.go` and `render.go` into config, the action package should just be used for defining:

* Handlers
* Resources
* custom middlewares

This is just a suggestion, but when changing the logic of the action package by moving some functions to another package it would make sense to define the new borders of actions.

**Comment by markbates** [comment]
@as27 agreed. The `actions` package would now become where all `buffalo.Handler` and `buffalo.Resource` types are defined. It would also house sub-packages like `actions/admin` or `actions/api/v1`, that sort of thing.

**Comment by markbates** [comment]
So, when investigating this, I ran into our old friend in Go, cyclical imports. :( Here's how:

The `actions` package needs the render engine configured in `config`. The `config` package needs the `actions` to map them to the router. 

Open for good ideas on how to handle this without getting all sorts of crazy messy.

**Comment by as27** [comment]
I would say the the routes definition should be not inside `config`. Maybe an additional package `routes` would make sense. 

The tree would be:

`config` ->`actions` -> `routes`

Configuration like render is used inside `actions`. And the handlers and resources defined there are used inside `routes`.

**Comment by markbates** [comment]
Playing around with this, and here's the tree structure that I have working so far:

```
coke
├── actions
│   ├── actions.go
│   ├── actions_test.go
│   ├── home.go
│   └── home_test.go
├── config
│   ├── config.go
│   └── render.go
├── database.yml
├── grifts
│   ├── routes.go
│   └── seed.go
├── locales
│   └── all.en-us.yaml
├── main.go
├── models
│   ├── models.go
│   └── models_test.go
├── routes
│   └── routes.go
└── templates
    ├── _flash.html
    ├── application.html
    └── index.html
```

I have a branch that will generate a new Buffalo app, successfully, with this structure. There's a lot of work to get all of the other generators and such working, but it's a start. I want to get feedback on this, before I move too much further down this path.

**Comment by markbates** [comment]
I think there's room to move `locales` and `database.yml` into the config directory as well.

**Comment by markbates** [comment]
I've decided not to pursue this idea, for now. I've been playing with it over the course of this dev cycle, and I don't like it. I feel like it adds too much complexity, and doesn't add enough value. I'm open to revisiting this prior to `1.0`, but for now, I don't think we need this.
