### ISSUE TITLE
Token based user authentication? 

### ISSUE THREAD

**Issue by ninja9158** [gobuffalo/buffalo#399]
HI,
Will consider integrating jwt middleware?

**Comment by markbates** [comment]
Absolutely!

**Comment by ninja9158** [comment]
HI!
Will it be supported in the near future?

**Comment by markbates** [comment]
Oh, I thought you were offering to write it. In terms of time line, that's the fastest way to get it added.

**Comment by stanislas-m** [comment]
@ninja9158 I'm just a bit curious, what do you think this middleware should do? Just extracting the token and provide it to the context, or something more advanced?

**Comment by Nearhan** [comment]
@ninja9158 @stanislas-m @markbates I would like to know the context as well. According to https://jwt.io/  there is this library https://github.com/SermoDigital/jose implements the standard algorithms.

**Comment by glycerine** [comment]
Thanks for GoBuffalo! I'm just discovering it now.

I think the most mature jwt library for go is this one
https://github.com/dgrijalva/jwt-go

and there are several middleware choices that already integrate it... to mention a few

https://github.com/labstack/echo  (https://echo.labstack.com/)

https://github.com/InVisionApp/rye

https://github.com/auth0/go-jwt-middleware

Has Buffalo taken an opinion on middleware?

**Comment by markbates** [comment]
We haven't done one yet, I also prefer the jose library, but that's my personal preference. I would love to see someone sketch out what this would look like.

**Comment by glycerine** [comment]
> We haven't done one yet, I also prefer the jose library, but that's my personal preference. I would love to see someone sketch out what this would look like.

Just to clarify, when you say "haven't done one yet", @markbates are you saying Buffalo hasn't picked a middleware?  I'd like to do a little project to get familiar with the internals of Buffalo, perhaps I could experiment with adding one.

**Comment by markbates** [comment]
@glycerine yeah, we don't currently have a JWT auth middleware. Would absolutely be open to a PR for it! :)

**Comment by glycerine** [comment]
More generally, beyond just jwt, is there a larger middleware framework currently in use?

**Comment by markbates** [comment]
Nope. Middleware is really straightforward. http://gobuffalo.io/docs/middleware I would recommend probably putting it in it's own package under the middleware package. That's what we've been doing with some of the more complex pieces of middleware.

**Comment by TheCrealm** [comment]
Im currently plan to build an authentication and authorization toolset for my project. There i want to use jwt. So maybe i could PR my jwt middleware when its ready.

More generally, is there any discussion to implement authentication and authorization tools (maybe with goth integration)? I need this in literally every project.. so now i want to bring up generators for this (like Devise@Rails) with a buffalo plugin.

**Comment by stanislas-m** [comment]
@TheCrealm, maybe you can use something like that, so you don't need to reinvent the wheel? https://github.com/ory/fosite

**Comment by TheCrealm** [comment]
That looks great. Maybe i will also use this :) But for now im more focused for fast development with buffalo. 

My first prototype simply implements password authentication like in this example https://github.com/gobuffalo/authrecipe

For better usage i try to implement my custom context which has helper Methods for User Model Access and Permissions. So in my actions i only have to use "if c.HasPermission("foo.bar")" to check if a user is logged in, set user in context and validate his permissions. 
In the background it will check several configured providers like database, goth or fosite .. also with jwt tokens. If you have a better idea for my use case please say.. im realatively new to golang and buffalo in general :)

Thanks

**Comment by otraore** [comment]
Any updates on this?

**Comment by markbates** [comment]
@otraore a PR for this was just merged and will be in the next release.
