### ISSUE TITLE
Command failing on MacOS Sierra 10.12

### ISSUE THREAD

**Issue by nubunto** [gobuffalo/buffalo#404]
Hi peeps!

What an amazing project! I was trying to get on top of building a project, but...

```
nubunto :: gobuffalo/buffalo/buffalo ‹master*› % buffalo
[1]    25165 killed     buffalo
```

Go version: `go version go1.8 darwin/amd64`

I compiled the binary inside the `github.com/gobuffalo/buffalo/buffalo` directory and same effect:
```
nubunto :: gobuffalo/buffalo/buffalo ‹master*› % ./buffalo
[1]    25207 killed     ./buffalo
```

Trying to trace system calls weren't successful as well...

```
nubunto :: gobuffalo/buffalo/buffalo ‹master*› % sudo dtrace -c ./buffalo 
dtrace: system integrity protection is on, some features will not be available

dtrace: failed to execute ./buffalo: unknown error
```

So I thought I reached out to you guys over here :smile:

Any thoughts?

**Comment by markbates** [comment]
https://github.com/gobuffalo/buffalo/issues/371  It's a known Go issue. Update to 1.8.1, rebuild your binaries, and you'll be all set.
