### ISSUE TITLE
Slow tests for `cmd/generate`

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#407]
Something is causing this package's tests to be really slow.

```
github.com/gobuffalo/buffalo/buffalo/cmd/generate	26.335s
```

**Comment by apaganobeleno** [comment]
@markbates should we move entirely to filetest here ?

**Comment by markbates** [comment]
probably. not sure why it's so slow though.

**Comment by apaganobeleno** [comment]
@markbates i can work moving this one to filetest, i will need to add a few features to filetest before having an equivalent filetest.

**Comment by markbates** [comment]
Awesome. Thanks. I suspect the cause of the slow down is to `go get` and `go imports` being called.

**Comment by apaganobeleno** [comment]
Closing this one given it has been covered by #439
