### ISSUE TITLE
treatment of field name '_id' is different between model and template.

### ISSUE THREAD

**Issue by sio4** [gobuffalo/buffalo#428]
Hello, I don't know this bug is still existing on current version. Anyway, when I generate a resource with following command, the result on model and template are different.

```
$ buffalo g resource user name email user_id icon_url
<...>
```

for model,
```
type User struct {
    ID           uuid.UUID `json:"id" db:"id"`
    CreatedAt    time.Time `json:"created_at" db:"created_at"`
    UpdatedAt    time.Time `json:"updated_at" db:"updated_at"`
    Name         string    `json:"name" db:"name"`
    Email        string    `json:"email" db:"email"`
    UserID       string    `json:"user_id" db:"user_id"`
    IconUrl      string    `json:"icon_url" db:"icon_url"`
}
```

for template,
```
<...>
<p>
  <strong>UserId</strong>: <%= user.UserId %>
</p>
<p>
  <strong>IconUrl</strong>: <%= user.IconUrl %>
</p>
<...>
```

currently I use e210597b371e6f6aed85b9d34d7d20f69314e72d

**Comment by markbates** [comment]
It's definitely still a bug. Thanks. @stanislas-m care to have a crack at this one?

**Comment by stanislas-m** [comment]
@markbates, I'll take a look on this this weekend.

**Comment by sio4** [comment]
OK, Thanks for your consideration. Than, If I manually change from one to the other, finally which one is the goal? UserID? or UserId?

**Comment by markbates** [comment]
`UserID` is the correct one, that's the idiomatic Go casing.

**Comment by sio4** [comment]
Thanks for response.

**Comment by markbates** [comment]
Fixed with https://github.com/gobuffalo/buffalo/pull/431
