### ISSUE TITLE
Worker package is not compatible with go1.7

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#448]
Running go 1.7:

```bash
$ go version
go version go1.7.1 linux/amd64
```

When I try to execute tests in package "worker" (current development branch), I have the following error:

```bash
# github.com/gobuffalo/buffalo/worker
./simple.go:73: undefined: time.Until
```

According to this commit (https://github.com/golang/go/commit/67ea710792eabdae1182e2bf4845f512136cccce), the Until function was added in go 1.8.

**Comment by markbates** [comment]
Yes, the developer branch now requires 1.8. It's not just that, but some other stuff around server context that also requires 1.8.

**Comment by stanislas-m** [comment]
@markbates, in this case, maybe we should close this one? https://github.com/gobuffalo/buffalo/issues/213

**Comment by markbates** [comment]
Not sure why we would close that ticket. It's still an open issue getting GAE support.

**Comment by stanislas-m** [comment]
Well, maybe I'm a bit confused, but Buffalo should work on GAE on the flexible env from now. For me, the remaining issue was about the standard env, which still needs Go 1.6, but you said the new Buffalo requires Go 1.8.

**Comment by markbates** [comment]
Buffalo should work on flex, yes, the goal, however, is to get it work on standard. We're still waiting for standard to get updated so we can actually work on GAE support. GAE won't go to 1.7 next it will jump to 1.8. Once they do that we'll start working on GAE support.

**Comment by stanislas-m** [comment]
Okay, I understand now. :) Thanks!
