### ISSUE TITLE
No Benchmark ? Seriously !

### ISSUE THREAD

**Issue by rebootcode** [gobuffalo/buffalo#490]
Hello Gophers,

Currently I am using gramework and get-ion ( earlier go-iris ) , but i am seriously surprised to see no benchmark has been published.

Well it completely depends on author , but providing no benchmark and being stupidly arrogant on it . Just put person under fool category. Why do you think below site exists :-

1. https://benchmarksgame.alioth.debian.org/
2. https://www.techempower.com/benchmarks/

There is no doubt, go-buffalo is rising star in golang and it seems to quicken development too, but without  benchmark , it looks like all novice programmer are jumping in and using the framework.

**Comment by markbates** [comment]
Yeah, seriously. No benchmarks. Here's why http://metabates.com/2017/03/03/youre-benchmarking-the-wrong-thing/

If you want benchmarks, go for it, no one is stopping you. I won't be doing them. They're subjective, fraught with bias and really don't prove anything. If Buffalo does not fit your style, then that's cool, it's not for everyone. Buffalo is about developer speed, not "raw" speed. It's plenty fast, it is Go after all. 

So whether you like it or not, that's up to you. There will never be any "official" benchmarks for benchmarks. Sorry.

**Comment by rebootcode** [comment]
Loosing usability ? https://github.com/kataras/iris  - Has not loose usability and stands with 700+ fork and 7000+ star

Moreover, it looks like your blog is not using buffalo too and running on hugo ?

Anyways, Just like your comment "will never be any official benchmarks" - "Will never use go-buffalo" .

Thanks & Sorry for being rude , but i felt this was need of hour , for some one ignoring lifeline called "benchmark".

Cheers

**Comment by azzuwan** [comment]
@rebootcode looks like your favorite framework has turned it's back on it's users. Kataras had just put iris in deprecated mode.

**Comment by rebootcode** [comment]
@azzuwan - IRIS has been acquired as it says, "well good things get sold" and i respect what author has done for his hard work. 

Though , there are fork, that are being maintained, But you still may not require any more, once you starts understanding framework and updating code your self. 

Great things comes with great price - One has to live with it.

Cheers
