### ISSUE TITLE
Pagination and auto-generated route functions

### ISSUE THREAD

**Issue by shendaras** [gobuffalo/buffalo#501]
Currently, attempting to alter the base index.html of a generated resource to handle pagination requires the template to appear something like below (ex. uses an 'article' resource):

```html
<li>
  <a href="<%= articlesPath() %>?page=<%= page %>"><%= page %></a>
</li>
```

Elsewhere, in the edit.html or show.html other template functions are mentioned which take a map argument. 

```html
<a href="<%= articlePath({ article_id: article.ID }) %>"
```

It would be nice to utilize that syntax when adding in other parameters, like the *page* to view, instead of writing out the URL piecemeal as above.

**Comment by apaganobeleno** [comment]
hey @shendaras thanks for reporting this one, i'll work on this one and keep you posted on its progress.
