### ISSUE TITLE
Make Routes in help clickable

### ISSUE THREAD

**Issue by corylanou** [gobuffalo/buffalo#509]
It's awesome that you get a list of routes when you develop.  it would be cool if those routes had a clickable path to quickly navigate to those routes.

**Comment by apaganobeleno** [comment]
@corylanou i think @markbates and i discussed this one before, i was wanting to add these links but Mark made me notice most of the links there will be to non-GET routes, so we thought by that time it didn't make much sense.

@markbates thoughts on this ? should we add these links ?

**Comment by tsauter** [comment]
it would be nice if all GETs are clickable. This will help to jump to the resources. All other routes should be then accessible form there.
