### ISSUE TITLE
How to start app at 0.0.0.0:3000?

### ISSUE THREAD

**Issue by jonahfang** [gobuffalo/buffalo#515]
I run buffalo application inside docker container,  I want to do like this:

```
app := actions.App()
log.Fatal(app.Start("0.0.0.0:3000"))
```

**Comment by markbates** [comment]
Just edit the main.go to do what youd like.

**Comment by jonahfang** [comment]
But I got error like this:

```

Starting application at 0.0.0.0:3000
time="2017-07-14T07:55:46+08:00" level=error msg="listen tcp: address :0.0.0.0:3000: too many colons in address"
2017/07/14 07:55:46 listen tcp: address :0.0.0.0:3000: too many colons in address
buffalo: 2017/07/14 07:55:46 === exit status 1
time="2017-07-14T07:55:46+08:00" level=error msg="listen tcp: address :0.0.0.0:3000: too many colons in address"
2017/07/14 07:55:46 listen tcp: address :0.0.0.0:3000: too many colons in address
```

**Comment by jonahfang** [comment]
@markbates any suggestions?

**Comment by markbates** [comment]
It looks like there is hard coded : in there https://github.com/gobuffalo/buffalo/blob/master/app.go#L38 it's a bug. The workaround would be to not use the start method and write your own until the next release.

**Comment by jonahfang** [comment]
But I run the buffalo app inside container(MacOS), how to browse the first page?

**Comment by markbates** [comment]
If you're using docker for mac you should be able to just hit local host:3000 also, you shouldn't need to bind it to 0.0.0.0 it should work out. The box as is.

-----------
Mark Bates

**Comment by jonahfang** [comment]
I use docker toolbox not docker for mac, so I cannot use localhost:3000.

**Comment by markbates** [comment]
I don't know toolbox. Sorry. I can't really help with that. Sorry.

**Comment by jonahfang** [comment]
Docker toolbox: <https://www.docker.com/products/docker-toolbox> use docker-machine, I must use url like http://192.168.99.100:3000 to launch the first web page where 192.168.99.100 is the IP address of the docker-machine vm.

**Comment by stanislas-m** [comment]
@jonahfang, try to use Start without ip:
``` go
app := actions.App()
log.Fatal(app.Start("3000"))
```
It should bind on 0.0.0.0 by default, so it will listen on http://192.168.99.100:3000 too.

**Comment by jonahfang** [comment]
@stanislas-m thanks for reply. I got 500 error like this:

```
Error Trace

dial tcp 127.0.0.1:5432: getsockopt: connection refused
could not create new transaction
vendor/github.com/markbates/pop.newTX
/go/src/vendor/github.com/markbates/pop/tx.go:26
vendor/github.com/markbates/pop.(*dB).Transaction
/go/src/vendor/github.com/markbates/pop/db.go:10
vendor/github.com/markbates/pop.(*Connection).NewTransaction
/go/src/vendor/github.com/markbates/pop/connection.go:126
vendor/github.com/markbates/pop.(*Connection).Transaction.func1
/go/src/vendor/github.com/markbates/pop/connection.go:105
vendor/github.com/markbates/pop.(*postgresql).Lock
/go/src/vendor/github.com/markbates/pop/postgresql.go:146
vendor/github.com/markbates/pop.(*Connection).Transaction
/go/src/vendor/github.com/markbates/pop/connection.go:119
vendor/github.com/gobuffalo/buffalo/middleware.glob..func1.1.1
/go/src/vendor/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:29
vendor/github.com/gobuffalo/buffalo/middleware/csrf.glob..func1.1
/go/src/vendor/github.com/gobuffalo/buffalo/middleware/csrf/csrf.go:111
```

**Comment by jonahfang** [comment]
It is the database config error, I will replace it with sqlite3.

**Comment by jonahfang** [comment]
@stanislas-m , thank you very much, it works now!

**Comment by stanislas-m** [comment]
@jonahfang, no problem!
