### ISSUE TITLE
Environment variables in .buffalo.dev.yml?

### ISSUE THREAD

**Issue by ianwalter** [gobuffalo/buffalo#516]
Where should users put local project environment variables? 
I'm using a .env file and github.com/joho/godotenv right now but it doesn't seem to work with Envy.
I think it might be nice if the dotenv functionality was added to Envy or if .buffalo.dev.yml
had a `environment` section (like a docker-compose.yml).

**Comment by markbates** [comment]
@ianwalter I've added a ticket for envy to support `.env` files. So I'm closing this ticket in favor of that ticket.
