### ISSUE TITLE
[Question] showing sql queries when testing or log to test.log

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#519]
hi,

how do i force test environment to generate log/test.log?
LogDir in opts does not work

thanks

**Comment by markbates** [comment]
So Buffalo uses https://github.com/sirupsen/logrus under the covers. So you can either create a new logger:

```go
app = buffalo.Automatic(buffalo.Options{
  Env:         ENV,
  SessionName: "_toodo_session",
  Logger: ....
})
```

or you can set the output to something else:

```go
App().Logger.Out = someFile
```

**Comment by u007** [comment]
hi @markbates 
where do i find the code that prints out [POP] sql sattements in log?

**Comment by u007** [comment]
iam getting this when callling
```
App().Logger.Out = file
```
```
App().Options.Logger.Out undefined (type buffalo.Logger has no field or method Out)
```

**Comment by markbates** [comment]
Sorry, my bad. The logger is an interface, so you'd have to cast it.

**Comment by u007** [comment]
Do you want me to submit a uber-go/zap version of buffalo logger ?
it has coloring and can support multiple output

**Comment by ajoses** [comment]
> Sorry, my bad. The logger is an interface, so you'd have to cast it.

Hi,

I'm trying to log to file, I found this solution, however, I'm unable to do it, this is my last attemp:

		fieldLogger := app.Logger.(logrus.FieldLogger)
		logg := fieldLogger.(*logrus.Entry)
		logg.Logger.SetOutput(os.Stdout)

but after running it I get a message:
panic: interface conversion: buffalo.logrusWrapper is not logrus.FieldLogger: missing method WithField

I'm relative new to golang and I know it something about the interfaces, but I don't get it yet. 

Any advice would be helpful

Thanks, awesome project!

Arnulfo José
