### ISSUE TITLE
Demo/Example Buffalo Application

### ISSUE THREAD

**Issue by corylanou** [gobuffalo/buffalo#520]
We should create another repo which is a demo/example app of how to use many of the buffalo features:

- [ ] Basic Forms
- [ ] Flash Messages
- [ ] Mailers
- [ ] Workers

We can add to the list but this is just a quick list off the top of my head.  Documentation is great, but nothing beats examples.

**Comment by gose** [comment]
Or extend https://github.com/gobuffalo/toodo

**Comment by markbates** [comment]
We do have this page http://gobuffalo.io/docs/examples to keep track of these sorts of things.

**Comment by bscott** [comment]
I think we can close this, the examples page shows quite a bit of usage.

**Comment by corylanou** [comment]
agreed, I didn't know about the demo app.  Guess I should rtfm :-).
