### ISSUE TITLE
Buffalo dev runtime error upon trying to access local host page

### ISSUE THREAD

**Issue by lucasmorgan** [gobuffalo/buffalo#521]
![image](https://user-images.githubusercontent.com/27509053/28228325-09805186-68ac-11e7-83cc-bed002666017.png)

after I use the buffalo dev command the server starts but as soon as I try to refresh the localhost:3000 page, I get the runtime error shown in the picture. Does anyone know what could be causing this?
I am on a windows machine

**Comment by markbates** [comment]
It looks like you have a `nil` session, but I'm not sure why that is. Do you have any reproduction steps you can add to help us figure it out?

**Comment by lucasmorgan** [comment]
I had to change the name of the webpack,config.js file in order to get around the buffalo dev fails to start with Unknown error, as shown in the the troubleshooting section on gobuffalo.io, but other than that have made no changes to the project generated by the buffalo new command

**Comment by markbates** [comment]
Can you give me more info about your environment? `go version` `go env`, etc...

It looks like you're getting a `nil` session, which according to the docs for https://github.com/gorilla/sessions/blob/master/store.go#L79 should never happen.

I'm not a windows person, but trying a new app on my bootcamp partition I had no problem with either `webpack.config.js` or starting the server.

According to the screen shot it looks like you're using `v0.9.1` can you try upgrading to `v0.9.1.2` and see if that helps?

**Comment by lucasmorgan** [comment]
I just updated and tried it, I was no longer getting the Buffalo Dev failing to start with Unknown Error, but as soon as I refresh the page I am still getting the nil  session. The screenshot has all the info about my environement
![screenshot 6](https://user-images.githubusercontent.com/27509053/28323623-5ecd1162-6ba7-11e7-879f-7199ac331db0.png)

**Comment by markbates** [comment]
Ok. Still trying to figure out why, but we'll get there! Like I said, I've never seen this and according to the Gorilla docs, it should never happen, but here we are. :)

**Comment by lucasmorgan** [comment]
Also as a side note, I downloaded and ran the simple Too Do app with no errors but haven't been able to run a project that was generated on my machine without getting the nil session

**Comment by lucasmorgan** [comment]
I managed to get around the bug and get the server to start! The bug has to do with the different paths in windows and the way you create the project

**Comment by apaganobeleno** [comment]
so @markbates i'll create a couple of bugs related with @lucasmorgan issue, those are mostly related with windows backslashes and the way we handle them when generating a new app.
