### ISSUE TITLE
Mac issue

### ISSUE THREAD

**Issue by radutopala** [gobuffalo/buffalo#524]
Installed via `go get -u -v github.com/gobuffalo/buffalo/buffalo`, then running `buffalo` gives `Killed: 9`.

I'm on `go version go1.8.3 darwin/amd64`.

**Comment by markbates** [comment]
This is a Go issue. Rebuild your binaries making sure you are at least `1.8.1`: http://gobuffalo.io/docs/troubleshooting

```
$ go install -v github.com/gobuffalo/buffalo/buffalo
```

**Comment by radutopala** [comment]
@markbates Just found #338.. tx
