### ISSUE TITLE
Documentation needs more informations

### ISSUE THREAD

**Issue by rof20004** [gobuffalo/buffalo#556]
I searched and not found:

What is a resource?
What is an action?

How to create only a REST api?

Thanks.

**Comment by u007** [comment]
it is alike rails
GET /users
POST /users
PUT /users/{id}
DEL /users/{id}

you may see the route when you open the browser to localhost:3000/

action are controller functionality that get executed when certain routes is being accessed

**Comment by rof20004** [comment]
Thanks @u007 

My last question is: How to create only a REST api?

**Comment by stanislas-m** [comment]
@rof20004 you can use the `--api` flag of the `buffalo new` command.

**Comment by rof20004** [comment]
@stanislas-m Thanks for answer, I tested with this command, but it generates views too, I want only to generate Go files, If is not possible, ok.

**Comment by markbates** [comment]
@rof20004 the `--api` flag is for the `buffalo new` command, and doesn't generate any templates or asset files. If you're trying to create a new resource and want it to be `JSON`, and not have views you need to pass the `--type=JSON` flag to the `buffalo generate resource` command.

All of the commands can be run with `--help` to find out what flags they take, see examples, and see if there are sub-commands.

For example running `buffalo generate resource --help` generates the following in `v0.9.5`:

```
Generates a new actions/resource file

Usage:
  buffalo generate resource [name] [flags]

Aliases:
  resource, r

Examples:
$ buffalo g resource users
Generates:

- actions/users.go
- actions/users_test.go
- models/user.go
- models/user_test.go
- migrations/2016020216301234_create_users.up.fizz
- migrations/2016020216301234_create_users.down.fizz

$ buffalo g resource users --skip-migration
Generates:

- actions/users.go
- actions/users_test.go
- models/user.go
- models/user_test.go

$ buffalo g resource users --skip-model
Generates:

- actions/users.go
- actions/users_test.go

$ buffalo g resource users --use-model users
Generates:

- actions/users.go
- actions/users_test.go

Flags:
  -h, --help                help for resource
  -n, --model-name string   allows to define a different model name for the resource being generated.
  -s, --skip-migration      sets resource generator not-to add model migration
      --skip-model          makes resource generator not to generate model nor migrations
      --type string         sets the resource type (html or json) (default "html")
  -u, --use-model string    generates crud options for a model
```

**Comment by rof20004** [comment]
@markbates 

Well, sorry, I did not saw this part in documentation

--type string         sets the resource type (html or json) (default "html")

Thanks for answer and sorry for wasting your times.

**Comment by markbates** [comment]
No worries, you didn't waste anyones time. Clearly more/better docs are needed. Happy to help.
