### ISSUE TITLE
Templates and migrations are bundled in binary with the `-e` flag

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#567]
When using the `-e` flag to build a binary it appears that all `packr` boxes are being ignored by the build process. Things like templates, migrations, etc... should always be in bundled in the binary. Assets are the only thing that should be excluded in the `-e` flag.

Related to #378

**Comment by stanislas-m** [comment]
@markbates, I can take this one.

**Comment by markbates** [comment]
@stanislas-m it's all yours! :)
