### ISSUE TITLE
Cannot install on windows 7 x64

### ISSUE THREAD

**Issue by Coccoonx** [gobuffalo/buffalo#574]
Hello,

It's been a while I'm trying to install buffalo on windows env but I cannot achieve.

I followed steps for go installation succesfully. But when I run 

`go install -v github.com/gobuffalo/buffalo/buffalo`

I have this error:
```
github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
```

I tried desperatly to install gcc (using [this](http://preshing.com/20141108/how-to-install-the-latest-gcc-on-windows/)) but at end I have this:
```
$ ../gcc-4.9.2/configure --program-suffix=-4.9.2 --enable-languages=c,c++ --disable-bootstrap --disable-shared
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-pc-mingw64
checking target system type... x86_64-pc-mingw64
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln works... yes
checking whether ln -s works... no, using cp -p
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... gawk
checking for libatomic support... no
checking for libcilkrts support... no
checking for libitm support... no
checking for libsanitizer support... no
checking for libvtv support... no
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/c/cygwin64/build-gcc':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details.
```

Please how can I get out of that?

Here is my `go env` : 

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Development\Projects\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

```

**Comment by barrongineer** [comment]
Try installing with [scoop](http://scoop.sh/).

Open PowerShell and run the following:
```
iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
scoop install gcc
```

**Comment by Coccoonx** [comment]
Thanks for suggestion.
Finally I use this [distro](https://nuwen.net/mingw.html) for gcc and installation goes well.

But Buffalo process takes too much time.  As you can on this screenshot, it takes around 11h to generate a new project. What can be the cause ?

![snapshot](https://user-images.githubusercontent.com/9346474/28912290-96127d48-782b-11e7-8762-aa3d81571697.jpg)

**Comment by hut8** [comment]
Looks like most of the time is spent with NPM. How long does that take without buffalo? That is, after you install node and just run `npm install` with the same package.json, how long does that take? How much RAM do you have and how much CPU is it using?

**Comment by Coccoonx** [comment]
Surely npm is the cause of that. It takes around one minute and more to log the first line of processing.
I run it on i5 CPU 2.5Ghz and 8GB Ram.
Finally I leave windows OS and I use linux. 
Now it is pretty interesting. 
Thanks for concerns
