### ISSUE TITLE
Problems with reserved SQL identifier

### ISSUE THREAD

**Issue by lukasmalkmus** [gobuffalo/buffalo#577]
So today I wanted to introduce a friend to buffalo and created a demo application:
`buffalo new test --db-type=sqlite3 --ci-provider=gitlab-ci --with-yarn`

I quickly created a new resource but did something, I usually wouldn't do:
`buffalo generate resource users name alter`
Is used german field names instead of english ones (`alter` is the german word for `age`).

As I opened up `localhost:3000/users` I was greeted with this error:
```
near "alter": syntax error couldn't select many SELECT users.alter, users.created_at, users.id, users.name, users.updated_at FROM users AS users LIMIT 20 OFFSET 0 []
```

Well, I guess this is because `ALTER` is one of SQLs keywords and it isn't escaped. Usually this doesn't affect me because I would never use anything else than english for field names, variable names, etc.

But this brought me to the following question: What if I was about to develop a buffalo app on top of an existing database which had this issue? Could I force `pop` to escape field names or would this require me to write these kinds of queries manually?

**Comment by markbates** [comment]
Closing in favor of https://github.com/markbates/pop/issues/113
