### ISSUE TITLE
Verbose log of workers

### ISSUE THREAD

**Issue by sio4** [gobuffalo/buffalo#579]
Hi,
Today I tried to use the simple worker. and I found the log level for "Performing" (worker/simple.go#L75) and "Completed" (worker/simple.go#L89) is Info. I think it can be Debug level because this logs need to be suppressed when I put this app in production.

**Comment by markbates** [comment]
A PR would be welcome for this.

**Comment by sio4** [comment]
OK, I will do this tonight.

**Comment by sio4** [comment]
Hi, @markbates I did branched from current development branch but it seems there is some missing commit not applied to development but exists on master. Can I do cherry pick as below before I start? This commit 5aa1cff287e97fd4f8e2169abbe3c6bd4bba9220 is for the path of `logrus`.

`git cherry-pick 5aa1cff287e97fd4f8e2169abbe3c6bd4bba9220`

**Comment by sio4** [comment]
Oops! I found the code on 'development' branch is also slightly outdated. Can I make PR against master for this? or Can I merge your works d7390f29d5c1626b7e7879433301fae3cad992ff and 093e7f3b6c626e85511e2f13335623075ad0f819 before I start?

**Comment by sio4** [comment]
I removed two of my own comments because it's my fault.
I just made simple changes on current development branch and requested a PR.

**Comment by sio4** [comment]
Thanks for merging it quickly. I hope it will get on the master soon.
Thanks.

**Comment by markbates** [comment]
Thank you! The next release is coming up soon. So it won't be a long wait. :)
