### ISSUE TITLE
(&DefaultContext{}).Redirect() has surprising format-string behavior

### ISSUE THREAD

**Issue by hut8** [gobuffalo/buffalo#586]
First, awesome framework. Thanks to everyone who's helped out with it 👍 

When I say surprising, I mean specifically for me, but I think others too 😄 

In a site I'm implementing, I'm using `c.Redirect(301,  someURL.Encode())`.  `someURL` includes query string parameters that need to be query-escaped (which ends up putting `%2F` strings in, among others).

I saw that `DefaultContext.Redirect()` looks like this:

```
http.Redirect(d.Response(), d.Request(), fmt.Sprintf(url, args...), status)
```

This causes the properly-escaped URL to be interpreted as a format string, which clearly does not work correctly. One of the parameters is encoded as:

```
http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fcallback%2Ffacebook
```

So the `%2F` ends up being interpreted as a floating point number.  That gives me this URL:

```
https://www.facebook.com/dialog/oauth?client_id=1234&redirect_uri=http%!A(MISSING)%!F(MISSING)%!F(MISSING)localhost%!A(MISSING)3000%!F(MISSING)login%!F(MISSING)callback%!F(MISSING)facebook&response_type=code&scope=public_profile
```

So my thought here is that maybe there should be a redirect that actually takes a `net/url.URL`, or alternatively, drop how it works currently and just take a single, non-format string with no extra parameters. It seems pretty risky a lot of the time, since just putting `%s` as the first argument won't escape parameters correctly. What are your thoughts?

**Comment by hut8** [comment]
I should probably add that `return c.Redirect(http.StatusTemporaryRedirect, "%s", authURL.String())` gives the expected result for me.

**Comment by markbates** [comment]
Instead of changing the signature of the method, or adding another one, could it be as simple as checking if there are any args? If there are args run it through fmt.Sprintf otherwise just use the string given. 

Would be easy to implement and a great first PR. :)

**Comment by hut8** [comment]
Great solution! I'll try to get to it today. Thanks for the opportunity 😄

**Comment by markbates** [comment]
Thanks for the find!

**Comment by hut8** [comment]
Looks like you beat me to it :smile: Thanks a bunch.
