### ISSUE TITLE
Provide way to mount other application

### ISSUE THREAD

**Issue by hut8** [gobuffalo/buffalo#602]
Hey there

I'm trying to integrate buffalo with an admin dashboard ([qor/admin](https://github.com/qor/admin)). Right now, it's almost impossible. This admin dashboard generates its own routes based on models that are passed in, so I would have to do something like this:

```go
	Admin := admin.New(&qor.Config{DB: DB})
	Admin.AddResource(&models.User{})
	Admin.AddResource(&models.Product{})
	Admin.AddResource(&models.OtherModel{})
	mux := http.NewServeMux()
	Admin.MountTo("/admin", mux)

	app.GET("/admin", buffalo.WrapHandler(mux))
	app.ANY("/admin/users", buffalo.WrapHandler(mux))
        app.ANY("/admin/products", buffalo.WrapHandler(mux))
        app.ANY("/admin/other_models", buffalo.WrapHandler(mux))
```

And even that wouldn't work correctly because of updates and deletes.

I also tried writing middleware that handled it separately, but it seems as though that can't work either, since the middleware isn't run if the route isn't found.

What about having an `app.Mount("/mount-point/", h http.Handler)` function, similar to how [Rails Engines](http://guides.rubyonrails.org/engines.html) work?

**Comment by markbates** [comment]
Definitely a good suggestion, in the meantime, this is how you would do it:

```go
func App() *buffalo.App {
	if app == nil {
		app = buffalo.Automatic(buffalo.Options{
			Env:         ENV,
			SessionName: "_liam_session",
		})

		app.GET("/", HomeHandler)
		app.ANY("/admin/{path:.+}", buffalo.WrapHandler(http.StripPrefix("/admin", Other())))
		app.ServeFiles("/assets", packr.NewBox("../public/assets"))
	}
	return app
}

func Other() http.Handler {
	f := func(res http.ResponseWriter, req *http.Request) {
		fmt.Fprintln(res, req.URL.String())
		fmt.Fprintln(res, req.Method)
	}
	mux := mux.NewRouter()
	mux.HandleFunc("/foo", f).Methods("GET")
	mux.HandleFunc("/bar", f).Methods("DELETE")
	return mux
}
```

**Comment by hut8** [comment]
Wow, that was fast. Thanks a bunch!

**Comment by markbates** [comment]
lol. you're welcome.

**Comment by sadegh-shahbazi** [comment]
qor-admin works in buffalo with authentication?
