### ISSUE TITLE
.env files support

### ISSUE THREAD

**Issue by dexafree** [gobuffalo/buffalo#606]
As now [envy supports loading .env files](https://github.com/gobuffalo/envy/pull/3), I'd like to add Buffalo the capability to automatically load them.

A great way of integrating it to buffalo would be allowing env overriding by GO_ENV:

* Common ENV settings that won't vary across environments: `.env`
* Environment dependant settings (ie: SMTP_USER): `.env.development`, `.env.production`, `.env.test`

That is: `.env` file will always be loaded, but also `.env.<ENVIRONMENT>` if it exists. The latter will be able to override any values that are needed (if a user wants it).

I was thinking about putting it on `buffalo.Automatic`, as `buffalo.New` allows for complete custom tailor made apps, and not every user that decides to go that path may want .env file support.

I also thought about putting it in `optionsWithDefaults`, but as it's called also in `buffalo.New` I don't know if it would be appropriate.

As I mentioned on the envy repo, take into account that globally initialized vars won't be affected by this, as the resolution of the value would be made at the start of the program, and that would imply that the env files have not been loaded yet. This could affect to variables like this:

```go
const PORT = envy.Get("PORT", "8080")
```

As this kind of values are resolved before any other call has been made (including the envy.Reload one).
But this cannot be solved by any means with any library, as it's a language behaviour.

Before starting to code it, I'd like for the proposal to be commented and approved.

**Comment by u007** [comment]
rails 5.1 recently added encrypted secret yml file. will be nice if we have this, then we dont need .env ?

```
bin/rails secrets:setup# generates config/secrets.yml.key and config/secrets.yml.enc
bin/rails secrets:edit# to edit config/secrets.yml and auto generate config/secrets.yml.enc
```

for more info:
http://www.starkandwayne.com/blog/rails-5-1-applications-can-be-a-lot-more-secretive-on-cloud-foundry-and-heroku/

**Comment by paganotoni** [comment]
@markbates what do you think about implementing application secrets ? should we go initially with .env support or go for secrets.yml?

**Comment by markbates** [comment]
I would need to see a proposal on how secrets would work and how they're different from a `.env` file.

**Comment by paganotoni** [comment]
Yeah, I don't have it very clear but would love to provide `.env`

**Comment by paganotoni** [comment]
@markbates i would love to get your feedback on #792 which is related to this one.

**Comment by paganotoni** [comment]
@markbates An addition to #792 would be to generate a SESSION_SECRET in the `.env` generated file WDYT?

**Comment by paganotoni** [comment]
Covered by #792
