### ISSUE TITLE
Build on Windows produces incorrect extension

### ISSUE THREAD

**Issue by hut8** [gobuffalo/buffalo#623]
I hate to be _that guy that uses Windows_ , but here I am 😄 

After creating a new project, if I run `buffalo b` on Windows, I get bin/my-project instead of bin/my-project.exe 

Looks like this line is at fault: https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/build.go#L422

It's a small bug; I believe that replacing `os.Getenv("GOOS")` with `runtime.GOOS` should work.

**Comment by markbates** [comment]
Any chance I could convince you to submit a PR for it? :)

-----------
Mark Bates

**Comment by hut8** [comment]
Indeed. Will submit shortly.
