### ISSUE TITLE
deployed binary cannot pass in argument to task

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#625]
buffalo v0.9.3

i just confirmed that the issue isnt about heroku.
i tried running this on my docker:
and my build app has been using heroku name(just naming)
./bin/app task user:create xxx

my task user:create is executed, but all arguments is missing
xxx wasn't passed in

**Comment by markbates** [comment]
This is fixed in the `v0.9.5` release coming in a few weeks. If you need this fix sooner, you can try out the https://github.com/gobuffalo/buffalo-xbuild plugin I'm working on, it has this fix in it.
