### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by TheDeadCode** [gobuffalo/buffalo#628]
Hello!

I'm sorry for my noobyness in advance, I'm a very recent go user

1. I noticed that Buffalo (Gorilla?) always cookies you, even if you're hitting the API. Is this expected behaviour? If so, how can we disable it?

2. Is there Lazy-SQL support? (Only connect/use the connection when an SQL query has to be made). Using no driver, I can easily reach 10,000 requests per second (our current use-case requires a minimum of 5.5k/s), although using any SQL driver, the rps drops to <2k/s. Most of our pages do not require SQL. Only a few of them require a query.

**Comment by markbates** [comment]
No need to apologized, they're great questions.

First, If you're doing an API, you probably want to use the `sessions.Null` session implementation:

```go
app = buffalo.Automatic(buffalo.Options{
      Env: ENV,
      SessionStore: sessions.Null{},
      ....
    })
```

As for the SQL question, if you remove the following line from `actions/app.go` it will stop putting a transaction on every request:

```go
app.Use(middleware.PopTransaction(models.DB))
```

That means, however, that there won't be a transaction in your context, `c.Value("tx")`, you'll need to access the `models.DB` connection directly.

Hopefully that should answer the questions. Feel free and re-open if not. Also, we have a great #buffalo slack channel on gophers.slack.com, you should join us there! :)
