### ISSUE TITLE
building linux binaries from the Mac with sqlite

### ISSUE THREAD

**Issue by nyrf** [gobuffalo/buffalo#638]
When use pg, everything works well. but when use sqlite and run `env GOOS=linux GOARCH=amd64 buffalo build --static`, got error 

```
warning: unable to find runtime/cgo.a
/Users/nyrf/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
thanks.

**Comment by markbates** [comment]
CGO is very difficult to cross compile in Go. It's a Go thing, not a Buffalo. The recommendation is either to use a cross compiler or compile on the platform you want to run on. I recommend the later. It's a lot easier, especially if you use Docker.
