### ISSUE TITLE
[question] best practices for concurrency vs db pool count

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#643]
hi,

i realized that, when i use apache bench to test my server,
any controller / action will freeze when concurrency hit same or higher than db pool.

i have a middleware that check for logged in user and query the db on every call.
when i remove this middleware, problem solved.
any advice for me to handle user session via api token and still maintain high concurrency without hitting db pool limit?

if db pool is set to very low, etc: 5, if i have 6 concurrent ajax call, the server freeze up without error, and all ajax timed out. i need to restart the server to have it working again.

thanks

**Comment by u007** [comment]
okay, i think ive narrowed down the culprit to pop.transaction.
if ive removed pop.transaction and added c.Set("tx", models.DB) and concurrency works again.
tested with db pool 30 and ab:
```
ab -c 80 -n 300 url..
```

i know a quick fix for this is to increase db pool and change all listing and show to use models.DB as tx.

is there any alternative to this? so that it wont freeze and time out?
supposed we expect it to not freeze, but able to resume when db pool is free from other connection, but it seems to be alike deadlock. unrecoverable freeze.

thanks

**Comment by stanislas-m** [comment]
@u007 I'm closing this one, since you said you found a solution in #675. Feel free to reopen it if it's not the case. :)

**Comment by u007** [comment]
right, but ive this problem in the end:
https://github.com/markbates/pop/issues/211

the webserver is almost forever hang

**Comment by stanislas-m** [comment]
@u007 [Pop v4.3.1](https://github.com/gobuffalo/pop/releases/tag/v4.3.1) Allows now to set max idle connections from the config file, just like the pool param. :)
