### ISSUE TITLE
Import error generating new app as API only

### ISSUE THREAD

**Issue by tsmith1024** [gobuffalo/buffalo#648]
I'm seeing issues similar to #492 using v0.9.4. 
`actions/render.go:5:2: imported and not used: "github.com/gobuffalo/packr"`

It appears to be related to newapp/templates/actions/render.go.tmpl importing packr in API mode, where the packr use is left out when in API mode.

I've got a fix I'll put a PR in for in just a minute to get this sorted out. Hope that works!

**Comment by markbates** [comment]
PR is very welcome!
