### ISSUE TITLE
CSS for error pages is broken in v0.9.5

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#650]
When the asset finger printing was introduced recently it broke the default error page in Buffalo because `/assets/application.css` returns a `404`. The solution appears to be to make the asset helpers available to that error page, which they're currently not.

**Comment by paganotoni** [comment]
thanks Mark, i'll work on this soon, when is our possible release date for 0.9.5 ?

**Comment by paganotoni** [comment]
solved in #667
