### ISSUE TITLE
Using i18n with buffalo in just api mode

### ISSUE THREAD

**Issue by fdonzello** [gobuffalo/buffalo#659]
Hi,

how do you use i18n to translate strings that you render as JSON response? Do you manually manage the translations file?

**Comment by stanislas-m** [comment]
You should be able to use the `Translate` function from your action file, and generate JSON with the translated string.

See: https://gobuffalo.io/docs/localization#use-i18n-in-actions

**Comment by fdonzello** [comment]
Thanks @stanislas-m 

It's weird I didn't find it when I opened this issue.

**Comment by stanislas-m** [comment]
@fdonzello The documentation part was added for the new release, and there was a major change on the `Translate` function: it used to return 2 args (which, in your case, was quite boring to handle).
