### ISSUE TITLE
webpack should using uglifyjsv3 to support JS ES6

### ISSUE THREAD

**Issue by netroby** [gobuffalo/buffalo#663]
https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

The current buffalo using 
```
$ grep -R uglify package.json 
    "uglifyjs-webpack-plugin": "~0.4.6",

```

**Comment by markbates** [comment]
PRs are always welcome. :)

**Comment by paganotoni** [comment]
I tried updating an existing app to use that plugin v1.0.1, and if works correctly after the update, if that's all we need we should be ok.

@netroby would be good if you could provide some details on the problem we're trying to solve by changing the plugin version just to have a way to check this is working as expected while implementing it.

**Comment by paganotoni** [comment]
As an update i tried with the following code (not JS expert here) and works with both versions of the plugin:

```js
class MyFirstES6Class {
  constructor(message) {
    this._message = message;
  }
 
  get message() {
    return this.message;
  }
 
}
 
var myClass = new MyFirstES6Class('Hello World!!');
console.log(myClass.message);
```

**Comment by netroby** [comment]
Looks good, ES6 supported fine.
