### ISSUE TITLE
How to resolve foreign keys?

### ISSUE THREAD

**Issue by arddor** [gobuffalo/buffalo#670]
I have multiple models which have a foreign key to another model, e.g.:

```go
type Company struct {
	ID        uuid.UUID `json:"id" db:"id"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	Name      string    `json:"name" db:"name"`
	Interval  int       `json:"interval" db:"interval"`
}

type User struct {
	ID        uuid.UUID `json:"id" db:"id"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	Firstname string    `json:"firstname" db:"firstname"`
	Lastname  string    `json:"lastname" db:"lastname"`
	Role      int       `json:"role" db:"role"`
	Mail      string    `json:"mail" db:"mail"`
	CompanyID uuid.UUID `json:"companyID" db:"companyID"`
	Company   *Company  `json:"company,omitempty" db:"-"`
}
```
I have added a company field to the user model and would like load the company in there in the controller. I would prefer to not have to do two queries for that and tried to do a join, but I could not find out how to get the fields into the Company struct. 

Is this currently possible or are there any plans to support that?

**Comment by markbates** [comment]
Currently, you can’t. But yes, there is all sorts of talk and discussion on how best to handle it. Several branches have been started and dropped. It’ll come, but no eta yet.

-----------
Mark Bates

**Comment by markbates** [comment]
Closing this as it's a dup of https://github.com/markbates/pop/issues/93
