### ISSUE TITLE
[notes] pop.transation in middleware with defer

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#675]
i've found the culprit that causes user update to freeze.
it turn out that i have a middleware that update the user table on every visit with user session.
and added it into defer alike this:
```
defer func() {
  // do not do transaction here
  err = tx.RawQuery("update users set online_at=? where id=?", time.Now(), user.ID).Exec()
  if err != nil {
    c.Logger().Errorf("Unable to save online at of user: %v, error: %v", user.ID, err.Error())
  }
}()
```
a working way is to:
```
go func() {
  err = tx.RawQuery("update users set online_at=? where id=?", time.Now(), user.ID).Exec()
  if err != nil {
    c.Logger().Errorf("Unable to save online at of user: %v, error: %v", user.ID, err.Error())
  }
}()
```
is it possible to update this in better words in the readme?

**Comment by paganotoni** [comment]
@markbates @stanislas-m what do you think would be the correct way to add this to the documentation, I'm thinking to add it in https://gobuffalo.io/docs/troubleshooting, does that sound good to you?

**Comment by u007** [comment]
maybe under common gotcha?

**Comment by markbates** [comment]
@stanislas-m wherever you think this bit of documentation belongs, I trust you.

**Comment by stanislas-m** [comment]
@u007 @paganotoni @markbates The troubleshooting section seems fine for this one. :)

**Comment by paganotoni** [comment]
Cool, I'll add it there and send PR
