### ISSUE TITLE
buffalo 0.9.5 build binary returns weird result

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#679]
hi,
ive just attempted to upgrade to buffalo 0.9.5 from 0.9.4.

buffalo dev was running fine with buffalo dev.
but when i build it for deployment,
it works, and i could start the instance.
but when i visit the site, im getting blank with symbol:
```
ᾋ
```

tested build for mac and cross compile to linux with same result
what do i need to change?

**Comment by markbates** [comment]
I’ve never seen that before. @paganotoni maybe it has to do with the asset changes?

**Comment by u007** [comment]
i found the issue, its because iam using dep ensure, it hardcoded all the version.
when i compare Gopkg.toml between a new project and my current one, i found all the version issues.
especially pakr version is way outdated.

ive to add in ^ to version prefix. but then i was caught in another bug here:
https://github.com/golang/dep/issues/484

so i ended up ditching dep and using glide.
then i added version for glide for package like gobuffalo/packr 
and run glide install

final binary works fine 👍 
great job !
