### ISSUE TITLE
assets uglifier for production only?

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#683]
hi,

new assets fingerprint and uglifier is awesome 👍 
managed to reduced js from 4mb to 1.6mb.

but there are a concern of performance for development.
the speed to recompile all assets took very long.

is it possible to have webpack command for different environment?
development, staging, production

maybe in webpack.yml (GO_ENV):
```
development: webpack --env.NODE_ENV=$GO_ENV -c ./webpack.config.js -watch
build: webpack --env.NODE_ENV=$GO_ENV -c ./webpack.config.js
```

with this, it will be awesome that we only run build to do uglifier and clean up
what do you think?

here are example:
https://webpack.js.org/guides/environment-variables/

thank you

**Comment by u007** [comment]
my build now increase to 200+mb

**Comment by u007** [comment]
i need a urgent fix for this.
thinking to find if webpack.$GO_ENV.config.js exists, otherwise use webpack.config.js to build

is this good?

**Comment by markbates** [comment]
@u007 https://github.com/gobuffalo/buffalo/pull/687 - I think that's a better solution.
