### ISSUE TITLE
Provide a Buffalo version based on Golang language version 1.7.x

### ISSUE THREAD

**Issue by hypervalley** [gobuffalo/buffalo#696]
I am testing the Golang language for the web and I've found your project, which has several positive predicates. As a user of Debian, I request you to evaluate the possibility of providing a Buffalo version based on Golang version 1.7.x. Debian allows you to install, via backports, up to Golang version 1.7.4 . Thus, the use of 1.8.x Golang version, in this distro, requires manual install, which is not ideal for projects in production, from the point of view of a Debian developer.

**Comment by markbates** [comment]
While we would love to provide support for all Go versions, unfortunately, that's just not possible. It takes too much effort to maintain multiple versions and we don't have the resources to do reliably provide support back that far. We've decided that maintaining the last 2 releases is the most realistic approach, so `1.8` and `1.9`.

For each version of Go that is supported we have to add the overhead of more testing, more bug maintenance in multiple code trees, etc... It's a significant amount of overhead. There's also the matter of the multiple packages that Buffalo depends on, they all have to maintain `1.7` indefinitely, which, again, is difficult. 

It's a "generally" agreed upon consensus to support the current, and the previous version of the language.

I hope you understand. The best solution is to try to get a Go installation package for Debian of `1.9`. That has a great advantage for everyone.

**Comment by stanislas-m** [comment]
@hypervalley, you can consider using a Docker environnement to build your app, so you can use a higher version than the one Debian provides. Buffalo provides a Docker image for this purpose.

If it's not possible for you, you can still download the version from the Go website.
