### ISSUE TITLE
assets is not return correct fingerprint

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#698]
hi,

my webpack actually contains 2 assets, 1 is the application.js and another is backend.js

then application.js works most of the time.
but backend.js sometimes does not refresh, i have to restart buffalo dev to have it reflected.
even thou i have shared js being updated, application.js get updated fine.

part of my webconfig below:
```
module.exports = {
  entry: {
    application: [
      'babel-polyfill',
      "./assets/js/application.js",
      "./node_modules/jquery-ujs/src/rails.js",
      "./assets/css/application.scss"
    ],
    backend: [
      'babel-polyfill',
      "./assets/js/backend.js",
      "./node_modules/jquery-ujs/src/rails.js",
      "./assets/css/backend.scss"
    ]
  },
  output: {
    filename: "[name].[hash].js",
    path: __dirname + "/public/assets"
  },
  //...
```

i suspect webpack works, but template is not reflected

**Comment by markbates** [comment]
@paganotoni want to take a look at this?

**Comment by paganotoni** [comment]
@markbates yes

**Comment by paganotoni** [comment]
hey @u007

I tried this in my machine and created [this](https://github.com/paganotoni/buffalo-thow-assets-entry-example) repo, it seems to work correctly with that sample application.

Are you running this on Linux, Mac or Windows os ?

**Comment by u007** [comment]
mac

**Comment by u007** [comment]
i found the issue,

i forgot new assetsbox requirement in render.go
```
package admin

import (
	"github.com/gobuffalo/packr"
	// "github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/buffalo/render"
	// "github.com/gobuffalo/velvet"
)

var r *render.Engine
var assetsBox = packr.NewBox("../../public/assets")

func init() {
	r = render.New(render.Options{
		// HTML layout to be used for all HTML requests:
		HTMLLayout: "backend.html",

		// Box containing all of the templates:
		TemplatesBox: packr.NewBox("../../templates"),
		AssetsBox:    assetsBox,

		// Add template helpers here:
		Helpers: render.Helpers{},
	})
}
```

**Comment by u007** [comment]
hi,
is it possible to add check on pakr/box.go that it checks for non setup of AssetsBox path or show warning when using packr.NewBox("") with empty string?

**Comment by u007** [comment]
finally got all working with external assets, thank you 👍
