### ISSUE TITLE
[feature] build only binary without assets compilation

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#700]
hi,

is it supposed to have buffalo build -e working this way?
ive tried, and realize it still call webpack compilation

is there any other flag to just compile binary for non assets handling?
thanks

**Comment by stanislas-m** [comment]
The `-e` option for `buffalo build` extracts the assets to a zip archive, instead of linking it in the binary. These assets still needs to be build, that's why the webpack compilation is still called.

**Comment by markbates** [comment]
This would be a pretty easy PR for anyone looking to do it. All it would be is added a new flag and turning off that part of the build system. The build system has been rewritten in `development` and is a lot easier to work with now.

**Comment by paganotoni** [comment]
I would love to work on this one
