### ISSUE TITLE
[feature] nice to have: middleware for default header to indicate gobuffalo?

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#707]
hi,

would it be nice to have this?
so we can start to have some statistic of usage worldwide.
but im not sure how they collect these information, but as long as we do have information on it in header.
or should it be in the meta header?

maybe without the version to avoid security issues

i realize wordpress doesnt show version, but somehow maybe the assets indicates it.
assets might be good way too, maybe as image

**Comment by markbates** [comment]
I'm torn on this one. Yes, it would be nice to ping an app and see that it's using Buffalo, but, with that said, I'm concerned about potential secure issues. 

I would love to hear opinions from people who have experience in this area before we make a decision.

**Comment by seblw** [comment]
IMO it's asking for troubles. That'd be just making the job easier for malicious guys.

**Comment by markbates** [comment]
I agree with @seblw I'm not a fan. I think it could possibly cause more issues than it helps.
