### ISSUE TITLE
Is there a way to define custom flags for generated binary?

### ISSUE THREAD

**Issue by ghaabor** [gobuffalo/buffalo#715]
I'd like to use the `flag` package to define a flag for the binary created by `buffalo build`. I'm aware that buffalo wraps my application's `main.go`. Is there a way to do something like this? My temporary solution was to use an env var but I'd rather use the flag.

**Comment by markbates** [comment]
@ghaabor currently no, but I just opened a PR to fix that in the next release https://github.com/gobuffalo/buffalo/pull/716
