### ISSUE TITLE
Localized Views

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#723]
We already have a way to handle translations for pieces in a template. Sometimes, it's better to create a specific page for a language (for instance, when a page is static). A good example is gobuffalo.io: all markdown documentation pages will be difficult to maintain if we extract all strings, and some samples have a better value if they are translated too.

# Localized Views

Rails supports this use case like that: http://guides.rubyonrails.org/action_view_overview.html#localized-views. Using a file suffix, the developer can provide a version for a specific language, or use a non-suffixed version as a fallback.

**Comment by paganotoni** [comment]
@stanislas-m I like this idea!! could we initially build it outside the framework (in gobuffalo) and then move it inside buffalo?

**Comment by markbates** [comment]
I think this is a great idea. It shouldn't be too hard to implement either. @stanislas-m would you like to take lead on this one?

**Comment by stanislas-m** [comment]
@markbates No problem. :)
