### ISSUE TITLE
auto reloading doesn't work when .go file change

### ISSUE THREAD

**Issue by xu4wang** [gobuffalo/buffalo#726]
I created one new project using 
```
buffalo new coke
```
and use 
```
buffalo dev 
```
to start the project.   I can access http://localhost:3000/ without any issue. I change the app.do controller, added another URL:

```
func App() *buffalo.App {
    ...
    app.GET("/", HomeHandler)
    app.GET("/test", HomeHandler)
}
```

I'm expecting the app will be rebuilt by buffalo and I can access http://lcoalhost:3000/test.

However, the app is NOT rebuilt. I get a 404 when accessing /test.
I'm using MacOS.

**Comment by rgerardi** [comment]
Hello @xu4wang,
I just tested on MacOS here and it works. The app is rebuilt and I can access the "/test" endpoint.
Do you see any error messages in the `buffalo dev` screen?

**Comment by paganotoni** [comment]
Just tested it and works correctly, closing this issue.

**Comment by xu4wang** [comment]
No there was nothing in the ‘buffalo dev' console.
Maybe my own installation issue. will test later.
