### ISSUE TITLE
Export goGet and goInstall from cmd package

### ISSUE THREAD

**Issue by intabulas** [gobuffalo/buffalo#73]
In playing around with buffalo I noticed that the goth generator doesn't install the two deps (goth and oauth) when the generator is run.  Unfortunately goGet and goInstall are not exported in the cmd package. 

Instead of generating hard coded exec.Command's for a PR ie:

```go
g.Add(gentronics.NewCommand(exec.Command("go", "get", "-u", "github.com/markbates/goth")))
g.Add(gentronics.NewCommand(exec.Command("go", "get", "-u", "github.com/mrjones/oauth")))
```
 it would be nice/cleaner to use goGet in the goth generator to install the dependencies

**Comment by markbates** [comment]
Sounds reasonable. Can you open a PR?

**Comment by intabulas** [comment]
unfortunately it creates a circular dependency :(

**Comment by markbates** [comment]
Boo. :( What about moving it to the `generate` package?

**Comment by intabulas** [comment]
Yeah that is what I am doing now for a PR

**Comment by intabulas** [comment]
So only thing I dont like is the namespace conflict in the soda generator (it imports another generate package) so I did a named import 
```go
bgenerate "github.com/gobuffalo/buffalo/buffalo/cmd/generate"
```
and it doesn't feel clean to me. I could just leave the old goGet/goInstall in cmd package and have it call generate.GoGet (for example), but it would have to move to a new file since new.go imports the same soda generate
