### ISSUE TITLE
Generating a resource composed by 2 words underscored

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo#734]
When generating a resource with 2 words where the words are separated with underscore buffalo generates views, model, and all necessary files, however, it uses underscored version in some places and camelcase in other, causing the resource not to work correctly.

````
buffalo g r person_event type description person_id:uuid
````

Uses `person_event` on the actions but uses `personEvent` on the view, causing some errors when running the app.

It should use `person_event` and `personEvent`.

**Comment by markbates** [comment]
Think you can fix that before Monday?

-----------
Mark Bates

**Comment by paganotoni** [comment]
Yes
