### ISSUE TITLE
service discovery

### ISSUE THREAD

**Issue by pablogore-zz** [gobuffalo/buffalo#743]
HI,
Will consider integrating consul /etcd as service discovery ?

**Comment by markbates** [comment]
Can you outline what you have in mind for this?

**Comment by seblw** [comment]
Probably something related to http://microservices.io/patterns/server-side-discovery.html but IMO this is far outside of scope.

**Comment by arschles** [comment]
I agree that it's out of scope, but maybe there's something orthogonal to Buffalo that does RPC (and service-discovery) in a Buffalo-friendly way?

Random thought: you could do tracing pretty transparently for the buffalo user:

- Create a middleware that populates the buffalo context with a trace ID
- The RPC framework is used in a buffalo handler, and takes the buffalo context

Just an idea, hope it helps

**Comment by markbates** [comment]
Fun fact there is already a request id populated for you in the context. :) it’s put into every log. It looks like xxx-yyy the first half is session scoped, the second half request scope. That way you can trace a users whole session, or a particular request of theirs. Hopefully that helps.

**Comment by arschles** [comment]
Oh nice, that'd be perfect

I'm sure there are more ways an RPC framework could be loosely coupled with buffalo. Hopefully that idea was useful to someone
