### ISSUE TITLE
Goth generator does not install required dependencies

### ISSUE THREAD

**Issue by intabulas** [gobuffalo/buffalo#75]
When you use the goth generator ex: 
```sh
buffalo g goth twitter facebook linkedin github
```
The two required dependencies ```github.com/markbates/goth``` and ```github.com/mrjones/oauth``` are not installed by default which will cause the server to crash

**Comment by markbates** [comment]
Didn't you just fix this? I'm confused.

**Comment by intabulas** [comment]
Yeah I was just being clean and not mixing the actual change to the generator with exporting Go*

**Comment by markbates** [comment]
closed by #78
