### ISSUE TITLE
Proposal: move github.com/gobuffalo/x/mail into Buffalo "Core"

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#752]
The [github.com/gobuffalo/x/mail](https://github.com/gobuffalo/x/tree/master/mail) seems to be pretty stable, based off of my usage. I think it would make a great addition to core. 

The argument for it would be that lots of people send emails from applications, so it should be baked in.

I don't see any cons to bringing it in.

The plan for migration would be to copy the package to `github.com/gobuffalo/buffalo/mail`, but leave the old `x/mail` package where it is, but updated the `README.md` to point out that package is no longer being maintained in favor of the one in the `buffalo` repo. This is similar to what happened what Go moved `context.Context` in `1.7`.

I'm looking for opinions, pros and cons on this, so please speak up. :)

**Comment by stanislas-m** [comment]
+1. Sending emails is a common use-case, it makes sense to add it to the core.

**Comment by seblw** [comment]
Optionally you could just move `x/mail` content to `buffalo/mail`, and create a type alias from `x/mail` to `mail` (new feature in Go 1.9, https://github.com/golang/proposal/blob/master/design/18130-type-alias.md), but that would require locking buffalo on Go 1.9.

**Comment by markbates** [comment]
Type aliases, for now are out. Buffalo has a minimum supported version of 1.8.1 so we can’t break those users yet. When 1.10 comes out the minimum version will go to 1.9 and then we can use aliases.

**Comment by stanislas-m** [comment]
@markbates, just my 2 cents: since the default Buffalo setup includes i18n configuration, does it make sense to add a similar config for the mailer generator? (since we can't use the one from the actions package, because of circular deps)
