### ISSUE TITLE
Buffalo slack channel link doesn't work

### ISSUE THREAD

**Issue by alvico** [gobuffalo/buffalo#759]
Hi,

I know this is not an issue but I can't find any other way of communicating with you guys, slack channel doesn't work apparently. 

Also, I'm struggling to disable https and or trying production conf when using development, it looks like somehow those settings are being constantly overwritten. 

cheers and thanks for this awesome feedback.

**Comment by stanislas-m** [comment]
@alvico The slack channel works fine here, what's your problem? :)

**Comment by markbates** [comment]
You need an invite for Slack. You can get one here https://invite.slack.golangbridge.org/

To change environments on your app you can use the `GO_ENV=production` Environment variable.

**Comment by alvico** [comment]
Thanks for the answers, reggarding the go_env stuff I tried before ofc, but couldn't change it when running buffalo dev, from the binary ofc yes I could.
