### ISSUE TITLE
Cannot map table name on pop model

### ISSUE THREAD

**Issue by susilolab** [gobuffalo/buffalo#764]
hi, i think i found a bug on pop library. i can't change table name using MapTableName. thanks

```Go
m := &pop.Model{Value: User{}}
fmt.Printf("tableName: %v\n", m.TableName()) // "users"

pop.MapTableName("user", "people")
m = &pop.Model{Value: User{}}
fmt.Printf("tableName: %v\n", m.TableName()) // "people"
```

**Comment by markbates** [comment]
The name of your struct is `User`, not `user`, you need to map the name of your struct.

```go
pop.MapTableName("User", "people")
```

**Comment by susilolab** [comment]
thanks it's work, i think the documention on source code need to be updated.
