### ISSUE TITLE
How to enable CORS

### ISSUE THREAD

**Issue by suhaschitade** [gobuffalo/buffalo#766]
Hi,
Could you please provide an example of how to enable cors in buffalo app for the custom APIs.

Essentially, I have created a route and exposed an API which will be consumed by ajax. When testing this I encountered below error
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

Regards,
Suhas

**Comment by suhaschitade** [comment]
I need to enable file access to chrome and changed file access to url. Everything is working now.
closing this issue

**Comment by danikarik** [comment]
@suhaschitade What package did you use?
