### ISSUE TITLE
Running a single test?

### ISSUE THREAD

**Issue by joshjordan** [gobuffalo/buffalo#769]
What's the right syntax for running specific tests or specific test files? It has become very difficult for us to hone in on the right output when debugging a failing test. I have tried reusing the commands that `buffalo tests` spits out as it starts up, but they target directories rather than single tests or test files, and they don't include the schema management that Buffalo does.

We love the framework - thanks for your hard work! If you can give us some notes on this, we'd be happy to clean it up and contribute back to documentation.

**Comment by markbates** [comment]
@joshjordan there are ways, but it is bizarrely difficult when using test suites. The good news, a patch for this in PR form now and should be in `0.10.2` which is slated for release this week.

The syntax will look like:

```
$ b test -m "Foo"
```

That will run all tests that have `Foo` in them.
