### ISSUE TITLE
Bug: Failed when install on PC doesn't have gcc

### ISSUE THREAD

**Issue by phuctk93** [gobuffalo/buffalo#777]
When you install buffalo on PC doesn't have gcc with cmd:
`go get -u -v github.com/gobuffalo/buffalo/buffalo`
This way will break at sql3-lite pack and buffalo cmd (cli) will not install your pc.

**Comment by markbates** [comment]
A gcc is a requirement, for now, as stated in the installation section of the docs. https://gobuffalo.io/docs/installation
