### ISSUE TITLE
Buffalo can not create a table containing specific characters (ms_, tr_).

### ISSUE THREAD

**Issue by Yuutakasan** [gobuffalo/buffalo#782]
In the internal table naming convention, "ms_" is given to the master and "tr_" is prefixed to the transaction, but processing of the language locale misidentifies the prefix and can not create the desired table .
* I'm trying to create a table called "ms_batch、tr_logs"

Is this a specification? Or is it a bug?

It seems that an error occurs if there is a character string in the following URL in the first character of the table.
http://www.unicode.org/cldr/charts/28/supplemental/language_plural_rules.html

* make project
```bash
$ buffalo new maintainer --db-type mysql
```
* make table
```bash
$ buffalo db create -e development
```

## pattern 1
* make resource
``` bash 
$ buffalo g resource ms_batchs name:nulls.String -s
```
* buffalo run
``` bash
$ buffalo dev
```
* error msg
multiple languages found in filename "ms_batchs.en-us.yaml": [ms-batchs en-us]; expected one

## pattern 2
* make resource
``` bash 
$ buffalo g resource tr_logs name:nulls.String log_text:nulls.String
```
* buffalo run
``` bash
$ buffalo dev
```
* error msg
multiple languages found in filename "tr_logs.en-us.yaml": [tr-logs en-us]; expected one

**Comment by stanislas-m** [comment]
@Yuutakasan, can you try the fix here? https://github.com/gobuffalo/buffalo/pull/791

**Comment by Yuutakasan** [comment]
After installing the Buffalo main unit from the development branch, I was able to confirm that I fixed it by following the same procedure.

thanx!
