### ISSUE TITLE
Support Unix domain sockets to bind Buffalo

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#783]
## Abstract
[Unix domain sockets](https://en.wikipedia.org/wiki/Unix_domain_socket) are an alternative way to bind a listening app on compatible systems (GNU/Linux, MacOS/BSD...). This is an IPC system materialized as a file, and allow to publish services locally.

Common use cases are proxies, since it allows to publish a service only to localhost system, without blocking a TCP port. *Docker* is a well known solution using this communication pipe by default. 

## Proposed changes
To allow Unix domain sockets to be used, we'll need to patch `app.go` to use `Listen` & `Serve`, instead of `ListenAndServe` which only uses TCP.

`Addr` option is already a string, so we just need to allow a new kind of value, prefixed with `unix://`. This way we can choose the right listener.

**Comment by markbates** [comment]
Love the idea. Make it so. :)
