### ISSUE TITLE
Broken layout on new project with --skip-webpack

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#784]
### Setup
* Buffalo 0.10.2
* Ubuntu GNU/Linux (applicable to Windows & MacOSX)

## Steps to reproduce
* Create a new project with buffalo, using the `--skip-webpack` option.
* Start `buffalo dev` and open a browser to see the home page.

### Expected behavior
The page has the same presentation as the webpack one.

### Current behavior
The page layout is degraded, due to Bootstrap css link missing (in the webpack setup, bootstrap is embedded using sass). 

## Proposed fix
Use the `WithWebpack` opt to detect if webpack is not used, then add Bootstrap link to the template.

```
{{- if not .opts.WithWebpack }}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{{- end }}
```

**Comment by paganotoni** [comment]
Closing this given PR #785 was already merged
