### ISSUE TITLE
Generating new project on Windows is adding drive letter and path in imports

### ISSUE THREAD

**Issue by mikeroosa** [gobuffalo/buffalo#788]
When generating a new project on Windows 7 it is adding the full path including drive to the import in main.go, app.go, init.go, and Dockerfile.

This is causing issue when trying to build the project.

version 0.10.2

Tried on another laptop running Windows 7 and code works fine. Same version.

**Comment by mikeroosa** [comment]
I found the issue with the windows 7 drive getting put into the imports. My gopath was set to C:\Code\go. In meta/app.go in the packagePath func envy.GoPath() is returning C:/Code/go just like GoPath is set to in the environment variables. However, the filepath.ToSlash(root) on the next line is returning a lowercase drive letter c: so it's not doing the replace correctly on the return line because of the case difference.

**Comment by BigJoe01** [comment]
Not works perfect, when root and src contains different case sensitive string.
The primary problem is case sensitive strings.replace.

**Comment by markbates** [comment]
This is fixed in the development branch if anyone wants to try it out.
