### ISSUE TITLE
Error When Generating Goth Code

### ISSUE THREAD

**Issue by briandowns** [gobuffalo/buffalo#79]
```
buffalo g goth github twitter
Buffalo version 0.6.0

Error: reflect: Call using *errors.withStack as type string
Usage:
  buffalo generate goth [provider provider...] [flags]

reflect: Call using *errors.withStack as type string
```

**Comment by markbates** [comment]
Try pulling down the latest version of github.com/markbates/gentronics. I reverted a change this morning that wasn't meant to be pushed to master. It'll solve this.

**Comment by briandowns** [comment]
That's super strange. I had the latest pulled I had thought. Maybe just not installed. Anyway, working great now. Thanks.
