### ISSUE TITLE
Windows buffalo.exe slow start, full path scan

### ISSUE THREAD

**Issue by BigJoe01** [gobuffalo/buffalo#790]
Hi,
In stat_windows.go , the Available() func reading full path environment variable with many
unnecessary directory and skip c:\windows directory only, when scanning plugins.
This cause slow exe startup.

**Comment by frederikhors** [comment]
This is still slow, @markbates. How can I help speed up on Windows? Installed using `go get -u -v github.com/gobuffalo/buffalo/buffalo` in a new Windows 10 PC.
