### ISSUE TITLE
Generated resource "statuses" inconsistent

### ISSUE THREAD

**Issue by mikeroosa** [gobuffalo/buffalo#794]
At the command line I typed:
```
buffalo g resource statuses name is_active:bool
```

In `actions/statuses.go`, I see:
/ Following naming logic is implemented in Buffalo:
// Model: Singular (Statuse)
// DB Table: Plural (statuses)
// Resource: Plural (Statuses)
// Path: Plural (/statuses)
// View Template Folder: Plural (/templates/statuses/)

Singular should be Status, but that's not the big problem. In actions/statuses.go it had this code throughout:
```
status := &models.Statuse{}
```

However, there was no `models/statuse.go` file. There was a `models/status.go` file.

In the `models/status.go` everything referred to the singular so I had to update this section:
```go
// Statuses is not required by pop and may be deleted
type Statuses []Status

// String is not required by pop and may be deleted
func (s Statuses) String() string {
	js, _ := json.Marshal(s)
	return string(js)
}
```

**Comment by markbates** [comment]
https://github.com/markbates/inflect/commit/f5fba5607384690a58dbaeaaf26863577eb4544a
