### ISSUE TITLE
PROPOSAL: Move markbates/pop to gobuffalo/pop and turn off SQLite support by default

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#799]
Please see issue https://github.com/markbates/pop/issues/164 and leave comments there.

**Comment by paganotoni** [comment]
I like this one, think is the right move given pop is a core package when developing buffalo apps and also that by bringing this package in we could have more attention into it resulting in more improvements and quick fixes

**Comment by stanislas-m** [comment]
@paganotoni +1
