### ISSUE TITLE
Generated app should have Buffalo Favicon

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo#801]
It would be good to add a buffalo favicon to the default generated app

**Comment by paganotoni** [comment]
@markbates I copied the favicon from gobuffalo.io and that's the one I'm using on #820, but wanted to ask you if you think is ok to do something like this for the favicon:

![screenshot 2017-12-20 21 19 14](https://user-images.githubusercontent.com/645522/34238222-93f5011e-e5ce-11e7-99a3-7f1e9c19a085.png)

The idea is to make Buffalo a bit more visible when on the favicon.

**Comment by stanislas-m** [comment]
@paganotoni Love this favicon version!
