### ISSUE TITLE
Database / Pop as an opt-in, not an opt-out

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#804]
Context
======

This is a thought on the user experience using Buffalo.

When I want to create a new Buffalo app, the documentation says I need to type:
 ```
$ buffalo new coke
 ```
* This is fine, the default configuration setups everything, but I still need to configure the database to make it work (as the README says).
* The second thing is that the files where created for PostgreSQL (which is a great choice, but not **the user choice**).

I think it's important for the user to have a **working app from the start**. _I said that I want to create a new app, it creates a new working app. So, when I go to the index page from my browser, I'm not expecting an error to display (it's something generated by Buffalo, so it should work from scratch, doesn't it?)_

Proposal
=======
In order to have a working app from scratch, here are some propositions:
* Have the database setup as an opt-in option instead of an opt-out option.
* Add a new command to init the database config, setup the CI & the needed files.

This way, it allows you to postpone the database choice, but if you have a clear idea from start, you can use the flag from the `new` command.

What's your opinion?

**Comment by arschles** [comment]
Another option could be to set up for sqlite -- I generally change my `database.yml` right after I `buffalo new`

I just came here from https://github.com/markbates/pop/issues/164, so not sure if it makes sense to do this though; just wanted to throw it out there.

**Comment by stanislas-m** [comment]
@arschles The problem with SQLite from now, is the mandatory GCC compiler. So we can't do that.

**Comment by arschles** [comment]
Ok, thanks @stanislas-m
