### ISSUE TITLE
test on action does not populate uri

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#806]
Hi,
i realize 
```
context.Request().URL.Path 

```
is empty in test,
anyway to populate this in test?
how about c.Request().Method?

sorry forgot to mention that it only happen within action, some how in middleware, it does show

thank you

**Comment by markbates** [comment]
Can you please provide reproduction steps to reproduce this?

**Comment by stanislas-m** [comment]
@u007 Do you have more info on this one?

**Comment by u007** [comment]
1. add in a middleware to app and fmt.println("uri: ", context.Request().URL.Path)
2. create a action test, and run test
```
package api_test
func (as *ActionSuite) Test_AccessResource_List() {
	var err error
	html := as.HTML("/api/users").Get()
}
```
notice uri is empty
3. then run buffalo dev
4. curl localhost:3000/api/users
notice in console of buffalo, uri is populated

**Comment by stanislas-m** [comment]
@u007 I just tested it, it works fine:

```
level=info msg="uri: /forums" request_id="a19d571f12-0b8b71e970"
level=info msg=/forums db="7.208928ms" duration="11.540333ms" human_size="4.1 kB" method=GET path=/forums render="3.731647ms" request_id="a19d571f12-0b8b71e970" size="4095" status="200"
```

I'm closing this issue, but feel free to reopen it if the problem occurs again.
