### ISSUE TITLE
FontAwesome icons disappear after first JS recompilation

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo#821]
I've seen that in some situations font-awesome icons don't show up after a change in the JS file, but will appear after `buffalo dev` is restarted.

I looked into the issue and seems when recompiling JS we are first cleaning the entire public/assets folder and only generating JS/CSS.

**Comment by paganotoni** [comment]
Update: Changing `webpack.config.js` rules section for fonts to:
```
...
 { test: /\.(woff|woff2|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/, use: "url-loader" },
 { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, use: "file-loader"},
...
```
Seems to fix it.

**Comment by robvdl** [comment]
I noticed this too, every time I changed a js file and it auto recompiles it failed to load .ttf, .woff, .woff2 files and it seemed the only way was to restart the app each time which is not a good workflow.

Any chance to get this fix in?  I guess in the mean time we can manually update webpack config in existing projects.
