### ISSUE TITLE
Webpack Hot Module Replacement not working

### ISSUE THREAD

**Issue by wiemann** [gobuffalo/buffalo#844]
Webpack [Hot Module Replacement](https://webpack.js.org/concepts/hot-module-replacement/) is not working even when enabling `HotModuleReplacementPlugin` in `webpack.config.js`. This is essential when working on a single page app in Vue / Angular etc. 

Can we figure out how to enable it and make enable it by default?

**Comment by markbates** [comment]
A PR would be great. Thanks.

**Comment by forrest321** [comment]
The new version of webpack should correct this. I spent some time digging to find updating webpack is going to be the best first step. There have been two releases since this was opened, so may no longer be an issue.

**Comment by stanislas-m** [comment]
Buffalo generates new apps with webpack `4.5.0` now, so it should be ok now. Please re-open the issue if you still have issues with the current version.
