### ISSUE TITLE
NODE_ENV not being set to production during build

### ISSUE THREAD

**Issue by bastiankoetsier** [gobuffalo/buffalo#845]
With the [removal](https://github.com/gobuffalo/buffalo/commit/436dc23f762ecc9aef1c759db2e7c09193944414#diff-d8610c51e98c7aa8d24252f5dbec0bfeR25) of loading the whole environment-variables before `exec`, it is prevented  that `NODE_ENV` gets actually [set](https://github.com/gobuffalo/buffalo/blob/master/buffalo/cmd/build/assets.go#L13) to `production`  during `buffalo build` .

This prevents the execution of webpack plugins like uglify for a production build.
It can be circumvented by setting `NODE_ENV=production buffalo build`

**Comment by Zarkopafilis** [comment]
Probably fixed by https://github.com/gobuffalo/buffalo/pull/846 (if it gets merged)
