### ISSUE TITLE
Fingerprint Images

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo#848]
At this point, Buffalo is using the fingerprint strategy on compiled CSS and JS but it's not being used for images, it would be good to add this to images in order to make asset compilation consistent in that sense.

This may have an impact in other areas like CSS backgrounds and fonts but the solution may be already implemented into webpack.

Changes to solve this will mostly be related to the webpack configuration but we will need to add an image helper to resolve fingerprinted image URLs from the `manifest.json` file as we do for CSS and JS.

**Comment by stanislas-m** [comment]
@paganotoni, I think #921 is related to this one: I tried the proposed change to the Manifest plugin, but since images are not in the manifest, it can't work.
