### ISSUE TITLE
sqlite3 dependency makes gotype very unhappy

### ISSUE THREAD

**Issue by kswope** [gobuffalo/buffalo#851]
I'm newish to go and this is the only go package I've used that flipped out like this.  

Is this normal, and if so, is gotype always going to be incompatible with buffalo?

(xenial)kevin@localhost:~/go/src/github.com/kswope/mybuffalo$ gotype main.go 
main.go:6:2: could not import github.com/kswope/mybuffalo/actions (type-checking package "github.com/kswope/mybuffalo/actions" failed (/home/kevin/go/src/github.com/kswope/mybuffalo/actions/app.go:4:2: could not import github.com/gobuffalo/buffalo (type-checking package "github.com/gobuffalo/buffalo" failed (/home/kevin/go/src/github.com/gobuffalo/buffalo/context.go:10:2: could not import github.com/gobuffalo/buffalo/render (type-checking package "github.com/gobuffalo/buffalo/render" failed (/home/kevin/go/src/github.com/gobuffalo/buffalo/render/helpers.go:9:2: could not import github.com/markbates/pop (type-checking package "github.com/markbates/pop" failed (/home/kevin/go/src/github.com/markbates/pop/sqlite.go:20:4: could not import github.com/mattn/go-sqlite3 (type-checking package "github.com/mattn/go-sqlite3" failed (/home/kevin/go/src/github.com/mattn/go-sqlite3/error.go:14:17: invalid constant type invalid type))))))))))

**Comment by markbates** [comment]
The problem appears to be because of the github.com/mattn/go-sqlite3 package, which is CGO. You should open this issue there. It's possible that CGO doesn't work with `gotype`.

**Comment by kswope** [comment]
I'm getting the impression that gotype isn't that popular a go tool and difficult to use and I should probably remove it from my list of linters.  Everything else passes, including gosimple and staticcheck.  Thanks for the quick reply.

**Comment by markbates** [comment]
Not going to lie to you, I’ve been writing Go for 5 years, and I teach it for a living, and I had never used (or heard of it I think) before.
