### ISSUE TITLE
Allow cookies to have a custom path

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#856]
Cookies are bound on a path, and by default it's the current "directory" in the URL: for instance, if I set a cookie in a "/users/set-cookie" URL, the cookie will be bound to "/users".

We should allow Buffalo to set cookies on a custom path, so I can set a site-wide ("/") cookie from a "/users/set-cookie" path.

**Comment by orderbynull** [comment]
@stanislas-m is it still relevant? I'd like to make contribution.

**Comment by stanislas-m** [comment]
@orderbynull It is, go ahead! :+1:

**Comment by stanislas-m** [comment]
Fixed with #1196.
