### ISSUE TITLE
Buffalo dev not starting

### ISSUE THREAD

**Issue by bscott** [gobuffalo/buffalo#86]
Tried a sample app and getting the following when visiting "localhost:3000". I made sure I have no other instance of Postgres running. 

```
<pre>dial tcp 127.0.0.1:5432: getsockopt: connection refused
could not create new transaction
github.com/markbates/pop.newTX
	/Users/bscott/go/src/github.com/markbates/pop/tx.go:26
github.com/markbates/pop.(*dB).Transaction
	/Users/bscott/go/src/github.com/markbates/pop/db.go:10
github.com/markbates/pop.(*Connection).NewTransaction
	/Users/bscott/go/src/github.com/markbates/pop/connection.go:117
github.com/markbates/pop.(*Connection).Transaction.func1
	/Users/bscott/go/src/github.com/markbates/pop/connection.go:96
github.com/markbates/pop.(*postgresql).Lock
	/Users/bscott/go/src/github.com/markbates/pop/postgresql.go:126
github.com/markbates/pop.(*Connection).Transaction
```

**Comment by markbates** [comment]
It looks like your Postgres is not running, or not on 5432. 

It's also possible that the username and/or password is wrong in the database.yml file. 

You could use SQLite as well, or MySQL, they're all supported.

**Comment by markbates** [comment]
You should also run `buffalo db create -a` that will create all of the databases defined in your database.yml, assuming it can connect.

**Comment by bscott** [comment]
ah so this brings up a good question, am I responsible for starting my own Postgres/SQL.. i was under the assumption that Buffalo does that ( like with rails server )

**Comment by bscott** [comment]
I was going to use Docker for Postgres Dev

**Comment by markbates** [comment]
Rails doesn't start up, or create databases for you. If offers tools like `rake db:create:all` you're still responsible for having everything running.

**Comment by markbates** [comment]
As long as you can connect to it like any other pg database you should be good.

**Comment by bscott** [comment]
That's right, ok thanks @markbates for the quick response.

**Comment by markbates** [comment]
Let me know if you have any other issues. I'm closing this for now.

**Comment by markbates** [comment]
Thanks to you for this issue. Because of it I've improved the docs around DB stuff: http://gobuffalo.io/docs/db

**Comment by bscott** [comment]
Also after using buffalo db create -a, I still had to. Tests the databases
manually, the command gave no error output.

**Comment by bscott** [comment]
Also @markbates, after using ```buffalo db create -a``` , I still had to create the databases
manually, as the command gave no error output but ```buffalo dev``` still complained that the database didn't exist. 

just this:

```
$ buffalo db create -a
Soda v3.10.0

```

**Comment by rogueloop** [comment]
we have to create our own PostgreSQL db with projectname_development and then change password

**Comment by rogueloop** [comment]
the   ```buffalo db create -a```  is not automatic
