### ISSUE TITLE
Generated Dockerfile contains JS related config for project generated with the --api flag

### ISSUE THREAD

**Issue by wung-s** [gobuffalo/buffalo#860]
In Dockerfile, as mentioned by @markbates in the Slack channel, line 9-11 shouldn't be generated when a project is generated with the `--api` flag
```
# this will cache the npm install step, unless package.json changes
ADD package.json .
ADD yarn.lock .
RUN yarn install --no-progress
```
Without commenting out the above lines, pushing to Heroku produces the following error:
`ADD failed: stat /var/lib/docker/tmp/docker-builder955994870/package.json: no such file or directory`

**Comment by markbates** [comment]
Thanks for opening this. It’s now fixed in development branch with commit https://github.com/gobuffalo/buffalo/commit/a0727638ba68e15de8abdc5c281cc8c0e005ee53
