### ISSUE TITLE
Error in pop/dialect

### ISSUE THREAD

**Issue by danikarik** [gobuffalo/buffalo#866]
I was testing issue #861 with newly created project:

`buffalo new buffalo-cors-api --api --skip-pop --skip-webpack --with-dep`

When I'm building binary, getting error:
`vendor/github.com/markbates/pop/dialect.go:59:11: cannot assign 1 values to 2 variables`

In previous version `uuid.NewV4()` returns `(UUID, error)`
In new project it returns just `UUID`, what causing error above.

**Comment by markbates** [comment]
You’re hitting this issue https://github.com/satori/go.uuid/issues/66

If you set the uuid package to use the master branch you’ll be fine. Unfortunately until that package sets a proper tag for their breaking change this will keep happening. :(
