### ISSUE TITLE
typo in generated database.yml?

### ISSUE THREAD

**Issue by bscott** [gobuffalo/buffalo#87]
I came across this in database.yml generated by the new command and wanted to make sure it's not a typo..

```
production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/sentry_production"}}
```

envOr ??

**Comment by markbates** [comment]
Not a typo. It's a helper function. It looks for an ENV var. if it isn't found it'll use the default. Useful for production.

**Comment by bscott** [comment]
@markbates Thanks
