### ISSUE TITLE
node-sass package giving errors on mac

### ISSUE THREAD

**Issue by HintikkaKimmo** [gobuffalo/buffalo#875]
I am getting following build errors for node-sass package when running on Mac OSX 10.12.6 (16G1212).

Updating node-sass to 4.7.2 fixes the issue. Should I commit the change for rest of the user group? 

```
RROR in ./~/css-loader?{"sourceMap":true}!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./assets/css/application.scss
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.3
```

**Comment by markbates** [comment]
Yes please.

**Comment by HintikkaKimmo** [comment]
@markbates I made a quick pull request. Just check I edited the correct file as I hadn't check how the templates work. Commit 30fb37ba66289efd3ef0d697f5289d224b0aeb45
