### ISSUE TITLE
Autoload pop model associations in templates

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#883]
When https://github.com/markbates/pop/pull/191 gets merged into Pop we will have a the ability to eagerly load model associations. 

For example:

```go
type User struct {
	ID        uuid.UUID `db:"id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
	Books     Books     `has_many:"books"`  // looks for rows matching user_id in books table
	Address   Address   `has_one:"address"` // looks for 1 row matching user_id in addresses table
}

type Book struct {
	ID        uuid.UUID `db:"id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
	UserID    uuid.UUID `db:"user_id"`
	User      User      `belongs_to:"user"`                                     // looks for a row in the users table
	Reviews   Reviews   `has_many:"publication_reviews" fk_id:"publication_id"` // looks for rows matching publication_id in publication_reviews table
}
```

If there's a `has_many`, `belongs_to`, or `has_one` tag, pop shouldn't load anything, it's like having `db:"-"`. 

However, if I were to do something like:

```go
db.Eager().First(&user)
```

It should load `Books` and `Address`.

If I did:

```go
db.Eager("Books").First(&user)
```

It would only load the `Books` association.

This proposal is for adding the ability to load, on demand, associations from within Plush templates.

For Example:

```go
func SomeHandler(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}
	u := &models.User{}
	if err := tx.First(u); err != nil {
		return errors.WithStack(err)
	}
	c.Set("user", u)
	return c.Render(200, r.HTML("foo.html"))
}
```

```html
// foo.html
<%= for (b) in user.Books { %>
  <%= b.Title %>
<% } %>
```

In this example, in the Plush template, a call to `user.Books` is made. 

1. Is `Books` already populated, if so, return.
2. If `Books` isn't populated then check and see if it's an association, if it try and load it and populate it on the `user`

We have access to the `pop.Transaction` in the template because it's set onto the `buffalo.Context` in  a piece of middleware. 

The difficult part here is to figure out how to hook into Plush when it is trying to figure out what to do with `user.Books`.

**Comment by stanislas-m** [comment]
Just to keep track, here is the opinion I gave on Slack:

I'm not fan of doing db-magic stuff from the template. In my opinion, the template should only care about displaying data, not fetching more data or making transformations.
I've also worked with Java Hibernate a lot, and that kind of magic stuff it provides is a nightmare to debug.

**Comment by markbates** [comment]
After getting a lot of great feedback on this, I think I'm going to make this it's own package somewhere that people can pull in if that want that functionality, but don't have to use if they don't want it. I think that makes the most sense.
