### ISSUE TITLE
Weird issue with Packr

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#884]
I tried to deploy this app https://github.com/xtrem-creative/ldap-password-selfservice on my Debian server. On my Ubuntu computer, it works just fine. I can build the binary, and move it on the Desktop without any problem:

![image](https://user-images.githubusercontent.com/1911803/35486123-d5c3019a-0469-11e8-99b4-7ea8820d758d.png)

When I deploy it on the Debian (9) server, the traces say the following:

```
Jan 28 18:27:14 nirvana ldap_password_selfservice[1102]: time="2018-01-28T18:27:14Z" level=info msg="Starting application at unix:/tmp/ldap-password-selfservice.sock"
Jan 28 18:27:14 nirvana ldap_password_selfservice[1102]: INFO[2018-01-28T18:27:14Z] Starting Simple Background Worker
Jan 28 18:27:22 nirvana ldap_password_selfservice[1102]: WARN[2018-01-28T18:27:22Z] nosupported languages found []string{"en", "en-US", "en-US", "fr"} request_id="94ab452f71-234f627590"
Jan 28 18:27:22 nirvana ldap_password_selfservice[1102]: WARN[2018-01-28T18:27:22Z] Your locale files are probably empty or missing request_id="94ab452f71-234f627590"
Jan 28 18:27:22 nirvana ldap_password_selfservice[1102]: INFO[2018-01-28T18:27:22Z] / content_type=text/html duration="1.181295ms" human_size="0 B" method=GET params="{}" path=/ render="402.336µs" request_id="94ab452f71-234f627590" size="0" status="0"
Jan 28 18:27:22 nirvana ldap_password_selfservice[1102]: ERRO[2018-01-28T18:27:22Z] file does not exist content_type=text/html duration="1.181295ms" human_size="0 B" method=GET params="{}" path=/ render="402.336µs" request_id="94ab452f71-234f627590" size="0" status="0"
Jan 28 18:43:05 nirvana ldap_password_selfservice[1102]: WARN[2018-01-28T18:43:05Z] nosupported languages found []string{"en", "en-US", "en-US", "fr"} request_id="94ab452f71-010fe885c0"
Jan 28 18:43:05 nirvana ldap_password_selfservice[1102]: WARN[2018-01-28T18:43:05Z] Your locale files are probably empty or missing request_id="94ab452f71-010fe885c0"
Jan 28 18:43:05 nirvana ldap_password_selfservice[1102]: INFO[2018-01-28T18:43:05Z] / content_type=text/html duration="4.126477ms" human_size="0 B" method=GET params="{}" path=/ render="164.745µs" request_id="94ab452f71-010fe885c0" size="0" status="0"
Jan 28 18:43:05 nirvana ldap_password_selfservice[1102]: ERRO[2018-01-28T18:43:05Z] file does not exist content_type=text/html duration="4.126477ms" human_size="0 B" method=GET params="{}" path=/ render="164.745µs" request_id="94ab452f71-010fe885c0" size="0" status="0"
```

![image](https://user-images.githubusercontent.com/1911803/35486201-dbdf3dd6-046a-11e8-911c-bacf0248589d.png)

I tried with a normal setup, to make sure the UNIX socket is not the cause, but the results are the same.

Digging deeper, if I try to print the locales box contents list (but it does the same with another box):
- On my computer, the contents shows correctly.
- On the server, the contents list is empty.

A few minutes ago, I pushed a modification on the gobuffalo.io repo, and the CI deployed the new version. Before @markbates intervention, the app showed the same kind of errors.

**Comment by stanislas-m** [comment]
With a constraint on packr v1.10.1, it works fine.

**Comment by stanislas-m** [comment]
More clues on this one: it works on my computer if I move the executable somewhere, because the fallback to the filesystem seems to be a hard link to the file location.

I definitely suspect something broken in packr.

**Comment by stanislas-m** [comment]
After more tests on this case, I've found a working setup by **upgrading the packr version used by the buffalo CLI**. It seems to work when the both versions (CLI & dep) are the same.

**Comment by fredcarle** [comment]
I'm getting the exact same problem deploying on ubuntu server. The bundled app works as expected on my local machine but on the server it can't seem to find any assets or template files. It also gives me an error regarding the locales `Your locale files are probably empty or missing`.
