### ISSUE TITLE
Add support for storing generator's options

### ISSUE THREAD

**Issue by alexdor** [gobuffalo/buffalo#887]
`buffalo new` should also create a file for storing extra flags that will be used when a user runs a generator. 

An example that this file would be useful is when a user creates a project with the `--api` flag. This flag should be stored somewhere so that every action generator skip's the template generation. 

I'm not sure if this file should be implemented as a yml with true/false values. For example:
```yml
skipTemplates: true
api: true
```
or if it should have a different structure.

**Comment by markbates** [comment]
The https://github.com/gobuffalo/buffalo/blob/master/meta/app.go type was added a release or two ago to be the start of solution for understand an apps structure and allowing Buffalo to do things with that information.

I think this idea should extend that. I think this goes beyond storing information about generators, it needs to store general information about the app, including what settings were used to create the application with, possibly what generators and with what settings, maybe, that sort of thing.

I'm thinking we should use either a `.buffalo.app.yml`, `.buffalo.app.toml`, or `.buffalo.app.json` file for this.

**Comment by alexdor** [comment]
Personally I prefer json format but I think that for the sake of consistency we should use a .yml file because the rest of the config is in .yml. What do you think?

So the first step would be to extend the App type (except, if you think that, we should create a new type) to include information like `IsAPI`, `DBType` and `VCS` and then create a file on the project's root to store all this options? Should any other option be stored? Maybe an option to skip template or model or action generation?

**Comment by alexdor** [comment]
@markbates ping

**Comment by markbates** [comment]
@alexdor sorry, I was only vacation so this slipped by me. 

I'm working on a new `buffalo dev` plugin, which needs config, so what I was thinking was something like this:

```
./buffalo/
  dev.toml
  test.toml
  app.toml
  etc...
```

As for what to put into `./buffalo/app.toml`, here are a few things I think should be there, but I'm open for suggestions:

* package: "GitHub.com/foo/bar"
* vcs: "git"
* npm: "yarn"
* database: "postgres"
* created_at: time
* version: "v0.11.0"
* app_type: "web"

**Comment by stanislas-m** [comment]
Closing this one in favor of #1153.
