### ISSUE TITLE
How to get Session ID?

### ISSUE THREAD

**Issue by danikarik** [gobuffalo/buffalo#894]
Hi!

I'm trying to get session ID from Handler in order to save Session ID and User ID pair. But this line returns empty string:
`c.Session().Session.ID`
I understand it's because session get its ID after sessionSaver middleware. I need SID to implement one active user session at time.

Any suggestions?

Thanks.

**Comment by markbates** [comment]
I don’t have an answer for you, Buffalo uses http://www.gorillatoolkit.org/pkg/sessions under the covers, so hopefully that can aid in your search for an answe.
