### ISSUE TITLE
bash: buffalo: command not found [Windows 10]

### ISSUE THREAD

**Issue by tobiasdalhof** [gobuffalo/buffalo#902]
Hello.

I'm not able to run `buffalo` in bash on Windows 10.

```bash
bash: buffalo: command not found
```

How to set this up?

Steps i've done:
1. Installed TDM-GCC
2. `go get -u -v github.com/gobuffalo/buffalo/buffalo`

Any help is highly appreciated

**Comment by markbates** [comment]
You want to add %GOPATH\bin to your %PATH%: https://golang.org/doc/code.html#GOPATH
