### ISSUE TITLE
[question] logging with user-id

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#904]
hi
ive created a custom buffalo logger .
i wanted to logs everything with user-id of the session.
but what is the correct way to do it?
i tried to assign the userId to a static variable within the logger from middleware,
but does this means if concurrently someone else is visiting the site, the userId may be overwritten by another user process?

thanks

**Comment by stanislas-m** [comment]
You can define your middleware on the request level, just like the pop transaction Middleware: https://github.com/gobuffalo/buffalo/blob/master/middleware/pop_transaction.go#L17

Then get the logger from the context, and inject the data you need, with `c.LogField`.

**Comment by u007** [comment]
yes, i just found out i could do it. 
but i also realize c.logfields will directly dump the log out.
it does not carry to Logger().Debugf

**Comment by paganotoni** [comment]
I don't know if this still and issue but i've solved this one by doing:

```
c.LogField("user_id", user.ID)
```

And it doesn't directly dump the log, so this one seems to be solved.

**Comment by paganotoni** [comment]
@u007 can you confirm its working for you ?

**Comment by u007** [comment]
yes, i guess it has to be manually logged
