### ISSUE TITLE
What is xxxxPath() in generated .html files?

### ISSUE THREAD

**Issue by PeterLamar** [gobuffalo/buffalo#905]
What is xxxxPath() in generated .html files? For example, in the toodo sample project there is an itemPath() in the _li.html file. I suppose it returns a POST to /item but I cannot figure out where these calls are defined. Thanks!

**Comment by markbates** [comment]
https://gobuffalo.io/docs/context#whats-in-the-context

-----------
Mark Bates

**Comment by paganotoni** [comment]
Hey @PeterLamar those helper functions that get added on the context based on route names when creating the context on each request:

See:
[https://github.com/gobuffalo/buffalo/blob/master/handler.go#L50](https://github.com/gobuffalo/buffalo/blob/master/handler.go#L50)

For more details.

**Comment by yatish27** [comment]
https://github.com/gobuffalo/buffalo/blob/8185597be9d91c31dce76c53c34ca66b8f017ec6/route.go#L80

**Comment by PeterLamar** [comment]
Wow, Thanks!!! Fastest resolution ever!
