### ISSUE TITLE
Proposal: allow 'buffalo test' to test a single package

### ISSUE THREAD

**Issue by arschles** [gobuffalo/buffalo#907]
It's often useful to run `buffalo test` against a single sub-package. For example, I may just want to fix a bug in one of my grifts, and in that case, I likely won't be interested in running my actions tests while I'm doing that edit-test work.

# Proposal

I am proposing that the `buffalo test` command treats the first argument differently. Currently, `buffalo test ./grifts/...` prepends `./grifts/...` to the list of packages that it passes to the `go test` command. 

My proposal is to make the first argument to `buffalo test` be the _only_ package passed to the `go test` command.

Instead of this behavior:

```console
$ buffalo test ./mypkg
dropped database mydb
created database mydb
loaded schema for mydb
go test -p 1 ./mypkg/... github.com/arschles/something/actions github.com/arschles/something/grifts github.com/arschles/something/mypkg
```

I'm proposing this behavior:

```console
$ buffalo test ./mypkg
dropped database mydb
created database mydb
loaded schema for mydb
go test -p 1 ./mypkg/...
```

This change would bring `buffalo test` a little bit more in line with the behavior of `go test`.

**Comment by paganotoni** [comment]
@arschles I like this proposal and think the proposed behavior makes much more sense than current one, I'm curious to know if there was a reason to do it the way we currently do it or we just didn't consider this behavior.

@arschles are you willing to work on this PR?
@markbates thoughts on this one?

**Comment by arschles** [comment]
Cool - I'll see if I can get this in tomorrow. Otherwise it'll have to be next wk
