### ISSUE TITLE
[question] Periodic Worker Perform

### ISSUE THREAD

**Issue by danikarik** [gobuffalo/buffalo#909]
Hello!

I use [GORM session store](https://github.com/wader/gormstore) in Buffalo app. To keep database clean, I have to run Cleanup func to delete expired sessions. In their doc looks like:
```
// initialize and setup cleanup
store := gormstore.New(gorm.Open(...), []byte("secret"))
// db cleanup every hour
// close quit channel to stop cleanup
quit := make(chan struct{})
go store.PeriodicCleanup(1*time.Hour, quit)
```

How can I use `worker.Perform` with periodic interval?

Doing it in `main.go` seems like no Buffalo way

**Comment by markbates** [comment]
https://gobuffalo.io/docs/workers

You probably want worker.PerformIn then at the end of the job you re-enqueue the job again for another hour.

**Comment by danikarik** [comment]
Thanks! I did that periodic clean up, but faced some problem with session.

I have handler which reads session values and returns them in JSON.

```
// AuthSession default implementation.
func AuthSession(c buffalo.Context) error {
	serialNumber := c.Session().Get("serialNumber")
	emailAddress := c.Session().Get("emailAddress")
	return c.Render(APISuccessWithResult(map[string]interface{}{
		"serialNumber": serialNumber,
		"emailAddress": emailAddress,
	}))
}
```

After that `sessionSaver` middleware tries to call `Save()` method of `SessionStore`. For some reason my database was off and I get this scenario:
1) Handler returned JSON with status 200
2) SessionSaver was called and detected error due to database off
3) I got `http: multiple response.WriteHeader calls`, because session save was called after JSON returned

I see `sessionSaver` is unexported that's why I cannot turn off middleware. I thought there is possible to skip that middleware and call `c.Session().Save()` manually and check for errors.

**Comment by markbates** [comment]
You can still call `c.Session().Save()` in your action and check for errors.

I'm closing this issue as the session stuff isn't related to the original ticket. If you still keep having session issues, please open another ticket so we can track and triage it properly. Thanks.
