### ISSUE TITLE
Flashes won't clear when using redis-backed session storage

### ISSUE THREAD

**Issue by iandelahorne** [gobuffalo/buffalo#911]
Seeing that buffalo uses gorilla's sessions package, I wanted to replace the cookie storage with a redis-backed storage from `gopkg.in/boj/redistore.v1`. When I did this, flash messages won't clear after dismissing them and reloading the page.

I created a repo at [lflux/sessionthing](https://github.com/lflux/sessionthing) where you can reproduce this by:
1. Setting up a Redis server at `:6379`
1. Cloning the repo and running `buffalo dev`
1. Visit http://localhost:3000/flash which will redirect to `/`
1. See the flash message `Success flash`. Dismiss and reload the page
1. The flash message will persist.

By setting `useRedis = false` in app.go which uses the default cookie storage, the flash message will no longer persist over page loads.

**Comment by paganotoni** [comment]
I Looked into this one, our problem seems to be 

https://github.com/gobuffalo/buffalo/blob/master/flash.go#L41

If we remove the `Save` call it works for redis, but will not work for our default session store.

**Comment by stanislas-m** [comment]
Fixed with #1141.
