### ISSUE TITLE
buffalo command not fround

### ISSUE THREAD

**Issue by Mawulijo** [gobuffalo/buffalo#918]
Hi,
After running **_$ go get -u -v github.com/gobuffalo/buffalo/buffalo_** command.
I realize my bash still couldn't run the buffalo command. ( **-bash: command not found buffalo** )
After several hours of troubleshooting, my solution was to build the buffalo command from my **$GOPATH/src/github.com/gobuffalo/buffalo/buffalo/main.go** file and **copied** it to **$GOPATH/bin** manually before I could commence. 
**_This, however, is not stated in the installation instructions._** 
I hope I wasn't doing anything wrong because my **$GOPATH** and **$GOPATH/bin** were all in my **.bash_profile** 
<img width="964" alt="screen shot 2018-02-14 at 1 03 07 pm" src="https://user-images.githubusercontent.com/15157923/36205696-8523ea58-1187-11e8-80b9-2af1f437e0d3.png">

**Comment by markbates** [comment]
You shouldn’t have to manually build and move the binary. When doing go get it should build and install the binary for you. If it didn’t there was a problem during the installation. The output from the installation should show you the problem. It’s usually a problem with a package not compiling or other issues with go get, which there are a few. go install, for future reference, will build and install a binary from the package you’re in without having to manually move everything.

**Comment by Mawulijo** [comment]
Thanks so much for the quick response. The output from the installation showed no problem though. I really appreciate the **go install** guide. I will keep in touch
