### ISSUE TITLE
Docker build fails for API-only projects due to missing package.json 

### ISSUE THREAD

**Issue by robbyoconnor** [gobuffalo/buffalo#927]
Since you don't need node for the asset pipeline since it is API only, it stands to reason that the package.json file shall be excluded from the Dockerfile.

**Comment by markbates** [comment]
This is fixed in the development branch, https://github.com/gobuffalo/buffalo/commit/51a22f8df6cc34da638dd9fc6737bb7f505902de, and will be in the next release. Thanks.
