### ISSUE TITLE
Default Production Error page is ugly.

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#930]
https://www.evernote.com/l/ABGjR5egIT9CL6QOL6bImIMVFRk96Nuluek

It would be nice to have, even just a little bit, of styling on that page.

**Comment by paganotoni** [comment]
@markbates i can come up with something simple here quick, I'll keep you posted.

**Comment by stanislas-m** [comment]
I'd love to have a "buffalo skull" version of the logo, for these pages.

Something like that:
![image](https://user-images.githubusercontent.com/1911803/36344213-382f0fb0-1417-11e8-8df3-fa017ef07718.png)

**Comment by AlhasanIQ** [comment]
i would suggest using something like the error pages included in the last version of laravel
