### ISSUE TITLE
Feature: serve the assets from the folder in prod env

### ISSUE THREAD

**Issue by hubyhuby** [gobuffalo/buffalo#937]
This is a feature request.
When deploying it is sometimes useful to be able to have the assets kept in a folder, exactly like in DEV mode.

In my use case I have a static blog, that I wish to update on a weekly base.
I need to copy the new files in the assets folder (or blog folder).

A similar  mechanism is available in gitea ( which lets you override the default templates just by creating a folder named custom https://github.com/go-gitea/gitea).

**Comment by markbates** [comment]
I don’t understand this request, to be honest. Why not use `buffalo build` which includes all assets and templates and such in the binary, then you never have to worry about those separate files?

You could also put those files in the same path as you have them on disk, and they should be served if they’re not in the binary. For example if your app is at GOPATH/src/github.com/foo/bar if you put your templates in that path + /templates on your server they should be picked up.

You could also, in your app, write some code that says if I’m in production look for the templates at this path on disk.

Unless I’m missing something I don’t see a) the benefit or b) the actual need for it. Again, that could be just a misunderstanding of the problem on my part, so please feel free and give me more details to help understand it.

-----------
Mark Bates

**Comment by hubyhuby** [comment]
Dear Mark,
The all packaged build is very nice and fits 90% of uses I guess. But in my case I would have to reload and restart my app every second day...to reload my static blog.

On gitea you can run the app and it will look for the files in the same directory... if you put them in there...
As you say it is maybe a bad habit to proceed this way.
The option to add some code to my app seems a much better solution.

**Comment by stanislas-m** [comment]
> In my use case I have a static blog, that I wish to update on a weekly base.
@hubyhuby In this case, a static blog should probably be non-static. :)

**Comment by hubyhuby** [comment]
LOL @stanislas-m 
And then we would call it statynamic!!
I think i am ready for the worst feat request of the year....and we are in february!!! Still time to improve :D
