### ISSUE TITLE
Where is the helper function '<resource>Path()' implemented?

### ISSUE THREAD

**Issue by verrol** [gobuffalo/buffalo#938]
Hi,

I am new to Buffalo and I tried the demo showed in the demo here to create a 'widget' resource: https://www.youtube.com/watch?time_continue=1736&v=75NjCfLLftw

The generated template for edit.html uses an helper 'widgetPath()':

<%= form_for(widget, {action: widgetPath({ widget_id: widget.ID }), method: "PUT"}) { %>
...
<% } %>

But I can't find where in my application the helper function 'wdigetPath()' is defined. Similarly, new.html uses 'wdigetsPath()' and I can't find that either.

My be I am over looking something, but I did a search in my project:
`grep 'widgetPath' -r . -l`

I am only seeing uses, but no definition.

Thanks.

**Comment by yatish27** [comment]
https://github.com/gobuffalo/buffalo/issues/905
This issue explains where the helper methods are defined

**Comment by paganotoni** [comment]
@verrol I'm closing this one given the answer as @yatish27 mentioned is in #905.
