### ISSUE TITLE
Update to use Webpack 4.x

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#941]
Since Webpack 4.x has officially been released, https://medium.com/webpack/webpack-4-released-today-6cdb994702d4, we should probably update the default asset pipeline to use it instead of 3.x.

**Comment by icechair** [comment]
So I dabbled a bit with this one.
Right now 2 used webpack plugins (extract-text and manifest) are incompatible with webpack 4. 
There are prerelease versions for both plugins which seem to work with webpack 4, but I would probably wait with the update until they both are out of prerelease.

Milestone for webpack-manifest-plugin [4.0.0](https://github.com/webpack-contrib/extract-text-webpack-plugin/milestone/3)
Milestone for extract-text-webpack-plugin [v2.x](https://github.com/webpack-contrib/extract-text-webpack-plugin/milestone/3)

uglifyjs also has some problems, the configuration schema changed in the latest version.

Should I first submit a pull request with failing integration tests?

**Comment by sbinet** [comment]
wrt uglifyjs: I had to modify a bit some of the autogenerated files for my buffalo-based project to make it work with bootstrap-4.

not sure whether this can help, but here it is:
https://github.com/go-saloon/saloon/commit/32169953dc8243f77df1e8d69cc012afbf96cb6f

**Comment by markbates** [comment]
Fixed with #1007
