### ISSUE TITLE
buffalo build stopped looking for vendor in the directory above

### ISSUE THREAD

**Issue by ghaabor** [gobuffalo/buffalo#949]
As of the release of 0.11.0 buffalo stopped looking for our vendor directory.
We have the following directory setup:
```
app
├── server
└── vendor
```
This is the command we run:
`cd ./server && buffalo build --tags=distribution -o ../server-bin`

When using 0.10.3 this command worked perfectly fine, it was able to locate the packages in `vendor`. Since 0.11.0 `buffalo build` is failing with this message:
```
../../../gobuffalo/pop/sqlite.go:20:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
    /usr/local/go/src/github.com/mattn/go-sqlite3 (from $GOROOT)
    /username/go/src/github.com/mattn/go-sqlite3 (from $GOPATH)
```

**Comment by Biboswan** [comment]
I have buffalo version 0.13.3 and project is 0.12.4.  I get the message `"github.com/ossn/fixme_backend/vendor/github.com/gobuffalo/pop".Connection) as type *"github.com/gobuffalo/pop".Connection in argument to popmw.Transaction` I also deleted the vendor but still same error

**Comment by markbates** [comment]
Dep support is going to be released in the next "major" version of Buffalo, so this issue won't be fixed. Sorry. https://github.com/gobuffalo/buffalo/issues/1545
