### ISSUE TITLE
Running db migrations should be idempotent 

### ISSUE THREAD

**Issue by robbyoconnor** [gobuffalo/buffalo#959]
If I run a migration which I already ran -- I shouldn't see the following: 

```
ERRO[0002] Error: error executing migrations/20180307021006_create_users.up.fizz, sql: CREATE TABLE "users" (
"id" UUID PRIMARY KEY,
"email" VARCHAR (255) NOT NULL,
"password_hash" VARCHAR (255) NOT NULL,
"created_at" timestamp NOT NULL,
"updated_at" timestamp NOT NULL
);: pq: relation "users" already exists
```

**Comment by kteb** [comment]
Normally pop will never run the same migration again except if you changed the timestamp of your file or modified something in the table schema_migration. BTW it's more a pop problem than a buffalo one.

**Comment by markbates** [comment]
@robbyoconnor I’m closing this since, as @kteb mentioned this is a Pop issue. If you could open an issue there with full steps to reproduce that would be great. 

They’re supposed to be idempotent so the steps to reproduce are critical to figuring it out. Thanks.

**Comment by robbyoconnor** [comment]
Sorry about that
