### ISSUE TITLE
support for generating models with []byte fields

### ISSUE THREAD

**Issue by sbinet** [gobuffalo/buffalo#967]
hi there,

I tried a few ways to generate a model that contains a `[]byte` field.

it seems possible to have a model that contains a `nulls.ByteSlice` but the fizz schema that is generated is not valid:

```
$> buffalo db g model user name:string avatar:nulls.ByteSlice
```

```go
type User struct {
	ID        uuid.UUID       `json:"id" db:"id"`
	CreatedAt time.Time       `json:"created_at" db:"created_at"`
	UpdatedAt time.Time       `json:"updated_at" db:"updated_at"`
	Name      string          `json:"name" db:"name"`
	Avatar    nulls.ByteSlice `json:"avatar" db:"avatar"`
}
```

```
$> cat migration/xxxx.create_users.up.fizz
create_table("usrs", func(t) {
	t.Column("id", "uuid", {"primary": true})
	t.Column("name", "string", {})
	t.Column("avatar", "byteslice", {"null": true})
})
```

and `byteslice` isn't a valid column type (at least for postgres, `bytea` seems like something one would want to use).

should this also something to be added to the `pop/slices` package?

**Comment by markbates** [comment]
That would make a great PR!

**Comment by sbinet** [comment]
ok. I am not sure where the entry point for _e.g._ the `db g model` is.
could you give me a few pointers ?

**Comment by markbates** [comment]
Of course!

This is what handles the initial mapping from the cli (`db g model user name:type name:type`):

https://github.com/gobuffalo/pop/blob/master/soda/cmd/generate/model.go#L193

And here's where you make database specific mappings:

https://github.com/gobuffalo/pop/blob/master/fizz/translators/postgres.go#L201
https://github.com/gobuffalo/pop/blob/master/fizz/translators/cockroach.go#L366
https://github.com/gobuffalo/pop/blob/master/fizz/translators/mysql.go#L214
https://github.com/gobuffalo/pop/blob/master/fizz/translators/sqlite.go#L377
