### ISSUE TITLE
Making Default Template Responsive

### ISSUE THREAD

**Issue by connelevalsam** [gobuffalo/buffalo#970]
This is not an issue. Just wanted to contribute to this great community.
Noticed that the default template makes me scroll left to right on mobile devices.
I know it's not much of a deal but most times even our mobile is connected to the company's network.
And before adding our contents there're things we might want to make sure are in place first.
So listing the routes and using mobile to check was stressful.
I know it's not a big contribution but at least I've tried :)

    _THIS IS MY_ **FIRST TIME**
[Buffalo_UI.zip](https://github.com/gobuffalo/buffalo/files/1818884/Buffalo_UI.zip)

Just attached the files i worked on

**Comment by markbates** [comment]
We're very happy to have you contribute, let's help you through the process of creating a pull request:

* https://help.github.com/articles/about-pull-requests/ - how PRs work on GitHub
* https://github.com/gobuffalo/buffalo/blob/master/CONTRIBUTING.md - how to contribute to Buffalo, including a nice guide on how to deal with forks and Go.
* https://github.com/gobuffalo/buffalo/tree/master/generators/newapp/templates - Most of the `buffalo new` templates are here, including those you probably want to change.

**Comment by gedw99** [comment]
i am planning to use this for mobiles, so i welcome this +1

**Comment by connelevalsam** [comment]
yeah... thanks

**Comment by connelevalsam** [comment]
Yeah... and I discovered bootstrap was or is the only defaults. What if
there could be an option cos www.Tachyons.io is fast growing and is light
too.

So during new app generation could specify either no css or tachyons css?

**Comment by paganotoni** [comment]
This one seems that have been covered.
