### ISSUE TITLE
buffalo allows mux to handle 405 responses

### ISSUE THREAD

**Issue by JeremyChase** [gobuffalo/buffalo#978]
If a 405 handler is defined, it is not used. This can be reproduced by creating an application with a 405 handler:

```
app.ErrorHandlers[405] = func(status int, err error, c buffalo.Context) error {
  res := c.Response()
  res.WriteHeader(status)
  res.Write([]byte(fmt.Sprintf("Oops!! There was an error %s", err.Error())))
  return nil
}
app.GET("/", HomeHandler)
```

The defined handler does not get used:
```
$ curl localhost:3000/ -i -X POST
HTTP/1.1 405 Method Not Allowed
Date: Sun, 18 Mar 2018 20:28:56 GMT
Content-Length: 0
```

Backstory: https://gophers.slack.com/archives/C3MSAFD40/p1521402776000101

**Comment by markbates** [comment]
@JeremyChase in case you're curious, here's the PR to fix this https://github.com/gobuffalo/buffalo/pull/979

**Comment by JeremyChase** [comment]
@markbates Ah - thank you - that clarifies what was happening:

https://github.com/gorilla/mux/blob/master/mux.go#L43-L68
