### ISSUE TITLE
Proposal: Vendor the Buffalo Binary inside Applications

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#986]
Recently in the Buffalo Slack channel an issue arose, and not for the first time. The user was saying that when they ran `buffalo g resource` they were getting `markbates/pop` imports instead of `gobuffalo/pop`. It turned out that while their app was running `v0.11.0` their binary was still at `v0.10.3`. This class of problem is common, using an older binary with a newer app, which can lead to all sorts of interesting issues.

I am proposing the following solution/idea:

Whenever `buffalo new` or `buffalo update` is run we copy the Buffalo binary into the project, potentially at `bin/buffalo` or `binstubs/buffalo`. This will allow users to run `./bin/buffalo g resource` and know that they're using the version of the Buffalo binary meant for their application. It would be recommended that this file be committed.

The upsides of this are always having the correct versioned binary for the app in question. We can even make the `buffalo` binary "smart" to look in that folder first, and if it finds a binary there, it will shell out commands to that binary instead. This means you wouldn't have to do `./bin/buffalo g resource`, but rather just `buffalo g resource`, and it will call the vendored binary in the app instead.

The downsides are if teams are using multiple OS's only the computer that runs `buffalo new` or `buffalo update` will create an insert a binary. So, for example, if this was done on a Mac, the Windows binary would be missing from `bin/`. The work around is to copy a windows binary into that folder. Having the binary in the app would also make the repo larger.

So while it looks like the downsides win, there is a lot of advantage to the upsides.

I'm opening this up for discussions, I'd love to hear your feedback on it.

**Comment by bketelsen** [comment]
someone (uber? lyft?) built a tool to vendor the binaries you need.

**Comment by alexsante** [comment]
@markbates  What if the binary had the ability to inspect the project and determine what version of the binary was used when it was created?  It could be a dotfile in the project root that holds that metadata.  Then whenever a buffalo command is used, it would inspect that file and complain if there's a mismatch.   `buffalo update` can also modify that file.

**Comment by markbates** [comment]
I thought of that, but I don’t like yelling if there’s a mismatch, although a warning would be good. The downside of that idea is if you have two projects running different versions of buffalo. The older version would keep yelling at you until you upgrade it, even if you don’t want to, or can’t update it.

**Comment by bketelsen** [comment]
there's already a .buffalo.dev.yml that could hold these things

**Comment by markbates** [comment]
Eventually that file will go away, in favor of something else, but that’s another issue for another time. :)

**Comment by dnnrly** [comment]
There isn't anything to stop `buffalo new` from getting various tools needed in a temporary GOPATH and copying the results to `./bin`.

Kind of hacky but you could definitely trust which version was built. Stops you from going down the Artifactory (or whatever) route or suffering multi platform issues.

**Comment by JeremyChase** [comment]
I prefer the idea of keeping the version in a dot file as @alexsante and @bketelsen initially suggested.

What if you added the following to `.buffalo.dev.yml`?

```
buffalo_version: <semver>
buffalo_version_mute_mismatch_warning: <boolean>
```

**Comment by robbyoconnor** [comment]
We could use `<insert alternative to rails here>`  

![](https://media.giphy.com/media/amxLHEPgGDCKs/giphy.gif)

**Comment by dnnrly** [comment]
https://github.com/dnnrly/buffalo-tool

Experimental tool vendoring plugin for buffalo. Driven by the version of buffalo that you specify or defaults to the current buffalo version. There's a fair amount of cruft and hardcoding but should serve to tease out any problems with the approach.
