### ISSUE TITLE
binding.go:27:14: undefined: formam.Decoder

### ISSUE THREAD

**Issue by joefazee** [gobuffalo/buffalo#988]
> MY SETUP: MacOS (10.13.4 Beta), go version go1.10 darwin/amd64. And i am within Go path.

I encountered an error when creating a new project using "buffalo new project_name". Attached is the screenshot.

<img width="994" alt="screen shot 2018-03-24 at 12 37 49" src="https://user-images.githubusercontent.com/1267708/37863582-89002f5a-2f60-11e8-8095-cadb8d5285a0.png">

After the error, i cd into the newly created project directory and ran "buffalo dev" and the same error was present.
<img width="681" alt="screen shot 2018-03-24 at 12 38 10" src="https://user-images.githubusercontent.com/1267708/37863585-914a5820-2f60-11e8-937d-0e0200e10233.png">

**Comment by markbates** [comment]
You appear to be missing some dependencies for your application/buffalo. Try reinstalling Buffalo and see if that fixes the problem.

**Comment by joefazee** [comment]
I have reinstalled twice and got the same error. I use this command 

> go get -u -v github.com/gobuffalo/buffalo/buffalo

**Comment by markbates** [comment]
You’re missing this package, at the very least, https://github.com/monoculum/formam

Try installing that and see if it fixes it. If not, there is something more fundamentally wrong with how things are set up for you. 

If that doesn’t work I would recommend going to the Buffalo slack channel and see if anyone there can help. 

Unfortunately I’m at a wedding today, so I can’t spend the usual amount of time I do to help debug. :(

**Comment by joefazee** [comment]
Thank you @markbates. I installed the formam package and it worked. Can we have it highlighted in the documentation as part of the dependencies? I had to browser inside the source file where you created the decoder variable figure it out.

**Comment by markbates** [comment]
It’s listed here with all the dependencies https://github.com/gobuffalo/buffalo/blob/master/SHOULDERS.md

This is the first time this has happened, which makes me think that’s there something else at play. Unfortunately I don’t have to the time today to look into it with you. Sorry. 

I’m closing this, but if you figure out what went wrong please open a ticket with the repo steps. Thanks.
