### ISSUE TITLE
Translate validation messages

### ISSUE THREAD

**Issue by fdonzello** [gobuffalo/buffalo#991]
Hi everybody,

I think that one feature that a lot of people will love could be to allow custom and, maybe, translated messages for validation errors.

I forked the gobuffalo/validate repo and pushed a commit. May someone take a look at it so that I can have a feedback to decide whether to continue on this way or change?

Commit: https://github.com/fdonzello/validate/commit/c4bdb88e0624ea71ba75cf804beba02c996b7b28

Thanks

**Comment by markbates** [comment]
I think it looks good. I'm going to close this issue, since it's on the wrong repo, but please open a PR though, it would be great.
