### ISSUE TITLE
Electron Shell

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [gobuffalo/buffalo#993]
Hi,
I think it is a good idea to make a recipe for gobuffalo to Electron Shell. It will be convenient way to port WEB applications to desktop client ( where people want hosted solution ).
What you guys think?

**Comment by robbyoconnor** [comment]
I like this as well...I'd love to see this plugin!

**Comment by mkungla** [comment]
Did anybody experiment with it or other solutions to build desktop apps with gobuffalo?

**Comment by robbyoconnor** [comment]
The problem with Electron is that it is slow as hell and bloated to boot.

**Comment by stanislas-m** [comment]
While it can be a good idea, we want to keep the Buffalo core as light as possible. Feel free to write a plugin for that. :) https://gobuffalo.io/en/docs/plugins#writing-a-plugin
